CONTRIBUTING.md
Initial draft of test case naming re-write
=> Contributing: updates the Test Case Names section. Closes gh-150

test/language/arrow-function/Arrow-Function_rules-for-prototype.js, test/language/arrow-function/Arrow-Function_semantics.js, test/language/arrow-function/Arrow-Function_syntax-variations.js
These tests are derived from the following files within the Google V8
project:
test/mjsunit/harmony/arrow-functions.js
```
test262 --command "v8 --harmony-arrow-functions" Arrow-Function;
test262 --command "js" Arrow-Function;
```
=> Import tests from Google V8 (Arrow Functions)

test/language/generators/generator.declaration.js, test/language/generators/generator.declareMethod.argSuperCall.js, test/language/generators/generator.declareMethod.argSuperProperty.js, test/language/generators/generator.declareMethod.bodySuperCall.js, test/language/generators/generator.declareMethod.bodySuperProperty.js, test/language/generators/generator.declareMethod.js, test/language/generators/generator.declareMethod.shadow-parameter-const.js, test/language/generators/generator.declareMethod.shadow-parameter-let.js, test/language/generators/generator.expression.implicit-name.js, test/language/generators/generator.expression.name.js, test/language/generators/generator.expression.no-name.js
batch of generator tests
fix info, desc
=> initial set of generator tests

test/language/generators/generator.declareMethod.argSuperProperty.js
=> format features correctly

tools/packaging/test262.py
Fix JUnit output so that it can be actually be parsed by JUnit and
Jenkins. Wrap XML output correctly and
post-process failure messages to avoid invalid XML characters.
=> Fix "junit" output option to produce valid JUnit XML

test/built-ins/Array/prototype/Symbol.iterator/property-descriptor.js, test/built-ins/Array/prototype/Symbol.iterator/prototype/Symbol.toStringTag/property-descriptor.js, test/built-ins/Array/prototype/Symbol.iterator/prototype/Symbol.toStringTag/value-direct.js, test/built-ins/Array/prototype/Symbol.iterator/prototype/Symbol.toStringTag/value-from-to-string.js, test/built-ins/Array/prototype/Symbol.iterator/prototype/next/iteration-mutable.js, test/built-ins/Array/prototype/Symbol.iterator/prototype/next/iteration.js, test/built-ins/Array/prototype/Symbol.iterator/prototype/next/non-own-slots.js, test/built-ins/Array/prototype/Symbol.iterator/prototype/next/property-descriptor.js, test/built-ins/Array/prototype/entries/iteration-mutable.js, test/built-ins/Array/prototype/entries/iteration.js, test/built-ins/Array/prototype/entries/property-descriptor.js, test/built-ins/Array/prototype/entries/returns-iterator.js, test/built-ins/Array/prototype/keys/iteration-mutable.js, test/built-ins/Array/prototype/keys/iteration.js, test/built-ins/Array/prototype/keys/property-descriptor.js, test/built-ins/Array/prototype/keys/returns-iterator.js, test/language/for-of/Array.prototype.Symbol.iterator.js, test/language/for-of/Array.prototype.entries.js, test/language/for-of/Array.prototype.keys.js, test/language/for-of/array.js
These tests are derived from the following files within the Google V8
project:
test/mjsunit/es6/array-iterator.js
=> Add Array Iteration Tests

harness/propertyHelper.js
After checking the writability of a given property, restore the property
value to its original state.
=> Make writability helper function non-destructive

tools/packaging/monkeyYaml.py, tools/packaging/test/test_monkeyYaml.py
This addresses the issue with property-descriptor.js; testing others now
EDIT: to be specific, the issue with "built-ins/Array/prototype/keys/property-descriptor.js".
=> candidate fix for #215

test/built-ins/String/prototype/concat/S15.5.4.6_A1_T10.js
v8 would fail this test, so it would be nice to have it
=> Add a test for String.prototype.concat() with single Object argument

test/built-ins/Array/prototype/find/Array.prototype.find_remove-after-start.js
=> Array.prototype.find does not skip holes

test/built-ins/Object/defineProperty/15.2.3.6-2-17-1.js, test/built-ins/String/prototype/replace/S15.5.4.11_A5_T1.js
=> Don't use Annex B extensions in main test suite

test/intl402/11.1.1_20_c.js
- Update minor unit for CLF
- Remove withdrawn currencies (LVL, LTL, USS)
- Update link to new location
Fixes #98
=> Changes for currency data

test/language/rest-parameters/arrow-function-invalid.js, test/language/rest-parameters/arrow-function.js, test/language/rest-parameters/expected-argument-count.js, test/language/rest-parameters/no-alias-arguments.js, test/language/rest-parameters/position-invalid.js, test/language/rest-parameters/rest-index.js, test/language/rest-parameters/rest-parameters-apply.js, test/language/rest-parameters/rest-parameters-call.js, test/language/rest-parameters/rest-parameters-produce-an-array.js, test/language/rest-parameters/with-new-target.js
These tests are derived from the following files within the Google V8 project:
test/mjsunit/harmony/rest-params.js
=> Import tests from Google V8 (Rest Parameters)

test/built-ins/Object/is/length.js, test/built-ins/Object/is/name.js, test/built-ins/Object/is/not-same-value-x-y-boolean.js, test/built-ins/Object/is/not-same-value-x-y-null.js, test/built-ins/Object/is/not-same-value-x-y-number.js, test/built-ins/Object/is/not-same-value-x-y-object.js, test/built-ins/Object/is/not-same-value-x-y-string.js, test/built-ins/Object/is/not-same-value-x-y-symbol.js, test/built-ins/Object/is/not-same-value-x-y-type.js, test/built-ins/Object/is/not-same-value-x-y-undefined.js, test/built-ins/Object/is/object-is.js, test/built-ins/Object/is/same-value-x-y-boolean.js, test/built-ins/Object/is/same-value-x-y-empty.js, test/built-ins/Object/is/same-value-x-y-null.js, test/built-ins/Object/is/same-value-x-y-number.js, test/built-ins/Object/is/same-value-x-y-object.js, test/built-ins/Object/is/same-value-x-y-string.js, test/built-ins/Object/is/same-value-x-y-symbol.js, test/built-ins/Object/is/same-value-x-y-undefined.js
=> 19.1.2.10 Object.is

test/built-ins/Symbol/auto-boxing-strict.js
This is a pull request that fixed a very simple typo
=> fixing a typo

test/built-ins/Error/prototype/S15.11.3.1_A1_T1.js, test/built-ins/Error/prototype/S15.11.3.1_A2_T1.js, test/built-ins/Error/prototype/S15.11.3.1_A3_T1.js, test/built-ins/Error/prototype/S15.11.4_A2.js, test/built-ins/Error/prototype/S15.11.4_A3.js, test/built-ins/Error/prototype/S15.11.4_A4.js, test/built-ins/Error/prototype/constructor/S15.11.4.1_A1_T2.js
Add missing "var" declarations and noStrict flags.
=> Fix strict mode errors in built-ins/Error

test/built-ins/Object/defineProperty/15.2.3.6-4-354-8.js, test/built-ins/Object/defineProperty/15.2.3.6-4-360-3.js, test/built-ins/Object/defineProperty/15.2.3.6-4-531-7.js, test/built-ins/Object/defineProperty/15.2.3.6-4-531-8.js, test/built-ins/Object/defineProperty/15.2.3.6-4-537.js, test/built-ins/Object/defineProperty/15.2.3.6-4-54.js, test/built-ins/Object/defineProperty/15.2.3.6-4-542.js, test/built-ins/Object/defineProperty/15.2.3.6-4-546.js, test/built-ins/Object/defineProperty/15.2.3.6-4-555.js, test/built-ins/Object/defineProperty/15.2.3.6-4-560.js, test/built-ins/Object/defineProperty/15.2.3.6-4-564.js, test/built-ins/Object/defineProperty/15.2.3.6-4-581.js, test/built-ins/Object/defineProperty/15.2.3.6-4-586.js, test/built-ins/Object/defineProperty/15.2.3.6-4-591.js, test/built-ins/Object/defineProperty/15.2.3.6-4-596.js, test/built-ins/Object/defineProperty/15.2.3.6-4-63.js, test/built-ins/Object/defineProperty/15.2.3.6-4-85.js
Fixes additional strict mode issues noted in #258
=> fix tests in strict mode - Object/defineProperty

test/built-ins/Object/defineProperty/15.2.3.6-4-217.js, test/built-ins/Object/defineProperty/15.2.3.6-4-256.js, test/built-ins/Object/defineProperty/15.2.3.6-4-470.js, test/built-ins/Object/defineProperty/15.2.3.6-4-501.js
Thanks to @anba for finding these
https://github.com/tc39/test262/pull/255/files#r29866584
=> add line note fixes from #255

test/built-ins/Array/isArray/15.4.3.2-0-5.js
This is simply an update to a comment.
=> The comment is no longer accurate, updating it

test/built-ins/Promise/all/S25.4.4.1_A1.3_T1.js, test/built-ins/Promise/race/S25.4.4.3_A1.2_T1.js, test/built-ins/Promise/reject/S25.4.4.4_A1.2_T1.js, test/built-ins/Promise/resolve/S25.4.4.5_A1.2_T1.js
`Promise` methods should not be enumerable, per https://people.mozilla.org/~jorendorff/es6-draft.html#table-4
=> `Promise` methods should not be enumerable

test/built-ins/Array/prototype/concat/S15.4.4.4_A4.1.js, test/built-ins/Array/prototype/join/S15.4.4.5_A6.1.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A5.1.js, test/built-ins/Array/prototype/push/S15.4.4.7_A6.1.js, test/built-ins/Array/prototype/reverse/S15.4.4.8_A5.1.js, test/built-ins/Array/prototype/shift/S15.4.4.9_A5.1.js, test/built-ins/Array/prototype/slice/S15.4.4.10_A5.1.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A7.1.js, test/built-ins/Array/prototype/splice/S15.4.4.12_A5.1.js, test/built-ins/Array/prototype/toLocaleString/S15.4.4.3_A4.1.js, test/built-ins/Array/prototype/toString/S15.4.4.2_A4.1.js, test/built-ins/Array/prototype/unshift/S15.4.4.13_A5.1.js, test/built-ins/Set/set-iterator-close-after-add-failure.js, test/built-ins/global/S10.2.3_A2.2_T1.js, test/built-ins/global/S10.2.3_A2.2_T2.js, test/built-ins/global/S10.2.3_A2.2_T3.js, test/built-ins/global/S10.2.3_A2.2_T4.js, test/language/statements/function/13.2-12-s.js, test/language/statements/function/13.2-16-s.js, test/language/statements/function/13.2-20-s.js, test/language/statements/function/13.2-24-s.js, test/language/statements/function/13.2-28-s.js, test/language/statements/function/13.2-8-s.js
- Add missing ".prototype" lookup in Array.prototype tests (Follow-up of #280)
- Add noStrict flag in global/S10.2.3_A2.2_*.js (implicit this-binding is part of the test)
- Provide correct this-binding in function/13.2-*.js
- Add missing assert.throws in "set-iterator-close-after-add-failure.js"
=> Additional tests with incorrect for-in context

test/built-ins/Math/acosh/acosh-descriptor.js, test/built-ins/Math/asinh/asinh-descriptor.js, test/built-ins/Math/atanh/atanh-descriptor.js, test/built-ins/Math/cbrt/cbrt-descriptor.js, test/built-ins/Math/cosh/cosh-descriptor.js, test/built-ins/Math/expm1/expm1-descriptor.js, test/built-ins/Math/hypot/hypot-descriptor.js, test/built-ins/Math/imul/imul-descriptor.js, test/built-ins/Math/log10/Log10-descriptor.js, test/built-ins/Math/log1p/Log1p-descriptor.js, test/built-ins/Math/log2/log2-descriptor.js, test/built-ins/Math/sign/sign-descriptor.js, test/built-ins/Math/sinh/sinh-descriptor.js, test/built-ins/Math/tanh/tanh-descriptor.js, test/built-ins/Math/trunc/trunc-descriptor.js
This also fixes #295 for me. We use this array syntax everywhere else for includes:
=> Use the more common array syntax for includes

test/built-ins/Object/assign/ObjectOverride-sameproperty.js, test/built-ins/Object/assign/OnlyOneArgument.js, test/built-ins/Object/assign/Override-notstringtarget.js, test/built-ins/Object/assign/Override.js, test/built-ins/Object/assign/Source-Null-Undefined.js, test/built-ins/Object/assign/Source-Number-Boolen-Symbol.js, test/built-ins/Object/assign/Source-String.js, test/built-ins/Object/assign/Target-Boolean.js, test/built-ins/Object/assign/Target-Null.js, test/built-ins/Object/assign/Target-Number.js, test/built-ins/Object/assign/Target-Object.js, test/built-ins/Object/assign/Target-String.js, test/built-ins/Object/assign/Target-Symbol.js, test/built-ins/Object/assign/Target-Undefined.js, test/built-ins/Object/assign/assign-descriptor.js, test/built-ins/Object/assign/assign-length.js
=> Add tests for Object-Assign

website/scripts/sth.js
Update the URLs used by dynamic script loading code according to the new
location of the recently-moved web site scripts.
=> Complete migration of website assets

tools/packaging/monkeyYaml.py, tools/packaging/test/test_monkeyYaml.py
=> monkeyYaml: Add support for line folding

test/built-ins/String/prototype/endsWith/String.prototype.endsWith_Fail.js, test/built-ins/String/prototype/endsWith/String.prototype.endsWith_Fail_2.js, test/built-ins/String/prototype/endsWith/String.prototype.endsWith_Success.js, test/built-ins/String/prototype/endsWith/String.prototype.endsWith_Success_2.js, test/built-ins/String/prototype/endsWith/String.prototype.endsWith_Success_3.js, test/built-ins/String/prototype/endsWith/String.prototype.endsWith_Success_4.js, test/built-ins/String/prototype/includes/String.prototype.includes_FailBadLocation.js, test/built-ins/String/prototype/includes/String.prototype.includes_FailLocation.js, test/built-ins/String/prototype/includes/String.prototype.includes_FailMissingLetter.js, test/built-ins/String/prototype/includes/String.prototype.includes_Success.js, test/built-ins/String/prototype/includes/String.prototype.includes_SuccessNoLocation.js, test/built-ins/String/prototype/includes/String.prototype.includes_lengthProp.js
The String.endsWith and String.includes tests didn't specify either an es6id or a features. Added a features attribute for these tests.
=> ES6 specific functions should declare a feature.

test/suite/ch11/11.13/11.13.1/11.13.1-4-29gs.js
SyntaxError => TypeError for writing to a non-writeable field.
Fixes #372 for es5
=> Fix 11.13.1-4-29gs.js incorrect comment explanation (es5)

harness/assert.js, test/built-ins/RegExp/unicode_identity_escape.js, test/built-ins/RegExp/unicode_restricted_brackets.js, test/built-ins/RegExp/unicode_restricted_character_class_escape.js, test/built-ins/RegExp/unicode_restricted_identity_escape.js, test/built-ins/RegExp/unicode_restricted_identity_escape_alpha.js, test/built-ins/RegExp/unicode_restricted_identity_escape_c.js, test/built-ins/RegExp/unicode_restricted_identity_escape_u.js, test/built-ins/RegExp/unicode_restricted_identity_escape_x.js, test/built-ins/RegExp/unicode_restricted_incomple_quantifier.js, test/built-ins/RegExp/unicode_restricted_octal_escape.js, test/built-ins/RegExp/unicode_restricted_quantifiable_assertion.js, test/built-ins/RegExp/unicode_restricted_quantifier_without_atom.js
Extension Annex B, "B.1.4 Regular Expressions Patterns" does not apply for Unicode RegExps.
=> B.1.4 and Unicode RegExps

harness/testIntl.js
=> Fix missing variable declaration

harness/runTestCase.js
Can be applied after #413, #415 and #416 are pulled in.
=> Remove harness/runTestCase.js

test/language/expressions/arrow-function/arrow/binding-tests-1.js, test/language/expressions/arrow-function/arrow/binding-tests-2.js, test/language/expressions/arrow-function/arrow/binding-tests-3.js, test/language/expressions/arrow-function/arrow/capturing-closure-variables-1.js, test/language/expressions/arrow-function/arrow/capturing-closure-variables-2.js, test/language/expressions/arrow-function/arrow/concisebody-lookahead-assignmentexpression-1.js, test/language/expressions/arrow-function/arrow/concisebody-lookahead-assignmentexpression-2.js
update tests for arrow-function
=> update tests for arrow-function

test/language/expressions/prefix-decrement/11.4.5-2-2gs.js
=> fixes increment typo

test/built-ins/Promise/all/ctx-ctor-throws.js, test/built-ins/Promise/prototype/then/ctor-throws.js, test/built-ins/Promise/race/ctx-ctor-throws.js, test/built-ins/Promise/reject/ctx-ctor-throws.js, test/built-ins/Promise/resolve/ctx-ctor-throws.js
See http://www.ecma-international.org/ecma-262/6.0/#sec-newpromisecapability
=> Improve Promise coverage: NewPromiseCapability

test/built-ins/Promise/all/invoke-resolve-return.js, test/built-ins/Promise/all/iter-step-err.js, test/built-ins/Promise/race/invoke-resolve-return.js, test/built-ins/Promise/race/iter-close.js, test/built-ins/Promise/race/iter-step-err.js
PerformPromiseAll: http://www.ecma-international.org/ecma-262/6.0/#sec-performpromiseall
PerformPromiseRace: http://www.ecma-international.org/ecma-262/6.0/#sec-performpromiserace
=> Improve Promise coverage: PerformPromiseAll & PeformPromiseRace

test/built-ins/Array/prototype/slice/S15.4.4.10_A3_T1.js, test/built-ins/Array/prototype/slice/S15.4.4.10_A3_T2.js
This fixes #458 and should allow Spidermonkey to successfully run test262 to completion.
Somebody has to check if signed a CLA before, I can't remember.
=> Stop test262 from hanging Spidermonkey with an unimportant error message

test/built-ins/Array/prototype/indexOf/fromindex-zero-conversion.js, test/built-ins/Array/prototype/lastIndexOf/fromindex-zero-conversion.js
=> Add tests for zero conversion on Array#indexOf and Array#lastIndexOf

test/built-ins/String/prototype/match/length.js, test/language/expressions/object/method-definition/generator-super-prop-param.js
=> Remove duplicate front matter keys

test/built-ins/Symbol/for/create-value.js, test/built-ins/Symbol/for/prop-desc.js, test/built-ins/Symbol/for/retrieve-value.js, test/built-ins/Symbol/for/to-string-err.js, test/built-ins/Symbol/keyFor/arg-non-symbol.js, test/built-ins/Symbol/keyFor/arg-symbol-registry-hit.js, test/built-ins/Symbol/keyFor/arg-symbol-registry-miss.js, test/built-ins/Symbol/keyFor/prop-desc.js, test/built-ins/Symbol/prototype/constructor.js, test/built-ins/Symbol/prototype/toString/prop-desc.js, test/built-ins/Symbol/prototype/valueOf/prop-desc.js, test/built-ins/Symbol/prototype/valueOf/this-val-non-obj.js, test/built-ins/Symbol/prototype/valueOf/this-val-obj-non-symbol.js, test/built-ins/Symbol/prototype/valueOf/this-val-obj-symbol.js, test/built-ins/Symbol/prototype/valueOf/this-val-symbol.js
I discovered some holes in the coverage for Symbol while working on some tests for realms. I think this addresses everything that was missing.
=> Improve test coverage for Symbol

README.md
Update the maintainer to @tcare as @goyakin is no longer maintaining the repo.
=> Update maintainer in README.MD

test/built-ins/Array/prototype/every/15.4.4.16-2-15.js, test/built-ins/Array/prototype/every/15.4.4.16-7-c-i-23.js, test/built-ins/Array/prototype/filter/15.4.4.20-2-15.js, test/built-ins/Array/prototype/filter/15.4.4.20-9-c-i-23.js, test/built-ins/Array/prototype/forEach/15.4.4.18-2-15.js, test/built-ins/Array/prototype/forEach/15.4.4.18-7-c-i-23.js, test/built-ins/Array/prototype/indexOf/15.4.4.14-1-17.js, test/built-ins/Array/prototype/indexOf/15.4.4.14-2-15.js, test/built-ins/Array/prototype/indexOf/15.4.4.14-9-b-i-23.js, test/built-ins/Array/prototype/lastIndexOf/15.4.4.15-1-17.js, test/built-ins/Array/prototype/lastIndexOf/15.4.4.15-2-15.js, test/built-ins/Array/prototype/lastIndexOf/15.4.4.15-8-b-i-23.js, test/built-ins/Array/prototype/map/15.4.4.19-2-15.js, test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-23.js, test/built-ins/Array/prototype/reduce/15.4.4.21-2-15.js, test/built-ins/Array/prototype/reduce/15.4.4.21-8-b-iii-1-23.js, test/built-ins/Array/prototype/reduce/15.4.4.21-9-c-i-23.js, test/built-ins/Array/prototype/reduceRight/15.4.4.22-2-15.js, test/built-ins/Array/prototype/reduceRight/15.4.4.22-8-b-iii-1-23.js, test/built-ins/Array/prototype/reduceRight/15.4.4.22-9-c-i-23.js, test/built-ins/Array/prototype/some/15.4.4.17-2-15.js, test/built-ins/Array/prototype/some/15.4.4.17-7-c-i-23.js
=> Remove unused variables

test/annexB/language/statements/for-in/bare-initializer.js, test/annexB/language/statements/for-in/const-initializer.js, test/annexB/language/statements/for-in/let-initializer.js, test/annexB/language/statements/for-in/nonstrict-initializer.js, test/annexB/language/statements/for-in/strict-initializer.js, test/annexB/language/statements/for-in/var-arraybindingpattern-initializer.js, test/annexB/language/statements/for-in/var-objectbindingpattern-initializer.js
These were re-introduced in sloppy mode per
https://github.com/tc39/ecma262/pull/614
These could use a review for filenames, style, frontmatter, etc.
=> Add tests for for-in initializers

test/intl402/Intl/getCanonicalLocales/main.js, test/intl402/Intl/getCanonicalLocales/preferred-subtag.js
Fix #743 
/cc @zbraniecki @littledan @caridy
=> islamicc should be canonicalized to islamic-civil

CONTRIBUTING.md
=> Fix markdown typo in contributing.md

test/built-ins/global/global-object.js, test/built-ins/global/property-descriptor.js
Closes #605, relates to #567 / https://github.com/tc39/proposal-global/issues/12 / https://github.com/bocoup/test262/commit/9c45e2ac684bae64614d8eb55789cae97323a7e7
=> Add `global` tests.

test/built-ins/global/global-object.js, test/built-ins/global/property-descriptor.js
=> Fix invalid yaml on tests for global

test/built-ins/Proxy/get/trap-is-undefined-receiver.js, test/built-ins/Proxy/set/trap-is-undefined-receiver.js
Sorry to be at it again, but it kind of breaks my tests :)
=> YAML tabs fix

INTERPRETING.md
=> Correct file reference in "interpreting" document

test/built-ins/ArrayIteratorPrototype/next/detach-typedarray-in-progress.js
Tests new logic in https://github.com/tc39/ecma262/pull/724
Not ready to merge yet, pending discussion in https://github.com/tc39/ecma262/issues/713
=> Test for new TypedArray iterator detach logic

test/language/arguments-object/mapped/nonconfigurable-descriptors-basic.js, test/language/arguments-object/mapped/nonconfigurable-descriptors-set-value-by-arguments.js, test/language/arguments-object/mapped/nonconfigurable-descriptors-set-value-with-define-property.js, test/language/arguments-object/mapped/nonconfigurable-descriptors-with-param-assign.js, test/language/arguments-object/mapped/nonconfigurable-nonenumerable-nonwritable-descriptors-basic.js, test/language/arguments-object/mapped/nonconfigurable-nonenumerable-nonwritable-descriptors-set-by-arguments.js, test/language/arguments-object/mapped/nonconfigurable-nonenumerable-nonwritable-descriptors-set-by-param.js, test/language/arguments-object/mapped/nonconfigurable-nonwritable-descriptors-basic.js, test/language/arguments-object/mapped/nonconfigurable-nonwritable-descriptors-define-property-consecutive.js, test/language/arguments-object/mapped/nonconfigurable-nonwritable-descriptors-set-by-arguments.js, test/language/arguments-object/mapped/nonconfigurable-nonwritable-descriptors-set-by-param.js, test/language/arguments-object/mapped/nonwritable-nonconfigurable-descriptors-basic.js, test/language/arguments-object/mapped/nonwritable-nonconfigurable-descriptors-set-by-arguments.js, test/language/arguments-object/mapped/nonwritable-nonconfigurable-descriptors-set-by-param.js, test/language/arguments-object/mapped/nonwritable-nonenumerable-nonconfigurable-descriptors-basic.js, test/language/arguments-object/mapped/nonwritable-nonenumerable-nonconfigurable-descriptors-set-by-arguments.js, test/language/arguments-object/mapped/nonwritable-nonenumerable-nonconfigurable-descriptors-set-by-define-property.js, test/language/arguments-object/mapped/nonwritable-nonenumerable-nonconfigurable-descriptors-set-by-param.js
Implementing test cases for issue #814
=> Adding test cases to validate property descriptors on cases of mapped arguments

test/intl402/PluralRules/builtin.js, test/intl402/PluralRules/can-be-subclassed.js, test/intl402/PluralRules/internals.js, test/intl402/PluralRules/length.js, test/intl402/PluralRules/name.js, test/intl402/PluralRules/prototype/bind.js, test/intl402/PluralRules/prototype/builtins.js, test/intl402/PluralRules/prototype/constructor/main.js, test/intl402/PluralRules/prototype/properties.js, test/intl402/PluralRules/prototype/prototype.js, test/intl402/PluralRules/prototype/resolvedOptions/builtins.js, test/intl402/PluralRules/prototype/resolvedOptions/name.js, test/intl402/PluralRules/prototype/resolvedOptions/properties.js, test/intl402/PluralRules/prototype/select/name.js, test/intl402/PluralRules/prototype/select/non-finite.js, test/intl402/PluralRules/prototype/select/tainting.js, test/intl402/PluralRules/supportedLocalesOf/arguments.js, test/intl402/PluralRules/supportedLocalesOf/main.js, test/intl402/PluralRules/supportedLocalesOf/name.js, test/intl402/PluralRules/supportedLocalesOf/supportedLocalesOf.js, test/intl402/PluralRules/this-not-ignored.js
This is not yet ready for landing, since the spec is not finalized,
but I'd like to get a preliminary feedback on the structure and list of tests to make it easier to land once we finalize the spec (there's just one issue remaining).
The spec is at https://github.com/tc39/proposal-intl-plural-rules
Can someone give me a general feedback on if this is the right way to structure the patch for the spec?
=> Add Intl.PluralRules tests

test/built-ins/Number/prototype/toFixed/return-type.js
Adds a test to ensure that toFixed returns a string value
=> Add Number.prototype.toFixed return value test

test/built-ins/Number/prototype/toFixed/length.js
Related: #825 
Add a test to confirm that the length member of Number.prototype.toFixed is 1.
=> Test that Number.prototype.toFixed.length is 1

test/built-ins/Array/prototype/every/15.4.4.16-0-2.js, test/built-ins/Array/prototype/every/length.js
=> Add Array.prototype.every.length tests

test/built-ins/Function/prototype/toString/AsyncFunction.js
This is a continuation of 4a5c52beb5c1c12540974ed697e75bfe5c500578.
=> add line feed following `{` of F.p.toString output for dynamic functions

test/built-ins/RegExp/S15.10.2.10_A5.1_T1.js
Thanks to @demurgos for spotting this bug at #858
=> Fix call to assert.notSameValue

test/built-ins/TypedArray/prototype/copyWithin/negative-out-of-bounds-end.js, test/built-ins/TypedArray/prototype/copyWithin/negative-out-of-bounds-start.js, test/built-ins/TypedArray/prototype/copyWithin/negative-out-of-bounds-target.js, test/built-ins/TypedArray/prototype/copyWithin/non-negative-out-of-bounds-end.js, test/built-ins/TypedArray/prototype/copyWithin/non-negative-out-of-bounds-target-and-start.js
ToInteger can result in the values +Infinity and -Infinity.
=> Add tests for %TypedArray%.prototype.copyWithin() with target/start/end=Infinity

test/language/statements/async-generator/yield-star-async-next.js, test/language/statements/async-generator/yield-star-async-return.js, test/language/statements/async-generator/yield-star-async-throw.js, test/language/statements/async-generator/yield-star-sync-next.js, test/language/statements/async-generator/yield-star-sync-return.js, test/language/statements/async-generator/yield-star-sync-throw.js
I'm about to write tests for yield* in async generator.
Here's tests for some basic flow, about execution order.
can I get some feedback before start writing more tests for abrupt cases?
=> Add some tests for execution order for yield* in async generator

test/built-ins/Atomics/wait/did-timeout.js, test/built-ins/Atomics/wait/good-views.js, test/built-ins/Atomics/wait/nan-timeout.js, test/built-ins/Atomics/wait/negative-timeout.js, test/built-ins/Atomics/wait/no-spurious-wakeup.js, test/built-ins/Atomics/wait/was-woken.js, test/built-ins/Atomics/wake/wake-all-on-loc.js, test/built-ins/Atomics/wake/wake-all.js, test/built-ins/Atomics/wake/wake-in-order.js, test/built-ins/Atomics/wake/wake-nan.js, test/built-ins/Atomics/wake/wake-negative.js, test/built-ins/Atomics/wake/wake-one.js, test/built-ins/Atomics/wake/wake-two.js, test/built-ins/Atomics/wake/wake-zero.js, test/built-ins/DataView/proto-from-ctor-realm-sab.js, test/built-ins/SharedArrayBuffer/proto-from-ctor-realm.js, test/built-ins/TypedArrays/buffer-arg-proto-from-ctor-realm-sab.js
=> fix $.agent to $262.agent

test/language/statements/with/unscopables-inc-dec.js
See https://bugzilla.mozilla.org/show_bug.cgi?id=1341061
=> Test that @@unscopables is looked up once for inc/dec.

CONTRIBUTING.md, INTERPRETING.md
=> Document test flag: `generated`

test/language/expressions/async-generators/return-suspendedStart-promise.js, test/language/expressions/async-generators/return-suspendedStart.js, test/language/expressions/async-generators/return-suspendedYield-promise.js, test/language/expressions/async-generators/return-suspendedYield-try-finally-return.js, test/language/expressions/async-generators/return-suspendedYield-try-finally-throw.js, test/language/expressions/async-generators/return-suspendedYield-try-finally.js, test/language/expressions/async-generators/return-suspendedYield.js, test/language/expressions/async-generators/throw-suspendedStart-promise.js, test/language/expressions/async-generators/throw-suspendedStart.js, test/language/expressions/async-generators/throw-suspendedYield-promise.js, test/language/expressions/async-generators/throw-suspendedYield-try-catch.js, test/language/expressions/async-generators/throw-suspendedYield-try-finally-return.js, test/language/expressions/async-generators/throw-suspendedYield-try-finally-throw.js, test/language/expressions/async-generators/throw-suspendedYield-try-finally.js, test/language/expressions/async-generators/throw-suspendedYield.js
=> Add descriptions for async-iter suspended execution tests

test/language/module-code/eval-rqstd-abrupt.js, test/language/module-code/instn-iee-err-ambiguous-as.js, test/language/module-code/instn-iee-err-ambiguous.js, test/language/module-code/instn-iee-err-circular-as.js, test/language/module-code/instn-iee-err-circular.js, test/language/module-code/instn-iee-err-dflt-thru-star-as.js, test/language/module-code/instn-iee-err-dflt-thru-star.js, test/language/module-code/instn-iee-err-not-found-as.js, test/language/module-code/instn-iee-err-not-found.js, test/language/module-code/instn-named-err-ambiguous-as.js, test/language/module-code/instn-named-err-ambiguous.js, test/language/module-code/instn-named-err-dflt-thru-star-as.js, test/language/module-code/instn-named-err-dflt-thru-star-dflt.js, test/language/module-code/instn-named-err-not-found-as.js, test/language/module-code/instn-named-err-not-found-dflt.js, test/language/module-code/instn-named-err-not-found.js, test/language/module-code/instn-star-err-not-found.js
=> Fix runtime error tests previously marked as early errors

test/built-ins/Array/prototype/copyWithin/negative-out-of-bounds-end.js, test/built-ins/Array/prototype/copyWithin/negative-out-of-bounds-start.js, test/built-ins/Array/prototype/copyWithin/negative-out-of-bounds-target.js, test/built-ins/Array/prototype/copyWithin/non-negative-out-of-bounds-end.js, test/built-ins/Array/prototype/copyWithin/non-negative-out-of-bounds-target-and-start.js
Fixes #861
Ref #849
Based on similar cases from `TypedArray.prototype.copyWithin`
=> Add Infinity test cases to Array.prototype.copyWithin

test/language/expressions/delete/S11.4.1_A3.1.js, test/language/expressions/this/S11.1.1_A3.1.js, test/language/expressions/this/S11.1.1_A3.2.js
Closes #771 
_Oh, function, MyFunction!_
=> Fix duplicate function declarations

test/annexB/language/expressions/object/__proto__-duplicate-computed.js, test/language/expressions/object/computed-__proto__.js
=> Add tests for computed __proto__ property keys

test/built-ins/Date/UTC/coercion-errors.js, test/built-ins/Date/UTC/coercion-order.js, test/built-ins/Date/coercion-errors.js, test/built-ins/Date/coercion-order.js
=> Fix Date coercion tests

src/dstr-assignment/obj-rest-obj-own-property.case, src/dstr-assignment/obj-rest-same-name.case, test/language/expressions/assignment/dstr-obj-rest-same-name.js, test/language/statements/for-of/dstr-obj-rest-same-name.js
=> Add case for obj rest name equal to a property

test/built-ins/TypedArrays/buffer-arg-proto-from-ctor-realm-sab.js, test/built-ins/TypedArrays/buffer-arg-use-custom-proto-if-object-sab.js
=> Fix invalid YAML.

src/spread/mult-err-obj-getter-throws.case, test/language/expressions/array/spread-err-mult-err-obj-getter-throws.js, test/language/expressions/call/spread-err-mult-err-obj-getter-throws.js, test/language/expressions/new/spread-err-mult-err-obj-getter-throws.js, test/language/expressions/super/call-spread-err-mult-err-obj-getter-throws.js
I've found this minor issue while working in a case sensitive file system.
=> Fix case sensitive

test/language/expressions/async-arrow-function/async-lineterminator-identifier-throws.js, test/language/expressions/async-arrow-function/early-errors-arrow-formals-lineterminator.js, test/language/expressions/async-arrow-function/early-errors-arrow-ident-lineterminator.js, test/language/expressions/object/method-definition/early-errors-object-method-arguments-in-formal-parameters.js, test/language/expressions/object/method-definition/early-errors-object-method-async-lineterminator.js, test/language/expressions/object/method-definition/early-errors-object-method-await-in-formals-default.js, test/language/expressions/object/method-definition/early-errors-object-method-await-in-formals.js, test/language/expressions/object/method-definition/early-errors-object-method-body-contains-super-call.js, test/language/expressions/object/method-definition/early-errors-object-method-duplicate-parameters.js, test/language/expressions/object/method-definition/early-errors-object-method-eval-in-formal-parameters.js, test/language/expressions/object/method-definition/early-errors-object-method-formals-body-duplicate.js, test/language/expressions/object/method-definition/early-errors-object-method-formals-contains-super-call.js
=> Update cases for async arrow fns with a line terminator

src/async-generators/yield-star-sync-next.case, src/async-generators/yield-star-sync-return.case, src/async-generators/yield-star-sync-throw.case, test/language/expressions/async-generator/named-yield-star-sync-next.js, test/language/expressions/async-generator/named-yield-star-sync-return.js, test/language/expressions/async-generator/named-yield-star-sync-throw.js, test/language/expressions/async-generator/yield-star-sync-next.js, test/language/expressions/async-generator/yield-star-sync-return.js, test/language/expressions/async-generator/yield-star-sync-throw.js, test/language/expressions/class/async-gen-method-static-yield-star-sync-next.js, test/language/expressions/class/async-gen-method-static-yield-star-sync-return.js, test/language/expressions/class/async-gen-method-static-yield-star-sync-throw.js, test/language/expressions/class/async-gen-method-yield-star-sync-next.js, test/language/expressions/class/async-gen-method-yield-star-sync-return.js, test/language/expressions/class/async-gen-method-yield-star-sync-throw.js, test/language/expressions/object/method-definition/async-gen-yield-star-sync-next.js, test/language/expressions/object/method-definition/async-gen-yield-star-sync-return.js, test/language/expressions/object/method-definition/async-gen-yield-star-sync-throw.js, test/language/statements/async-generator/yield-star-sync-next.js, test/language/statements/async-generator/yield-star-sync-return.js, test/language/statements/async-generator/yield-star-sync-throw.js, test/language/statements/class/async-gen-method-static-yield-star-sync-next.js, test/language/statements/class/async-gen-method-static-yield-star-sync-return.js, test/language/statements/class/async-gen-method-static-yield-star-sync-throw.js, test/language/statements/class/async-gen-method-yield-star-sync-next.js, test/language/statements/class/async-gen-method-yield-star-sync-return.js, test/language/statements/class/async-gen-method-yield-star-sync-throw.js
Ordering of done and value property loads changed in
https://github.com/tc39/proposal-async-iteration/commit/395b2e3b2f5acb62f9fae11c5e189423d4af50e6
=> Update Async-from-Sync Iterator yield* tests

test/built-ins/RegExp/property-escapes/Assigned.js, test/built-ins/RegExp/property-escapes/General_Category_-_Other.js, test/built-ins/RegExp/property-escapes/General_Category_-_Surrogate.js
https://github.com/mathiasbynens/unicode-property-escapes-tests/commit/c62ed61cfc7c3c7d596f922facee2c0152555d8f
=> Fix three broken RegExp property escape tests

INTERPRETING.md
=> INTERPRETING.md missed two `$` => `$262` changes.

test/built-ins/ArrayBuffer/length.js, test/built-ins/ArrayBuffer/name.js, test/built-ins/ArrayBuffer/prop-desc.js
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>
=> ArrayBuffer: name, length, prop-desc

test/built-ins/RegExp/prototype/dotAll/length.js, test/built-ins/RegExp/prototype/dotAll/name.js, test/built-ins/RegExp/prototype/dotAll/prop-desc.js, test/built-ins/RegExp/prototype/dotAll/this-val-invalid-obj.js, test/built-ins/RegExp/prototype/dotAll/this-val-non-obj.js, test/built-ins/RegExp/prototype/dotAll/this-val-regexp-prototype.js, test/built-ins/RegExp/prototype/dotAll/this-val-regexp.js
=> Update RegExp#dotAll tests

test/language/statements/async-function/let-newline-await-in-async-function.js, test/language/statements/let/syntax/let-newline-await-in-normal-function.js, test/language/statements/let/syntax/let-newline-yield-in-generator-function.js, test/language/statements/let/syntax/let-newline-yield-in-normal-function.js
Tests for the PR https://github.com/tc39/ecma262/pull/885
=> Tests for PR to Prohibit ASI between 'let' and 'yield'/'await'

harness/propertyHelper.js, test/harness/verifyProperty-value.js
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>
=> Update verifyProperty to allow checking `value`

test/built-ins/Array/isArray/15.4.3.2-0-1.js, test/built-ins/Array/isArray/15.4.3.2-0-2.js, test/built-ins/Array/isArray/15.4.3.2-0-3.js, test/built-ins/Array/isArray/15.4.3.2-0-4.js, test/built-ins/Array/isArray/15.4.3.2-0-5.js, test/built-ins/Array/isArray/15.4.3.2-0-6.js, test/built-ins/Array/isArray/15.4.3.2-0-7.js, test/built-ins/Array/isArray/15.4.3.2-1-1.js, test/built-ins/Array/isArray/15.4.3.2-1-10.js, test/built-ins/Array/isArray/15.4.3.2-1-11.js, test/built-ins/Array/isArray/15.4.3.2-1-12.js, test/built-ins/Array/isArray/15.4.3.2-1-13.js, test/built-ins/Array/isArray/15.4.3.2-1-15.js, test/built-ins/Array/isArray/15.4.3.2-1-2.js, test/built-ins/Array/isArray/15.4.3.2-1-3.js, test/built-ins/Array/isArray/15.4.3.2-1-4.js, test/built-ins/Array/isArray/15.4.3.2-1-5.js, test/built-ins/Array/isArray/15.4.3.2-1-6.js, test/built-ins/Array/isArray/15.4.3.2-1-7.js, test/built-ins/Array/isArray/15.4.3.2-1-8.js, test/built-ins/Array/isArray/15.4.3.2-1-9.js, test/built-ins/Array/isArray/15.4.3.2-2-1.js, test/built-ins/Array/isArray/15.4.3.2-2-2.js, test/built-ins/Array/isArray/15.4.3.2-2-3.js, test/built-ins/Array/isArray/name.js
I added esid to the front matter for Array/isArray.
=> Add esid to Array/isArray front matter

test/built-ins/Array/length/15.4.5.1-3.d-1.js, test/built-ins/Array/length/15.4.5.1-3.d-2.js, test/built-ins/Array/length/15.4.5.1-3.d-3.js, test/built-ins/Array/length/S15.4.2.2_A1.1_T1.js, test/built-ins/Array/length/S15.4.2.2_A1.1_T2.js, test/built-ins/Array/length/S15.4.2.2_A1.1_T3.js, test/built-ins/Array/length/S15.4.2.2_A1.2_T1.js, test/built-ins/Array/length/S15.4.2.2_A2.1_T1.js, test/built-ins/Array/length/S15.4.2.2_A2.2_T1.js, test/built-ins/Array/length/S15.4.2.2_A2.2_T2.js, test/built-ins/Array/length/S15.4.2.2_A2.2_T3.js, test/built-ins/Array/length/S15.4.2.2_A2.3_T1.js, test/built-ins/Array/length/S15.4.2.2_A2.3_T2.js, test/built-ins/Array/length/S15.4.2.2_A2.3_T3.js, test/built-ins/Array/length/S15.4.2.2_A2.3_T4.js, test/built-ins/Array/length/S15.4.2.2_A2.3_T5.js, test/built-ins/Array/length/S15.4.4_A1.3_T1.js, test/built-ins/Array/length/S15.4.5.1_A1.1_T1.js, test/built-ins/Array/length/S15.4.5.1_A1.1_T2.js, test/built-ins/Array/length/S15.4.5.1_A1.2_T1.js, test/built-ins/Array/length/S15.4.5.1_A1.2_T3.js, test/built-ins/Array/length/S15.4.5.1_A1.3_T1.js, test/built-ins/Array/length/S15.4.5.1_A1.3_T2.js, test/built-ins/Array/length/S15.4.5.2_A3_T4.js
This wasn't as bad as I thought it'd be mapping ES5IDs to ESIDs, but I did have to do some of it manually. :/ 
Sorry my editor will clean up trailing whitespace by default. 
@rwaldron @leobalter
=> add esid to frontmatter for Array/length

test/built-ins/Array/of/construct-this-with-the-number-of-arguments.js, test/built-ins/Array/of/creates-a-new-array-from-arguments.js, test/built-ins/Array/of/does-not-use-prototype-properties.js, test/built-ins/Array/of/length.js, test/built-ins/Array/of/name.js, test/built-ins/Array/of/not-a-constructor.js, test/built-ins/Array/of/of.js, test/built-ins/Array/of/return-a-custom-instance.js, test/built-ins/Array/of/return-a-new-array-object.js, test/built-ins/Array/of/return-abrupt-from-contructor.js, test/built-ins/Array/of/return-abrupt-from-data-property-using-proxy.js, test/built-ins/Array/of/return-abrupt-from-data-property.js, test/built-ins/Array/of/return-abrupt-from-setting-length.js, test/built-ins/Array/of/sets-length.js
=> add esid to Array/of

test/built-ins/undefined/15.1.1.3-0.js, test/built-ins/undefined/15.1.1.3-1.js, test/built-ins/undefined/15.1.1.3-2.js, test/built-ins/undefined/15.1.1.3-3.js, test/built-ins/undefined/S15.1.1.3_A1.js, test/built-ins/undefined/S15.1.1.3_A3_T1.js, test/built-ins/undefined/S15.1.1.3_A3_T2.js, test/built-ins/undefined/S15.1.1.3_A4.js
PR also takes care of a few wonky indents.
=> Add `esid` to `built-ins/undefined`

test/built-ins/Array/prototype/entries/iteration-mutable.js, test/built-ins/Array/prototype/entries/iteration.js, test/built-ins/Array/prototype/entries/length.js, test/built-ins/Array/prototype/entries/name.js, test/built-ins/Array/prototype/entries/prop-desc.js, test/built-ins/Array/prototype/entries/return-abrupt-from-this.js, test/built-ins/Array/prototype/entries/returns-iterator-from-object.js, test/built-ins/Array/prototype/entries/returns-iterator.js
=> add esid to array/prototype/entries

test/built-ins/Array/prototype/fill/coerced-indexes.js, test/built-ins/Array/prototype/fill/fill-values-custom-start-and-end.js, test/built-ins/Array/prototype/fill/fill-values-relative-end.js, test/built-ins/Array/prototype/fill/fill-values-relative-start.js, test/built-ins/Array/prototype/fill/fill-values.js, test/built-ins/Array/prototype/fill/length.js, test/built-ins/Array/prototype/fill/name.js, test/built-ins/Array/prototype/fill/prop-desc.js, test/built-ins/Array/prototype/fill/return-abrupt-from-end-as-symbol.js, test/built-ins/Array/prototype/fill/return-abrupt-from-end.js, test/built-ins/Array/prototype/fill/return-abrupt-from-setting-property-value.js, test/built-ins/Array/prototype/fill/return-abrupt-from-start-as-symbol.js, test/built-ins/Array/prototype/fill/return-abrupt-from-start.js, test/built-ins/Array/prototype/fill/return-abrupt-from-this-length-as-symbol.js, test/built-ins/Array/prototype/fill/return-abrupt-from-this-length.js, test/built-ins/Array/prototype/fill/return-abrupt-from-this.js, test/built-ins/Array/prototype/fill/return-this.js
=> add esid to array/prototype/fill tests

test/built-ins/Array/prototype/find/array-altered-during-loop.js, test/built-ins/Array/prototype/find/length.js, test/built-ins/Array/prototype/find/name.js, test/built-ins/Array/prototype/find/predicate-call-parameters.js, test/built-ins/Array/prototype/find/predicate-call-this-non-strict.js, test/built-ins/Array/prototype/find/predicate-call-this-strict.js, test/built-ins/Array/prototype/find/predicate-called-for-each-array-property.js, test/built-ins/Array/prototype/find/predicate-is-not-callable-throws.js, test/built-ins/Array/prototype/find/predicate-not-called-on-empty-array.js, test/built-ins/Array/prototype/find/prop-desc.js, test/built-ins/Array/prototype/find/return-abrupt-from-predicate-call.js, test/built-ins/Array/prototype/find/return-abrupt-from-property.js, test/built-ins/Array/prototype/find/return-abrupt-from-this-length-as-symbol.js, test/built-ins/Array/prototype/find/return-abrupt-from-this-length.js, test/built-ins/Array/prototype/find/return-abrupt-from-this.js, test/built-ins/Array/prototype/find/return-found-value-predicate-result-is-true.js, test/built-ins/Array/prototype/find/return-undefined-if-predicate-returns-false-value.js
=> add esid to array/prototype/find tests

test/built-ins/Array/prototype/findIndex/array-altered-during-loop.js, test/built-ins/Array/prototype/findIndex/length.js, test/built-ins/Array/prototype/findIndex/name.js, test/built-ins/Array/prototype/findIndex/predicate-call-parameters.js, test/built-ins/Array/prototype/findIndex/predicate-call-this-non-strict.js, test/built-ins/Array/prototype/findIndex/predicate-call-this-strict.js, test/built-ins/Array/prototype/findIndex/predicate-called-for-each-array-property.js, test/built-ins/Array/prototype/findIndex/predicate-is-not-callable-throws.js, test/built-ins/Array/prototype/findIndex/predicate-not-called-on-empty-array.js, test/built-ins/Array/prototype/findIndex/prop-desc.js, test/built-ins/Array/prototype/findIndex/return-abrupt-from-predicate-call.js, test/built-ins/Array/prototype/findIndex/return-abrupt-from-property.js, test/built-ins/Array/prototype/findIndex/return-abrupt-from-this-length-as-symbol.js, test/built-ins/Array/prototype/findIndex/return-abrupt-from-this-length.js, test/built-ins/Array/prototype/findIndex/return-abrupt-from-this.js, test/built-ins/Array/prototype/findIndex/return-index-predicate-result-is-true.js, test/built-ins/Array/prototype/findIndex/return-negative-one-if-predicate-returns-false-value.js
=> add esid to array/prototype/findIndex tests

test/built-ins/Array/prototype/join/S15.4.4.5_A1.1_T1.js, test/built-ins/Array/prototype/join/S15.4.4.5_A1.2_T1.js, test/built-ins/Array/prototype/join/S15.4.4.5_A1.2_T2.js, test/built-ins/Array/prototype/join/S15.4.4.5_A1.3_T1.js, test/built-ins/Array/prototype/join/S15.4.4.5_A2_T1.js, test/built-ins/Array/prototype/join/S15.4.4.5_A2_T2.js, test/built-ins/Array/prototype/join/S15.4.4.5_A2_T3.js, test/built-ins/Array/prototype/join/S15.4.4.5_A2_T4.js, test/built-ins/Array/prototype/join/S15.4.4.5_A3.1_T1.js, test/built-ins/Array/prototype/join/S15.4.4.5_A3.1_T2.js, test/built-ins/Array/prototype/join/S15.4.4.5_A3.2_T1.js, test/built-ins/Array/prototype/join/S15.4.4.5_A3.2_T2.js, test/built-ins/Array/prototype/join/S15.4.4.5_A4_T3.js, test/built-ins/Array/prototype/join/S15.4.4.5_A5_T1.js, test/built-ins/Array/prototype/join/S15.4.4.5_A6.6.js, test/built-ins/Array/prototype/join/S15.4.4.5_A6.7.js, test/built-ins/Array/prototype/join/name.js
=> add esid to array/prototype/join

test/built-ins/Array/prototype/keys/iteration-mutable.js, test/built-ins/Array/prototype/keys/iteration.js, test/built-ins/Array/prototype/keys/length.js, test/built-ins/Array/prototype/keys/name.js, test/built-ins/Array/prototype/keys/prop-desc.js, test/built-ins/Array/prototype/keys/return-abrupt-from-this.js, test/built-ins/Array/prototype/keys/returns-iterator-from-object.js, test/built-ins/Array/prototype/keys/returns-iterator.js
=> add esid to array/prototype/keys test

test/built-ins/Array/prototype/pop/S15.4.4.6_A1.1_T1.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A1.2_T1.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A2_T1.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A2_T2.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A2_T3.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A2_T4.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A3_T1.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A3_T2.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A3_T3.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A4_T1.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A4_T2.js, test/built-ins/Array/prototype/pop/S15.4.4.6_A5.7.js, test/built-ins/Array/prototype/pop/name.js
=> add esid to array/prototype/pop tests

test/built-ins/Array/prototype/push/S15.4.4.7_A1_T1.js, test/built-ins/Array/prototype/push/S15.4.4.7_A1_T2.js, test/built-ins/Array/prototype/push/S15.4.4.7_A2_T1.js, test/built-ins/Array/prototype/push/S15.4.4.7_A2_T2.js, test/built-ins/Array/prototype/push/S15.4.4.7_A2_T3.js, test/built-ins/Array/prototype/push/S15.4.4.7_A3.js, test/built-ins/Array/prototype/push/S15.4.4.7_A4_T1.js, test/built-ins/Array/prototype/push/S15.4.4.7_A4_T2.js, test/built-ins/Array/prototype/push/S15.4.4.7_A4_T3.js, test/built-ins/Array/prototype/push/S15.4.4.7_A5_T1.js, test/built-ins/Array/prototype/push/S15.4.4.7_A6.7.js, test/built-ins/Array/prototype/push/name.js
=> add esid to array/prototype/push tests

test/built-ins/Array/prototype/Symbol.iterator.js
=> add esid to array/protoype

test/built-ins/ArrayIteratorPrototype/Symbol.toStringTag/property-descriptor.js, test/built-ins/ArrayIteratorPrototype/Symbol.toStringTag/value-direct.js, test/built-ins/ArrayIteratorPrototype/Symbol.toStringTag/value-from-to-string.js
=> add esid to ArrayIterator/toStringTag tests

test/built-ins/Array/prototype/reverse/S15.4.4.8_A1_T1.js, test/built-ins/Array/prototype/reverse/S15.4.4.8_A1_T2.js, test/built-ins/Array/prototype/reverse/S15.4.4.8_A2_T1.js, test/built-ins/Array/prototype/reverse/S15.4.4.8_A2_T2.js, test/built-ins/Array/prototype/reverse/S15.4.4.8_A2_T3.js, test/built-ins/Array/prototype/reverse/S15.4.4.8_A3_T3.js, test/built-ins/Array/prototype/reverse/S15.4.4.8_A4_T1.js, test/built-ins/Array/prototype/reverse/S15.4.4.8_A4_T2.js, test/built-ins/Array/prototype/reverse/S15.4.4.8_A5.7.js, test/built-ins/Array/prototype/reverse/get_if_present_with_delete.js, test/built-ins/Array/prototype/reverse/name.js
=> add esid to array/prototype/reverse tests

test/built-ins/Array/prototype/shift/S15.4.4.9_A1.1_T1.js, test/built-ins/Array/prototype/shift/S15.4.4.9_A1.2_T1.js, test/built-ins/Array/prototype/shift/S15.4.4.9_A2_T1.js, test/built-ins/Array/prototype/shift/S15.4.4.9_A2_T2.js, test/built-ins/Array/prototype/shift/S15.4.4.9_A2_T3.js, test/built-ins/Array/prototype/shift/S15.4.4.9_A2_T4.js, test/built-ins/Array/prototype/shift/S15.4.4.9_A2_T5.js, test/built-ins/Array/prototype/shift/S15.4.4.9_A3_T3.js, test/built-ins/Array/prototype/shift/S15.4.4.9_A4_T1.js, test/built-ins/Array/prototype/shift/S15.4.4.9_A4_T2.js, test/built-ins/Array/prototype/shift/S15.4.4.9_A5.7.js, test/built-ins/Array/prototype/shift/name.js
=> add esid to array/prototype/shift tests

test/built-ins/Array/prototype/sort/S15.4.4.11_A1.1_T1.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A1.2_T1.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A1.2_T2.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A1.3_T1.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A1.4_T1.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A1.4_T2.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A1.5_T1.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A2.1_T1.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A2.1_T2.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A2.1_T3.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A2.2_T1.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A2.2_T2.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A2.2_T3.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A3_T1.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A3_T2.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A4_T3.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A5_T1.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A6_T2.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A7.7.js, test/built-ins/Array/prototype/sort/S15.4.4.11_A8.js, test/built-ins/Array/prototype/sort/bug_596_1.js, test/built-ins/Array/prototype/sort/bug_596_2.js, test/built-ins/Array/prototype/sort/name.js
=> add esid to array/prototype/sort tests

test/built-ins/Array/prototype/toLocaleString/S15.4.4.3_A1_T1.js, test/built-ins/Array/prototype/toLocaleString/S15.4.4.3_A3_T1.js, test/built-ins/Array/prototype/toLocaleString/S15.4.4.3_A4.7.js, test/built-ins/Array/prototype/toLocaleString/name.js, test/built-ins/Array/prototype/toLocaleString/primitive_this_value.js, test/built-ins/Array/prototype/toLocaleString/primitive_this_value_getter.js
=> add esid to array/prototype/toLocaleString tests

test/built-ins/Array/prototype/Symbol.unscopables/prop-desc.js
=> add esid to array/prototype/Symbol.unscopables tests

test/built-ins/Array/prototype/toString/S15.4.4.2_A1_T1.js, test/built-ins/Array/prototype/toString/S15.4.4.2_A1_T2.js, test/built-ins/Array/prototype/toString/S15.4.4.2_A1_T3.js, test/built-ins/Array/prototype/toString/S15.4.4.2_A1_T4.js, test/built-ins/Array/prototype/toString/S15.4.4.2_A3_T1.js, test/built-ins/Array/prototype/toString/S15.4.4.2_A4.7.js, test/built-ins/Array/prototype/toString/name.js
=> add esid to array/prototype/toString tests

test/built-ins/Array/prototype/unshift/S15.4.4.13_A1_T1.js, test/built-ins/Array/prototype/unshift/S15.4.4.13_A1_T2.js, test/built-ins/Array/prototype/unshift/S15.4.4.13_A2_T1.js, test/built-ins/Array/prototype/unshift/S15.4.4.13_A2_T2.js, test/built-ins/Array/prototype/unshift/S15.4.4.13_A2_T3.js, test/built-ins/Array/prototype/unshift/S15.4.4.13_A3_T2.js, test/built-ins/Array/prototype/unshift/S15.4.4.13_A4_T1.js, test/built-ins/Array/prototype/unshift/S15.4.4.13_A4_T2.js, test/built-ins/Array/prototype/unshift/S15.4.4.13_A5.7.js, test/built-ins/Array/prototype/unshift/name.js
=> add esid to array/prototype/unshift tests

test/built-ins/Array/prototype/values/iteration-mutable.js, test/built-ins/Array/prototype/values/iteration.js, test/built-ins/Array/prototype/values/length.js, test/built-ins/Array/prototype/values/name.js, test/built-ins/Array/prototype/values/prop-desc.js, test/built-ins/Array/prototype/values/returns-iterator-from-object.js, test/built-ins/Array/prototype/values/returns-iterator.js, test/built-ins/Array/prototype/values/this-val-non-obj-coercible.js
=> add esid to array/prototype/values tests

test/built-ins/ArrayBuffer/allocation-limit.js, test/built-ins/ArrayBuffer/data-allocation-after-object-creation.js, test/built-ins/ArrayBuffer/newtarget-prototype-is-not-object.js, test/built-ins/ArrayBuffer/prototype-from-newtarget.js, test/built-ins/ArrayBuffer/undefined-newtarget-throws.js, test/built-ins/ArrayBuffer/zero-length.js
=> add esid to ArrayBuffer tests

test/built-ins/ArrayBuffer/isView/length.js, test/built-ins/ArrayBuffer/isView/name.js
=> add esid to ArrayBuffer/isView tests

test/built-ins/ArrayBuffer/prototype/Symbol.toStringTag.js, test/built-ins/ArrayBuffer/prototype/constructor.js
=> add esid to ArrayBuffer/prototype tests

test/built-ins/ArrayBuffer/prototype/byteLength/length.js, test/built-ins/ArrayBuffer/prototype/byteLength/name.js
=> add esid to ArrayBuffer/prototype/byteLength tests

test/built-ins/ArrayBuffer/prototype/slice/context-is-not-arraybuffer-object.js, test/built-ins/ArrayBuffer/prototype/slice/context-is-not-object.js, test/built-ins/ArrayBuffer/prototype/slice/descriptor.js, test/built-ins/ArrayBuffer/prototype/slice/end-default-if-absent.js, test/built-ins/ArrayBuffer/prototype/slice/end-default-if-undefined.js, test/built-ins/ArrayBuffer/prototype/slice/end-exceeds-length.js, test/built-ins/ArrayBuffer/prototype/slice/extensible.js, test/built-ins/ArrayBuffer/prototype/slice/length.js, test/built-ins/ArrayBuffer/prototype/slice/name.js, test/built-ins/ArrayBuffer/prototype/slice/negative-end.js, test/built-ins/ArrayBuffer/prototype/slice/negative-start.js, test/built-ins/ArrayBuffer/prototype/slice/nonconstructor.js, test/built-ins/ArrayBuffer/prototype/slice/number-conversion.js, test/built-ins/ArrayBuffer/prototype/slice/species-constructor-is-not-object.js, test/built-ins/ArrayBuffer/prototype/slice/species-constructor-is-undefined.js, test/built-ins/ArrayBuffer/prototype/slice/species-is-not-constructor.js, test/built-ins/ArrayBuffer/prototype/slice/species-is-not-object.js, test/built-ins/ArrayBuffer/prototype/slice/species-is-null.js, test/built-ins/ArrayBuffer/prototype/slice/species-is-undefined.js, test/built-ins/ArrayBuffer/prototype/slice/species-returns-larger-arraybuffer.js, test/built-ins/ArrayBuffer/prototype/slice/species-returns-not-arraybuffer.js, test/built-ins/ArrayBuffer/prototype/slice/species-returns-same-arraybuffer.js, test/built-ins/ArrayBuffer/prototype/slice/species-returns-smaller-arraybuffer.js, test/built-ins/ArrayBuffer/prototype/slice/species.js, test/built-ins/ArrayBuffer/prototype/slice/start-default-if-absent.js, test/built-ins/ArrayBuffer/prototype/slice/start-default-if-undefined.js, test/built-ins/ArrayBuffer/prototype/slice/start-exceeds-end.js, test/built-ins/ArrayBuffer/prototype/slice/start-exceeds-length.js, test/built-ins/ArrayBuffer/prototype/slice/tointeger-conversion-end.js, test/built-ins/ArrayBuffer/prototype/slice/tointeger-conversion-start.js
=> add esid to ArrayBuffer/prototype/slice tests

test/built-ins/ArrayBuffer/Symbol.species/symbol-species-name.js
=> add esid to ArrayBuffer/symbol.species tests

test/built-ins/Boolean/prototype/S15.6.3.1_A1.js, test/built-ins/Boolean/prototype/S15.6.3.1_A2.js, test/built-ins/Boolean/prototype/S15.6.3.1_A3.js, test/built-ins/Boolean/prototype/S15.6.3.1_A4.js, test/built-ins/Boolean/prototype/S15.6.4_A1.js, test/built-ins/Boolean/prototype/S15.6.4_A2.js, test/built-ins/Boolean/prototype/constructor/S15.6.4.1_A1.js, test/built-ins/Boolean/prototype/toString/S15.6.4.2_A1_T1.js, test/built-ins/Boolean/prototype/toString/S15.6.4.2_A1_T2.js, test/built-ins/Boolean/prototype/toString/S15.6.4.2_A2_T1.js, test/built-ins/Boolean/prototype/toString/S15.6.4.2_A2_T2.js, test/built-ins/Boolean/prototype/toString/S15.6.4.2_A2_T3.js, test/built-ins/Boolean/prototype/toString/S15.6.4.2_A2_T4.js, test/built-ins/Boolean/prototype/toString/S15.6.4.2_A2_T5.js, test/built-ins/Boolean/prototype/toString/length.js, test/built-ins/Boolean/prototype/toString/name.js, test/built-ins/Boolean/prototype/valueOf/S15.6.4.3_A1_T1.js, test/built-ins/Boolean/prototype/valueOf/S15.6.4.3_A1_T2.js, test/built-ins/Boolean/prototype/valueOf/S15.6.4.3_A2_T1.js, test/built-ins/Boolean/prototype/valueOf/S15.6.4.3_A2_T2.js, test/built-ins/Boolean/prototype/valueOf/S15.6.4.3_A2_T3.js, test/built-ins/Boolean/prototype/valueOf/S15.6.4.3_A2_T4.js, test/built-ins/Boolean/prototype/valueOf/S15.6.4.3_A2_T5.js, test/built-ins/Boolean/prototype/valueOf/length.js, test/built-ins/Boolean/prototype/valueOf/name.js
=> update esid on Boolean/prototype tests

harness/arrayContains.js, harness/assert.js, harness/assertRelativeDateMs.js, harness/atomicsHelper.js, harness/byteConversionValues.js, harness/compareArray.js, harness/dateConstants.js, harness/decimalToHexString.js, harness/detachArrayBuffer.js, harness/doneprintHandle.js, harness/fnGlobalObject.js, harness/nans.js, harness/nativeFunctionMatcher.js, harness/promiseHelper.js, harness/propertyHelper.js, harness/proxyTrapsHelper.js, harness/regExpUtils.js, harness/simdUtilities.js, harness/sta.js, harness/tcoHelper.js, harness/testAtomics.js, harness/testBuiltInObject.js, harness/testIntl.js, harness/testTypedArray.js, harness/timer.js, test/harness/arrayContains.js, test/harness/detachArrayBuffer-host-detachArrayBuffer.js, test/harness/detachArrayBuffer.js
Before: 
```
$ python tools/lint/lint.py --whitelist lint.whitelist harness/*.js
Linting 25 files.
Linting complete. 25 errors found.
harness/regExpUtils.js: FRONTMATTER - No valid YAML-formatted frontmatter
harness/regExpUtils.js: LICENSE - No license information found.
harness/dateConstants.js: FRONTMATTER - No valid YAML-formatted frontmatter
harness/testTypedArray.js: FRONTMATTER - No valid YAML-formatted frontmatter
harness/fnGlobalObject.js: FRONTMATTER - No valid YAML-formatted frontmatter
harness/fnGlobalObject.js: LICENSE - No license information found.
harness/simdUtilities.js: FRONTMATTER - No valid YAML-formatted frontmatter
harness/decimalToHexString.js: FRONTMATTER - No valid YAML-formatted frontmatter
harness/byteConversionValues.js: FRONTMATTER - No valid YAML-formatted …
```
=> Update all harness files to pass linting.

test/built-ins/ArrayBuffer/Symbol.species/length.js, test/built-ins/ArrayIteratorPrototype/next/Float32Array.js, test/built-ins/ArrayIteratorPrototype/next/Float64Array.js, test/built-ins/ArrayIteratorPrototype/next/Int16Array.js, test/built-ins/ArrayIteratorPrototype/next/Int32Array.js, test/built-ins/ArrayIteratorPrototype/next/Int8Array.js, test/built-ins/ArrayIteratorPrototype/next/Uint16Array.js, test/built-ins/ArrayIteratorPrototype/next/Uint32Array.js, test/built-ins/ArrayIteratorPrototype/next/Uint8Array.js, test/built-ins/ArrayIteratorPrototype/next/Uint8ClampedArray.js, test/built-ins/ArrayIteratorPrototype/next/args-mapped-expansion-after-exhaustion.js, test/built-ins/ArrayIteratorPrototype/next/args-mapped-expansion-before-exhaustion.js, test/built-ins/ArrayIteratorPrototype/next/args-mapped-iteration.js, test/built-ins/ArrayIteratorPrototype/next/args-mapped-truncation-before-exhaustion.js, test/built-ins/ArrayIteratorPrototype/next/args-unmapped-expansion-after-exhaustion.js, test/built-ins/ArrayIteratorPrototype/next/args-unmapped-expansion-before-exhaustion.js, test/built-ins/ArrayIteratorPrototype/next/args-unmapped-iteration.js, test/built-ins/ArrayIteratorPrototype/next/args-unmapped-truncation-before-exhaustion.js, test/built-ins/ArrayIteratorPrototype/next/iteration-mutable.js, test/built-ins/ArrayIteratorPrototype/next/iteration.js, test/built-ins/ArrayIteratorPrototype/next/length.js, test/built-ins/ArrayIteratorPrototype/next/name.js, test/built-ins/ArrayIteratorPrototype/next/non-own-slots.js, test/built-ins/ArrayIteratorPrototype/next/property-descriptor.js
@leobalter @rwaldron Can you pay extra attention to this one because the es6id didn't map to the spec perfectly.
=> add esid to ArrayIterator/next tests

test/built-ins/Boolean/S15.6.1.1_A1_T1.js, test/built-ins/Boolean/S15.6.1.1_A1_T2.js, test/built-ins/Boolean/S15.6.1.1_A1_T3.js, test/built-ins/Boolean/S15.6.1.1_A1_T4.js, test/built-ins/Boolean/S15.6.1.1_A1_T5.js, test/built-ins/Boolean/S15.6.1.1_A2.js, test/built-ins/Boolean/S15.6.2.1_A1.js, test/built-ins/Boolean/S15.6.2.1_A2.js, test/built-ins/Boolean/S15.6.2.1_A3.js, test/built-ins/Boolean/S15.6.2.1_A4.js, test/built-ins/Boolean/S15.6.3_A1.js, test/built-ins/Boolean/S15.6.3_A2.js, test/built-ins/Boolean/S15.6.3_A3.js, test/built-ins/Boolean/S9.2_A1_T1.js, test/built-ins/Boolean/S9.2_A2_T1.js, test/built-ins/Boolean/S9.2_A3_T1.js, test/built-ins/Boolean/S9.2_A4_T1.js, test/built-ins/Boolean/S9.2_A4_T3.js, test/built-ins/Boolean/S9.2_A5_T1.js, test/built-ins/Boolean/S9.2_A5_T3.js, test/built-ins/Boolean/S9.2_A6_T1.js, test/built-ins/Boolean/symbol-coercion.js
=> add esid to boolean frontmatter

test/built-ins/DataView/prototype/Symbol.toStringTag.js, test/built-ins/DataView/prototype/buffer/length.js, test/built-ins/DataView/prototype/buffer/name.js, test/built-ins/DataView/prototype/byteLength/length.js, test/built-ins/DataView/prototype/byteLength/name.js, test/built-ins/DataView/prototype/byteOffset/length.js, test/built-ins/DataView/prototype/byteOffset/name.js, test/built-ins/DataView/prototype/getFloat32/name.js, test/built-ins/DataView/prototype/getFloat64/name.js, test/built-ins/DataView/prototype/getInt16/name.js, test/built-ins/DataView/prototype/getInt32/name.js, test/built-ins/DataView/prototype/getInt8/length.js, test/built-ins/DataView/prototype/getInt8/name.js, test/built-ins/DataView/prototype/getUint16/name.js, test/built-ins/DataView/prototype/getUint32/name.js, test/built-ins/DataView/prototype/getUint8/length.js, test/built-ins/DataView/prototype/getUint8/name.js, test/built-ins/DataView/prototype/setFloat32/name.js, test/built-ins/DataView/prototype/setFloat64/name.js, test/built-ins/DataView/prototype/setInt16/name.js, test/built-ins/DataView/prototype/setInt32/name.js, test/built-ins/DataView/prototype/setInt8/length.js, test/built-ins/DataView/prototype/setInt8/name.js, test/built-ins/DataView/prototype/setUint16/name.js, test/built-ins/DataView/prototype/setUint32/name.js, test/built-ins/DataView/prototype/setUint8/length.js, test/built-ins/DataView/prototype/setUint8/name.js
=> add esid to Dataview frontmatter

test/built-ins/Proxy/ownKeys/call-parameters-object-getownpropertynames.js, test/built-ins/Proxy/ownKeys/call-parameters-object-getownpropertysymbols.js, test/built-ins/Proxy/ownKeys/call-parameters-object-keys.js, test/built-ins/Proxy/ownKeys/extensible-return-trap-result-absent-not-configurable-keys.js, test/built-ins/Proxy/ownKeys/extensible-return-trap-result.js, test/built-ins/Proxy/ownKeys/not-extensible-missing-keys-throws.js, test/built-ins/Proxy/ownKeys/not-extensible-new-keys-throws.js, test/built-ins/Proxy/ownKeys/not-extensible-return-keys.js, test/built-ins/Proxy/ownKeys/null-handler.js, test/built-ins/Proxy/ownKeys/return-all-non-configurable-keys.js, test/built-ins/Proxy/ownKeys/return-duplicate-entries-throws.js, test/built-ins/Proxy/ownKeys/return-duplicate-symbol-entries-throws.js, test/built-ins/Proxy/ownKeys/return-is-abrupt.js, test/built-ins/Proxy/ownKeys/return-not-list-object-throws-realm.js, test/built-ins/Proxy/ownKeys/return-not-list-object-throws.js, test/built-ins/Proxy/ownKeys/trap-is-not-callable-realm.js, test/built-ins/Proxy/ownKeys/trap-is-not-callable.js, test/built-ins/Proxy/ownKeys/trap-is-undefined.js
Ref: https://github.com/tc39/ecma262/pull/833
=> Proxy, [[OwnPropertyKeys]]: If trapResult contains any duplicate entries, throw a TypeError

test/language/statements/do-while/decl-fun.js
=> Fix erroneous description for one of the `do ... while` tests

test/language/expressions/greater-than-or-equal/bigint-and-number.js
Ref https://github.com/tc39/test262/pull/1198#discussion_r137060514
cc @anba
=> Fix assertion for Number.MIN_VALUE >= 0n

test/intl402/Collator/prototype/10.3_a.js, test/intl402/DateTimeFormat/prototype/12.3_a.js, test/intl402/NumberFormat/prototype/11.3_a.js
This proposal was started in https://github.com/tc39/ecma402/issues/122,
and specified in https://github.com/tc39/ecma402/pull/148
=> Add tests for proposal to make Intl prototypes not instances

test/harness/testTypedArray-conversions-call-error.js, test/harness/testTypedArray-conversions.js, test/harness/testTypedArray.js
Caught in the CI run where it lints all the files.
nice catch, @rwaldron!
=> Missing features in the test/harness files

test/intl402/Collator/default-options-object-prototype.js, test/intl402/Date/prototype/toLocaleString/default-options-object-prototype.js, test/intl402/DateTimeFormat/default-options-object-prototype.js, test/intl402/Number/prototype/toLocaleString/default-options-object-prototype.js, test/intl402/NumberFormat/default-options-object-prototype.js, test/intl402/String/prototype/localeCompare/default-options-object-prototype.js
Tests for ECMA 402 PR https://github.com/tc39/ecma402/pull/170
The tests on Date/DateTimeFormat are valid without the PR.
=> intl: Tests for default options tweak proposal

test/language/expressions/object/identifier-shorthand-invalid-computed-name.js, test/language/expressions/object/identifier-shorthand-invalid-zero.js
=> Add tests to verify valid object shorthand properties

harness/typeCoercion.js, test/built-ins/BigInt/asUintN/arithmetic.js, test/built-ins/BigInt/asUintN/asUintN.js, test/built-ins/BigInt/asUintN/bigint-tobigint.js, test/built-ins/BigInt/asUintN/bits-toindex.js, test/built-ins/BigInt/asUintN/length.js, test/built-ins/BigInt/asUintN/name.js, test/built-ins/BigInt/asUintN/order-of-steps.js
* typeCoercion.js supports ToIndex
* typeCoercion.js supports ToBigInt
* updated BigInt.asIntN type coercion tests to use typeCoercion.js
I haven't run this through any implementation to test it yet, so there may be silly typos. I'll look into possibly doing that tomorrow.
=> BigInt.asUintN tests

harness/typeCoercion.js, test/built-ins/BigInt/prototype/valueOf/length.js, test/built-ins/BigInt/prototype/valueOf/name.js, test/built-ins/BigInt/prototype/valueOf/prop-desc.js, test/built-ins/BigInt/prototype/valueOf/this-value-err.js, test/built-ins/BigInt/prototype/valueOf/this-value.js
Tests for the BigInt valueOf method
=> BigInt valueOf tests

test/intl402/DateTimeFormat/prototype/resolvedOptions/hourCycle.js
Adds a test for https://github.com/tc39/ecma402/pull/135
=> Intl.DateTimeFormat hourCycle tests

test/language/expressions/unary-minus/bigint-non-primitive.js, test/language/expressions/unary-minus/bigint.js
=> BigInt unary minus tests

test/built-ins/RegExp/incomplete_hex_unicode_escape.js
See relevant firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1408452
=> Test for proper handling of incomplete hex escapes

.travis.yml
=> ci: Add email notifications for on_failure

CONTRIBUTING.md
=> CONTRIBUTING.md Fix mistake in test generation section

tools/lint/lint.py
=> tools/lint: install  PyYAML if not available

test/built-ins/BigInt/prototype/Symbol.toStringTag.js
Tests the fix for https://github.com/tc39/proposal-bigint/issues/92
=> BigInt: Add test for BigInt.prototype[Symbol.toStringTag]

test/built-ins/BigInt/prototype/Symbol.toStringTag.js
=> Add missing parameter and reorder actual, expected assertion parameters

src/class-fields/initializer-eval-super/cls-decl-fields-eval.template, src/class-fields/initializer-eval-super/cls-decl-fields-indirect-eval.template, src/class-fields/initializer-eval-super/cls-expr-fields-eval.template, src/class-fields/initializer-eval-super/cls-expr-fields-indirect-eval.template, src/class-fields/initializer-eval/cls-expr-fields-eval.template, src/class-fields/initializer-eval/cls-expr-fields-indirect-eval.template, test/language/expressions/class/fields-derived-cls-direct-eval-err-contains-supercall-1.js, test/language/expressions/class/fields-derived-cls-direct-eval-err-contains-supercall-2.js, test/language/expressions/class/fields-derived-cls-direct-eval-err-contains-supercall.js, test/language/expressions/class/fields-derived-cls-direct-eval-err-contains-superproperty-1.js, test/language/expressions/class/fields-derived-cls-direct-eval-err-contains-superproperty-2.js, test/language/expressions/class/fields-derived-cls-indirect-eval-err-contains-supercall-1.js, test/language/expressions/class/fields-derived-cls-indirect-eval-err-contains-supercall-2.js, test/language/expressions/class/fields-derived-cls-indirect-eval-err-contains-supercall.js, test/language/expressions/class/fields-derived-cls-indirect-eval-err-contains-superproperty-1.js, test/language/expressions/class/fields-derived-cls-indirect-eval-err-contains-superproperty-2.js, test/language/expressions/class/fields-direct-eval-err-contains-arguments.js, test/language/expressions/class/fields-direct-eval-err-contains-newcall.js, test/language/expressions/class/fields-indirect-eval-err-contains-arguments.js, test/language/expressions/class/fields-indirect-eval-err-contains-newcall.js, test/language/statements/class/fields-derived-cls-direct-eval-err-contains-supercall-1.js, test/language/statements/class/fields-derived-cls-direct-eval-err-contains-supercall-2.js, test/language/statements/class/fields-derived-cls-direct-eval-err-contains-supercall.js, test/language/statements/class/fields-derived-cls-direct-eval-err-contains-superproperty-1.js, test/language/statements/class/fields-derived-cls-direct-eval-err-contains-superproperty-2.js, test/language/statements/class/fields-derived-cls-indirect-eval-err-contains-supercall-1.js, test/language/statements/class/fields-derived-cls-indirect-eval-err-contains-supercall-2.js, test/language/statements/class/fields-derived-cls-indirect-eval-err-contains-supercall.js, test/language/statements/class/fields-derived-cls-indirect-eval-err-contains-superproperty-1.js, test/language/statements/class/fields-derived-cls-indirect-eval-err-contains-superproperty-2.js
=>  fix typos in class field templates

test/built-ins/Promise/prototype/finally/species-constructor.js, test/built-ins/Promise/prototype/finally/species-symbol.js
=> Promise.p.finally: test SpeciesConstructor and Symbol.species lookup

.travis.yml, CONTRIBUTING.md
This is intended to resolve gh-1285.
=> Formalize installation procedure

test/intl402/DateTimeFormat/prototype/resolvedOptions/resolved-locale-with-hc-unicode.js
Tests for the proposed change in tc39/ecma402#204
=> Add test case for tc39/ecma402#204

harness/dateConstants.js, test/intl402/DateTimeFormat/prototype/format/date-constructor-not-called.js, test/intl402/DateTimeFormat/prototype/format/time-clip-near-time-boundaries.js, test/intl402/DateTimeFormat/prototype/format/time-clip-to-integer.js, test/intl402/DateTimeFormat/prototype/formatToParts/date-constructor-not-called.js, test/intl402/DateTimeFormat/prototype/formatToParts/time-clip-near-time-boundaries.js, test/intl402/DateTimeFormat/prototype/formatToParts/time-clip-to-integer.js
tc39/ecma402#194 is not yet merged and may need to be presented at tc39 (https://github.com/tc39/ecma402/pull/194#issuecomment-340605709).
=> Add test cases for tc39/ecma402#194

test/built-ins/TypedArrays/typedarray-arg-detached-when-species-retrieved-different-type.js, test/built-ins/TypedArrays/typedarray-arg-detached-when-species-retrieved-same-type.js
This is a test case for the normative change in tc39/ecma262#1009 (not yet approved or merged!).
=> Add test case for tc39/ecma262#1009

test/built-ins/Promise/prototype/finally/invokes-then-with-function.js
- per https://github.com/tc39/ecma262/pull/1083#issuecomment-361775023
=> Promise.prototype.finally: add more tests

tools/generation/lib/case.py, tools/generation/lib/expander.py, tools/generation/lib/template.py, tools/generation/test/expected/normal/nested/path2-normal.js, tools/generation/test/expected/normal/path1-normal.js, tools/generation/test/fixtures/normal.case, tools/generation/test/fixtures/normal/normal.template
@leobalter identified a deficiency in the generation tool this evening.
=> [generation] Tolerate unicode in source files

test/built-ins/Map/iterator-items-are-not-object.js, test/built-ins/Math/atan2/S15.8.2.5_A16.js, test/built-ins/Math/atan2/S15.8.2.5_A8.js, test/built-ins/Math/pow/applying-the-exp-operator_A1.js, test/built-ins/Math/pow/applying-the-exp-operator_A10.js, test/built-ins/Math/pow/applying-the-exp-operator_A11.js, test/built-ins/Math/pow/applying-the-exp-operator_A12.js, test/built-ins/Math/pow/applying-the-exp-operator_A13.js, test/built-ins/Math/pow/applying-the-exp-operator_A14.js, test/built-ins/Math/pow/applying-the-exp-operator_A15.js, test/built-ins/Math/pow/applying-the-exp-operator_A16.js, test/built-ins/Math/pow/applying-the-exp-operator_A17.js, test/built-ins/Math/pow/applying-the-exp-operator_A18.js, test/built-ins/Math/pow/applying-the-exp-operator_A19.js, test/built-ins/Math/pow/applying-the-exp-operator_A2.js, test/built-ins/Math/pow/applying-the-exp-operator_A20.js, test/built-ins/Math/pow/applying-the-exp-operator_A21.js, test/built-ins/Math/pow/applying-the-exp-operator_A22.js, test/built-ins/Math/pow/applying-the-exp-operator_A3.js, test/built-ins/Math/pow/applying-the-exp-operator_A4.js, test/built-ins/Math/pow/applying-the-exp-operator_A5.js, test/built-ins/Math/pow/applying-the-exp-operator_A6.js, test/built-ins/Math/pow/applying-the-exp-operator_A7.js, test/built-ins/Math/pow/applying-the-exp-operator_A8.js, test/built-ins/Math/pow/applying-the-exp-operator_A9.js
=> Fix whitespace

test/built-ins/TypedArray/prototype/set/array-arg-src-tonumber-value-type-conversions.js
=> Add missing feature flag to TA + BigInt test

test/language/expressions/tagged-template/cache-eval-inner-function.js
Thanks to @caitp  for highlighting this test case in https://github.com/tc39/ecma262/pull/890#issuecomment-365342631
=> Add test for eval-in-function template tags

test/built-ins/TypedArray/prototype/buffer/BigInt/detached-buffer.js, test/built-ins/TypedArray/prototype/buffer/BigInt/return-buffer.js, test/built-ins/TypedArray/prototype/subarray/BigInt/return-abrupt-from-begin-symbol.js, test/built-ins/TypedArray/prototype/subarray/BigInt/return-abrupt-from-begin.js, test/built-ins/TypedArray/prototype/subarray/BigInt/return-abrupt-from-end.js, test/built-ins/TypedArray/prototype/toLocaleString/BigInt/empty-instance-returns-empty-string.js, test/built-ins/TypedArray/prototype/toLocaleString/BigInt/get-length-uses-internal-arraylength.js, test/built-ins/TypedArray/prototype/toLocaleString/BigInt/return-abrupt-from-firstelement-tolocalestring.js, test/built-ins/TypedArray/prototype/toLocaleString/BigInt/return-abrupt-from-nextelement-tolocalestring.js, test/built-ins/TypedArray/prototype/toLocaleString/BigInt/return-result.js
=> Remove unused parameter for testWithBigIntTypedArrayConstructors

test/built-ins/AsyncGeneratorPrototype/Symbol.toStringTag.js, test/built-ins/AsyncGeneratorPrototype/constructor.js, test/built-ins/AsyncGeneratorPrototype/next/iterator-result-prototype.js, test/built-ins/AsyncGeneratorPrototype/next/length.js, test/built-ins/AsyncGeneratorPrototype/next/name.js, test/built-ins/AsyncGeneratorPrototype/next/prop-desc.js, test/built-ins/AsyncGeneratorPrototype/next/request-queue-await-order.js, test/built-ins/AsyncGeneratorPrototype/next/request-queue-order-state-executing.js, test/built-ins/AsyncGeneratorPrototype/next/request-queue-order.js, test/built-ins/AsyncGeneratorPrototype/next/request-queue-promise-resolve-order.js, test/built-ins/AsyncGeneratorPrototype/next/return-promise.js, test/built-ins/AsyncGeneratorPrototype/next/this-val-not-async-generator.js, test/built-ins/AsyncGeneratorPrototype/next/this-val-not-object.js, test/built-ins/AsyncGeneratorPrototype/return/iterator-result-prototype.js, test/built-ins/AsyncGeneratorPrototype/return/length.js, test/built-ins/AsyncGeneratorPrototype/return/name.js, test/built-ins/AsyncGeneratorPrototype/return/prop-desc.js, test/built-ins/AsyncGeneratorPrototype/return/request-queue-order-state-executing.js, test/built-ins/AsyncGeneratorPrototype/return/return-promise.js, test/built-ins/AsyncGeneratorPrototype/return/return-state-completed.js, test/built-ins/AsyncGeneratorPrototype/return/this-val-not-async-generator.js, test/built-ins/AsyncGeneratorPrototype/return/this-val-not-object.js, test/built-ins/AsyncGeneratorPrototype/throw/length.js, test/built-ins/AsyncGeneratorPrototype/throw/name.js, test/built-ins/AsyncGeneratorPrototype/throw/prop-desc.js, test/built-ins/AsyncGeneratorPrototype/throw/request-queue-order-state-executing.js, test/built-ins/AsyncGeneratorPrototype/throw/return-rejected-promise.js, test/built-ins/AsyncGeneratorPrototype/throw/this-val-not-async-generator.js, test/built-ins/AsyncGeneratorPrototype/throw/this-val-not-object.js, test/built-ins/AsyncGeneratorPrototype/throw/throw-state-completed.js
=> async-iteration: first set of AsyncGeneratorPrototype tests

test/built-ins/ArrayBuffer/length.js, test/built-ins/SharedArrayBuffer/length.js, test/built-ins/TypedArray/invoked.js, test/built-ins/TypedArray/length.js, test/built-ins/TypedArray/name.js, test/built-ins/TypedArray/prototype.js, test/built-ins/TypedArrays/BigInt64Array/length.js, test/built-ins/TypedArrays/BigUint64Array/length.js, test/built-ins/TypedArrays/Float32Array/length.js, test/built-ins/TypedArrays/Float64Array/length.js, test/built-ins/TypedArrays/Int16Array/length.js, test/built-ins/TypedArrays/Int32Array/length.js, test/built-ins/TypedArrays/Int8Array/length.js, test/built-ins/TypedArrays/Uint16Array/length.js, test/built-ins/TypedArrays/Uint32Array/length.js, test/built-ins/TypedArrays/Uint8Array/length.js, test/built-ins/TypedArrays/Uint8ClampedArray/length.js
=> Fix length prop tests for the TypedArrays ctors family

test/built-ins/AsyncFromSyncIteratorPrototype/next/return-promise.js, test/built-ins/AsyncFromSyncIteratorPrototype/return/iterator-result-unwrap-promise.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/iterator-result-poisoned-done.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/iterator-result-poisoned-value.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/iterator-result-unwrap-promise.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/iterator-result.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/poisoned-get-throw.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/poisoned-throw.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/result-object-error.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-undefined.js, test/built-ins/TypedArrays/ctors/buffer-arg/bufferbyteoffset-throws-from-modulo-element-size.js, test/built-ins/TypedArrays/ctors/buffer-arg/byteoffset-throws-from-modulo-element-size.js
Fixes issues in: https://github.com/tc39/test262/issues/1470
Thanks for the finds, @anba !
=> TypedArray and Async Iteration bug fixes

test/built-ins/TypedArrays/ctors-bigint/object-arg/#undefined-tobigint.js#, test/built-ins/TypedArrays/ctors-bigint/object-arg/bigint-tobigint64.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/bigint-tobiguint64.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/boolean-tobigint.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/null-tobigint.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/number-tobigint.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/string-nan-tobigint.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/string-tobigint.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/symbol-tobigint.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/throws-setting-obj-to-primitive-typeerror.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/throws-setting-obj-to-primitive.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/throws-setting-obj-tostring.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/throws-setting-obj-valueof-typeerror.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/throws-setting-obj-valueof.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/undefined-tobigint.js, test/built-ins/TypedArrays/ctors-bigint/typedarray-arg/src-typedarray-not-big-throws.js, test/built-ins/TypedArrays/ctors/typedarray-arg/src-typedarray-big-throws.js
These tests test big int conversions the TypedArray ( object ) constructor to BigUint64Arrays and BigInt64Arrays.
Please carefully check my math in:
https://github.com/tc39/test262/pull/1469/commits/c2b0dd074b476fd13801885afed63d2bee4e753f#diff-64dc9707edf46514eec6565e02b094d9
and 
https://github.com/tc39/test262/pull/1469/commits/c2b0dd074b476fd13801885afed63d2bee4e753f#diff-82cea797113325d9b6a206a9865093ea
=> Bigint typedarray conversion

test/built-ins/TypedArray/prototype/fill/BigInt/fill-values-conversion-once.js, test/built-ins/TypedArray/prototype/fill/BigInt/fill-values-non-numeric-throw.js, test/built-ins/TypedArray/prototype/set/BigInt/array-arg-negative-integer-offset-throws.js, test/built-ins/TypedArray/prototype/set/BigInt/array-arg-return-abrupt-from-tointeger-offset-symbol.js, test/built-ins/TypedArray/prototype/set/BigInt/array-arg-targetbuffer-detached-on-tointeger-offset-throws.js, test/built-ins/TypedArray/prototype/set/BigInt/array-arg-targetbuffer-detached-throws.js
=> WIP BigInt: some fixes listed in #1461

test/built-ins/TypedArray/prototype/set/BigInt/string-tobigint.js, test/built-ins/TypedArrays/ctors-bigint/object-arg/string-tobigint.js, test/built-ins/TypedArrays/internals/Set/BigInt/string-tobigint.js
small fix -- we thought it was a big in V8 but it was a bug in my test :)
=> BigInt: fix error type in BigInt from string conversion

test/language/expressions/greater-than-or-equal/bigint-and-incomparable-string.js, test/language/expressions/greater-than-or-equal/bigint-and-string.js, test/language/expressions/greater-than/bigint-and-incomparable-string.js, test/language/expressions/greater-than/bigint-and-string.js, test/language/expressions/less-than-or-equal/bigint-and-incomparable-string.js, test/language/expressions/less-than-or-equal/bigint-and-string.js, test/language/expressions/less-than/bigint-and-incomparable-string.js, test/language/expressions/less-than/bigint-and-string.js
Add tests for comparisons between BigInt and string values. This commit checks for the string-to-bigint coercion changes in tc39/proposal-bigint@4768527d9dcf4c04b22a7382d41091e470d8a7fd.
=> bigint comparison tests

test/language/eval-code/direct/block-decl-eval-source-is-strict-nostrict.js, test/language/eval-code/direct/block-decl-eval-source-is-strict-onlystrict.js, test/language/eval-code/direct/block-decl-nostrict.js, test/language/eval-code/direct/block-decl-onlystrict.js, test/language/eval-code/direct/switch-case-decl-eval-source-is-strict-nostrict.js, test/language/eval-code/direct/switch-case-decl-eval-source-is-strict-onlystrict.js, test/language/eval-code/direct/switch-case-decl-nostrict.js, test/language/eval-code/direct/switch-case-decl-onlystrict.js, test/language/eval-code/direct/switch-dflt-decl-eval-source-is-strict-nostrict.js, test/language/eval-code/direct/switch-dflt-decl-eval-source-is-strict-onlystrict.js, test/language/eval-code/direct/switch-dflt-decl-nostrict.js, test/language/eval-code/direct/switch-dflt-decl-onlystrict.js, test/language/function-code/block-decl-nostrict.js, test/language/function-code/block-decl-onlystrict.js, test/language/function-code/switch-case-decl-nostrict.js, test/language/function-code/switch-case-decl-onlystrict.js, test/language/function-code/switch-dflt-decl-nostrict.js, test/language/function-code/switch-dflt-decl-onlystrict.js
(Some changes are only for consistency)
Fixes #1364
=> Corrections to sec-web-compat-evaldeclarationinstantiation and sec-web-compat-functiondeclarationinstantiation tests. Fixes gh-1364

test/language/expressions/greater-than/bigint-and-boolean.js, test/language/expressions/less-than/bigint-and-boolean.js
These tests are important to check if ```ToNumeric``` are being implemented properly. It closes #1541.
=> Added tests of relational comparison among BigInt and boolean

test/intl402/Locale/invalid-tag-throws-symbol.js, test/intl402/Locale/prop-desc.js, test/intl402/Locale/prototype/maximize/length.js, test/intl402/Locale/prototype/maximize/prop-desc.js
- fix mixed up test & info
- add Symbol feature
- maximize length is 0
- maximize configurability is true
=> Intl.Locale: minor fixups

test/language/expressions/greater-than/bigint-and-string.js, test/language/expressions/less-than/bigint-and-string.js
=> Adding prefixed string to compare with BigInt

harness/testIntl.js
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
=> Intl: Update language subtag data to "IANA language subtag registry, file date 2018-04-23"

INTERPRETING.md, tools/lint/lib/checks/frontmatter.py
=> Frontmatter: Adds top level "locale" attribute, w/ "tags" attribute to declare language tags, subtags. Fixes gh-1515

features.txt, test/built-ins/String/fromCodePoint/argument-is-Symbol.js, test/built-ins/String/fromCodePoint/argument-is-not-integer.js, test/built-ins/String/fromCodePoint/argument-not-coercible.js, test/built-ins/String/fromCodePoint/arguments-is-empty.js, test/built-ins/String/fromCodePoint/fromCodePoint.js, test/built-ins/String/fromCodePoint/length.js, test/built-ins/String/fromCodePoint/name.js, test/built-ins/String/fromCodePoint/number-is-out-of-range.js, test/built-ins/String/fromCodePoint/return-string-value.js, test/built-ins/String/fromCodePoint/to-number-conversions.js
Supports the changes from #1605 and fix its CI build
=> Adds String.fromCodePoint to the features list

test/language/statements/class/super/in-constructor-superproperty-evaluation.js, test/language/statements/class/super/in-constructor.js, test/language/statements/class/super/in-getter.js, test/language/statements/class/super/in-methods.js, test/language/statements/class/super/in-setter.js, test/language/statements/class/super/in-static-getter.js, test/language/statements/class/super/in-static-methods.js, test/language/statements/class/super/in-static-setter.js
super[super()] should evaluate and resolve super() first
=> SuperProperty evaluation order

features.txt, test/intl402/ListFormat/prototype/toStringTag/toString.js, test/intl402/ListFormat/prototype/toStringTag/toStringTag.js
The specification changed in https://github.com/tc39/proposal-intl-list-format/pull/13.
=> Add a test for Intl.ListFormat.prototype[@@toStringTag].

features.txt, test/intl402/Segmenter/prototype/toStringTag/toString.js, test/intl402/Segmenter/prototype/toStringTag/toStringTag.js
This was added to the specification in https://github.com/tc39/proposal-intl-segmenter/pull/29.
=> Add a test for Intl.Segmenter.prototype[@@toStringTag].

test/intl402/NumberFormat/prototype/format/format-negative-numbers.js
The specification was updated in https://github.com/tc39/ecma402/pull/232.
=> Update the test for negative zero in NumberFormat.

harness/doneprintHandle.js
This is not a breaking change, it simply adds explicit handling to the function
=> Make doneprinthandle.js accept the input and produce the output expected by test262-harness.

test/built-ins/Array/prototype/flat/array-like-objects.js, test/built-ins/Array/prototype/flat/length.js, test/built-ins/Array/prototype/flat/name.js, test/built-ins/Array/prototype/flat/non-numeric-depth-should-not-throw.js, test/built-ins/Array/prototype/flat/non-object-ctor-throws.js, test/built-ins/Array/prototype/flat/prop-desc.js, test/built-ins/Array/prototype/flat/proxy-access-count.js, test/built-ins/Array/prototype/flatMap/array-like-objects.js, test/built-ins/Array/prototype/flatMap/length.js, test/built-ins/Array/prototype/flatMap/name.js, test/built-ins/Array/prototype/flatMap/non-object-ctor-throws.js, test/built-ins/Array/prototype/flatMap/prop-desc.js, test/built-ins/Array/prototype/flatMap/proxy-access-count.js
some quick changes here with some cleanup included. The tests are basically the same.
cc @michaelficarra
=> some quick fixes for Array.prototype.{flat,flatMap} tests

implementation-contributed/curation_logs/javascriptcore.json, implementation-contributed/javascriptcore/stress/characters-regexp-ignore-case.js, implementation-contributed/javascriptcore/stress/characters-regexp.js, implementation-contributed/javascriptcore/stress/dataview-jit-bounds-checks.js, implementation-contributed/javascriptcore/stress/dataview-jit-get.js, implementation-contributed/javascriptcore/stress/dataview-jit-neuter.js, implementation-contributed/javascriptcore/stress/dataview-jit-set.js, implementation-contributed/javascriptcore/stress/dataview-jit-unaligned-accesses.js
Changes imported in this pull request include all changes made since
[ffc7368147](https://github.com///github/blob/ffc7368147) in JavaScriptCore and all changes made since [ac84caea5](../blob/ac84caea5) in
test262.
These are new files added in JavaScriptCore and have been synced to the
`implementation-contributed/javascriptcore` directory.
- [implementation-contributed/javascriptcore/stress/characters-regexp-ignore-case.js](../blob/javascriptcore-test262-automation-export-ac84caea5/implementation-contributed/javascriptcore/stress/characters-regexp-ignore-case.js)
- [implementation-contributed/javascriptcore/stress/characters-regexp.js](../blob/javascriptcore-test262-automation-export-ac84caea5/implementation-contributed/javascriptcore/stress/characters-regexp.js)
- …
=> Import test changes from JavaScriptCore

features.txt, src/async-functions/syntax/async-class-decl-private-method.template, src/async-functions/syntax/async-class-decl-static-private-method.template, src/async-functions/syntax/async-class-expr-private-method.template, src/async-functions/syntax/async-class-expr-static-private-method.template, src/async-generators/default/async-class-decl-private-method.template, src/async-generators/default/async-class-decl-static-private-method.template, src/async-generators/default/async-class-expr-private-method.template, src/async-generators/default/async-class-expr-static-private-method.template, src/async-generators/syntax/async-class-decl-private-method.template, src/async-generators/syntax/async-class-decl-static-private-method.template, src/async-generators/syntax/async-class-expr-private-method.template, src/async-generators/syntax/async-class-expr-static-private-method.template, src/generators/default/class-decl-method.template, src/generators/default/class-decl-private-method.template, src/generators/default/class-decl-static-private-method.template, src/generators/default/class-expr-private-method.template, src/generators/default/class-expr-static-private-method.template, src/generators/syntax/class-decl-private-method.template, src/generators/syntax/class-decl-static-private-method.template, src/generators/syntax/class-expr-private-method.template, src/generators/syntax/class-expr-static-private-method.template
Summary of changes:
1. Add tests for private generator methods
=> test: Add private generator method tests (#1343)

implementation-contributed/curation_logs/v8.json, implementation-contributed/v8/mjsunit/compiler/int64.js, implementation-contributed/v8/mjsunit/compiler/number-add.js
Changes imported in this pull request include all changes made since
[3a79fe2363](https://github.com///github/blob/3a79fe2363) in V8 and all changes made since [8138074de](../blob/8138074de) in
test262.
These are new files added in V8 and have been synced to the
`implementation-contributed/v8` directory.
- [implementation-contributed/v8/mjsunit/compiler/int64.js](../blob/v8-test262-automation-export-8138074de/implementation-contributed/v8/mjsunit/compiler/int64.js)
- [implementation-contributed/v8/mjsunit/compiler/number-add.js](../blob/v8-test262-automation-export-8138074de/implementation-contributed/v8/mjsunit/compiler/number-add.js)
=> Import test changes from V8

test/built-ins/Atomics/wait/was-woken-before-timeout.js, test/built-ins/TypedArrayConstructors/Float32Array/length.js
First was introduced [here](https://github.com/tc39/test262/pull/1479/files#diff-1e9f6c0fc0c996566e881503eb23ef29L24).
Second was introduced [here](https://github.com/tc39/test262/commit/7f3a1c1be970b62defe0bc4a542c6efb9d0295bb#diff-4107580a3fb39f9dd84fc8336aacc891L21).
=> Fix stray 'bigint' feature flags

test/built-ins/RegExp/prototype/Symbol.matchAll/isregexp-called-once.js
=> assert calls order for Symbol.match on matchAll usage

test/language/reserved-words/unreserved-words.js
=> Revert "Fix "undefiend" typo in unreserved-words.js"

src/dynamic-import/default/nested-if-braceless.template, test/language/module-code/dynamic-import/usage/nested-if-braceless-eval-gtbndng-indirect-update-dflt.js, test/language/module-code/dynamic-import/usage/nested-if-braceless-eval-gtbndng-indirect-update.js, test/language/module-code/dynamic-import/usage/nested-if-braceless-returns-promise.js
=> [dynamic import] Fix async test to verify completion

test/intl402/NumberFormat/constructor-locales-arraylike.js
/cc @littledan @rwaldron @gsathya
=> intl: fix mistyped test for array-like objects

test/intl402/Collator/usage-de.js
Ref: https://github.com/tc39/ecma402/issues/256.
Fixes https://github.com/tc39/test262/issues/1696.
=> Intl.Collator: Add a test for search and sort in German.

test/intl402/Segmenter/prototype/segment/segment-grapheme-iterable.js, test/intl402/Segmenter/prototype/segment/segment-line-iterable.js, test/intl402/Segmenter/prototype/segment/segment-sentence-iterable.js, test/intl402/Segmenter/prototype/segment/segment-word-iterable.js
=> fix usage of assertFalse

src/dynamic-import/syntax/invalid/nested-with-expression.template, src/dynamic-import/syntax/valid/nested-with-expression.template, test/language/expressions/dynamic-import/syntax/invalid/nested-with-expression-assignment-expr-not-optional.js, test/language/expressions/dynamic-import/syntax/invalid/nested-with-expression-no-new-call-expression.js, test/language/expressions/dynamic-import/syntax/invalid/nested-with-expression-no-rest-param.js, test/language/expressions/dynamic-import/syntax/invalid/nested-with-expression-not-extensible-args.js, test/language/expressions/dynamic-import/syntax/invalid/nested-with-expression-not-extensible-no-trailing-comma.js, test/language/expressions/dynamic-import/syntax/valid/nested-with-expression-empty-str-is-valid-assign-expr.js, test/language/expressions/dynamic-import/syntax/valid/nested-with-expression-nested-imports.js, test/language/expressions/dynamic-import/syntax/valid/nested-with-expression-script-code-valid.js
=> import() in with expression position

test/intl402/Segmenter/iterator/branding.js
Based on: https://github.com/tc39/test262/blob/44fc8165d54de9c9f0128f70eda56bdcb5dde82c/implementation-contributed/v8/intl/segmenter/segment-iterator-ownPropertyDescriptor.js
=> Fix Intl.Segmenter branding.js

.travis.yml, package.json, tools/scripts/ci_test.sh
I'm experimenting with Travis CI configuration and this PR should help.
~~It's currently WIP, so please hang on, don't merge.~~
=> Use travis ci to run new or modified test files on engines on each PR

test/intl402/Segmenter/iterator/following.js, test/intl402/Segmenter/iterator/granularity.js, test/intl402/Segmenter/iterator/position.js, test/intl402/Segmenter/iterator/preceding.js, test/intl402/Segmenter/iterator/prototype.js, test/intl402/Segmenter/prototype/segment/segment-grapheme-following.js, test/intl402/Segmenter/prototype/segment/segment-grapheme-iterable.js, test/intl402/Segmenter/prototype/segment/segment-grapheme-next.js, test/intl402/Segmenter/prototype/segment/segment-grapheme-preceding.js, test/intl402/Segmenter/prototype/segment/segment-grapheme.js, test/intl402/Segmenter/prototype/segment/segment-line-following.js, test/intl402/Segmenter/prototype/segment/segment-line-iterable.js, test/intl402/Segmenter/prototype/segment/segment-line-next.js, test/intl402/Segmenter/prototype/segment/segment-line-preceding.js, test/intl402/Segmenter/prototype/segment/segment-line.js, test/intl402/Segmenter/prototype/segment/segment-sentence-following.js, test/intl402/Segmenter/prototype/segment/segment-sentence-iterable.js, test/intl402/Segmenter/prototype/segment/segment-sentence-next.js, test/intl402/Segmenter/prototype/segment/segment-sentence-preceding.js, test/intl402/Segmenter/prototype/segment/segment-sentence.js, test/intl402/Segmenter/prototype/segment/segment-tostring.js, test/intl402/Segmenter/prototype/segment/segment-word-following.js, test/intl402/Segmenter/prototype/segment/segment-word-iterable.js, test/intl402/Segmenter/prototype/segment/segment-word-next.js, test/intl402/Segmenter/prototype/segment/segment-word-preceding.js, test/intl402/Segmenter/prototype/segment/segment-word.js
https://github.com/tc39/proposal-intl-segmenter/pull/55
=> Rename position to index

test/intl402/ListFormat/constructor/constructor/options-order.js
Sync with https://github.com/tc39/proposal-intl-list-format/pull/36
=> Move localeMatcher before type and style

features.txt
Move features belonging to proposals that have been incorporated into the standard to the corresponding section.
=> Update features.txt status

test/intl402/RelativeTimeFormat/prototype/resolvedOptions/order.js
Change per
https://github.com/tc39/proposal-intl-relative-time/pull/99
and
https://github.com/tc39/proposal-intl-relative-time/pull/100
=> Add "numberingSystem" to resolvedOptions()

test/built-ins/TypedArray/stability.js
https://github.com/tc39/ecma262/pull/1433
=> Add tests for %TypedArray%.prototype.sort stability

src/class-elements/private-field-as-arrow-function.case, src/class-elements/private-field-as-async-arrow-function.case, src/class-elements/private-field-as-async-function.case, src/class-elements/private-field-as-function.case, src/class-elements/private-field-super-access-throws.case, test/language/expressions/class/elements/private-field-as-arrow-function.js, test/language/expressions/class/elements/private-field-as-async-arrow-function.js, test/language/expressions/class/elements/private-field-as-async-function.js, test/language/expressions/class/elements/private-field-as-function.js, test/language/expressions/class/elements/private-field-super-access-throws.js, test/language/statements/class/elements/private-field-as-arrow-function.js, test/language/statements/class/elements/private-field-as-async-arrow-function.js, test/language/statements/class/elements/private-field-as-async-function.js, test/language/statements/class/elements/private-field-as-function.js, test/language/statements/class/elements/private-field-super-access-throws.js
This is handling missing tests from #2066.
=> Adding case where private field stores a function

test/language/statements/do-while/S12.6.1_A4_T5.js, test/language/statements/while/S12.6.2_A4_T5.js
=> Fix assertions previously not reached before

test/annexB/built-ins/Function/createdynfn-no-line-terminator-html-close-comment-body.js, test/annexB/built-ins/Function/createdynfn-no-line-terminator-html-close-comment-params.js
Ref #2095
cc @anba @gnarf @iamstolis @gsathya @rwaldron
=> Add new tests to observe required leading line terminator

src/class-elements/initializer-eval-super-call/cls-decl-fields-eval.template, src/class-elements/initializer-eval-super-call/cls-decl-fields-indirect-eval.template, src/class-elements/initializer-eval-super-call/cls-decl-private-fields-eval.template, src/class-elements/initializer-eval-super-call/cls-decl-private-fields-indirect-eval.template, src/class-elements/initializer-eval-super-call/cls-expr-fields-eval.template, src/class-elements/initializer-eval-super-call/cls-expr-fields-indirect-eval.template, src/class-elements/initializer-eval-super-call/cls-expr-private-fields-eval.template, src/class-elements/initializer-eval-super-call/cls-expr-private-fields-indirect-eval.template, test/language/expressions/class/elements/private-derived-cls-direct-eval-err-contains-supercall-1.js, test/language/expressions/class/elements/private-derived-cls-direct-eval-err-contains-supercall-2.js, test/language/expressions/class/elements/private-derived-cls-direct-eval-err-contains-supercall.js, test/language/expressions/class/elements/private-derived-cls-indirect-eval-err-contains-supercall-1.js, test/language/expressions/class/elements/private-derived-cls-indirect-eval-err-contains-supercall-2.js, test/language/expressions/class/elements/private-derived-cls-indirect-eval-err-contains-supercall.js, test/language/statements/class/elements/private-derived-cls-direct-eval-err-contains-supercall-1.js, test/language/statements/class/elements/private-derived-cls-direct-eval-err-contains-supercall-2.js, test/language/statements/class/elements/private-derived-cls-direct-eval-err-contains-supercall.js, test/language/statements/class/elements/private-derived-cls-indirect-eval-err-contains-supercall-1.js, test/language/statements/class/elements/private-derived-cls-indirect-eval-err-contains-supercall-2.js, test/language/statements/class/elements/private-derived-cls-indirect-eval-err-contains-supercall.js
=> Add missing feature tags

test/language/statements/class/elements/privatefield-on-proxy.js, test/language/statements/class/elements/privategetter-on-proxy.js, test/language/statements/class/elements/privatemethods-on-proxy.js
=> Adding tests to verify private fields on Proxy Objects

test/built-ins/Date/prototype/toDateString/negative-year.js, test/built-ins/Date/prototype/toString/negative-year.js, test/built-ins/Date/prototype/toUTCString/negative-year.js
Ref https://github.com/tc39/ecma262/issues/1035
=> Add tests for string representations of Date objects with negative years

test/intl402/ListFormat/prototype/format/en-us-short.js
I somehow missed the last line last time I proposed https://github.com/tc39/test262/pull/2111
=> correct the test case

test/language/expressions/class/elements/fields-asi-same-line-1.js, test/language/expressions/class/elements/fields-asi-same-line-2.js, test/language/statements/class/elements/fields-asi-same-line-1.js, test/language/statements/class/elements/fields-asi-same-line-2.js
I didn't see any tests for this case.
These tests are slightly silly, but I would check these into our repo without hesitation, so I figure there's no reason not to at least offer them.
=> Add a couple more tests for ASI with fields.

CONTRIBUTING.md, INTERPRETING.md
@jugglinmike please review this updated language for the new `_FIXTURE.js` rules.
=> INTERPRETING.md/CONTRIBUTING.md: revised rules for _FIXTURE.js files

features.txt, test/intl402/DateTimeFormat/prototype/formatRange/date-is-infinity-throws.js, test/intl402/DateTimeFormat/prototype/formatRange/date-is-nan-throws.js, test/intl402/DateTimeFormat/prototype/formatRange/date-undefined-throws.js, test/intl402/DateTimeFormat/prototype/formatRange/date-x-greater-than-y-throws.js, test/intl402/DateTimeFormat/prototype/formatRange/length.js, test/intl402/DateTimeFormat/prototype/formatRange/name.js, test/intl402/DateTimeFormat/prototype/formatRange/this-is-not-object-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-is-infinity-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-is-nan-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-undefined-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-x-greater-than-y-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/length.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/name.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/this-is-not-object-throws.js
I did copy some code from pre-existing tests. I am not sure how to make the copyright / license text correctly for that. Please comment about that part.
@leobalter @anba @littledan @Ms2ger @gsathya
=> Add tests for Intl.DateTimeFormat formatRange and formatRangeToParts

test/built-ins/Array/prop-desc.js
=> Add Array property descriptor test

test/intl402/DateTimeFormat/prototype/formatRange/argument-date-string.js, test/intl402/DateTimeFormat/prototype/formatRange/argument-near-time-boundaries.js, test/intl402/DateTimeFormat/prototype/formatRange/argument-to-integer.js, test/intl402/DateTimeFormat/prototype/formatRange/date-is-infinity-throws.js, test/intl402/DateTimeFormat/prototype/formatRange/date-is-nan-throws.js, test/intl402/DateTimeFormat/prototype/formatRange/date-undefined-throws.js, test/intl402/DateTimeFormat/prototype/formatRange/date-x-greater-than-y-throws.js, test/intl402/DateTimeFormat/prototype/formatRange/en-US.js, test/intl402/DateTimeFormat/prototype/formatRange/this-is-not-object-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/argument-date-string.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/argument-near-time-boundaries.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/argument-to-integer.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-is-infinity-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-is-nan-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-undefined-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-x-greater-than-y-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/en-US.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/this-is-not-object-throws.js
Correction for tests introduced in tc39#2134.
=> Fix invalid YAML in formatRange* tests.

src/class-elements/private-method-comparison.case, src/class-elements/private-method-get-and-call.case, test/language/expressions/class/elements/private-method-comparison.js, test/language/expressions/class/elements/private-method-get-and-call.js, test/language/statements/class/elements/private-method-comparison-multiple-evaluations-of-class.js, test/language/statements/class/elements/private-method-comparison.js, test/language/statements/class/elements/private-method-get-and-call.js
=> Tests to cover private methods comparison

test/built-ins/Promise/get-prototype-abrupt.js
=> Fix description of Promise constructor test

src/accessor-names/private/cls-private-decl-static.template, src/accessor-names/private/cls-private-expr-static.template, test/language/expressions/class/elements/private-accessor-name/static-private-escape-sequence-ZWJ.js, test/language/expressions/class/elements/private-accessor-name/static-private-escape-sequence-ZWNJ.js, test/language/expressions/class/elements/private-accessor-name/static-private-escape-sequence-u2118.js, test/language/expressions/class/elements/private-accessor-name/static-private-escape-sequence-u6F.js, test/language/expressions/class/elements/private-accessor-name/static-private-name-ZWJ.js, test/language/expressions/class/elements/private-accessor-name/static-private-name-ZWNJ.js, test/language/expressions/class/elements/private-accessor-name/static-private-name-common.js, test/language/expressions/class/elements/private-accessor-name/static-private-name-dollar.js, test/language/expressions/class/elements/private-accessor-name/static-private-name-u2118.js, test/language/expressions/class/elements/private-accessor-name/static-private-name-underscore.js, test/language/statements/class/elements/private-accessor-name/static-private-escape-sequence-ZWJ.js, test/language/statements/class/elements/private-accessor-name/static-private-escape-sequence-ZWNJ.js, test/language/statements/class/elements/private-accessor-name/static-private-escape-sequence-u2118.js, test/language/statements/class/elements/private-accessor-name/static-private-escape-sequence-u6F.js, test/language/statements/class/elements/private-accessor-name/static-private-name-ZWJ.js, test/language/statements/class/elements/private-accessor-name/static-private-name-ZWNJ.js, test/language/statements/class/elements/private-accessor-name/static-private-name-common.js, test/language/statements/class/elements/private-accessor-name/static-private-name-dollar.js, test/language/statements/class/elements/private-accessor-name/static-private-name-u2118.js, test/language/statements/class/elements/private-accessor-name/static-private-name-underscore.js
=> Fix feature flag

test/built-ins/Symbol/not-callable.js
=> Verify that symbols are not callable

src/class-elements/private-method-shadowed-by-getter-on-nested-class.case, test/language/expressions/class/elements/private-method-shadowed-by-getter-on-nested-class.js, test/language/statements/class/elements/private-method-shadowed-by-getter-on-nested-class.js
Ref https://github.com/tc39/test262/pull/2150#discussion_r285706248
cc @caiolima @littledan
=> Add assertion for private method shadowed by getter case

test/language/statements/for-await-of/async-gen-dstr-const-ary-ptrn-init-err.js, test/language/statements/for-await-of/async-gen-dstr-const-obj-ptrn-init-err.js, test/language/statements/for-await-of/async-gen-dstr-let-ary-ptrn-init-err.js, test/language/statements/for-await-of/async-gen-dstr-let-obj-ptrn-init-err.js, test/language/statements/for-await-of/async-gen-dstr-var-ary-ptrn-init-err.js, test/language/statements/for-await-of/async-gen-dstr-var-obj-ptrn-init-err.js, test/language/statements/for-await-of/head-const-init.js, test/language/statements/for-await-of/head-let-init.js, test/language/statements/for-await-of/head-var-init.js, test/language/statements/for-of/dstr/const-ary-ptrn-init-err.js, test/language/statements/for-of/dstr/const-obj-ptrn-init-err.js, test/language/statements/for-of/dstr/let-ary-ptrn-init-err.js, test/language/statements/for-of/dstr/let-obj-ptrn-init-err.js, test/language/statements/for-of/dstr/var-ary-ptrn-init-err.js, test/language/statements/for-of/dstr/var-obj-ptrn-init-err.js, test/language/statements/for-of/head-const-init.js, test/language/statements/for-of/head-let-init.js, test/language/statements/for-of/head-var-init.js
=> Add for-of head Initializer tests

src/class-elements/eval-contains-superproperty-1.case, src/class-elements/eval-contains-superproperty-2.case, test/language/expressions/class/elements/derived-cls-direct-eval-contains-superproperty-1.js, test/language/expressions/class/elements/derived-cls-direct-eval-contains-superproperty-2.js, test/language/expressions/class/elements/derived-cls-indirect-eval-contains-superproperty-1.js, test/language/expressions/class/elements/derived-cls-indirect-eval-contains-superproperty-2.js, test/language/expressions/class/elements/private-derived-cls-direct-eval-contains-superproperty-1.js, test/language/expressions/class/elements/private-derived-cls-direct-eval-contains-superproperty-2.js, test/language/expressions/class/elements/private-derived-cls-indirect-eval-contains-superproperty-1.js, test/language/expressions/class/elements/private-derived-cls-indirect-eval-contains-superproperty-2.js, test/language/statements/class/elements/derived-cls-direct-eval-contains-superproperty-1.js, test/language/statements/class/elements/derived-cls-direct-eval-contains-superproperty-2.js, test/language/statements/class/elements/derived-cls-indirect-eval-contains-superproperty-1.js, test/language/statements/class/elements/derived-cls-indirect-eval-contains-superproperty-2.js, test/language/statements/class/elements/private-derived-cls-direct-eval-contains-superproperty-1.js, test/language/statements/class/elements/private-derived-cls-direct-eval-contains-superproperty-2.js, test/language/statements/class/elements/private-derived-cls-indirect-eval-contains-superproperty-1.js, test/language/statements/class/elements/private-derived-cls-indirect-eval-contains-superproperty-2.js
=>  Update tests description for super.x in eval

test/intl402/DateTimeFormat/constructor-options-dayPeriod-invalid.js, test/intl402/DateTimeFormat/constructor-options-dayPeriod-valid.js, test/intl402/DateTimeFormat/constructor-options-order-fractionalSecondDigits.js, test/intl402/DateTimeFormat/constructor-options-order-quarter.js, test/intl402/DateTimeFormat/taint-Object-prototype-dayPeriod.js, test/intl402/DateTimeFormat/taint-Object-prototype-fractionalSecondDigits.js, test/intl402/DateTimeFormat/taint-Object-prototype-quarter.js
Ref https://github.com/tc39/test262/pull/2194
cc @FrankYFTang
=> Quick cleanups for Intl tests

harness/propertyHelper.js, test/harness/verifyProperty-same-value.js
=> Use SameValue in verifyProperty helper

features.txt, test/built-ins/Proxy/defineProperty/targetdesc-not-configurable-writable-desc-not-writable.js, test/built-ins/Proxy/deleteProperty/targetdesc-is-configurable-target-is-not-extensible.js, test/built-ins/Proxy/getOwnPropertyDescriptor/resultdesc-is-not-configurable-not-writable-targetdesc-is-writable.js
Per [this comment](https://github.com/tc39/ecma262/pull/666#issuecomment-492708383).
=> Add "proxy-missing-checks" feature tag

test/built-ins/Object/subclass-object-arg.js
Refs #2177 
Refs https://github.com/tc39/test262/pull/2177#discussion_r294062202
=> fix built-ins/Object/subclass-object-arg

INTERPRETING.md, features.txt
See: https://github.com/bterlson/eshost/issues/83
=> INTERPRETING.md: Add $262.gc() and "host-gc-required" feature

test/built-ins/Promise/all/invoke-resolve-get-error-close.js, test/built-ins/Promise/allSettled/invoke-resolve-get-error-close.js, test/built-ins/Promise/race/invoke-resolve-get-error-close.js
=> Fix invoke-resolve-get-error-close tests

test/built-ins/FinalizationGroup/prototype/cleanupSome/poisoned-callback-throws.js, test/built-ins/FinalizationGroup/prototype/cleanupSome/poisoned-cleanup-callback-throws.js, test/built-ins/FinalizationGroup/prototype/cleanupSome/return-undefined-with-gc.js, test/built-ins/FinalizationGroup/prototype/cleanupSome/return-undefined.js
=> Fix tests for FinalizationGroup

test/built-ins/Set/prototype/values/does-not-have-setdata-internal-slot-weakset.js
The test tries to test against WeakSet, but used WeakMap instead.
=> Fix WeakMap/WeakSet typo

test/intl402/DateTimeFormat/prototype/format/dayPeriod-long-en.js, test/intl402/DateTimeFormat/prototype/format/dayPeriod-narrow-en.js, test/intl402/DateTimeFormat/prototype/format/dayPeriod-short-en.js, test/intl402/DateTimeFormat/prototype/formatToParts/dayPeriod-long-en.js, test/intl402/DateTimeFormat/prototype/formatToParts/dayPeriod-narrow-en.js, test/intl402/DateTimeFormat/prototype/formatToParts/dayPeriod-short-en.js
cc @FrankYFTang 
I believe these tests finish missing coverage for https://github.com/tc39/ecma402/pull/346
=> Add tests for DateTimeFormat using dayPeriod

src/class-elements/prod-private-getter-before-super-return-in-field-initializer.case, src/class-elements/prod-private-method-before-super-return-in-field-initializer.case, src/class-elements/prod-private-setter-before-super-return-in-field-initializer.case, test/language/expressions/class/elements/prod-private-getter-before-super-return-in-field-initializer.js, test/language/expressions/class/elements/prod-private-method-before-super-return-in-field-initializer.js, test/language/expressions/class/elements/prod-private-setter-before-super-return-in-field-initializer.js, test/language/statements/class/elements/private-class-field-on-frozen-objects.js, test/language/statements/class/elements/private-getter-visible-to-direct-eval-on-initializer.js, test/language/statements/class/elements/private-method-visible-to-direct-eval-on-initializer.js, test/language/statements/class/elements/prod-private-getter-before-super-return-in-field-initializer.js, test/language/statements/class/elements/prod-private-method-before-super-return-in-field-initializer.js, test/language/statements/class/elements/prod-private-setter-before-super-return-in-field-initializer.js
Found while updating test262 in Babel's tests suite.
=> Add missing features to class fields tests

test/intl402/DateTimeFormat/prototype/format/dayPeriod-long-en.js, test/intl402/DateTimeFormat/prototype/format/dayPeriod-narrow-en.js, test/intl402/DateTimeFormat/prototype/format/dayPeriod-short-en.js, test/intl402/DateTimeFormat/prototype/formatToParts/dayPeriod-long-en.js, test/intl402/DateTimeFormat/prototype/formatToParts/dayPeriod-narrow-en.js, test/intl402/DateTimeFormat/prototype/formatToParts/dayPeriod-short-en.js
Mistakes which I didn't catch while reviewing #2217
=> Correct features to Intl.DateTimeFormat-dayPeriod

CONTRIBUTING.md, test/intl402/BigInt/prototype/toLocaleString/builtin.js, test/intl402/BigInt/prototype/toLocaleString/default-options-object-prototype.js, test/intl402/BigInt/prototype/toLocaleString/length.js, test/intl402/BigInt/prototype/toLocaleString/returns-same-results-as-NumberFormat.js, test/intl402/BigInt/prototype/toLocaleString/taint-Intl-NumberFormat.js, test/intl402/BigInt/prototype/toLocaleString/this-value-invalid.js, test/intl402/BigInt/prototype/toLocaleString/throws-same-exceptions-as-NumberFormat.js, test/intl402/DateTimeFormat/prototype/formatRange/argument-date-string.js, test/intl402/DateTimeFormat/prototype/formatRange/argument-near-time-boundaries.js, test/intl402/DateTimeFormat/prototype/formatRange/argument-to-integer.js, test/intl402/DateTimeFormat/prototype/formatRange/builtin.js, test/intl402/DateTimeFormat/prototype/formatRange/prop-desc.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/argument-date-string.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/argument-near-time-boundaries.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/argument-to-integer.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/builtin.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/prop-desc.js, tools/lint/lib/checks/license.py, tools/lint/test/fixtures/license_invalid_year_range.js, tools/packaging/parseTestRecord.py
cc @mathiasbynens @gsathya 
Closes #2148
=> Fix linter to prevent year ranges.

test/built-ins/Object/create/properties-arg-to-object-bigint.js, test/built-ins/Object/create/properties-arg-to-object-non-empty-string.js, test/built-ins/Object/create/properties-arg-to-object-null.js, test/built-ins/Object/create/properties-arg-to-object.js
=> Add coverage for non object values of the Properties arg of Object.create

test/intl402/NumberFormat/currencyDisplay-unit.js
to sync with https://github.com/tc39/proposal-unified-intl-numberformat/pull/54
@sffc @leobalter
=> Change to narrow-symbol to camelCase

test/language/expressions/division/line-terminator.js, test/language/expressions/division/no-magic-asi-from-block-eval.js, test/language/expressions/division/no-magic-asi.js, test/language/expressions/modulus/line-terminator.js, test/language/expressions/multiplication/line-terminator.js
Plus some line terminator checks
---
Hopefully this should address the second case mentioned by @jorendorff in #2230
=> Add cases for division after a Block

test/language/literals/numeric/numeric-separator-literal-lol-00-err.js, test/language/literals/numeric/numeric-separator-literal-lol-01-err.js, test/language/literals/numeric/numeric-separator-literal-lol-07-err.js, test/language/literals/numeric/numeric-separator-literal-lol-0_0-err.js, test/language/literals/numeric/numeric-separator-literal-lol-0_1-err.js, test/language/literals/numeric/numeric-separator-literal-lol-0_7-err.js, test/language/literals/numeric/numeric-separator-literal-nonoctal-08-err.js, test/language/literals/numeric/numeric-separator-literal-nonoctal-09-err.js, test/language/literals/numeric/numeric-separator-literal-nonoctal-0_8-err.js, test/language/literals/numeric/numeric-separator-literal-nonoctal-0_9-err.js
cc @gsathya @devsnek @rkirsling
=> Add tests for Numeric Separators not allowed in legacy octal and non octal literals

src/class-elements/static-private-method-access-on-inner-arrow-function.case, src/class-elements/static-private-method-access-on-inner-function.case, test/language/expressions/class/elements/static-private-method-access-on-inner-arrow-function.js, test/language/expressions/class/elements/static-private-method-access-on-inner-function.js, test/language/statements/class/elements/static-private-method-access-on-inner-arrow-function.js, test/language/statements/class/elements/static-private-method-access-on-inner-function.js
Per @caiolima's [comment](https://github.com/tc39/test262/pull/2235#pullrequestreview-261292330) on #2235.
cc: @jbhoosreddy
=> Add tests for static private method access inside nested functions

src/class-elements/static-field-declaration.case, test/language/expressions/class/elements/static-field-declaration.js, test/language/statements/class/elements/static-field-declaration.js
Adding tests to validate public static fields declaration.
Cc @mkubilayk, @jbhoosreddy.
=> Tests to cover simple declaration of static fields.

.circleci/config.yml, tools/generation/lib/case.py, tools/generation/lib/expander.py, tools/generation/lib/template.py, tools/generation/lib/test.py, tools/generation/lib/util/find_comments.py, tools/generation/test/run.py
=> Generation: Support Python 3

test/language/expressions/optional-chaining/member-expression.js
=> Fix typo from optional chaining test

test/language/expressions/class/private-static-field-multiple-evaluations-of-class-direct-eval.js, test/language/expressions/class/private-static-field-multiple-evaluations-of-class-eval-indirect.js, test/language/expressions/class/private-static-field-multiple-evaluations-of-class-factory.js, test/language/expressions/class/private-static-field-multiple-evaluations-of-class-function-ctor.js, test/language/expressions/class/private-static-field-multiple-evaluations-of-class-realm.js, test/language/expressions/class/private-static-method-brand-check-multiple-evaluations-of-class-direct-eval.js, test/language/expressions/class/private-static-method-brand-check-multiple-evaluations-of-class-eval-indirect.js, test/language/expressions/class/private-static-method-brand-check-multiple-evaluations-of-class-factory.js, test/language/expressions/class/private-static-method-brand-check-multiple-evaluations-of-class-function-ctor.js, test/language/expressions/class/private-static-method-brand-check-multiple-evaluations-of-class-realm.js
We are adding test to verify that every evaluation of a class generates a new Private Name or Private Brand.
Cc. @spectranaut and @leobalter
=> Private static members with multiple evaluation of class

src/class-elements/private-static-method-name.case, src/class-elements/static-field-anonymous-function-name.case, test/language/expressions/class/elements/private-static-method-name.js, test/language/expressions/class/elements/static-field-anonymous-function-name.js, test/language/statements/class/elements/private-static-method-name.js, test/language/statements/class/elements/static-field-anonymous-function-name.js
=> Adding tests to verify if '.name' of static members are configured properly

test/language/module-code/top-level-await/await-expr-func-expression.js
=> Fix a test for TLA

src/class-elements/fields-anonymous-function-length.case, src/class-elements/private-method-length.case, src/class-elements/private-static-method-length.case, src/class-elements/static-field-anonymous-function-length.case, test/language/expressions/class/elements/fields-anonymous-function-length.js, test/language/expressions/class/elements/private-method-length.js, test/language/expressions/class/elements/private-static-method-length.js, test/language/expressions/class/elements/static-field-anonymous-function-length.js, test/language/statements/class/elements/fields-anonymous-function-length.js, test/language/statements/class/elements/private-method-length.js, test/language/statements/class/elements/private-static-method-length.js, test/language/statements/class/elements/static-field-anonymous-function-length.js
=> Added private method length cases

src/class-elements/private-async-generator-method-name.case, src/class-elements/private-async-method-name.case, src/class-elements/private-generator-method-name.case, src/class-elements/private-static-async-generator-method-name.case, src/class-elements/private-static-async-method-name.case, src/class-elements/private-static-generator-method-name.case, test/language/expressions/class/elements/private-async-generator-method-name.js, test/language/expressions/class/elements/private-async-method-name.js, test/language/expressions/class/elements/private-generator-method-name.js, test/language/expressions/class/elements/private-static-async-generator-method-name.js, test/language/expressions/class/elements/private-static-async-method-name.js, test/language/expressions/class/elements/private-static-generator-method-name.js, test/language/statements/class/elements/private-async-generator-method-name.js, test/language/statements/class/elements/private-async-method-name.js, test/language/statements/class/elements/private-generator-method-name.js, test/language/statements/class/elements/private-static-async-generator-method-name.js, test/language/statements/class/elements/private-static-async-method-name.js, test/language/statements/class/elements/private-static-generator-method-name.js
=> Adding missing variations to verify private method name setup

test/language/expressions/call/tco-cross-realm-class-construct.js, test/language/expressions/call/tco-cross-realm-class-derived-construct.js, test/language/expressions/call/tco-cross-realm-fun-call.js, test/language/expressions/call/tco-cross-realm-fun-construct.js, test/language/expressions/class/private-getter-brand-check-multiple-evaluations-of-class-realm-function-ctor.js, test/language/expressions/class/private-getter-brand-check-multiple-evaluations-of-class-realm.js, test/language/expressions/class/private-method-brand-check-multiple-evaluations-of-class-realm-function-ctor.js, test/language/expressions/class/private-method-brand-check-multiple-evaluations-of-class-realm.js, test/language/expressions/class/private-setter-brand-check-multiple-evaluations-of-class-realm-function-ctor.js, test/language/expressions/class/private-setter-brand-check-multiple-evaluations-of-class-realm.js, test/language/expressions/class/private-static-field-multiple-evaluations-of-class-realm.js, test/language/expressions/class/private-static-getter-multiple-evaluations-of-class-realm.js, test/language/expressions/class/private-static-method-brand-check-multiple-evaluations-of-class-realm.js, test/language/expressions/class/private-static-setter-multiple-evaluations-of-class-realm.js
=> Add missing features for tests using cross-realm

test/built-ins/NativeErrors/EvalError/proto-from-ctor-realm.js, test/built-ins/NativeErrors/RangeError/proto-from-ctor-realm.js, test/built-ins/NativeErrors/ReferenceError/proto-from-ctor-realm.js, test/built-ins/NativeErrors/SyntaxError/proto-from-ctor-realm.js, test/built-ins/NativeErrors/TypeError/proto-from-ctor-realm.js, test/built-ins/NativeErrors/URIError/proto-from-ctor-realm.js
=> Add "proto-from-ctor-realm" tests for native errors

test/built-ins/Proxy/set/call-parameters-prototype-dunder-proto.js, test/built-ins/Proxy/set/call-parameters-prototype.js, test/built-ins/Proxy/set/call-parameters.js
=> Improve Proxy/set call parameters coverage

src/class-elements/prod-private-method-initialize-order.case, test/language/expressions/class/elements/private-methods/prod-private-method-initialize-order.js, test/language/statements/class/elements/private-methods/prod-private-method-initialize-order.js
Bug found while parsing Test262 tests with Babel
=> Add missing feature to prod-private-method-initialize-order.case

test/built-ins/AsyncFunction/proto-from-ctor-realm.js, test/built-ins/AsyncGeneratorFunction/proto-from-ctor-realm.js
Similar tests:
* [Function/proto-from-ctor-realm.js](https://github.com/tc39/test262/blob/master/test/built-ins/Function/proto-from-ctor-realm.js)
* [GeneratorFunction/proto-from-ctor-realm.js](https://github.com/tc39/test262/blob/master/test/built-ins/GeneratorFunction/proto-from-ctor-realm.js)
Related: #2334, #2335, #2336, #2340, #2346.
=> Add "proto-from-ctor-realm" tests for async functions

.circleci/config.yml
=> Fix JSC execution in Circle CI

test/built-ins/FinalizationGroup/prototype/cleanupSome/poisoned-callback-throws.js
=> Fix typo: iterator => iterator

test/built-ins/RegExp/match-indices/indices-groups-object-undefined.js, test/built-ins/RegExp/match-indices/indices-groups-object-unmatched.js, test/built-ins/RegExp/match-indices/indices-groups-object.js, test/built-ins/RegExp/match-indices/indices-groups-properties.js
https://chromium-review.googlesource.com/c/v8/v8/+/1845656/7/test/test262/testcfg.py#60
cc @rbuckton
=> Add missing `regexp-match-indices` feature tags

test/language/statements/class/elements/private-field-is-visible-in-computed-properties.js
Refs: https://github.com/tc39/proposal-class-fields/pull/269
cc @caiolima @littledan @syg
=> Undefined private name access in computed property keys should throw TypeError

test/intl402/ListFormat/constructor/constructor/proto-from-ctor-realm.js, test/intl402/Locale/proto-from-ctor-realm.js, test/intl402/RelativeTimeFormat/constructor/constructor/proto-from-ctor-realm.js, test/intl402/Segmenter/constructor/constructor/proto-from-ctor-realm.js
Closes #2345.
Follow-up of #2334.
Related: #2335, #2336, #2340, #2342.
=> Add "proto-from-ctor-realm" tests for Intl proposals

test/intl402/ListFormat/prototype/format/iterable-invalid.js, test/intl402/ListFormat/prototype/format/iterable.js, test/intl402/ListFormat/prototype/formatToParts/iterable-invalid.js, test/intl402/ListFormat/prototype/formatToParts/iterable.js
Add tests to test the iterable
=> Add tests for ListFormat StringListFromIterable ( iterable )

test/intl402/ListFormat/prototype/format/iterable-getiterator-throw.js, test/intl402/ListFormat/prototype/format/iterable-iteratorclose.js, test/intl402/ListFormat/prototype/format/iterable-iteratorstep-throw.js, test/intl402/ListFormat/prototype/format/iterable-iteratorvalue-throw.js, test/intl402/ListFormat/prototype/format/iterable-undefined.js, test/intl402/ListFormat/prototype/formatToParts/iterable-getiterator-throw.js, test/intl402/ListFormat/prototype/formatToParts/iterable-iteratorclose.js, test/intl402/ListFormat/prototype/formatToParts/iterable-iteratorstep-throw.js, test/intl402/ListFormat/prototype/formatToParts/iterable-iteratorvalue-throw.js, test/intl402/ListFormat/prototype/formatToParts/iterable-undefined.js
Fix  #2386
In addition to what I already put into https://github.com/tc39/test262/pull/2380
@Ms2ger @rwaldron @leobalter @littledan @zbraniecki
=> Add more tests for ListFormat

test/intl402/DateTimeFormat/prototype/formatRangeToParts/pattern-on-calendar.js, test/intl402/DateTimeFormat/prototype/formatToParts/pattern-on-calendar.js
address  https://github.com/tc39/test262/issues/2333
@rwaldron @anba @leobalter @Ms2ger @littledan
=> Add test to ensure Intl.DateTimeFormat choose pattern by calendar

test/built-ins/Proxy/has/call-in-prototype.js, test/built-ins/Proxy/set/call-parameters-prototype-dunder-proto.js, test/built-ins/Proxy/set/call-parameters-prototype.js
=> Add test for Proxy "has" trap on prototype

test/built-ins/String/prototype/matchAll/flags-undefined-throws.js, test/built-ins/String/prototype/matchAll/regexp-get-matchAll-throws.js, test/built-ins/String/prototype/matchAll/regexp-matchAll-is-undefined-or-null.js, test/built-ins/String/prototype/matchAll/regexp-matchAll-throws.js, test/built-ins/String/prototype/matchAll/regexp-prototype-get-matchAll-throws.js, test/built-ins/String/prototype/matchAll/regexp-prototype-matchAll-invocation.js, test/built-ins/String/prototype/matchAll/regexp-prototype-matchAll-throws.js
Fixes #2398
cc @joshualitt @syg @rkirsling
=> [matchAll] pass a global regex

test/intl402/DateTimeFormat/constructor-calendar-numberingSystem-order.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/pattern-on-calendar.js, test/intl402/DateTimeFormat/prototype/formatToParts/pattern-on-calendar.js, test/intl402/NumberFormat/constructor-numberingSystem-order.js
=> Yaml consistency

test/intl402/DateTimeFormat/prototype/formatRangeToParts/pattern-on-calendar.js
add features to fix problem introduced in https://github.com/tc39/test262/pull/2381/
@Ms2ger @rkirsling @leobalter
=> add features: [Intl.DateTimeFormat-formatRange]

test/intl402/DateTimeFormat/prototype/resolvedOptions/hourCycle-dateStyle.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/hourCycle-timeStyle.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/hourCycle.js
In particular, when using dateStyle/timeStyle.
See also <https://github.com/tc39/proposal-intl-datetime-style/issues/34>.
=> Add more tests for DateTimeFormat.hourCycle/hour12.

test/intl402/DisplayNames/prototype/resolvedOptions/default-option-values.js, test/intl402/DisplayNames/prototype/resolvedOptions/length.js, test/intl402/DisplayNames/prototype/resolvedOptions/name.js, test/intl402/DisplayNames/prototype/resolvedOptions/option-fallback.js, test/intl402/DisplayNames/prototype/resolvedOptions/option-style.js, test/intl402/DisplayNames/prototype/resolvedOptions/option-type.js, test/intl402/DisplayNames/prototype/resolvedOptions/prop-desc.js, test/intl402/DisplayNames/prototype/resolvedOptions/return-object.js, test/intl402/DisplayNames/prototype/resolvedOptions/this-not-object-throws.js, test/intl402/DisplayNames/prototype/resolvedOptions/this-object-lacks-internal-throws.js
=> Add tests for Intl.DisplayNames#resolvedOptions

test/built-ins/AggregateError/newtarget-proto-custom.js, test/built-ins/AggregateError/newtarget-proto-fallback.js
Ref tc39/proposal-promise-any#49
cc @anba
=> Fix tests for AggregateError

test/language/expressions/optional-chaining/optional-call-preserves-this.js
=> Add test verifying that optional call preserves `this`.

test/language/expressions/optional-chaining/new-target-optional-call.js, test/language/expressions/optional-chaining/super-property-optional-call.js
Adds regression tests for #2414, CC: @jridgewell.
fixes: #2414
=> feat: regression tests for optional call

test/built-ins/Error/prototype/toString/invalid-receiver.js, test/built-ins/Error/prototype/toString/undefined-props.js, test/built-ins/Object/freeze/throws-when-false.js, test/built-ins/Object/preventExtensions/throws-when-false.js, test/built-ins/Object/seal/throws-when-false.js, test/built-ins/Reflect/preventExtensions/target-is-not-object-throws.js, test/language/expressions/delete/super-property.js, test/language/expressions/optional-chaining/new-target-optional-call.js
=> fix delete test, add error tests, fix lint

test/intl402/DisplayNames/options-type-valid.js, test/intl402/DisplayNames/prototype/resolvedOptions/option-type.js
to sync with https://github.com/tc39/proposal-intl-displaynames/pull/63
=> Remove date related types for Intl.DisplayNames

test/language/expressions/class/super-evaluation-order.js
For https://github.com/tc39/ecma262/pull/1775
=> super evaluation order tests

test/built-ins/TypedArray/prototype/copyWithin/coerced-values-end-detached-prototype.js, test/built-ins/TypedArray/prototype/copyWithin/coerced-values-end-detached.js, test/built-ins/TypedArray/prototype/copyWithin/coerced-values-start-detached.js
=> Fix syntax typos + whitespace

test/built-ins/Array/prototype/pop/throws-with-string-receiver.js, test/built-ins/Array/prototype/push/throws-with-string-receiver.js, test/built-ins/Array/prototype/shift/throws-with-string-receiver.js, test/built-ins/Array/prototype/unshift/throws-with-string-receiver.js
=> Add tests for Array methods throwing with string receiver.

test/intl402/DateTimeFormat/invalid-numbering-system-calendar-options.js, test/intl402/NumberFormat/invalid-numbering-system-options.js
It is related with #2331.
Cc @leobalter @littledan @FrankYFTang
=> Added tests with invalid values for calendar and numberingSystem

test/built-ins/JSON/stringify/replacer-function-object-deleted-property.js
=> Test that JSON.stringify calls replacer on deleted properties

test/language/literals/numeric/numeric-separators/numeric-separator-literal-dil-dot-nsl-dd-err.js
from https://bugzilla.mozilla.org/show_bug.cgi?id=1609547
=> Add test for NumericLiteralSeparator after decimal point followed by DecimalDigit

test/intl402/NumberFormat/prototype/format/unit-de-DE.js, test/intl402/NumberFormat/prototype/format/unit-en-US.js, test/intl402/NumberFormat/prototype/format/unit-ja-JP.js, test/intl402/NumberFormat/prototype/format/unit-ko-KR.js, test/intl402/NumberFormat/prototype/format/unit-zh-TW.js, test/intl402/NumberFormat/prototype/formatToParts/unit-de-DE.js, test/intl402/NumberFormat/prototype/formatToParts/unit-en-US.js, test/intl402/NumberFormat/prototype/formatToParts/unit-ja-JP.js, test/intl402/NumberFormat/prototype/formatToParts/unit-ko-KR.js, test/intl402/NumberFormat/prototype/formatToParts/unit-zh-TW.js
This ensures https://github.com/tc39/proposal-unified-intl-numberformat/pull/93 is covered.
=> Change the unit in the NumberFormat unit tests.

test/built-ins/TypedArray/prototype/includes/detached-buffer-tointeger.js, test/built-ins/TypedArray/prototype/includes/searchelement-not-integer.js
Security tests for TypedArray.prototype.includes
=> TypedArray includes tests

test/built-ins/Promise/prototype/finally/rejected-observable-then-calls-argument.js, test/built-ins/Promise/prototype/finally/resolved-observable-then-calls-argument.js
Followup to #2471.
Thunks have a length of zero, since they take no arguments.
cc @devsnek @shvaikalesh
=> `Promise.prototype.finally` thunks have a length of 0

test/built-ins/AggregateError/newtarget-proto-fallback.js
=> Fix: AggregateError/newtarget-proto-fallback. Closes gh-2515

test/language/expressions/new/ctorExpr-fn-ref-before-args-eval-fn-wrapup.js, test/language/expressions/new/ctorExpr-fn-ref-before-args-eval.js, test/language/expressions/new/ctorExpr-isCtor-after-args-eval-fn-wrapup.js, test/language/expressions/new/ctorExpr-isCtor-after-args-eval.js
=> Add coverage for EvaluateNew

test/language/module-code/verify-dfs-a_FIXTURE.js, test/language/module-code/verify-dfs-b_FIXTURE.js, test/language/module-code/verify-dfs.js
=> add dfs tests for https://github.com/tc39/ecma262/pull/1669

src/class-elements/static-as-valid-instance-field.case, test/language/expressions/class/elements/static-as-valid-instance-field.js, test/language/statements/class/elements/static-as-valid-instance-field.js
=> Adding case where 'static' is used as a field name

src/class-elements/static-as-valid-instance-field-assigned.case, src/class-elements/static-as-valid-static-field-assigned.case, src/class-elements/static-as-valid-static-field.case, test/language/expressions/class/elements/static-as-valid-instance-field-assigned.js, test/language/expressions/class/elements/static-as-valid-instance-field.js, test/language/expressions/class/elements/static-as-valid-static-field-assigned.js, test/language/expressions/class/elements/static-as-valid-static-field.js, test/language/statements/class/elements/static-as-valid-instance-field-assigned.js, test/language/statements/class/elements/static-as-valid-static-field-assigned.js, test/language/statements/class/elements/static-as-valid-static-field.js
As we added a case for instance field in https://github.com/tc39/test262/pull/2550, we also need a test case for static field named as `static` as well.
=> Adding test to cover case where there is a static field named as 'static'

test/built-ins/NativeErrors/AggregateError/proto-from-ctor-realm.js
JSC bug: [Implement Promise.any and AggregateError](https://bugs.webkit.org/show_bug.cgi?id=202566).
Follow-up of #2335.
=> Add "proto-from-ctor-realm" test for AggregateError

test/intl402/Locale/prototype/minimize/removing-likely-subtags-first-adds-likely-subtags.js
=> Revert "Correct the expectation of zh-Hant for Locale.minimize"

test/built-ins/BigInt/prototype/toString/a-z.js, test/built-ins/Number/prototype/toString/a-z.js
Uncovered by @phoddie and @isomorphic-git
https://twitter.com/phoddie/status/1258258515912581120
=> BigInt/Number.prototype.toString(...), Step 6

test/language/module-code/export-star-as-dflt.js
=> Fix exported bindings and ns

src/class-elements/fields-anonymous-function-length.case, test/language/expressions/class/elements/fields-anonymous-function-length.js, test/language/statements/class/elements/fields-anonymous-function-length.js
Also removes each one grammar and spelling mistake. Introduced in #2322.
=> Fix features in private method length tests

src/class-elements/private-method-referenced-from-static-method.case, test/language/expressions/class/elements/private-method-referenced-from-static-method.js, test/language/statements/class/elements/private-method-referenced-from-static-method.js
=> Fix feature flag in private-method-referenced-from-static-method

make.py, tools/generation/lib/test.py
Also fixes an issue in `tools/generation/`
=> Make make.py python3 compatible

test/language/eval-code/direct/strict-caller-function-context.js, test/language/eval-code/direct/strict-caller-global.js
=> Add tests for direct eval calls in strict context

test/annexB/built-ins/String/prototype/replaceAll/custom-replacer-emulates-undefined.js
=> Fix [[IsHTMLDDA]] Symbol.replaceAll test

test/language/module-code/instn-once.js
Very minor, update comment related to this test.
=> update comments in instn-once.js

test/built-ins/AsyncFromSyncIteratorPrototype/return/return-null.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-null.js, test/built-ins/TypedArrayConstructors/ctors/object-arg/iterator-is-null-as-array-like.js, test/language/expressions/async-generator/yield-star-getiter-async-return-method-is-null.js, test/language/expressions/async-generator/yield-star-getiter-async-throw-method-is-null.js, test/language/expressions/yield/star-return-is-null.js, test/language/expressions/yield/star-throw-is-null.js, test/language/statements/for-await-of/iterator-close-non-throw-get-method-is-null.js, test/language/statements/for-of/iterator-close-non-throw-get-method-is-null.js
=> Improve GetMethod coverage with `null`

test/built-ins/Promise/prototype/finally/rejected-observable-then-calls-argument.js, test/language/expressions/async-generator/yield-thenable-create-resolving-functions-reject.js, test/language/expressions/async-generator/yield-thenable-create-resolving-functions-resolve.js
=> Improve Promise built-in functions coverage

test/built-ins/Promise/all/invoke-resolve-on-promises-every-iteration-of-custom.js, test/built-ins/Promise/all/invoke-resolve-on-promises-every-iteration-of-promise.js, test/built-ins/Promise/all/invoke-resolve-on-values-every-iteration-of-promise.js, test/built-ins/Promise/all/resolve-ignores-late-rejection-deferred.js, test/built-ins/Promise/all/resolve-ignores-late-rejection.js, test/built-ins/Promise/all/resolve-not-callable-reject-with-typeerror.js, test/built-ins/Promise/allSettled/invoke-resolve-on-promises-every-iteration-of-custom.js, test/built-ins/Promise/allSettled/invoke-resolve-on-promises-every-iteration-of-promise.js, test/built-ins/Promise/allSettled/invoke-resolve-on-values-every-iteration-of-promise.js, test/built-ins/Promise/allSettled/resolve-ignores-late-rejection-deferred.js, test/built-ins/Promise/allSettled/resolve-ignores-late-rejection.js, test/built-ins/Promise/allSettled/resolve-not-callable-reject-with-typeerror.js
This is related to #2629. More tests will be added over time.
=> Promise.all, Promise.allSettled: additional coverage

.github/workflows/mirror-master-and-main.yml
Ref https://github.com/chancancode/branch-rename#gradual-migration
=> Add GitHub Workflow to mirror master and main branches

test/intl402/DateTimeFormat/constructor-options-order-timedate-style.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/order-style.js
See
https://github.com/tc39/proposal-intl-datetime-style/pull/43
@zbraniecki @Ms2ger
=> Sync the test w/ changes in intl-datetime-style 43

test/annexB/built-ins/Function/createdynfn-no-line-terminator-html-close-comment-body.js
=> Fix tests for HTML comments in function body evaluation

test/built-ins/Promise/allSettled/reject-element-function-multiple-calls.js, test/built-ins/Promise/allSettled/resolve-from-same-thenable.js
@leobalter can you take a close look at this one for me?
=> Promise.allSettled: coverage updates, R2

test/built-ins/Atomics/waitAsync/bigint/negative-index-throws.js, test/built-ins/Atomics/waitAsync/bigint/out-of-range-index-throws.js, test/built-ins/Atomics/waitAsync/bigint/poisoned-object-for-timeout-throws-agent.js, test/built-ins/Atomics/waitAsync/bigint/poisoned-object-for-timeout-throws.js, test/built-ins/Atomics/waitAsync/bigint/symbol-for-timeout-throws-agent.js, test/built-ins/Atomics/waitAsync/negative-index-throws.js, test/built-ins/Atomics/waitAsync/out-of-range-index-throws.js, test/built-ins/Atomics/waitAsync/poisoned-object-for-timeout-throws-agent.js, test/built-ins/Atomics/waitAsync/poisoned-object-for-timeout-throws.js, test/built-ins/Atomics/waitAsync/symbol-for-timeout-throws-agent.js, test/built-ins/Atomics/waitAsync/validate-arraytype-before-value-coercion.js
Closes #2689
cc @marjakh @rwaldron
=> Fix typo in the tests for waitAsync

test/built-ins/NativeErrors/AggregateError/order-of-args-evaluation.js
=> AggregateError updates. Ref gh-2646

test/built-ins/JSON/stringify/replacer-array-proxy.js
Fixing the language in the current test files.
There are still parts to be fixed within the `implementation-contributed/` folder but they can be resolved by updating the files through the automated import process. 
The remaining files are
- implementation-contributed/v8/mjsunit/es6/unscopables.js
- implementation-contributed/v8/mjsunit/testcfg.py
- implementation-contributed/v8/mjsunit/es6/promises.js
They've already been [fixed in V8](https://github.com/v8/v8/commit/6574a7133d175f5ffec389f236742c248ca231a0#diff-88b35a89cc8fdc6e579dfde6b0cb9ccb).
@rwaldron can handle the remaining part as the automation bot is maintained by Bocoup.
=> Fix language in test file

harness/testIntl.js, test/intl402/DisplayNames/ctor-custom-prototype.js, test/intl402/DisplayNames/ctor-default-prototype.js, test/intl402/DisplayNames/instance-extensible.js, test/intl402/DisplayNames/locales-symbol-length.js, test/intl402/DisplayNames/options-fallback-abrupt-throws.js, test/intl402/DisplayNames/options-fallback-invalid-throws.js, test/intl402/DisplayNames/options-fallback-toString-abrupt-throws.js, test/intl402/DisplayNames/options-fallback-valid.js, test/intl402/DisplayNames/options-localeMatcher-valid.js, test/intl402/DisplayNames/options-random-properties-unchecked.js, test/intl402/DisplayNames/options-style-valid.js, test/intl402/DisplayNames/options-type-invalid-throws.js, test/intl402/DisplayNames/options-type-valid.js, test/intl402/DisplayNames/proto-from-ctor-realm.js, test/intl402/DisplayNames/prototype/resolvedOptions/default-option-values.js, test/intl402/DisplayNames/prototype/resolvedOptions/option-fallback.js, test/intl402/DisplayNames/prototype/resolvedOptions/option-style.js, test/intl402/DisplayNames/prototype/resolvedOptions/return-object.js
Update the tests to the latest version after we make
the type option now required
Spec:
https://tc39.es/proposal-intl-displaynames/
Changes of spec:
https://github.com/tc39/proposal-intl-displaynames/pull/76
https://github.com/tc39/proposal-intl-displaynames/pull/83
@anba @Ms2ger @rwaldron @zbraniecki @littledan @rkirsling @syg @leobalter
=> Intl.DisplayNames make type required

test/annexB/language/statements/class/subclass/superclass-prototype-emulates-undefined.js
Follow-up of #2579.
See also #2652.
=> Test [[IsHTMLDDA]] object as "prototype" of superclass

.github/workflows/update-master-after-main.yml, CONTRIBUTING.md, INTERPRETING.md, harness/atomicsHelper.js, make.py, package.json, test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T2.js, test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T3.js, tools/lint/lib/checks/license.py, tools/lint/test/fixtures/license_alternate_5.js, tools/packaging/parseTestRecord.py, tools/scripts/ci_build.sh, tools/scripts/ci_lint.sh, tools/scripts/ci_test.sh, tools/scripts/deploy.sh
=> Rename usage of master to main

.github/workflows/update-master-after-main.yml
=> Fix bad renaming, main should upstream to master

test/built-ins/Reflect/Symbol.toStringTag.js
see https://github.com/tc39/ecma262/pull/2057
=> Add tests for `Reflect[Symbol.toStringTag]`

test/annexB/language/expressions/typeof/emulates-undefined.js
=> Test [[IsHTMLDDA]] object with `typeof` operator

test/annexB/language/expressions/coalesce/emulates-undefined.js, test/annexB/language/expressions/conditional/emulates-undefined.js, test/annexB/language/expressions/logical-and/emulates-undefined.js, test/annexB/language/expressions/logical-assignment/emulates-undefined-and.js, test/annexB/language/expressions/logical-assignment/emulates-undefined-coalesce.js, test/annexB/language/expressions/logical-assignment/emulates-undefined-or.js, test/annexB/language/expressions/logical-not/emulates-undefined.js, test/annexB/language/expressions/logical-or/emulates-undefined.js, test/annexB/language/statements/if/emulated-undefined.js
Closes #1372.
Related: #2725, #2706.
Tested manually in FF 81 and Chrome 86: all tests pass.
=> Test [[IsHTMLDDA]] object with ToBoolean and nullish coalescing

test/built-ins/Atomics/notify/null-bufferdata-throws.js, test/built-ins/Atomics/wait/null-bufferdata-throws.js
Re: https://github.com/tc39/test262/issues/2721
=> Atomics: fix test info contents to match definition as it appears in ES2020. Fixes gh-2721

test/built-ins/Array/length/define-own-prop-length-coercion-order-set.js, test/built-ins/Array/length/define-own-prop-length-coercion-order.js, test/built-ins/Array/length/define-own-prop-length-no-value-order.js, test/built-ins/Array/length/define-own-prop-length-overflow-order.js
JSC bug: [Assertion failure when redefining array length](https://bugs.webkit.org/show_bug.cgi?id=158791).
=> Test "length" [[Value]] coercion & overflow check order in ArraySetLength

test/intl402/Segmenter/constructor/constructor/options-granularity-abrupt-throws.js, test/intl402/Segmenter/constructor/constructor/options-granularity-invalid.js, test/intl402/Segmenter/constructor/constructor/options-granularity-toString-abrupt-throws.js, test/intl402/Segmenter/constructor/constructor/options-localeMatcher-abrupt-throws.js, test/intl402/Segmenter/constructor/constructor/options-localeMatcher-toString-abrupt-throws.js, test/intl402/Segmenter/constructor/constructor/options-localeMatcher-valid.js, test/intl402/Segmenter/constructor/constructor/options-null.js, test/intl402/Segmenter/ctor-custom-get-prototype-poison-throws.js, test/intl402/Segmenter/ctor-custom-prototype.js, test/intl402/Segmenter/ctor-default-prototype.js, test/intl402/Segmenter/proto-from-ctor-realm.js, test/intl402/Segmenter/prototype/Symbol.toStringTag.js, test/intl402/Segmenter/prototype/segment/containing/branding.js, test/intl402/Segmenter/prototype/segment/containing/breakable-input.js, test/intl402/Segmenter/prototype/segment/containing/index-throws.js, test/intl402/Segmenter/prototype/segment/containing/iswordlike.js, test/intl402/Segmenter/prototype/segment/containing/length.js, test/intl402/Segmenter/prototype/segment/containing/name.js, test/intl402/Segmenter/prototype/segment/containing/one-index.js, test/intl402/Segmenter/prototype/segment/containing/out-of-bound-index.js, test/intl402/Segmenter/prototype/segment/containing/prop-desc.js, test/intl402/Segmenter/prototype/segment/containing/unbreakable-input.js, test/intl402/Segmenter/prototype/segment/containing/word-iswordlike.js, test/intl402/Segmenter/prototype/segment/containing/zero-index.js, test/intl402/Segmenter/prototype/segment/nested-next.js, test/intl402/Segmenter/prototype/segment/next-inside-next.js, test/intl402/Segmenter/prototype/segment/next-mix-with-containing.js
@leobalter @gibson042 @zbraniecki @anba
=> Add more tests for Intl.Segmenter

test/built-ins/Promise/prototype/finally/rejected-observable-then-calls-PromiseResolve.js, test/built-ins/Promise/prototype/finally/resolved-observable-then-calls-PromiseResolve.js
JSC bug: [`Promise.prototype.finally` should perform `PromiseResolve`](https://bugs.webkit.org/show_bug.cgi?id=176006).
_cc_ @ljharb
=> Test that Promise.prototype.finally calls PromiseResolve

test/built-ins/FinalizationRegistry/gc-has-one-chance-to-call-cleanupCallback.js
Per recommendation here: https://github.com/web-platform-tests/wpt/pull/25496/files#r488316588
=> Refactor: built-ins/FinalizationRegistry/gc-has-one-chance-to-call-cleanupCallback.js

src/dstr-assignment/obj-rest-non-string-computed-property.case, test/language/expressions/assignment/dstr/obj-rest-non-string-computed-property.js, test/language/statements/for-of/dstr/obj-rest-non-string-computed-property.js
=> Add coverage for rest properties with computed key

test/built-ins/Date/UTC/fp-evaluation-order.js
This adds a test for https://github.com/tc39/ecma262/pull/2120.
=> Coverage: Date arithmetic is floating point

test/language/module-code/early-export-ill-formed-string.js, test/language/module-code/export-expname-binding-string.js, test/language/module-code/export-expname-from-binding-string.js, test/language/module-code/export-expname-from-star-string.js, test/language/module-code/export-expname-from-star.js, test/language/module-code/export-expname-from-string-binding.js, test/language/module-code/export-expname-from-string-string.js, test/language/module-code/export-expname-from-string.js, test/language/module-code/export-expname-import-string-binding.js, test/language/module-code/export-expname_FIXTURE.js
see https://github.com/tc39/ecma262/pull/2154
=> tests for https://github.com/tc39/ecma262/pull/2154

test/intl402/Collator/constructor-options-throwing-getters.js
To test change in https://github.com/tc39/ecma402/pull/459
=> Add the check of collation in options

test/language/module-code/export-expname-from-as-unpaired-surrogate.js, test/language/module-code/export-expname-from-star-unpaired-surrogate.js, test/language/module-code/export-expname-from-unpaired-surrogate.js, test/language/module-code/export-expname-import-unpaired-surrogate.js, test/language/module-code/export-expname-string-binding.js, test/language/module-code/export-expname-unpaired-surrogate.js
=> Add SyntaxError tests for string literal export name

test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/BigInt/detached-buffer-realm.js, test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/BigInt/key-is-numericindex-desc-configurable.js, test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/BigInt/key-is-numericindex.js, test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/key-is-numericindex-desc-configurable.js, test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/key-is-numericindex.js
=> Align detached buffer semantics with web reality, R2

test/built-ins/TypedArray/prototype/every/BigInt/callbackfn-detachbuffer.js, test/built-ins/TypedArray/prototype/filter/BigInt/callbackfn-detachbuffer.js, test/built-ins/TypedArray/prototype/find/BigInt/predicate-may-detach-buffer.js, test/built-ins/TypedArray/prototype/forEach/BigInt/callbackfn-detachbuffer.js, test/built-ins/TypedArray/prototype/map/BigInt/callbackfn-detachbuffer.js, test/built-ins/TypedArray/prototype/reduce/BigInt/callbackfn-detachbuffer.js, test/built-ins/TypedArray/prototype/reduceRight/BigInt/callbackfn-detachbuffer.js, test/built-ins/TypedArray/prototype/some/BigInt/callbackfn-detachbuffer.js, test/built-ins/TypedArrayConstructors/internals/GetOwnProperty/index-prop-desc.js, test/built-ins/TypedArrayConstructors/internals/Set/BigInt/detached-buffer.js
=> Align detached buffer semantics with web reality, R4. Fixes gh-2879

test/built-ins/Array/prototype/at/name.js, test/built-ins/Array/prototype/at/prop-desc.js, test/built-ins/Array/prototype/at/returns-item-relative-index.js, test/built-ins/Array/prototype/at/returns-item.js, test/built-ins/Array/prototype/at/returns-undefined-for-holes-in-sparse-arrays.js, test/built-ins/String/prototype/at/name.js, test/built-ins/String/prototype/at/prop-desc.js, test/built-ins/String/prototype/at/returns-code-unit.js, test/built-ins/String/prototype/at/returns-item-relative-index.js, test/built-ins/String/prototype/at/returns-item.js, test/built-ins/TypedArray/prototype/at/name.js, test/built-ins/TypedArray/prototype/at/prop-desc.js
includes nit pick using verifyProperty
Ref #2905
=> Fix missing renames for item->at

test/intl402/DateTimeFormat/prototype/formatRange/date-x-greater-than-y-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-x-greater-than-y-throws.js
Update the description of some Intl.DateTimeFormat formatRange(ToParts) tests based on changes introduced in tc39/proposal-intl-DateTimeFormat-formatRange#23
=> Update description of intl402 formatRange(ToParts) tests

harness/testIntl.js, test/intl402/Intl/getCanonicalLocales/canonicalized-tags.js, test/intl402/Intl/getCanonicalLocales/preferred-grandfathered.js, test/intl402/Intl/getCanonicalLocales/preferred-variant.js, test/intl402/Locale/extensions-grandfathered.js
=> Update test according to CLDR38

test/intl402/Locale/likely-subtags-grandfathered.js
see http://unicode.org/reports/tr35/#LocaleId_Canonicalization
@anba
=> Update the test based on v35 of UTS35

test/language/statements/for-of/head-lhs-async-dot.js, test/language/statements/for-of/head-lhs-async-invalid.js, test/language/statements/for/head-init-async-of.js
This adds tests for https://github.com/tc39/ecma262/pull/2256.
=> add tests for `for ( async of`

src/class-elements/super-access-from-arrow-func-on-field.case, test/language/expressions/class/elements/super-access-from-arrow-func-on-field.js, test/language/statements/class/elements/super-access-from-arrow-func-on-field.js
=> Adding test case for super access from class field defined as arrow function

features.txt, test/language/expressions/in/private-field-in.js, test/language/expressions/in/private-field-invalid-assignment-target.js, test/language/expressions/in/private-field-invalid-identifier-complex.js, test/language/expressions/in/private-field-invalid-identifier-simple.js, test/language/expressions/in/private-field-invalid-rhs.js, test/language/expressions/in/private-field-presence-accessor-shadowed.js, test/language/expressions/in/private-field-presence-accessor.js, test/language/expressions/in/private-field-presence-field-shadowed.js, test/language/expressions/in/private-field-presence-field.js, test/language/expressions/in/private-field-presence-method-shadowed.js, test/language/expressions/in/private-field-presence-method.js, test/language/expressions/in/private-field-rhs-await-absent.js, test/language/expressions/in/private-field-rhs-await-present.js, test/language/expressions/in/private-field-rhs-non-object.js, test/language/expressions/in/private-field-rhs-unresolvable.js, test/language/expressions/in/private-field-rhs-yield-absent.js, test/language/expressions/in/private-field-rhs-yield-present.js
I have two questions about the "private class fields" proposal which have bearing on the tests for this proposal:
- [the fallibility of ResolveBinding when applied to a PrivateEnvironment](https://github.com/tc39/ecma262/pull/1668/files#r584007453)
- [the expected behavior of GetValue when applied to a private name binding](https://github.com/tc39/ecma262/pull/1668/files#r570729429)
=> Add tests for stage 3 proposal "private fields in"

src/computed-property-names/computed-property-name-from-assignment-expression-coalesce.case, src/computed-property-names/computed-property-name-from-assignment-expression-logical-and.case, src/computed-property-names/computed-property-name-from-assignment-expression-logical-or.case, test/language/expressions/class/cpn-class-expr-accessors-computed-property-name-from-assignment-expression-coalesce.js, test/language/expressions/class/cpn-class-expr-accessors-computed-property-name-from-assignment-expression-logical-and.js, test/language/expressions/class/cpn-class-expr-accessors-computed-property-name-from-assignment-expression-logical-or.js, test/language/expressions/class/cpn-class-expr-computed-property-name-from-assignment-expression-coalesce.js, test/language/expressions/class/cpn-class-expr-computed-property-name-from-assignment-expression-logical-and.js, test/language/expressions/class/cpn-class-expr-computed-property-name-from-assignment-expression-logical-or.js, test/language/expressions/class/cpn-class-expr-fields-computed-property-name-from-assignment-expression-coalesce.js, test/language/expressions/class/cpn-class-expr-fields-computed-property-name-from-assignment-expression-logical-and.js, test/language/expressions/class/cpn-class-expr-fields-computed-property-name-from-assignment-expression-logical-or.js, test/language/expressions/class/cpn-class-expr-fields-methods-computed-property-name-from-assignment-expression-coalesce.js, test/language/expressions/class/cpn-class-expr-fields-methods-computed-property-name-from-assignment-expression-logical-and.js, test/language/expressions/class/cpn-class-expr-fields-methods-computed-property-name-from-assignment-expression-logical-or.js, test/language/expressions/object/cpn-obj-lit-computed-property-name-from-assignment-expression-coalesce.js, test/language/expressions/object/cpn-obj-lit-computed-property-name-from-assignment-expression-logical-and.js, test/language/expressions/object/cpn-obj-lit-computed-property-name-from-assignment-expression-logical-or.js, test/language/statements/class/cpn-class-decl-accessors-computed-property-name-from-assignment-expression-coalesce.js, test/language/statements/class/cpn-class-decl-accessors-computed-property-name-from-assignment-expression-logical-and.js, test/language/statements/class/cpn-class-decl-accessors-computed-property-name-from-assignment-expression-logical-or.js, test/language/statements/class/cpn-class-decl-computed-property-name-from-assignment-expression-coalesce.js, test/language/statements/class/cpn-class-decl-computed-property-name-from-assignment-expression-logical-and.js, test/language/statements/class/cpn-class-decl-computed-property-name-from-assignment-expression-logical-or.js, test/language/statements/class/cpn-class-decl-fields-computed-property-name-from-assignment-expression-coalesce.js, test/language/statements/class/cpn-class-decl-fields-computed-property-name-from-assignment-expression-logical-and.js, test/language/statements/class/cpn-class-decl-fields-computed-property-name-from-assignment-expression-logical-or.js, test/language/statements/class/cpn-class-decl-fields-methods-computed-property-name-from-assignment-expression-coalesce.js, test/language/statements/class/cpn-class-decl-fields-methods-computed-property-name-from-assignment-expression-logical-and.js, test/language/statements/class/cpn-class-decl-fields-methods-computed-property-name-from-assignment-expression-logical-or.js
=> Apply `logical-assignment-operators` feature flag

test/built-ins/TypedArrayConstructors/internals/Set/BigInt/key-is-canonical-invalid-index-prototype-chain-set.js, test/built-ins/TypedArrayConstructors/internals/Set/BigInt/key-is-canonical-invalid-index-reflect-set.js, test/built-ins/TypedArrayConstructors/internals/Set/BigInt/key-is-valid-index-prototype-chain-set.js, test/built-ins/TypedArrayConstructors/internals/Set/BigInt/key-is-valid-index-reflect-set.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-canonical-invalid-index-prototype-chain-set.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-canonical-invalid-index-reflect-set.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-valid-index-prototype-chain-set.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-valid-index-reflect-set.js
⚠️ **don't merge yet** ⚠️
Ref. https://github.com/tc39/ecma262/pull/1556
=> Test TypedArray's [[Set]] internal method with altered receiver

tools/lint/lib/checks/features.py, tools/lint/test/fixtures/test/features_duplicated.js
As highlighted by gh-3006. cc @jmdyck
=> lint: disallow duplicate values in "features" tag

features.txt
@rwaldron @leobalter @ryzokuken @zbraniecki @anba @Ms2ger @litt
=> Add feature values for ECMA402 Stage 3 proposals

features.txt, test/built-ins/ArrayBuffer/prototype/maxByteLength/detached-buffer.js, test/built-ins/ArrayBuffer/prototype/maxByteLength/invoked-as-accessor.js, test/built-ins/ArrayBuffer/prototype/maxByteLength/invoked-as-func.js, test/built-ins/ArrayBuffer/prototype/maxByteLength/length.js, test/built-ins/ArrayBuffer/prototype/maxByteLength/name.js, test/built-ins/ArrayBuffer/prototype/maxByteLength/prop-desc.js, test/built-ins/ArrayBuffer/prototype/maxByteLength/return-maxbytelength-non-resizable.js, test/built-ins/ArrayBuffer/prototype/maxByteLength/return-maxbytelength-resizable.js, test/built-ins/ArrayBuffer/prototype/maxByteLength/this-has-no-arraybufferdata-internal.js, test/built-ins/ArrayBuffer/prototype/maxByteLength/this-is-not-object.js, test/built-ins/ArrayBuffer/prototype/maxByteLength/this-is-sharedarraybuffer.js, test/built-ins/ArrayBuffer/prototype/resizable/detached-buffer.js, test/built-ins/ArrayBuffer/prototype/resizable/invoked-as-accessor.js, test/built-ins/ArrayBuffer/prototype/resizable/invoked-as-func.js, test/built-ins/ArrayBuffer/prototype/resizable/length.js, test/built-ins/ArrayBuffer/prototype/resizable/name.js, test/built-ins/ArrayBuffer/prototype/resizable/prop-desc.js, test/built-ins/ArrayBuffer/prototype/resizable/return-resizable.js, test/built-ins/ArrayBuffer/prototype/resizable/this-has-no-arraybufferdata-internal.js, test/built-ins/ArrayBuffer/prototype/resizable/this-is-not-object.js, test/built-ins/ArrayBuffer/prototype/resizable/this-is-sharedarraybuffer.js
=> Resizable ArrayBuffer: ArrayBuffer accessors

features.txt, test/built-ins/DataView/prototype/byteLength/resizable-array-buffer-auto.js, test/built-ins/DataView/prototype/byteLength/resizable-array-buffer-fixed.js, test/built-ins/DataView/prototype/byteOffset/resizable-array-buffer-auto.js, test/built-ins/DataView/prototype/byteOffset/resizable-array-buffer-fixed.js
=> Resizable ArrayBuffer: DataView accessors

features.txt, test/built-ins/SharedArrayBuffer/options-maxbytelength-diminuitive.js, test/built-ins/SharedArrayBuffer/options-maxbytelength-excessive.js, test/built-ins/SharedArrayBuffer/options-maxbytelength-negative.js, test/built-ins/SharedArrayBuffer/options-maxbytelength-object.js, test/built-ins/SharedArrayBuffer/options-maxbytelength-poisoned.js, test/built-ins/SharedArrayBuffer/options-maxbytelength-undefined.js, test/built-ins/SharedArrayBuffer/options-non-object.js
=> Resizable ArrayBuffer: SharedArrayBuffer ctor

features.txt, test/built-ins/SharedArrayBuffer/prototype/grow/descriptor.js, test/built-ins/SharedArrayBuffer/prototype/grow/extensible.js, test/built-ins/SharedArrayBuffer/prototype/grow/grow-larger-size.js, test/built-ins/SharedArrayBuffer/prototype/grow/grow-same-size.js, test/built-ins/SharedArrayBuffer/prototype/grow/grow-smaller-size.js, test/built-ins/SharedArrayBuffer/prototype/grow/length.js, test/built-ins/SharedArrayBuffer/prototype/grow/name.js, test/built-ins/SharedArrayBuffer/prototype/grow/new-length-excessive.js, test/built-ins/SharedArrayBuffer/prototype/grow/new-length-negative.js, test/built-ins/SharedArrayBuffer/prototype/grow/new-length-non-number.js, test/built-ins/SharedArrayBuffer/prototype/grow/nonconstructor.js, test/built-ins/SharedArrayBuffer/prototype/grow/this-is-not-arraybuffer-object.js, test/built-ins/SharedArrayBuffer/prototype/grow/this-is-not-object.js, test/built-ins/SharedArrayBuffer/prototype/grow/this-is-not-resizable-arraybuffer-object.js, test/built-ins/SharedArrayBuffer/prototype/grow/this-is-sharedarraybuffer.js
=> Resizable ArrayBuffer: SharedArrayBuffer methods 

features.txt, test/built-ins/SharedArrayBuffer/prototype/growable/invoked-as-accessor.js, test/built-ins/SharedArrayBuffer/prototype/growable/invoked-as-func.js, test/built-ins/SharedArrayBuffer/prototype/growable/length.js, test/built-ins/SharedArrayBuffer/prototype/growable/name.js, test/built-ins/SharedArrayBuffer/prototype/growable/prop-desc.js, test/built-ins/SharedArrayBuffer/prototype/growable/return-growable.js, test/built-ins/SharedArrayBuffer/prototype/growable/this-has-no-arraybufferdata-internal.js, test/built-ins/SharedArrayBuffer/prototype/growable/this-is-arraybuffer.js, test/built-ins/SharedArrayBuffer/prototype/growable/this-is-not-object.js, test/built-ins/SharedArrayBuffer/prototype/maxByteLength/invoked-as-accessor.js, test/built-ins/SharedArrayBuffer/prototype/maxByteLength/invoked-as-func.js, test/built-ins/SharedArrayBuffer/prototype/maxByteLength/length.js, test/built-ins/SharedArrayBuffer/prototype/maxByteLength/name.js, test/built-ins/SharedArrayBuffer/prototype/maxByteLength/prop-desc.js, test/built-ins/SharedArrayBuffer/prototype/maxByteLength/return-maxbytelength-growable.js, test/built-ins/SharedArrayBuffer/prototype/maxByteLength/return-maxbytelength-non-growable.js, test/built-ins/SharedArrayBuffer/prototype/maxByteLength/this-has-no-arraybufferdata-internal.js, test/built-ins/SharedArrayBuffer/prototype/maxByteLength/this-is-arraybuffer.js, test/built-ins/SharedArrayBuffer/prototype/maxByteLength/this-is-not-object.js
=> Resizable ArrayBuffer: SharedArrayBuffer accessors

features.txt, test/built-ins/TypedArrayConstructors/ctors/buffer-arg/excessive-offset-throws-resizable-ab.js, test/built-ins/TypedArrayConstructors/ctors/typedarray-arg/out-of-bounds-when-species-retrieved-different-type.js, test/built-ins/TypedArrayConstructors/ctors/typedarray-arg/out-of-bounds-when-species-retrieved-same-type.js, test/built-ins/TypedArrayConstructors/internals/HasProperty/resizable-array-buffer-auto.js, test/built-ins/TypedArrayConstructors/internals/HasProperty/resizable-array-buffer-fixed.js, test/built-ins/TypedArrayConstructors/internals/OwnPropertyKeys/integer-indexes-resizable-array-buffer-auto.js, test/built-ins/TypedArrayConstructors/internals/OwnPropertyKeys/integer-indexes-resizable-array-buffer-fixed.js
=> Resizable ArrayBuffer: TypedArray constructor

features.txt, test/built-ins/TypedArray/prototype/byteLength/resizable-array-buffer-auto.js, test/built-ins/TypedArray/prototype/byteLength/resizable-array-buffer-fixed.js, test/built-ins/TypedArray/prototype/byteOffset/resizable-array-buffer-auto.js, test/built-ins/TypedArray/prototype/byteOffset/resizable-array-buffer-fixed.js, test/built-ins/TypedArray/prototype/length/resizable-array-buffer-auto.js, test/built-ins/TypedArray/prototype/length/resizable-array-buffer-fixed.js
=> Resizable ArrayBuffer: TypedArray accessors

harness/compareArray.js, harness/sta.js
Also see https://github.com/tc39/test262/issues/3032
=> Remove usage of rest and default parameters in harness

test/built-ins/SharedArrayBuffer/options-maxbytelength-undefined.js, test/built-ins/SharedArrayBuffer/options-non-object.js, test/built-ins/SharedArrayBuffer/prototype/growable/this-is-arraybuffer.js, test/built-ins/SharedArrayBuffer/prototype/maxByteLength/this-is-arraybuffer.js
=> Correct errors in SharedArrayBuffer tests

test/intl402/DateTimeFormat/constructor-options-timeZoneName-invalid.js, test/intl402/DateTimeFormat/constructor-options-timeZoneName-valid.js
=> Add tests: "Extend TimeZoneName Option" proposal

tools/generation/lib/util/parse_yaml.py
@rwaldron Looks like I missed a comment update during iteration on #3041
=> Fix typo in comment

test/built-ins/Realm/extensibility.js, test/built-ins/Realm/instance-extensibility.js, test/built-ins/Realm/instance.js, test/built-ins/Realm/prototype/Symbol.toStringTag.js, test/built-ins/Realm/prototype/evaluate/not-constructor.js, test/built-ins/Realm/prototype/evaluate/returns-primitive-values.js, test/built-ins/Realm/prototype/evaluate/throws-when-argument-is-not-a-string.js, test/built-ins/Realm/prototype/evaluate/validates-realm-object.js, test/built-ins/Realm/prototype/evaluate/wrapped-functions-new-wrapping-on-each-evaluation.js, test/built-ins/Realm/prototype/importValue/not-constructor.js, test/built-ins/Realm/prototype/importValue/validates-realm-object.js
This is adding a few things to #3046
=> A few tweaks to the Realms tests

test/intl402/Locale/prototype/calendars/output-array.js, test/intl402/Locale/prototype/collations/output-array-values.js, test/intl402/Locale/prototype/hourCycles/output-array-values.js, test/intl402/Locale/prototype/numberingSystems/output-array.js, test/intl402/Locale/prototype/textInfo/output-object-keys.js, test/intl402/Locale/prototype/timeZones/output-array.js, test/intl402/Locale/prototype/weekInfo/output-object-keys.js
/cc @ryzokuken @FrankYFTang @Ms2ger
=> Improve coverage for Intl Locale Info proposal

test/built-ins/TypedArrayConstructors/internals/HasProperty/resizable-array-buffer-fixed.js
=> Correct typo in expected value

test/intl402/DisplayNames/options-languagedisplay-abrupt-throws.js, test/intl402/DisplayNames/options-languagedisplay-invalid-throws.js, test/intl402/DisplayNames/options-languagedisplay-toString-abrupt-throws.js, test/intl402/DisplayNames/options-languagedisplay-valid.js, test/intl402/DisplayNames/prototype/of/type-calendar-invalid.js, test/intl402/DisplayNames/prototype/of/type-calendar-valid.js, test/intl402/DisplayNames/prototype/of/type-datetimefield-invalid.js, test/intl402/DisplayNames/prototype/of/type-datetimefield-valid.js, test/intl402/DisplayNames/prototype/resolvedOptions/option-fallback.js, test/intl402/DisplayNames/prototype/resolvedOptions/option-languagedisplay.js, test/intl402/DisplayNames/prototype/resolvedOptions/option-style.js, test/intl402/DisplayNames/prototype/resolvedOptions/option-type.js, test/intl402/DisplayNames/prototype/resolvedOptions/return-object.js
https://tc39.es/intl-displaynames-v2/
=> Add tests for proposal, "Intl.DisplayNames v2"

test/language/expressions/in/private-field-in-nested.js, test/language/expressions/in/private-field-invalid-assignment-reference.js, test/language/statements/class/elements/get-access-of-missing-private-static-getter.js, test/language/statements/class/elements/private-method-double-initialisation-get-and-set.js, test/language/statements/class/elements/private-method-double-initialisation-get.js, test/language/statements/class/elements/private-method-double-initialisation-set.js, test/language/statements/class/elements/private-method-double-initialisation.js, test/language/statements/class/elements/private-method-not-writable.js, test/language/statements/class/elements/private-static-method-not-writable.js, test/language/statements/class/elements/privatefieldset-evaluation-order-1.js, test/language/statements/class/elements/privatefieldset-evaluation-order-2.js, test/language/statements/class/elements/privatefieldset-evaluation-order-3.js, test/language/statements/class/elements/privatefieldset-typeerror-10.js, test/language/statements/class/elements/privatefieldset-typeerror-11.js, test/language/statements/class/elements/privatefieldset-typeerror-6.js, test/language/statements/class/elements/privatefieldset-typeerror-7.js, test/language/statements/class/elements/privatefieldset-typeerror-8.js, test/language/statements/class/elements/privatefieldset-typeerror-9.js, test/language/statements/class/elements/set-access-of-missing-private-static-setter.js
This adds tests for implementation bugs in SpiderMonkey [1], plus
additional tests for implementation bugs in V8 and JSC.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1723155
=> Add various private field and private method tests

test/built-ins/Object/entries/order-after-define-property-with-function.js, test/built-ins/Object/keys/order-after-define-property-with-function.js, test/built-ins/Object/keys/order-after-define-property.js, test/language/computed-property-names/class/static/method-number-order.js, test/language/computed-property-names/class/static/method-number.js, test/language/computed-property-names/class/static/method-string-order.js, test/language/computed-property-names/class/static/method-symbol-order.js, test/language/computed-property-names/class/static/method-symbol.js, test/language/statements/class/definition/fn-length-static-precedence-order.js, test/language/statements/class/definition/fn-name-static-precedence-order.js, test/language/statements/class/definition/fn-name-static-precedence.js
So SpiderMonkey can run the other parts of these tests.
The SpiderMonkey bug for this issue is <https://bugzilla.mozilla.org/show_bug.cgi?id=1629803>.
=> Split files which test for the property order of functions

features.txt
For https://github.com/tc39/test262/issues/3131
=> Add Intl-enumeration

test/built-ins/Math/hypot/Math.hypot_ToNumberErr.js, test/built-ins/Math/hypot/Math.hypot_Zero_2.js
https://bugs.webkit.org/show_bug.cgi?id=229843
=> Test Math.hypot argument coercion

test/built-ins/Math/hypot/Math.hypot_ToNumberErr.js
Remove semantics which are not necessary to exercise the behavior under
test.
=> Simplify test

test/built-ins/Temporal/Now/plainDateTimeISO/extensible.js, test/built-ins/Temporal/Now/plainDateTimeISO/length.js, test/built-ins/Temporal/Now/plainDateTimeISO/name.js, test/built-ins/Temporal/Now/plainDateTimeISO/not-a-constructor.js, test/built-ins/Temporal/Now/plainDateTimeISO/prop-desc.js, test/built-ins/Temporal/Now/plainDateTimeISO/return-value.js, test/built-ins/Temporal/Now/plainDateTimeISO/time-zone-undefined.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-getoffsetnanosecondsfor-invocation.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-getoffsetnanosecondsfor-non-integer.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-getoffsetnanosecondsfor-non-method.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-getoffsetnanosecondsfor-not-a-number.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-getoffsetnanosecondsfor-out-of-range.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-getoffsetnanosecondsfor-poisoned.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-getoffsetnanosecondsfor-throws.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-getoffsetnanosecondsfor-wrong-type.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-object-fail-call-tostring.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-object-fail-get-timezone.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-object-fail-has-nested-timezone.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-object-fail-has-timezone.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-object.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-string-datetime.js
In service of gh-3002
/cc @ptomato @Ms2ger
=> Add tests for Temporal.Now.plainDateTimeISO

test/built-ins/ShadowRealm/prototype/evaluate/returns-symbol-values.js, test/built-ins/ShadowRealm/prototype/evaluate/wrapped-function-multiple-different-realms.js
cc @philomates @rwaldron 
Ref #3197
=> Fix ShadowRealms tests typos/issues

test/built-ins/Temporal/Now/plainDateTimeISO/timezone-string-datetime.js
=> improve the case with the version without :

test/built-ins/ShadowRealm/prototype/evaluate/wrapped-function-proto-from-caller-realm.js
ShadowRealm could be used cross realms.
=> Add tests for cross realms in ShadowRealm.prototype.evaluate

test/built-ins/ShadowRealm/prototype/evaluate/wrapped-function-throws-typeerror-from-caller-realm.js
Refs: https://github.com/tc39/test262/pull/3251#discussion_r724404491
Tests for https://github.com/tc39/proposal-shadowrealm/pull/330.
=> Add coverage on error throwing of wrapped function created in different realms

CONTRIBUTING.md
=> Document more test metadata in contribution guide

test/intl402/Locale/prototype/weekInfo/output-object-keys.js
weekendStart / weekendEnd are merged into one weekend array.
=> Update Intl.Locale info API test

test/built-ins/Temporal/PlainYearMonth/prototype/since/largestunit-disallowed-units.js, test/built-ins/Temporal/PlainYearMonth/prototype/since/mixed-calendar-invalid.js, test/built-ins/Temporal/PlainYearMonth/prototype/since/options-invalid.js, test/built-ins/Temporal/PlainYearMonth/prototype/since/smallestunit-disallowed-units.js
Further tests related to Demitasse port. (See https://github.com/tc39/test262/pull/3313#partial-pull-merging.)
=> Tests disallowed/invalid arguments in PYM.since

test/intl402/NumberFormat/prototype/format/useGrouping-extended-en-IN.js, test/intl402/NumberFormat/prototype/format/useGrouping-extended-en-US.js
=> Fix wrong expectation in useGrouping-extended-en-* tests

features.txt, test/intl402/DurationFormat/prototype/prototype_attributes.js, test/intl402/DurationFormat/prototype/toStringTag.js
=> test(Intl.DurationFormat.prototype): check prototype

test/intl402/NumberFormat/prototype/format/value-decimal-string.js
=> correct test result in NumberFormat/...value-decimal-string.js

harness/temporalHelpers.js, test/built-ins/Temporal/TimeZone/prototype/getNextTransition/instant-string.js, test/built-ins/Temporal/TimeZone/prototype/getOffsetNanosecondsFor/instant-string.js, test/built-ins/Temporal/TimeZone/prototype/getOffsetStringFor/instant-string.js, test/built-ins/Temporal/TimeZone/prototype/getPreviousTransition/instant-string.js, test/built-ins/Temporal/ZonedDateTime/prototype/equals/zoneddatetime-string.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/zoneddatetime-string.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/zoneddatetime-string.js
Here are some minor maintenance-type changes that I wrote while working on #3346, separated out of that PR for ease of review.
=> Various fixes to Temporal tests

test/built-ins/ShadowRealm/prototype/importValue/throws-if-import-value-does-not-exist.js
Refs: https://github.com/tc39/test262/pull/3341#discussion_r768942494
=> Revert removal of module flag in ShadowRealm.prototype.importValue tests

test/built-ins/DataView/custom-proto-access-resizes-buffer-invalid-by-length.js, test/built-ins/DataView/custom-proto-access-resizes-buffer-invalid-by-offset.js, test/built-ins/DataView/custom-proto-access-resizes-buffer-valid-by-length.js, test/built-ins/DataView/custom-proto-access-resizes-buffer-valid-by-offset.js
This is intended to resolve gh-3327.
/cc @marjakh
=> Add tests: resizing ArrayBuffer from DataView ctor

test/built-ins/Temporal/PlainDate/from/argument-object.js
2nd argument of TemporalHelpers.assertPlainDate is year, not Temporal.PlainDate object.
@Ms2ger
=> Fix incorrect argument

test/intl402/DurationFormat/instance/extensibility.js, test/intl402/DurationFormat/instance/length.js, test/intl402/DurationFormat/instance/name.js, test/intl402/DurationFormat/instance/prop-desc.js, test/intl402/DurationFormat/instance/prototype.js, test/intl402/DurationFormat/prototype/constructor/prop-desc.js, test/intl402/DurationFormat/prototype/constructor/value.js, test/intl402/DurationFormat/prototype/format/length.js, test/intl402/DurationFormat/prototype/format/name.js, test/intl402/DurationFormat/prototype/format/prop-desc.js, test/intl402/DurationFormat/prototype/format/throw-invoked-as-func.js, test/intl402/DurationFormat/prototype/formatToParts/length.js, test/intl402/DurationFormat/prototype/formatToParts/name.js, test/intl402/DurationFormat/prototype/formatToParts/prop-desc.js, test/intl402/DurationFormat/prototype/formatToParts/throw-invoked-as-func.js, test/intl402/DurationFormat/prototype/resolvedOptions/length.js, test/intl402/DurationFormat/prototype/resolvedOptions/name.js, test/intl402/DurationFormat/prototype/resolvedOptions/prop-desc.js, test/intl402/DurationFormat/prototype/resolvedOptions/throw-invoked-as-func.js, test/intl402/DurationFormat/prototype/toStringTag/toString.js, test/intl402/DurationFormat/prototype/toStringTag/toStringTag.js
Add initial tests to Intl.DurationFormat proposal #3305 
Proposal: https://github.com/tc39/proposal-intl-duration-format
=> Test DurationFormat

test/built-ins/ShadowRealm/WrappedFunction/length-throws-typeerror.js, test/built-ins/ShadowRealm/WrappedFunction/length.js, test/built-ins/ShadowRealm/WrappedFunction/name-throws-typeerror.js, test/built-ins/ShadowRealm/WrappedFunction/name.js
Add test coverages on [CopyNameAndLength](https://tc39.es/proposal-shadowrealm/#sec-copynameandlength) in [WrappedFunctionCreate](https://tc39.es/proposal-shadowrealm/#sec-wrappedfunctioncreate).
=> Test WrappedFunction properties

test/built-ins/ShadowRealm/WrappedFunction/length-throws-typeerror.js, test/built-ins/ShadowRealm/WrappedFunction/name-throws-typeerror.js, test/built-ins/ShadowRealm/WrappedFunction/name.js
Also adds more non-string cases for copying names.
=> Fix WrappedFunction throwing tests

test/built-ins/ShadowRealm/WrappedFunction/throws-typeerror-on-revoked-proxy.js, test/built-ins/ShadowRealm/prototype/evaluate/throws-typeerror-wrap-throwing.js
As per https://github.com/tc39/proposal-shadowrealm/pull/349 updates.
=> Add test for throwing WrappedFunction

test/built-ins/Temporal/Duration/compare/twenty-five-hour-day.js
References:
+ https://github.com/tc39/proposal-temporal/issues/1791
=> Add test for DST balancing

implementation-contributed/v8/mjsunit/harmony/to-number.js, test/built-ins/Number/S15.7.1.1_A1.js, test/language/expressions/unary-plus/S11.4.6_A3_T3.js
Fixes #3442
This modifies existing test files, but we could also consider adding one (or more?) new files.
=> Test that "INFINITY" is not recognized as numeric

.circleci/config.yml
=> CI: disable graaljs test run

test/built-ins/Temporal/PlainYearMonth/limits.js, test/built-ins/Temporal/PlainYearMonth/prototype/add/calendar-datefromfields-called.js, test/built-ins/Temporal/PlainYearMonth/prototype/subtract/calendar-datefromfields-called.js
I missed adding these in 27f0104bc65693959d85c0bdb41a4937e796abba
=> Add reference ISO days to PlainYearMonth assertions

test/built-ins/Temporal/Duration/compare/argument-string-negative-fractional-units.js, test/built-ins/Temporal/Duration/from/argument-string-negative-fractional-units.js, test/built-ins/Temporal/Duration/prototype/add/argument-string-negative-fractional-units.js, test/built-ins/Temporal/Duration/prototype/subtract/argument-string-negative-fractional-units.js, test/built-ins/Temporal/Instant/prototype/add/argument-string-negative-fractional-units.js, test/built-ins/Temporal/Instant/prototype/subtract/argument-string-negative-fractional-units.js, test/built-ins/Temporal/PlainDateTime/prototype/add/argument-string-negative-fractional-units.js, test/built-ins/Temporal/PlainDateTime/prototype/subtract/argument-string-negative-fractional-units.js, test/built-ins/Temporal/PlainTime/prototype/add/argument-string-negative-fractional-units.js, test/built-ins/Temporal/PlainTime/prototype/subtract/argument-string-negative-fractional-units.js, test/built-ins/Temporal/ZonedDateTime/prototype/add/argument-string-negative-fractional-units.js, test/built-ins/Temporal/ZonedDateTime/prototype/subtract/argument-string-negative-fractional-units.js
=> Expect precise result for negative fractional units

.circleci/config.yml
i published a version of esvu with a fix for graal. I wish y'all had pinged me sooner :smile: 
Fixes #3401.
=> reenable graaljs

test/intl402/DurationFormat/prototype/format/invalid-negative-duration-throws.js, test/intl402/DurationFormat/prototype/formatToParts/invalid-negative-duration-throws.js
Test invalid negative duration objects - https://github.com/tc39/proposal-intl-duration-format/issues/99#issuecomment-1171114963
=> test invalid negative durations objects

test/intl402/DurationFormat/prototype/format/invalid-arguments-throws.js, test/intl402/DurationFormat/prototype/formatToParts/invalid-arguments-throws.js
meta: add a missing feature flag .  cc @iamstolis
=> DurationFormat -> add missing feature flag  

test/built-ins/Array/prototype/group/array-like.js, test/built-ins/Array/prototype/group/callback-arg.js, test/built-ins/Array/prototype/group/emptyList.js, test/built-ins/Array/prototype/group/evenOdd.js, test/built-ins/Array/prototype/group/groupLength.js, test/built-ins/Array/prototype/group/null-prototype.js, test/built-ins/Array/prototype/group/sparse-array.js, test/built-ins/Array/prototype/group/toPropertyKey.js, test/built-ins/Array/prototype/groupToMap/array-like.js, test/built-ins/Array/prototype/groupToMap/callback-arg.js, test/built-ins/Array/prototype/groupToMap/emptyList.js, test/built-ins/Array/prototype/groupToMap/evenOdd.js, test/built-ins/Array/prototype/groupToMap/groupLength.js, test/built-ins/Array/prototype/groupToMap/invalid-property-key.js, test/built-ins/Array/prototype/groupToMap/map-instance.js, test/built-ins/Array/prototype/groupToMap/negativeZero.js, test/built-ins/Array/prototype/groupToMap/sparse-array.js, test/built-ins/Array/prototype/groupToMap/this-arg-strict.js, test/built-ins/Array/prototype/groupToMap/this-arg.js
Rather than add `arrow-function`, i just changed all the arrows to normal functions, since nothing was relying on any arrow-specific differences.
=> Fix features in tests from #3354

test/intl402/NumberFormat/test-option-useGrouping-extended.js, test/intl402/NumberFormat/test-option-useGrouping.js
Applied changes related with https://github.com/tc39/test262/pull/3659
=> Update:RangeError when useGrouping is string 'undefined'

test/intl402/DurationFormat/prototype/format/style-options-en.js
Sync to https://github.com/tc39/proposal-intl-duration-format/pull/119
Use "unit" type for listFormat
=> Sync to intl-duration-format PR 119

test/built-ins/Temporal/Duration/prototype/round/nanoseconds-to-days-precision-exact-mathematical-values-1.js, test/built-ins/Temporal/Duration/prototype/round/nanoseconds-to-days-precision-exact-mathematical-values-2.js, test/built-ins/Temporal/Duration/prototype/total/precision-exact-mathematical-values-1.js, test/built-ins/Temporal/Duration/prototype/total/precision-exact-mathematical-values-2.js, test/built-ins/Temporal/ZonedDateTime/prototype/hoursInDay/precision-exact-mathematical-values.js
Temporal tests written for the SpiderMonkey implementation. Mostly
covers edge cases around mathematical operations and regression tests
for reported spec bugs.
=> Import SpiderMonkey Temporal tests

test/built-ins/TypedArray/prototype/toReversed/this-value-invalid.js, test/built-ins/TypedArray/prototype/toSorted/this-value-invalid.js
Otherwise $DETACHBUFFER() is not defined in those files.
=> Add missing includes to toSorted/toReversed this-value-invalid.js tests

package.json
This should fix the CI failures for GraalJS.
Closes: #3692
=> Upgrade esvu

implementation-contributed/v8/mjsunit/es6/unicode-escapes-in-regexps.js
Ref. https://bugs.chromium.org/p/v8/issues/detail?id=13377
=> Add `/iu` Unicode case folding tests

test/built-ins/WeakMap/iterator-items-are-not-object-close-iterator.js, test/built-ins/WeakSet/prototype/add/returns-this-symbol.js, test/built-ins/WeakSet/prototype/add/returns-this-when-ignoring-duplicate-symbol.js
These are the remaining substantial changes from #2890.
Fixes #2890.
=> Add missed changes for Symbols as WeakMap keys proposal.

features.txt
Next proposal that the Igalia team plans to tackle is Array.fromAsync. This adds the feature flag.
=> Add feature flag for Array.fromAsync

.circleci/config.yml
=> CI: Disable GraalJS.

.circleci/config.yml
Closes https://github.com/tc39/test262/issues/3703
=> re-enable graaljs

test/intl402/DurationFormat/prototype/format/invalid-arguments-throws.js, test/intl402/DurationFormat/prototype/formatToParts/invalid-arguments-throws.js
https://github.com/tc39/proposal-intl-duration-format/pull/130
=> sync with duration-format PR130

harness/temporalHelpers.js, test/built-ins/Temporal/Duration/prototype/add/relativeto-zoneddatetime-nanoseconds-to-days-range-errors.js, test/built-ins/Temporal/Duration/prototype/round/relativeto-zoneddatetime-nanoseconds-to-days-range-errors.js, test/built-ins/Temporal/Duration/prototype/subtract/relativeto-zoneddatetime-nanoseconds-to-days-range-errors.js, test/built-ins/Temporal/Duration/prototype/total/relativeto-zoneddatetime-nanoseconds-to-days-range-errors.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/nanoseconds-to-days-range-errors.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/nanoseconds-to-days-range-errors.js
Corresponds to https://github.com/tc39/proposal-temporal/pull/2387 and follow-up https://github.com/tc39/proposal-temporal/pull/2444. Many thanks again to @anba for the inspiration and help.
=> Temporal operation NanosecondsToDays: Test RangeErrors reachable in Duration and ZonedDateTime

test/built-ins/Temporal/PlainDate/argument-convert.js, test/built-ins/Temporal/PlainDate/prototype/year/validate-calendar-value.js, test/built-ins/Temporal/PlainDate/prototype/yearOfWeek/validate-calendar-value.js, test/built-ins/Temporal/PlainDateTime/prototype/year/validate-calendar-value.js, test/built-ins/Temporal/PlainDateTime/prototype/yearOfWeek/validate-calendar-value.js, test/built-ins/Temporal/PlainYearMonth/prototype/year/validate-calendar-value.js, test/built-ins/Temporal/ZonedDateTime/prototype/year/validate-calendar-value.js, test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/validate-calendar-value.js
Updates Temporal tests as per the normative change in PR: https://github.com/tc39/proposal-temporal/pull/2438
=> Temporal: Update Temporal test262 as per the normative changes

test/built-ins/ArrayBuffer/prototype/detached/detached-buffer-resizable.js, test/built-ins/ArrayBuffer/prototype/detached/detached-buffer.js, test/built-ins/ArrayBuffer/prototype/detached/invoked-as-accessor.js, test/built-ins/ArrayBuffer/prototype/detached/invoked-as-func.js, test/built-ins/ArrayBuffer/prototype/detached/length.js, test/built-ins/ArrayBuffer/prototype/detached/name.js, test/built-ins/ArrayBuffer/prototype/detached/prop-desc.js, test/built-ins/ArrayBuffer/prototype/detached/this-has-no-arraybufferdata-internal.js, test/built-ins/ArrayBuffer/prototype/detached/this-is-not-object.js, test/built-ins/ArrayBuffer/prototype/detached/this-is-sharedarraybuffer-resizable.js, test/built-ins/ArrayBuffer/prototype/detached/this-is-sharedarraybuffer.js
See https://tc39.es/proposal-arraybuffer-transfer/
=> ArrayBuffer.prototype.detached tests

test/intl402/DurationFormat/prototype/formatToParts/formatToParts-styles-en.js, test/intl402/DurationFormat/prototype/formatToParts/invalid-arguments-throws.js
Test formatToParts output https://github.com/tc39/proposal-intl-duration-format/pull/126
=> Coverage DurationFormat formatToParts

features.txt, tools/lint/lib/checks/features.py, tools/lint/test/fixtures/features.txt, tools/lint/test/run.py
- Move flags to bottom section that are for proposals already in a published standard
- Remove unused flags
- More guidance for people adding new flags
=> Feature flags cleanup

test/intl402/Temporal/Calendar/prototype/mergeFields/gregorian-mutually-exclusive-fields.js, test/intl402/Temporal/Calendar/prototype/mergeFields/japanese-mutually-exclusive-fields.js
Normative PR: https://github.com/tc39/proposal-temporal/pull/2505
=> Temporal: Test updates for mergeFields output property order

test/staging/JSON/json-parse-with-source-snapshot.js, test/staging/JSON/json-parse-with-source.js
These are copied over from `mjsunit/harmony/`.
=> Add V8 tests for JSON.parse with source to staging/

test/built-ins/ArrayBuffer/prototype/transfer/new-length-excessive.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/descriptor.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/extensible.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/from-fixed-to-larger.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/from-fixed-to-same.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/from-fixed-to-smaller.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/from-fixed-to-zero.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/from-resizable-to-larger.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/from-resizable-to-same.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/from-resizable-to-smaller.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/from-resizable-to-zero.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/length.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/name.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/new-length-excessive.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/new-length-non-number.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/nonconstructor.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/this-is-detached.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/this-is-not-arraybuffer-object.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/this-is-not-object.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/this-is-sharedarraybuffer.js
These are copied from ArrayBuffer/prototype/transfer/ with expectations adjusted.
See https://tc39.es/proposal-arraybuffer-transfer/
=> Add tests for ArrayBuffer.prototype.transferToFixedLength

test/built-ins/TypedArray/prototype/filter/BigInt/speciesctor-destination-resizable.js, test/built-ins/TypedArray/prototype/filter/BigInt/speciesctor-get-species-custom-ctor-length-throws-resizable-arraybuffer.js, test/built-ins/TypedArray/prototype/filter/speciesctor-destination-resizable.js, test/built-ins/TypedArray/prototype/filter/speciesctor-get-species-custom-ctor-length-throws-resizable-arraybuffer.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-destination-resizable.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-species-custom-ctor-length-throws-resizable-arraybuffer.js, test/built-ins/TypedArray/prototype/map/speciesctor-destination-resizable.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-species-custom-ctor-length-throws-resizable-arraybuffer.js, test/built-ins/TypedArray/prototype/slice/BigInt/speciesctor-destination-resizable.js, test/built-ins/TypedArray/prototype/slice/BigInt/speciesctor-get-species-custom-ctor-length-throws-resizable-arraybuffer.js, test/built-ins/TypedArray/prototype/slice/speciesctor-destination-resizable.js, test/built-ins/TypedArray/prototype/slice/speciesctor-get-species-custom-ctor-length-throws-resizable-arraybuffer.js
Adds some more tests for resizable ArrayBuffer.
Fixes: https://github.com/tc39/test262/issues/3723
=> Add resizable ArrayBuffer tests in %%TypedArray%%

CONTRIBUTING.md
Hello! First time contributor, hoping to make additional contributions in the near future. I was going through the CONTRIBUTING doc and found this extra backtick that shouldn't be there. 
Thanks!
=> Remove backtick from CONTRIBUTING.md

test/built-ins/Temporal/Duration/prototype/round/zero-day-length-1.js, test/built-ins/Temporal/Duration/prototype/round/zero-day-length-2.js, test/built-ins/Temporal/Duration/prototype/total/zero-day-length-1.js, test/built-ins/Temporal/Duration/prototype/total/zero-day-length-2.js
Based on test cases provided by @anba in https://github.com/tc39/proposal-temporal/issues/2333. (Thanks!)
=> Temporal: Tests for malicious time zones with zero-length days

test/built-ins/Map/groupBy/iterator-next-throws.js, test/built-ins/Object/groupBy/iterator-next-throws.js
=> groupBy: fix throwing iterator tests

test/intl402/DisplayNames/prototype/of/type-region-invalid.js
Added missing test for invalid "region" type in Intl.DisplayNames.of()
=> Invalid region tag, Intl.DisplayNames.prototype.of()

test/intl402/Locale/constructor-options-firstDayOfWeek-invalid.js, test/intl402/Locale/constructor-options-firstDayOfWeek-valid.js, test/intl402/Locale/prototype/firstDayOfWeek/branding.js, test/intl402/Locale/prototype/firstDayOfWeek/name.js, test/intl402/Locale/prototype/firstDayOfWeek/prop-desc.js, test/intl402/Locale/prototype/firstDayOfWeek/valid-id.js, test/intl402/Locale/prototype/firstDayOfWeek/valid-options.js, test/intl402/Locale/prototype/getWeekInfo/firstDay-by-id.js, test/intl402/Locale/prototype/getWeekInfo/firstDay-by-option.js
Test for enhancement in
https://github.com/tc39/proposal-intl-locale-info/pull/70
=> Add test for firstDayOfWeek in LocaleInfo PR 70

tools/packaging/parseTestRecord.py
The "imp" module is deprecated in Python 3.4 and will be removed in Python 3.12. Use it only if the current Python version is too old to use the "importlib" module.
=> Replace "imp" module with "importlib" in parseTestRecord

test/built-ins/Iterator/prototype/Symbol.toStringTag/prop-desc.js, test/built-ins/Iterator/prototype/Symbol.toStringTag/weird-setter.js, test/built-ins/Iterator/prototype/constructor/prop-desc.js, test/built-ins/Iterator/prototype/constructor/weird-setter.js
=> fix broken Iterator.prototype constructor/Symbol.toStringTag tests

test/built-ins/DataView/byteOffset-validated-against-initial-buffer-length.js, test/built-ins/TypedArray/from/from-array-mapper-detaches-result.js, test/built-ins/TypedArray/from/from-array-mapper-makes-result-out-of-bounds.js, test/built-ins/TypedArray/from/from-typedarray-into-itself-mapper-detaches-result.js, test/built-ins/TypedArray/from/from-typedarray-into-itself-mapper-makes-result-out-of-bounds.js, test/built-ins/TypedArray/from/from-typedarray-mapper-detaches-result.js, test/built-ins/TypedArray/from/from-typedarray-mapper-makes-result-out-of-bounds.js, test/built-ins/TypedArray/from/iterated-array-changed-by-tonumber.js, test/built-ins/TypedArray/of/resized-with-out-of-bounds-and-in-bounds-indices.js, test/built-ins/TypedArray/prototype/fill/absent-indices-computed-from-initial-length.js, test/built-ins/TypedArray/prototype/includes/index-compared-against-initial-length-out-of-bounds.js, test/built-ins/TypedArray/prototype/includes/index-compared-against-initial-length.js, test/built-ins/TypedArray/prototype/join/separator-tostring-once-after-resized.js, test/built-ins/TypedArray/prototype/subarray/result-byteOffset-from-out-of-bounds.js, test/built-ins/TypedArray/prototype/values/make-in-bounds-after-exhausted.js, test/built-ins/TypedArray/prototype/values/make-out-of-bounds-after-exhausted.js, test/built-ins/TypedArray/prototype/with/index-validated-against-current-length.js, test/built-ins/TypedArrayConstructors/ctors/object-arg/iterated-array-changed-by-tonumber.js, test/built-ins/TypedArrayConstructors/ctors/object-arg/iterated-array-with-modified-array-iterator.js, test/built-ins/TypedArrayConstructors/internals/Set/resized-out-of-bounds-to-in-bounds-index.js
Covers spec compliance issues in at least one of JSC, V8, or SM.
=> Add tests for resizable array buffer views

rfcs/async-helpers.md
**PR Summary**:
PR #3872 moved the location of the JS file. This PR adjusts sources to changes.
=> Update the location of `2nd-param-non-object.js`

test/language/expressions/assignment/destructuring/iterator-destructuring-property-reference-target-evaluation-order.js, test/language/expressions/assignment/destructuring/keyed-destructuring-property-reference-target-evaluation-order.js, test/language/expressions/member-expression/computed-reference-null-or-undefined.js
Ensure that the following cases are covered:
- https://github.com/tc39/ecma262/issues/3295#issuecomment-2058110314
- https://github.com/tc39/ecma262/issues/2659#issue-1131245695
=> Add additional tests for tc39/ecma262#3307.

harness/asyncHelpers.js, test/built-ins/Promise/try/throws.js
=> `Promise.try`: avoid unneeded syntax

test/built-ins/Temporal/PlainDateTime/prototype/since/wrapping-at-end-of-month.js, test/built-ins/Temporal/PlainDateTime/prototype/until/wrapping-at-end-of-month.js
Tests for https://github.com/tc39/proposal-temporal/issues/2820
=> Temporal: Tests for bug with PlainDateTime since/until near month boundaries

test/built-ins/Array/prototype/findLast/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/findLast/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/findLast/resizable-buffer.js, test/built-ins/TypedArray/prototype/findLast/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/findLast/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/findLast/resizable-buffer.js
=>  RAB: Integrate staging tests for the .findLast method

test/built-ins/AbstractModuleSource/prototype.js, test/built-ins/AbstractModuleSource/prototype/Symbol.toStringTag.js
`verifyProperty` needs to be restored.
=> Fix AbstractModuleSource verifyProperty calls

test/built-ins/Array/prototype/some/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/some/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/some/resizable-buffer.js, test/built-ins/TypedArray/prototype/some/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/some/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/some/resizable-buffer.js
=>  RAB: Integrate staging tests for the .some method

INTERPRETING.md
Refs: https://github.com/tc39/test262/pull/3980#discussion_r1715282780
=> Update INTERPRETING.md fixing `$262.AbstractModuleSource` position

test/built-ins/TypedArrayConstructors/internals/Set/BigInt/key-is-canonical-invalid-index-prototype-chain-set.js, test/built-ins/TypedArrayConstructors/internals/Set/BigInt/key-is-canonical-invalid-index-reflect-set.js, test/built-ins/TypedArrayConstructors/internals/Set/BigInt/key-is-valid-index-prototype-chain-set.js, test/built-ins/TypedArrayConstructors/internals/Set/BigInt/key-is-valid-index-reflect-set.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-canonical-invalid-index-prototype-chain-set.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-canonical-invalid-index-reflect-set.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-valid-index-prototype-chain-set.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-valid-index-reflect-set.js
Reverts tc39/test262#2975
In #2957, @rwaldron requested a new PR to be made with these tests; that never seems to have happened.
=> Revert "Revert "Test TypedArray's [[Set]] internal method with altered receiver""

.github/workflows/esmeta-test262.yml
To pick up https://github.com/es-meta/esmeta/pull/254
=> update es-meta version to v0.4.2

test/built-ins/NativeErrors/AggregateError/errors-iterabletolist.js, test/language/computed-property-names/object/accessor/getter.js, test/language/computed-property-names/object/accessor/setter.js
- test computed accessor properties with number and Symbol keys
- test AggregateError constructor w/o mandatory 1st (iterable) errors param
Closes #4219
=> add tests for issues discussed in #4219

test/language/statements/with/get-binding-value-call-with-proxy-env.js, test/language/statements/with/get-binding-value-idref-with-proxy-env.js, test/language/statements/with/has-binding-call-with-proxy-env.js, test/language/statements/with/has-binding-idref-with-proxy-env.js, test/language/statements/with/set-mutable-binding-idref-compound-assign-with-proxy-env.js, test/language/statements/with/set-mutable-binding-idref-with-proxy-env.js
Adds coverage for <https://bugzilla.mozilla.org/show_bug.cgi?id=1166408>.
=> Add test coverage for correct binding object MOP executions in with-environment

harness/propertyHelper.js
Ref https://github.com/tc39/test262/pull/4234#discussion_r1771684267
=> harness/propertyHelper.js: Capture primordials that might be affected at runtime by verification

harness/compareArray.js, test/harness/compare-array-arguments.js, test/harness/compare-array-arraylike.js, test/harness/compare-array-falsy-arguments.js
It looks like #4240 was not tested, cc @lahma
=> Fix compareArray.js harness tests

test/built-ins/Array/prototype/toString/non-callable-join-string-tag.js, test/built-ins/Proxy/revocable/tco-fn-realm.js
=> Avoid using destructuring in tco-fn-realm.js

test/annexB/built-ins/Date/prototype/setYear/date-value-read-before-tonumber-when-date-is-invalid.js, test/annexB/built-ins/Date/prototype/setYear/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setDate/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setDate/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setFullYear/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setFullYear/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setHours/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setHours/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setMilliseconds/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setMilliseconds/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setMinutes/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setMinutes/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setMonth/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setMonth/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setSeconds/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setSeconds/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setUTCDate/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setUTCDate/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setUTCFullYear/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setUTCFullYear/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setUTCHours/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setUTCHours/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setUTCMilliseconds/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setUTCMilliseconds/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setUTCMinutes/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setUTCMinutes/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setUTCMonth/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setUTCMonth/date-value-read-before-tonumber-when-date-is-valid.js, test/built-ins/Date/prototype/setUTCSeconds/date-value-read-before-tonumber-when-date-is-invalid.js, test/built-ins/Date/prototype/setUTCSeconds/date-value-read-before-tonumber-when-date-is-valid.js
Related PR: https://github.com/tc39/ecma262/pull/2136
=> Ensure NaN time values are correctly handled in various Date setters

.github/workflows/esmeta-test262.yml
One of the core developers of SBT has kindly created an action to replace the missing SBT in newer Ubuntu images.
https://github.com/marketplace/actions/setup-sbt-installer
Closes: #4267
=> CI: Setup SBT manually

make.py, tools/generation/lib/template.py, tools/generation/lib/test.py
Found these while working on other stuff.
=> A few minor fixes for the test generation tool

features.txt, test/built-ins/Error/isError/bigints.js, test/built-ins/Error/isError/error-subclass.js, test/built-ins/Error/isError/errors-other-realm.js, test/built-ins/Error/isError/errors.js, test/built-ins/Error/isError/fake-errors.js, test/built-ins/Error/isError/is-a-constructor.js, test/built-ins/Error/isError/name.js, test/built-ins/Error/isError/non-error-objects-other-realm.js, test/built-ins/Error/isError/non-error-objects.js, test/built-ins/Error/isError/primitives.js, test/built-ins/Error/isError/prop-desc.js, test/built-ins/Error/isError/symbols.js
See https://github.com/tc39/test262/pull/4266#issuecomment-2419000590
=> add missing Error.isError feature flag

test/built-ins/Temporal/PlainYearMonth/prototype/add/subtract-from-last-representable-month.js, test/built-ins/Temporal/PlainYearMonth/prototype/subtract/subtract-from-last-representable-month.js
See https://github.com/tc39/proposal-temporal/issues/3029
=> Add tests for adding negative durations to/subtracting durations from the last representable year/month of the ISO calendar

test/built-ins/Error/isError/bigints.js, test/built-ins/Error/isError/error-subclass.js, test/built-ins/Error/isError/symbols.js
=> Error.isError: fix test bugs

test/built-ins/Error/isError/errors-other-realm.js, test/built-ins/Error/isError/errors.js
=> `Error.isError`: fix remaining issues from #4304

test/language/import/import-defer/deferred-namespace-object/to-string-tag.js
Test for https://github.com/tc39/proposal-defer-import-eval/pull/58.
Spec: https://tc39.es/proposal-defer-import-eval/#sec-modulenamespacecreate
=> Add test for @@toStringTag on deferred module namespaces

test/language/import/import-defer/errors/module-throws/trigger-evaluation.js, test/language/import/import-defer/syntax/valid-default-binding-named-defer.js
Fixes two minor issues in import-defer tests that can cause test failures.
=> Fix two minor errors for import-defer tests

test/intl402/DurationFormat/prototype/format/taint-temporal-duration-prototype.js, test/intl402/DurationFormat/prototype/format/temporal-duration-object-arg.js, test/intl402/DurationFormat/prototype/format/temporal-duration-string-arg.js, test/intl402/DurationFormat/prototype/formatToParts/taint-temporal-duration-prototype.js, test/intl402/DurationFormat/prototype/formatToParts/temporal-duration-object-arg.js, test/intl402/DurationFormat/prototype/formatToParts/temporal-duration-string-arg.js, test/intl402/Temporal/Duration/prototype/toLocaleString/returns-same-results-as-DurationFormat.js, test/intl402/Temporal/Duration/prototype/toLocaleString/taint-duration-prototype.js
Basic tests for <https://github.com/tc39/proposal-temporal/issues/3089> to get some initial coverage.
=> Add basic tests for Intl.DurationFormat accepting Temporal.Duration

README.md
Title says it all. Similar to #4438, there's a bunch of extra whitespace in this file that my editor automatically cleaned up but I wanted to keep this commit a one-liner. Let me know if you'd like me to clean up all the docs in the repo, it wouldn't take me much effort.
=> Update link to test262-harness repo

test/built-ins/Temporal/PlainMonthDay/from/constrain-to-leap-day.js, test/intl402/Temporal/Instant/prototype/toLocaleString/dateStyle-timeStyle-undefined.js, test/intl402/Temporal/Instant/prototype/toLocaleString/options-conflict.js, test/intl402/Temporal/PlainDate/prototype/toLocaleString/dateStyle-timeStyle-undefined.js, test/intl402/Temporal/PlainDate/prototype/toLocaleString/options-conflict.js, test/intl402/Temporal/PlainDateTime/prototype/toLocaleString/dateStyle-timeStyle-undefined.js, test/intl402/Temporal/PlainDateTime/prototype/toLocaleString/options-conflict.js, test/intl402/Temporal/PlainMonthDay/from/constrain-to-leap-day.js, test/intl402/Temporal/PlainMonthDay/prototype/toLocaleString/dateStyle-timeStyle-undefined.js, test/intl402/Temporal/PlainMonthDay/prototype/toLocaleString/dateStyle.js, test/intl402/Temporal/PlainMonthDay/prototype/toLocaleString/options-conflict.js, test/intl402/Temporal/PlainTime/prototype/toLocaleString/options-conflict.js, test/intl402/Temporal/PlainTime/prototype/toLocaleString/timeStyle-undefined.js, test/intl402/Temporal/PlainYearMonth/prototype/toLocaleString/dateStyle-undefined.js, test/intl402/Temporal/PlainYearMonth/prototype/toLocaleString/dateStyle.js, test/intl402/Temporal/PlainYearMonth/prototype/toLocaleString/options-conflict.js, test/intl402/Temporal/ZonedDateTime/prototype/toLocaleString/dateStyle-timeStyle-undefined.js, test/intl402/Temporal/ZonedDateTime/prototype/toLocaleString/options-conflict.js
- Better coverage of dateStyle and timeStyle
- Coverage of a weird PlainMonthDay calendar edge case
=> Some more Temporal coverage

test/intl402/PluralRules/constructor-option-read-order.js, test/intl402/PluralRules/constructor-options-throwing-getters.js, test/intl402/PluralRules/default-options-object-prototype.js, test/intl402/PluralRules/prototype/constructor/notation.js, test/intl402/PluralRules/prototype/resolvedOptions/order.js, test/intl402/PluralRules/prototype/resolvedOptions/properties.js, test/intl402/PluralRules/prototype/resolvedOptions/return-keys-order-default.js, test/intl402/PluralRules/prototype/select/notation.js
Refs: https://github.com/tc39/ecma402/pull/989
=> Add 'notation' option to PluralRules tests and update related assertions

test/harness/verifyProperty-value-error.js
Found in https://github.com/babel/babel/pull/17315. Regression from #4468.
=> Fix error message check in `verifyProperty-value-error.js`

test/built-ins/TypedArray/prototype/copyWithin/coerced-target-start-end-shrink.js
Ref https://github.com/tc39/ecma262/pull/3619
Ref https://github.com/tc39/ecma262/issues/3618
=> [TypedArray.prototype.copyWithin] Cover overlapping source/destination ranges

.github/workflows/checks.yml, .github/workflows/esmeta-test262.yml
As seen at https://github.com/tc39/test262/actions/runs/16462995254/job/46533977407?pr=4545 for the 1577 changed files of #4545
=> Try to avoid "Argument list too long" when many files are changed

test/built-ins/Array/prototype/toSorted/comparefn-controls-sort.js, test/built-ins/Array/prototype/toSorted/comparefn-default.js, test/built-ins/TypedArray/prototype/toReversed/reverses.js, test/built-ins/TypedArray/prototype/toSorted/comparefn-controls-sort.js, test/built-ins/TypedArray/prototype/toSorted/comparefn-default.js
Addresses testing gaps identified in https://github.com/tc39/test262/issues/4575
I have signed the [Test262 CLA](http://tc39.github.io/test262-cla)
=> Add additional tests for copy by array features
