tc39/test262

harness/assert.js
Ran into this today, probably just an omission when the assert function's variable was renamed.
=> fix undefined var

test/built-ins/Promise/resolve/S25.Promise_resolve_foreign_thenable_1.js, test/built-ins/Promise/resolve/S25.Promise_resolve_foreign_thenable_2.js
This includes two new 'foreign thenables' tests, plus a fix to the previous 'foreign thenables' test, which never called the `onResolve` or `onReject` functions, thus making it an unintentional test of Promise timeouts.  (oops!)
=> 2 new tests re: foreign thenables

harness/propertyHelper.js
First check if descriptor is set up correctly, then actually
verify that the attribute (writability, enumerability,
configurability) is as expected.
=> harness: add checks of descriptor attributes

test/annexB/B.2.3.10.js, test/annexB/B.2.3.11.js, test/annexB/B.2.3.12.js, test/annexB/B.2.3.13.js, test/annexB/B.2.3.14.js, test/annexB/B.2.3.2.js, test/annexB/B.2.3.3.js, test/annexB/B.2.3.4.js, test/annexB/B.2.3.5.js, test/annexB/B.2.3.6.js, test/annexB/B.2.3.7.js, test/annexB/B.2.3.8.js, test/annexB/B.2.3.9.js
This is the first of a series of test imports from the Google V8 project. The commit message body for this patch contains information relating to the provenance of the tests.
Some modifications were made to retrofit those tests to the Test262 harness. Since each change has the potential to introduce a new bug, I have opted to include the V8 "MJSUnit" assertion suite as a helper utility in Test262. It may seem like overkill for the small set of tests here, but it may be re-used by future contributions from V8.
=> First v8 tests

test/built-ins/Symbol/species/Symbol.species.builtin-getter-name.js, test/built-ins/Symbol/species/Symbol.species.exists.js, test/built-ins/Symbol/species/Symbol.species.in_Array.js, test/built-ins/Symbol/species/Symbol.species.in_ArrayBuffer.js, test/built-ins/Symbol/species/Symbol.species.in_Map.js, test/built-ins/Symbol/species/Symbol.species.in_Promise.js, test/built-ins/Symbol/species/Symbol.species.in_RegExp.js, test/built-ins/Symbol/species/Symbol.species.in_Set.js, test/built-ins/Symbol/species/Symbol.species.notChangedByExtends.js
Initial tests for property existence
move getter name test to builtin-getter-name
initial cut at extends test
=> Symbol.species tests

test/built-ins/Array/prototype/concat/Array.prototype.concat_arity.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like-length-to-string-throws.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like-length-value-of-throws.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like-negative-length.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like-primitive-non-number-length.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like-string-length.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like-to-length-throws.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_descriptor.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_holey-sloppy-arguments.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_large-typed-array.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_length-throws.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_no-prototype.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_non-array.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_sloppy-arguments-throws.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_sloppy-arguments-with-dupes.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_sloppy-arguments.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_small-typed-array.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-boolean-wrapper.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-function.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-getter-throws.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-number-wrapper.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-reg-exp.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-sparse-object.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_spreadable-string-wrapper.js, test/built-ins/Array/prototype/concat/Array.prototype.concat_strict-arguments.js, test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T2.js, test/built-ins/Array/prototype/concat/S15.4.4.4_A3_T3.js
These tests are derived from the following files within the Google V8
project:
test/mjsunit/harmony/array-concat.js
Blocked by https://github.com/tc39/test262/pull/153
=> Import tests from Google V8 (Array isConcatSpreadable)

test/language/for-of/break-from-catch.js, test/language/for-of/break-from-try.js, test/language/for-of/break-label.js, test/language/for-of/break.js, test/language/for-of/continue-from-catch.js, test/language/for-of/continue-from-try.js, test/language/for-of/continue-label.js, test/language/for-of/continue.js, test/language/for-of/generator.js, test/language/for-of/generic-iterable.js, test/language/for-of/head-expr-obj-iterator-method.js, test/language/for-of/head-expr-primitive-iterator-method.js, test/language/for-of/head-expr-to-obj.js, test/language/for-of/iterator-as-proxy.js, test/language/for-of/iterator-next-reference.js, test/language/for-of/iterator-next-result-done-attr.js, test/language/for-of/iterator-next-result-type.js, test/language/for-of/iterator-next-result-value-attr.js, test/language/for-of/nested.js, test/language/for-of/return.js
These tests are derived from the following files within the Google V8
project:
test/mjsunit/es6/iteration-semantics.js
=> Import tests from Google V8 (iteration semantics)

test/language/object-literal/concise-generator.js, test/language/object-literal/descriptor.js, test/language/object-literal/getter.js, test/language/object-literal/identifier-reference-property-get-access.js, test/language/object-literal/let-non-strict-access.js, test/language/object-literal/let-non-strict-syntax.js, test/language/object-literal/method.js, test/language/object-literal/not-defined.js, test/language/object-literal/properties-names-eval-arguments.js, test/language/object-literal/setter.js, test/language/object-literal/yield-non-strict-access.js, test/language/object-literal/yield-non-strict-syntax.js
These tests are derived from the following files within the Google V8 project:
test/mjsunit/harmony/method-name-eval-arguments.js
test/mjsunit/harmony/object-literals-method.js
test/mjsunit/harmony/object-literals-property-shorthand.js
test/mjsunit/harmony/object-literals-super.js
=> Import tests from Google V8 (Object Literal Concise Method and Property Initialization)

harness/testBuiltInObject.js
In ES6 the function length property was changed to become
configurable.
=> Function length property is configurable

test/built-ins/Math/round/S15.8.2.15_A7.js
Seems, `Math.round(x)` is implemented as `Math.floor(x + 0.5)` in some JavaScript engines.
The "Note 2 for Math.round"  was fixed for ES6 (see http://es5.github.io/#x15.8.2.15 and https://people.mozilla.org/~jorendorff/es6-draft.html#sec-math.round )
=> More tests for Math.round

harness/assert.js
When invoked without a custom assertion message, `assert.sameValue` and
`assert.notSameValue` automatically create a message that describes the
actual and expected values.
Extend both assertion methods to also include this information in cases
where a custom message has been specified.
=> Extend assertion error messages

harness/propertyHelper.js
Only attempt to re-set the property value in cases where it was
successfully modified as part of the function's execution. This avoids
errors when the underlying value is not writable. Rename the internal
result-tracking variable to make this more clear.
=> Fix bug in `isWritable` utility function

harness/testBuiltInObject.js
The `testBuiltInObject` function verifies the presence of the specified
properties for *all* object types (not just function objects). Update
the error messages to reflect this.
=> Correct error messages

test/annexB/labelled-function-declaration.js, test/built-ins/Object/getOwnPropertyNames/15.2.3.4-4-2.js, test/built-ins/Object/getOwnPropertyNames/15.2.3.4-4-44.js, test/built-ins/Object/getOwnPropertyNames/15.2.3.4-4-49.js, test/built-ins/Object/getOwnPropertyNames/15.2.3.4-4-b-2.js, test/built-ins/Object/is/length.js, test/language/block-scope/syntax/for-in/acquire-properties-from-array.js, test/language/block-scope/syntax/for-in/acquire-properties-from-object.js, test/language/class/method-definition/yield-as-function-expression-binding-identifier.js, test/language/class/method-definition/yield-as-generator-method-binding-identifier.js, test/language/class/method-definition/yield-as-identifier-in-nested-function.js, test/language/computed-property-names/basics/symbol.js, test/language/computed-property-names/class/method/symbol.js, test/language/computed-property-names/class/static/method-number.js, test/language/computed-property-names/class/static/method-string.js, test/language/computed-property-names/class/static/method-symbol.js, test/language/computed-property-names/object/method/symbol.js, test/language/expressions/object/method-definition/yield-as-function-expression-binding-identifier.js, test/language/statements/labeled/labelled-function-declaration-strict.js, test/language/statements/let/syntax/identifier-let-allowed-as-lefthandside-expression-strict.js
- in-statement-position-label-statement.js is an Annex-B test (B.3.2 Labelled Function Declarations), moved to annexB directory
- identifier-let-allowed-as-lefthandside-expression-strict.js needs to check for a SyntaxError (ES6, 12.1.1)
- method-*.js: compareArray() no longer sorts its input, added Array.prototype.sort() calls
=> Invalid language tests

test/built-ins/Array/isArray/15.4.3.2-0-5.js, test/built-ins/Array/prototype/S15.4.3.1_A5.js, test/built-ins/Array/prototype/S15.4.4_A1.1_T2.js, test/built-ins/Array/prototype/S15.4.4_A1.2_T1.js, test/built-ins/Array/prototype/S15.4.4_A1.3_T1.js, test/built-ins/Array/prototype/push/S15.4.4.7_A2_T2.js, test/built-ins/Function/prototype/bind/15.3.4.5-15-2.js, test/built-ins/RegExp/15.10.4.1-1.js, test/built-ins/RegExp/S15.10.3.1_A2_T1.js, test/built-ins/RegExp/S15.10.3.1_A2_T2.js, test/built-ins/RegExp/S15.10.4.1_A2_T1.js, test/built-ins/RegExp/S15.10.4.1_A2_T2.js, test/built-ins/RegExp/prototype/exec/S15.10.6.2_A5_T3.js, test/language/expressions/object/11.1.5-2gs.js, test/language/expressions/object/11.1.5-4-4-a-1-s.js, test/language/expressions/object/11.1.5_4-4-b-1.js, test/language/expressions/object/11.1.5_4-4-b-2.js, test/language/expressions/object/11.1.5_4-4-c-1.js, test/language/expressions/object/11.1.5_4-4-c-2.js, test/language/expressions/object/11.1.5_4-4-d-1.js, test/language/expressions/object/11.1.5_4-4-d-2.js, test/language/expressions/object/11.1.5_4-4-d-3.js, test/language/expressions/object/11.1.5_4-4-d-4.js
- Duplicate properties are allowed in object literals: test/language/expressions/object/*.js
- RegExpBuiltinExec was changed to use ToLength(lastIndex): test/built-ins/RegExp/prototype/exec/S15.10.6.2_A5_T3.js
- Non-undefined flags arguments allowed in RegExp constructor call: test/built-ins/RegExp/*.js
- Array.prototype.push throws TypeError if new length exceeds Number.MAX_SAFE_INTEGER: test/built-ins/Array/prototype/push/S15.4.4.7_A2_T2.js
- .length property of bound functions is configurable: test/built-ins/Function/prototype/bind/15.3.4.5-15-2.js
- Array.prototype changed back to exotic Array object: test/built-ins/Array/prototype/*.js, test/built-ins/Array/isArray/15.4.3.2-0-5.js
=> Update remaining tests for ES2015 compatibility (rev38)

test/built-ins/Boolean/S15.6.1.1_A1_T5.js, test/built-ins/Boolean/prototype/S15.6.3.1_A2.js, test/built-ins/Boolean/prototype/S15.6.3.1_A3.js
Add missing "var" declarations and noStrict flags.
=> Fix strict mode errors in built-ins/Boolean

test/built-ins/Number/MAX_VALUE/S15.7.3.2_A2.js, test/built-ins/Number/MIN_VALUE/S15.7.3.3_A2.js, test/built-ins/Number/NEGATIVE_INFINITY/S15.7.3.5_A2.js, test/built-ins/Number/NaN/S15.7.3.4_A2.js, test/built-ins/Number/POSITIVE_INFINITY/S15.7.3.6_A2.js, test/built-ins/Number/prototype/S15.7.3.1_A1_T1.js, test/built-ins/Number/prototype/S15.7.3.1_A1_T3.js
Add missing "var" declarations and noStrict flags.
=> Fix strict mode errors in built-ins/Number

test/built-ins/Object/isExtensible/15.2.3.13-2-1.js, test/built-ins/Object/prototype/S15.2.3.1_A1.js, test/built-ins/Object/prototype/S15.2.3.1_A2.js, test/built-ins/Object/prototype/S15.2.4_A4.js, test/built-ins/Object/prototype/hasOwnProperty/S15.2.4.5_A10.js, test/built-ins/Object/prototype/hasOwnProperty/S15.2.4.5_A7.js, test/built-ins/Object/prototype/hasOwnProperty/S15.2.4.5_A8.js, test/built-ins/Object/prototype/isPrototypeOf/S15.2.4.6_A7.js, test/built-ins/Object/prototype/isPrototypeOf/S15.2.4.6_A8.js, test/built-ins/Object/prototype/propertyIsEnumerable/S15.2.4.7_A7.js, test/built-ins/Object/prototype/propertyIsEnumerable/S15.2.4.7_A8.js, test/built-ins/Object/prototype/toLocaleString/S15.2.4.3_A10.js, test/built-ins/Object/prototype/toLocaleString/S15.2.4.3_A7.js, test/built-ins/Object/prototype/toLocaleString/S15.2.4.3_A8.js, test/built-ins/Object/prototype/toLocaleString/S15.2.4.3_A9.js, test/built-ins/Object/prototype/toString/S15.2.4.2_A7.js, test/built-ins/Object/prototype/toString/S15.2.4.2_A9.js, test/built-ins/Object/prototype/valueOf/S15.2.4.4_A10.js, test/built-ins/Object/prototype/valueOf/S15.2.4.4_A7.js, test/built-ins/Object/prototype/valueOf/S15.2.4.4_A8.js, test/built-ins/Object/prototype/valueOf/S15.2.4.4_A9.js
- Add missing "var" declarations and noStrict flags
- Remove invalid noStrict flags
- ietestcenter tests need fixed, require updates to use propertyHelper.js
=> Fix some strict mode errors in built-ins/Object

test/built-ins/Object/defineProperty/15.2.3.6-4-591.js
This is a candidate fix to the line note on #259
https://github.com/tc39/test262/pull/259#discussion_r29866745
=> Candidate fix of empty catch{}

test/built-ins/Array/S15.4.3_A2.3.js, test/built-ins/GeneratorPrototype/throw/from-state-completed.js, test/built-ins/GeneratorPrototype/throw/from-state-suspended-start.js
Add missing noStrict flags and variable declarations.
=> Fix remaining strict mode errors in built-ins

test/built-ins/Array/prototype/join/S15.4.4.5_A3.1_T1.js
Test for x.join(NaN) reports an error using the content of x.join("NaN"). This is confusing.
=> S15.4.4.5_A3.1_T1.js: Fix inconsistent error message

test/built-ins/Array/prototype/concat/Array.prototype.concat_array-like-negative-length.js
Since ES5 uses ToUint32, this test will cause those implementations to loop for a very long time. This uses a much more negative number so ES5 impls will still fail but not loop forever.
=> Use a very negative number so ES5 implementations don't loop forever

test/language/expressions/object/prop-def-id-eval-error-2.js, test/language/expressions/object/prop-def-id-eval-error.js, test/language/expressions/object/prop-def-id-get-error.js, test/language/expressions/object/prop-def-id-valid.js
There are three unique error cases for this production:
1. Identifier resolution
2. Value retrieval
3. Property creation
Testing (1) was difficult. Neither [ResolveBinding](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-resolvebinding) nor [GetIdentifierReference](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getidentifierreference) throw an error, but the latter delegates to [HasBinding](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-declarative-environment-records-hasbinding-n). HasBinding never returns an abrupt completion for Declarative Environment Records, so I had to resort to using an Object Environment Record via a `with` statement. In addition to disqualifying strict mode, this approach requires a Symbol to trigger the error. I recognize that …
=> Add tests for IdentifierReference as property

test/built-ins/Array/prototype/concat/S15.4.4.4_A4.1.js
The test checks Array.concat which is undefined; instead it should check Array.prototype.concat.
=> S15.4.4.4_A4.1 length enumerable should be checked on Array.prototype.concat

tools/packaging/templates/runner.test262.html
Test262 now accepts community contributions. Update the copy on the
website to reflect this.
@bterlson I have some ideas for more extensive documentation refactoring, but I thought it would be best to keep this patch small so we can more quickly correct the text on the site in production.
=> Update contribution information

test/language/eval-code/10.4.2-3-c-3-s.js
Test case 10.4.2-3-c-2-s verifies that eval can't instantiate variables in the calling context. However, it does not verify that the variable isn't matched to the global context either. Added test case 10.4.2-3-c-3-s to check for this.
=> Add tests for variable instantiation for eval in strict mode

test/language/generators/Generator_restricted-properties.js
One of the generator tests did not specify a `features` or an `es6id`. Added the `features` attribute.
=> Generator test should specify generators feature.

test/language/statements/for-of/body-dstr-assign-error.js, test/language/statements/for-of/body-dstr-assign.js, test/language/statements/for-of/body-put-error.js, test/language/statements/for-of/generator-close-via-break.js, test/language/statements/for-of/generator-close-via-return.js, test/language/statements/for-of/generator-close-via-throw.js, test/language/statements/for-of/generator-next-error.js, test/language/statements/for-of/generator.js, test/language/statements/for-of/generic-iterable.js, test/language/statements/for-of/iterator-as-proxy.js, test/language/statements/for-of/iterator-close-get-method-error.js, test/language/statements/for-of/iterator-close-non-object.js, test/language/statements/for-of/iterator-close-via-break.js, test/language/statements/for-of/iterator-close-via-return.js, test/language/statements/for-of/iterator-close-via-throw.js, test/language/statements/for-of/iterator-next-error.js, test/language/statements/for-of/iterator-next-reference.js, test/language/statements/for-of/iterator-next-result-done-attr.js, test/language/statements/for-of/iterator-next-result-type.js, test/language/statements/for-of/iterator-next-result-value-attr-error.js, test/language/statements/for-of/iterator-next-result-value-attr.js
Extend coverage of the `for..of` statement to include various error cases and iterator closing semantics
=> for..of additions

CONTRIBUTING.md, test/language/import/dup-bound-names.js, test/language/module-code/dup-export-decl.js, test/language/module-code/dup-export-dflt.js, test/language/module-code/dup-export-id-as.js, test/language/module-code/dup-export-id.js, test/language/module-code/dup-lables.js, test/language/module-code/dup-lex.js, test/language/module-code/export-unresolvable.js, test/language/module-code/import-as-stmt-list-item.js, test/language/module-code/lex-and-var.js, test/language/module-code/new-target.js, test/language/module-code/super.js, test/language/module-code/undef-break.js, test/language/module-code/undef-continue.js
@bterlson When it comes to ES6 modules, I think we're limited in what we can
practically test without a loader. Still, it seems like a good idea to get
*some* coverage into test262 because it will pave the way for more rigorous
tests in the future. For instance: harnesses will have to be made aware of
modules so they can parse the source text accordingly. I'm proposing a new
flag, `module`. I prefer this to a boolean frontmatter tag because the relation
with `onlyStrict` and `noStrict` is more clear.
Of all the tests we might write, tests for early errors seem like the most
likely to be useful to implementors today (minimal though they may be).
I've placed the test for `import`'s early error in `language/import` because it
is not technically a statement. At the same time, neither are …
=> Add tests for early errors in module syntax

test/language/expressions/delete/11.4.1-4.a-5.js
Test 11.4.1-4.a-5 states that it verifies that an environment object cannot be deleted. However, this was giving a false positive. It was actually testing where a "var" declaration on an environment object cannot be deleted (there are other tests for this). This test case fails on Chrome 43, Firefox 38 and Internet Explorer 11.
**Please review**: This test has been modified to actually test what the description states it should be testing. However, I cannot find a reference in [the specs](http://ecma-international.org/ecma-262/5.1/) that this test should actually succeed. And, none of the major browsers implement this. Thus I'm not sure whether this test should be modified or deleted. In either case, as the test is right now, it's of no use since it's not testing what it says it should be …
=> Fixed testing deletion of an environment object.

test/language/module-code/lex-and-var.js
This test exercises an early error, so it should be declared with the
`negative` tag.
Originally identified by @anba here: https://github.com/tc39/test262/pull/300/files#r32065154 . Thanks, André!
=> Insert omitted `negative` tag

tools/packaging/monkeyYaml.py, tools/packaging/test/test_monkeyYaml.py
monkeyYaml didn't split lines correctly leading to \r in resulting
values.
Fixes #295
=> Fix monkey yaml's handling of carriage return

test/built-ins/Number/string-binary-literal-invalid.js, test/built-ins/Number/string-binary-literal.js, test/built-ins/Number/string-octal-literal-invald.js, test/built-ins/Number/string-octal-literal.js, test/language/literals/numeric/binary-invalid-digit.js, test/language/literals/numeric/binary-invalid-leading.js, test/language/literals/numeric/binary-invalid-truncated.js, test/language/literals/numeric/binary-invalid-unicode.js, test/language/literals/numeric/binary.js, test/language/literals/numeric/octal-invalid-digit.js, test/language/literals/numeric/octal-invalid-leading.js, test/language/literals/numeric/octal-invalid-truncated.js, test/language/literals/numeric/octal-invalid-unicode.js, test/language/literals/numeric/octal.js
Add tests for BinaryIntegerLiterals and OctalIntegerLiterals.
=> ES6 numeric literals

test/built-ins/Array/prototype/find/Array.prototype.find_empty-array-undefined.js, test/built-ins/Array/prototype/find/Array.prototype.find_length-property.js, test/built-ins/Array/prototype/find/Array.prototype.find_modify-after-start.js, test/built-ins/Array/prototype/find/Array.prototype.find_non-returning-predicate.js, test/built-ins/Array/prototype/find/Array.prototype.find_noncallable-predicate.js, test/built-ins/Array/prototype/find/Array.prototype.find_predicate-arguments.js, test/built-ins/Array/prototype/find/Array.prototype.find_push-after-start.js, test/built-ins/Array/prototype/find/Array.prototype.find_remove-after-start.js, test/built-ins/Array/prototype/find/Array.prototype.find_return-found-value.js, test/built-ins/Array/prototype/find/Array.prototype.find_this-defined.js, test/built-ins/Array/prototype/find/Array.prototype.find_this-global.js, test/built-ins/Array/prototype/find/Array.prototype.find_this-is-object.js, test/built-ins/Array/prototype/find/Array.prototype.find_this-undefined.js
A number of Array.prototype.find tests were missing a feature specification.
=> The Array.prototype.find function is an ES6 function.

test/built-ins/Array/prototype/fill/S22.1.3.6_T1.js
One of the Array.prototype.fill tests specifies an es5id. Changed to an es6id.
=> The Array.prototype.fill function is an ES6 function.

test/language/module-code/lex-and-var.js
The `Negative` tag accepts a string value (not a list)
Resolves gh-323
=> Fix typo in test meta-data

harness/$PRINT.js, test/built-ins/Object/prototype/hasOwnProperty/S15.2.4.5_A7.js, test/built-ins/Object/prototype/isPrototypeOf/S15.2.4.6_A1.js, test/built-ins/Object/prototype/valueOf/S15.2.4.4_A7.js, test/built-ins/String/prototype/indexOf/S15.5.4.7_A7.js, test/built-ins/String/prototype/search/S15.5.4.12_A7.js, test/built-ins/String/prototype/substring/S15.5.4.15_A7.js, test/built-ins/String/prototype/toLocaleLowerCase/S15.5.4.17_A7.js, test/language/function-code/S10.2.1_A4_T2.js, test/language/function-code/S10.2.1_A5.1_T1.js, test/language/function-code/S10.2.1_A5.1_T2.js, test/language/function-code/S10.2.1_A5.2_T1.js, test/language/statements/block/S12.1_A2.js, test/language/types/number/S8.5_A5.js
@anba [requested this while reviewing another patch](https://github.com/tc39/test262/pull/307#issuecomment-110505474), and I thought it was a good idea. As noted in the commit message, this work also surfaced some tautological tests.
Commit message:
> The `$PRINT` helper function has no effect on test behavior. The
> following tests use it to report assertion outcomes (and as a result
> will fail silently):
>
> - test/language/function-code/S10.2.1_A4_T2.js
> - test/language/function-code/S10.2.1_A5.1_T1.js
> - test/language/function-code/S10.2.1_A5.1_T2.js
> - test/language/function-code/S10.2.1_A5.2_T1.js
>
> Remove the function definition and all references within tests. Update
> tests that use it as an error reporting mechanism to instead use an
> appropriate `assert` helper function.
=> Remove $PRINT helper function

harness/sth.js, tools/packaging/templates/runner.bestPractice.html, tools/packaging/templates/runner.intl402.html, tools/packaging/templates/runner.test262.html
Since the Python runner was updated to include `assert.js` in all tests
unconditionally, a number of tests have been written that implicitly
rely on its presence. The browser runner does not currently provide this
file's contents to these tests, so they fail unconditionally.
Update the browser runner to inject that file's contents into every test
context.
Note: the existing approach to file retrieval (namely loading via
synchronous XHR requests) is inefficient and deprecated in some
browsers. It is honored here for the sake of consistency and to minimize
the changeset necessary to fix the browser runner.
=> Update browser runner to inject `assert.js`

test/built-ins/Promise/all/S25.4.4.1_A5.1_T1.js, test/built-ins/Promise/prototype/then/S25.4.5.3_A3.1_T1.js, test/built-ins/Promise/race/S25.4.4.3_A4.1_T1.js
This test's description concerns the behavior of `Promise.all` when the
IteratorStep abstract operation fails due to an abrupt completion
returned by the iterator's `next` method. The test body did not actually
assert that functionality.
Update the test body to correctly define the requisite iterator and
assert that the specific error created is the one thrown from the
invocation of `Promise.all`
=> Fix bugs in Promise tests

harness/math_precision.js
It was missing vars which was causing issues with our test harness
since we run all the files in strict mode.
=> Fix issue with math_precision.js

test/built-ins/Date/S15.9.3.1_A5_T1.js, test/built-ins/Date/S15.9.3.1_A5_T2.js, test/built-ins/Date/S15.9.3.1_A5_T3.js, test/built-ins/Date/S15.9.3.1_A5_T4.js, test/built-ins/Date/S15.9.3.1_A5_T5.js, test/built-ins/Date/S15.9.3.1_A5_T6.js
The `environment.js` file has been empty since its initial introduction
to this project [1]. It has no effect on any of the contexts in which it
is currently referenced, so it may be safely removed.
[1] be82787a00f8b2de474e1bfb29d65d04af72255f
=> Remove empty "include" file

harness/fnExists.js, test/language/expressions/delete/11.4.1-5-3.js
The `fnExists` function defines a generic way to determine if any number
of values are function instances. Because it is only used by a single
test, the additional complexity required by the generalized code (and
the organizational drawbacks to maintaining another "include" file) are
not justified. Remove the file and update the test to assert the
function's existence directly.
=> Remove unnecessary "include" file

test/built-ins/Object/assign/ObjectOverride-sameproperty.js, test/built-ins/Object/assign/Source-Number-Boolen-Symbol.js
Two tests started the configuration block with a /*-- instead of a /*---.
=> Fixed invalid configuration block delimiters.

tools/packaging/parseTestRecord.py
The "monkeyYaml" parser is intended to serve as a lightweight fallback
to Python's standard YAML parser in contexts where the latter is not
available. Any intentionally-simplified implementation will necessarily
exhibit non-standard behavior for different input, so not all input
accepted by the standard parser will be accepted by "monkeyYaml". If
loaded exclusively in fallback situations, these edge cases can only be
identified (and debugged) in the environments that require the fallback.
This has allowed developers to unknowingly author tests that cause
errors.
Update the test runner to use "monkeyYaml" in all cases, ensuring more
consistent behavior across contexts and precluding this class of
regression.
This depends on gh-346
=> Use "monkeyYaml" in all environments

CONTRIBUTING.md, test/language/directive-prologue/10.1.1-2gs.js, test/language/directive-prologue/10.1.1-5gs.js, test/language/directive-prologue/10.1.1-8gs.js, test/language/directive-prologue/14.1-4gs.js, test/language/directive-prologue/14.1-5gs.js, tools/packaging/test262.py, website/scripts/sth.js
Some tests involving the directive prologue are invalidated by source
text transformations that insert executable code in the beginning of the
script. Implement a `raw` flag that allows these tests to opt-out of
this transformation. Update the relevant tests to use this flag (and
remove references to globals only available when code is injected).
Update the Python runner accordingly:
- Do not run tests marked as "raw" in strict mode
- Reject invalid test configurations
Update the browser runner accordingly:
- Do not modify the script body of tests marked as "raw"
=> Implement `raw` flag

test/language/expressions/assignment/11.13.1-4-29gs.js
SyntaxError => TypeError for writing to a non-writeable field.
Fixes #372 for master
=> Fix 11.13.1-4-29gs.js incorrect comment explanation (master)

test/built-ins/Array/prototype/concat/is-concat-spreadable-get-err.js, test/built-ins/Array/prototype/concat/is-concat-spreadable-val-falsey.js, test/built-ins/Array/prototype/concat/is-concat-spreadable-val-truthy.js, test/built-ins/Array/prototype/concat/is-concat-spreadable-val-undefined.js, test/built-ins/Symbol/isConcatSpreadable/prop-desc.js
`test/built-ins/Array/prototype/concat/is-concat-spreadable-val-undefined.js` is prone to false positives, but I want to make sure that implementers don't simply coerce any "own" property.
=> Add tests for @@isConcatSpreadable

test/built-ins/RegExp/prototype/Symbol.match/get-unicode-error.js, test/built-ins/RegExp/prototype/Symbol.match/u-advance-after-empty.js, test/built-ins/RegExp/prototype/Symbol.replace/get-unicode-error.js, test/built-ins/RegExp/prototype/Symbol.replace/u-advance-after-empty.js, test/built-ins/RegExp/prototype/Symbol.search/u-lastindex-advance.js, test/built-ins/RegExp/prototype/Symbol.split/u-lastindex-adv-thru-failure.js, test/built-ins/RegExp/prototype/Symbol.split/u-lastindex-adv-thru-match.js, test/built-ins/RegExp/prototype/exec/u-captured-value.js, test/built-ins/RegExp/prototype/exec/u-lastindex-adv.js, test/built-ins/RegExp/prototype/exec/u-lastindex-value.js, test/built-ins/RegExp/prototype/flags/u-attr-err.js, test/built-ins/RegExp/prototype/flags/u-coercion.js, test/built-ins/RegExp/prototype/flags/u.js, test/built-ins/RegExp/prototype/unicode/length.js, test/built-ins/RegExp/prototype/unicode/name.js, test/built-ins/RegExp/prototype/unicode/prop-desc.js, test/built-ins/RegExp/prototype/unicode/this-invald-obj.js, test/built-ins/RegExp/prototype/unicode/this-non-obj.js, test/built-ins/RegExp/prototype/unicode/this-regexp.js, test/language/literals/regexp/u-astral.js, test/language/literals/regexp/u-case-mapping.js, test/language/literals/regexp/u-dec-esc.js, test/language/literals/regexp/u-invalid-char-esc.js, test/language/literals/regexp/u-invalid-char-range-a.js, test/language/literals/regexp/u-invalid-char-range-b.js, test/language/literals/regexp/u-surrogate-pairs.js, test/language/literals/regexp/u-unicode-esc-bounds.js, test/language/literals/regexp/u-unicode-esc-non-hex.js, test/language/literals/regexp/u-unicode-esc.js
I'd like to draw attention to two tests in particular since they both concern a very specific condition (for example, good ol' step 8.g.iv.5.d):
- test/built-ins/RegExp/prototype/Symbol.match/u-lastindex.js
- test/built-ins/RegExp/prototype/Symbol.replace/u-lastindex.js
Despite a careful reading, I'm still not convinced those test cases properly express the detail documented in their info/description. I decided I may have looked at it for too long and that some fresh perspective would help
@mathiasbynens Would you mind taking a look?
=> Add tests for RegExp `u` flag

test/built-ins/RegExp/prototype/exec/S15.10.6.2_A5_T3.js, test/built-ins/RegExp/prototype/test/S15.10.6.3_A1_T22.js
Previously, test262 had only a test that ensured that ToLength (for
example, rather than ToInteger) was used in test'ing a RegExp, not
in calls to exec. Although in the ES5 and ES2015 specs there is only
one code path, in some implementations, ToLength is called in from
separate code paths. This patch makes a new test for exec'ing a
RegExp and ensures that ToLength is called.
=> Reinforce test for the use of ToLength(lastIndex) in RegExp

test/built-ins/Array/from/get-iter-method-err.js, test/built-ins/Array/from/iter-adv-err.js, test/built-ins/Array/from/iter-cstm-ctor-err.js, test/built-ins/Array/from/iter-cstm-ctor.js, test/built-ins/Array/from/iter-get-iter-err.js, test/built-ins/Array/from/iter-get-iter-val-err.js, test/built-ins/Array/from/iter-map-fn-args.js, test/built-ins/Array/from/iter-map-fn-err.js, test/built-ins/Array/from/iter-map-fn-return.js, test/built-ins/Array/from/iter-map-fn-this-arg.js, test/built-ins/Array/from/iter-map-fn-this-non-strict.js, test/built-ins/Array/from/iter-map-fn-this-strict.js, test/built-ins/Array/from/iter-set-elem-prop-err.js, test/built-ins/Array/from/iter-set-elem-prop.js, test/built-ins/Array/from/iter-set-length-err.js, test/built-ins/Array/from/iter-set-length.js, test/built-ins/Array/prototype/values/length.js, test/built-ins/Array/prototype/values/name.js, test/built-ins/Array/prototype/values/prop-desc.js, test/built-ins/Array/prototype/values/this-val-non-obj-coercible.js, test/built-ins/IteratorPrototype/Symbol.iterator/length.js, test/built-ins/IteratorPrototype/Symbol.iterator/name.js, test/built-ins/IteratorPrototype/Symbol.iterator/prop-desc.js, test/built-ins/IteratorPrototype/Symbol.iterator/return-val.js, test/built-ins/String/prototype/Symbol.iterator/length.js, test/built-ins/String/prototype/Symbol.iterator/name.js, test/built-ins/String/prototype/Symbol.iterator/prop-desc.js, test/built-ins/String/prototype/Symbol.iterator/this-val-non-obj-coercible.js, test/built-ins/String/prototype/Symbol.iterator/this-val-to-str-err.js, test/built-ins/Symbol/iterator/prop-desc.js
Because the well-known `@@iterator` Symbol is used in many parts of the ES6 specification, it already has substantial coverage in Test262. See, for instance:
- [`language/statements/for-of`](https://github.com/tc39/test262/tree/d62f3a82b97dba22a0be2798fbe34548e96a439f/test/language/statements/for-of)
- [`built-ins/ArrayIteratorPrototype`](https://github.com/tc39/test262/tree/d62f3a82b97dba22a0be2798fbe34548e96a439f/test/built-ins/ArrayIteratorPrototype)
- [`built-ins/MapIteratorPrototype`](https://github.com/tc39/test262/tree/d62f3a82b97dba22a0be2798fbe34548e96a439f/test/built-ins/MapIteratorPrototype)
- [`built-ins/SetIteratorPrototype`](https://github.com/tc39/test262/tree/d62f3a82b97dba22a0be2798fbe34548e96a439f/test/built-ins/SetIteratorPrototype)
- …
=> Add tests for @@iterator

harness/assert.js
Expected/actual values should be delimited in a way that
isn't confusable with actual string quotes " '
=> Use guillemets («») to quote string values - fixes #174

test/built-ins/Array/from/Array.from_arity.js
An extra newline in a comment prevented the import from being parsed properly.
=> Fix Array.from_arity test

test/built-ins/Function/prototype/Symbol.hasInstance/length.js, test/built-ins/Function/prototype/Symbol.hasInstance/name.js, test/built-ins/Function/prototype/Symbol.hasInstance/prop-desc.js, test/built-ins/Function/prototype/Symbol.hasInstance/this-val-bound-target.js, test/built-ins/Function/prototype/Symbol.hasInstance/this-val-not-callable.js, test/built-ins/Function/prototype/Symbol.hasInstance/this-val-poisoned-prototype.js, test/built-ins/Function/prototype/Symbol.hasInstance/this-val-prototype-non-obj.js, test/built-ins/Function/prototype/Symbol.hasInstance/value-get-prototype-of-err.js, test/built-ins/Function/prototype/Symbol.hasInstance/value-negative.js, test/built-ins/Function/prototype/Symbol.hasInstance/value-non-obj.js, test/built-ins/Function/prototype/Symbol.hasInstance/value-positive.js, test/built-ins/Symbol/hasInstance/prop-desc.js, test/language/expressions/instanceof/symbol-hasinstance-get-err.js, test/language/expressions/instanceof/symbol-hasinstance-invocation.js, test/language/expressions/instanceof/symbol-hasinstance-not-callable.js, test/language/expressions/instanceof/symbol-hasinstance-to-boolean.js
Assert the behavior of the built-in method on the FunctionPrototype and
the usage of the Symbol by the `instanceof` operator.
=> Add tests for well-known Symbol, @@hasInstance

test/built-ins/String/prototype/toLocaleLowerCase/special_casing.js, test/built-ins/String/prototype/toLocaleLowerCase/special_casing_conditional.js, test/built-ins/String/prototype/toLocaleUpperCase/special_casing.js, test/built-ins/String/prototype/toLowerCase/special_casing.js, test/built-ins/String/prototype/toLowerCase/special_casing_conditional.js, test/built-ins/String/prototype/toUpperCase/special_casing.js, test/intl402/String/prototype/toLocaleLowerCase/capital_I_with_dot.js, test/intl402/String/prototype/toLocaleLowerCase/special_casing_Azeri.js, test/intl402/String/prototype/toLocaleLowerCase/special_casing_Lithuanian.js, test/intl402/String/prototype/toLocaleLowerCase/special_casing_Turkish.js, test/intl402/String/prototype/toLocaleUpperCase/special_casing_Azeri.js, test/intl402/String/prototype/toLocaleUpperCase/special_casing_Lithuanian.js, test/intl402/String/prototype/toLocaleUpperCase/special_casing_Turkish.js
Changes in "test/built-ins/String/prototype":
- String.prototype.to{LowerCase, UpperCase, LocaleLowerCase, LocaleUpperCase} are specified to implement the locale-insensitive case mappings defined in SpecialCasings.txt, add new tests for this requirement.
- The tests for toLowerCase and toLocaleLowerCase resp. toUpperCase and toLocaleUpperCase are the same. This is intentional, the methods need to implement the same functionality. 
Changes in "test/intl402/String/prototype":
- String.prototype.to{LocaleLowerCase, LocaleUpperCase} are additionally specified to implement the locale-sensitive case mappings defined in SpecialCasings.txt, add new tests for this requirement.
Notes:
1. ~~This PR currently depends on #397~~ (No longer applies, re-based and force pushed.)
1. The test cases also …
=> String.prototype.to{Lower,Upper} tests for special casing

test/built-ins/Array/prototype/reverse/get_if_present_with_delete.js, test/built-ins/Array/prototype/splice/called_with_one_argument.js, test/built-ins/Array/prototype/splice/set_length_no_args.js, test/built-ins/Array/prototype/toLocaleString/primitive_this_value.js, test/built-ins/Array/prototype/toLocaleString/primitive_this_value_getter.js, test/built-ins/Date/TimeClip_negative_zero.js, test/built-ins/Date/construct_with_date.js, test/built-ins/Error/message_property.js, test/built-ins/Error/message_property_native_error.js, test/built-ins/Object/prototype/hasOwnProperty/symbol_own_property.js, test/built-ins/Object/prototype/hasOwnProperty/symbol_property_toPrimitive.js, test/built-ins/Object/prototype/hasOwnProperty/symbol_property_toString.js, test/built-ins/Object/prototype/hasOwnProperty/symbol_property_valueOf.js, test/built-ins/Object/prototype/propertyIsEnumerable/symbol_own_property.js, test/built-ins/Object/prototype/propertyIsEnumerable/symbol_property_toPrimitive.js, test/built-ins/Object/prototype/propertyIsEnumerable/symbol_property_toString.js, test/built-ins/Object/prototype/propertyIsEnumerable/symbol_property_valueOf.js, test/built-ins/Object/prototype/toLocaleString/primitive_this_value.js, test/built-ins/Object/prototype/toLocaleString/primitive_this_value_getter.js, test/built-ins/RegExp/call_with_non_regexp_same_constructor.js, test/built-ins/RegExp/call_with_regexp_match_falsy.js, test/built-ins/RegExp/call_with_regexp_not_same_constructor.js, test/built-ins/String/prototype/toLocaleLowerCase/supplementary_plane.js, test/built-ins/String/prototype/toLocaleUpperCase/supplementary_plane.js, test/built-ins/String/prototype/toLowerCase/supplementary_plane.js, test/built-ins/String/prototype/toUpperCase/supplementary_plane.js
- String case functions iterate over code points
- Has called before Get in Array.p.reverse
- Add test for web-compat Array.p.splice behaviour; Plus missing test for no arguments case
- ToObject no longer applied to this-value in Array.p.toLocaleString
- ToObject no longer applied to this-value in Object.p.toLocaleString
- Add tests for Object.p.propertyIsEnumerable and symbol property keys
- Add tests for Object.p.hasOwnProperty and symbol property keys
- Test property descriptor attributes of message property
- Tests for RegExp constructor checks
- Date constructor when called with date object
- TimeClip never returns negative zero
=> Tests for changes introduced in ES2015 (Annex E)

test/built-ins/RegExp/prototype/Symbol.search/coerce-string-err.js, test/built-ins/RegExp/prototype/Symbol.search/coerce-string.js, test/built-ins/RegExp/prototype/Symbol.search/cstm-exec-return-index.js, test/built-ins/RegExp/prototype/Symbol.search/cstm-exec-return-invalid.js, test/built-ins/RegExp/prototype/Symbol.search/failure-return-val.js, test/built-ins/RegExp/prototype/Symbol.search/get-lastindex-err.js, test/built-ins/RegExp/prototype/Symbol.search/length.js, test/built-ins/RegExp/prototype/Symbol.search/match-err.js, test/built-ins/RegExp/prototype/Symbol.search/name.js, test/built-ins/RegExp/prototype/Symbol.search/prop-desc.js, test/built-ins/RegExp/prototype/Symbol.search/set-lastindex-init-err.js, test/built-ins/RegExp/prototype/Symbol.search/set-lastindex-init.js, test/built-ins/RegExp/prototype/Symbol.search/set-lastindex-restore-err.js, test/built-ins/RegExp/prototype/Symbol.search/set-lastindex-restore.js, test/built-ins/RegExp/prototype/Symbol.search/success-get-index-err.js, test/built-ins/RegExp/prototype/Symbol.search/success-return-val.js, test/built-ins/RegExp/prototype/Symbol.search/this-val-non-obj.js, test/built-ins/String/prototype/search/cstm-search-get-err.js, test/built-ins/String/prototype/search/cstm-search-invocation.js, test/built-ins/String/prototype/search/invoke-builtin-search-searcher-undef.js, test/built-ins/String/prototype/search/invoke-builtin-search.js, test/built-ins/Symbol/search/prop-desc.js
@bterlson same as gh-399, I believe modification of a built-in is required by one test (same reason, different method: `built-ins/String/prototype/search/invoke-builtin-search.js`).
=> Add tests for well-known Symbol: @@search

test/built-ins/Promise/all/S25.4.4.1_A3.1_T3.js, test/built-ins/Promise/all/S25.4.4.1_A5.1_T1.js, test/built-ins/Promise/executor-function-extensible.js, test/built-ins/Promise/executor-function-length.js, test/built-ins/Promise/executor-function-name.js, test/built-ins/Promise/executor-function-nonconstructor.js, test/built-ins/Promise/executor-function-prototype.js, test/built-ins/Promise/race/S25.4.4.3_A2.2_T3.js, test/built-ins/Promise/race/S25.4.4.3_A4.1_T1.js, test/built-ins/Promise/race/S25.4.4.3_A4.1_T2.js, test/built-ins/Promise/symbol-species.js
This allows these tests to be more easily reused to test Promise implementations in isolation (for example, `core-js` and `es6-shim`).
=> Remove unnecessary ES2015 syntax; add feature flags where appropriate.

test/language/statements/const/syntax/const-declaring-let-split-across-two-lines.js, test/language/statements/let/syntax/let-let-declaration-split-across-two-lines.js, test/language/statements/let/syntax/let-let-declaration-with-initializer-split-across-two-lines.js
See the extensive comment in the testcase for explanation and justification of this testcase.
Caveat: I've verified this test passes in a SpiderMonkey implementing the semantics described in this testcase, but I haven't verified all the test262 testcase structure/formatting is correct and doesn't contain any errors.
=> Add a test verifying that |let<newline>let| isn't subjected to ASI, matches LexicalDeclaration, and is then treated as an early error

test/language/expressions/instanceof/primitive-prototype-with-object.js, test/language/expressions/instanceof/primitive-prototype-with-primitive.js, test/language/expressions/instanceof/prototype-getter-with-object-throws.js, test/language/expressions/instanceof/prototype-getter-with-object.js, test/language/expressions/instanceof/prototype-getter-with-primitive.js
New tests because implementation reality doesn't match spec. And browsers don't have a common behaviour so it's also not possible to change the spec to match browsers.
=> Add tests for instanceof operator when prototype property is primitive or getter

test/language/destructuring/binding/initialization-requires-object-coercible-null.js, test/language/destructuring/binding/initialization-requires-object-coercible-undefined.js, test/language/destructuring/binding/initialization-returns-normal-completion-for-empty-objects.js, test/language/destructuring/binding/syntax/array-elements-with-initializer.js, test/language/destructuring/binding/syntax/array-elements-with-object-patterns.js, test/language/destructuring/binding/syntax/array-elements-without-initializer.js, test/language/destructuring/binding/syntax/array-pattern-with-elisions.js, test/language/destructuring/binding/syntax/array-pattern-with-no-elements.js, test/language/destructuring/binding/syntax/array-rest-elements.js, test/language/destructuring/binding/syntax/object-pattern-with-no-property-list.js, test/language/destructuring/binding/syntax/property-list-bindings-elements.js, test/language/destructuring/binding/syntax/property-list-followed-by-a-single-comma.js, test/language/destructuring/binding/syntax/property-list-single-name-bindings.js, test/language/destructuring/binding/syntax/property-list-with-property-list.js, test/language/destructuring/binding/syntax/recursive-array-and-object-patterns.js
I believe at least the minimal tests for syntax is ready, but there's a lot of other tests to bring to this PR.
Possibly coming up next week:
Extra, maybe not necessary for this coverage goal:
=> Destructuring Binding - syntax and simple initialization

test/language/statements/for-in/head-decl-expr.js, test/language/statements/for-in/head-expr-expr.js, test/language/statements/for-in/head-var-expr.js, test/language/statements/for-of/head-decl-no-expr.js, test/language/statements/for-of/head-expr-no-expr.js, test/language/statements/for-of/head-var-no-expr.js
Although the `for..in` statement allows Expressions to define the
iterator, only an AssignmentExpression may occupy this position in the
`for..of` statement.
=> Add tests for iterator expression in ForIn/Of head

harness/tco-helper.js, test/language/expressions/call/tco-call-args.js, test/language/expressions/call/tco-member-args.js, test/language/expressions/comma/tco-final.js, test/language/expressions/conditional/tco-cond.js, test/language/expressions/conditional/tco-pos.js, test/language/expressions/logical-and/tco-right.js, test/language/expressions/logical-or/tco-right.js, test/language/expressions/tagged-template/tco-call.js, test/language/expressions/tagged-template/tco-member.js, test/language/expressions/tco-pos.js, test/language/statements/block/tco-stmt-list.js, test/language/statements/block/tco-stmt.js, test/language/statements/do-while/tco-body.js, test/language/statements/for/tco-const-body.js, test/language/statements/for/tco-let-body.js, test/language/statements/for/tco-lhs-body.js, test/language/statements/for/tco-var-body.js, test/language/statements/if/tco-else-body.js, test/language/statements/if/tco-if-body.js, test/language/statements/labeled/tco.js, test/language/statements/return/tco.js, test/language/statements/switch/tco-case-body-dflt.js, test/language/statements/switch/tco-case-body.js, test/language/statements/switch/tco-dftl-body.js, test/language/statements/try/tco-catch-finally.js, test/language/statements/try/tco-catch.js, test/language/statements/try/tco-finally.js, test/language/statements/while/tco-body.js
I'm using the testing strategy discussed in gh-466 to assert proper tail call optimization. As noted in that discussion, runtime behavior in the event of a stack overflow is not currently specified. The `callCount` variable in these tests is intended to guard against bizarre runtime behavior in these cases--even if the failed recursion does not throw a runtime error or crash outright, the final assertion will fail.
Unfortunately, the lack of standard behavior in the event of stack overflow makes asserting the negative case (i.e. "no optimization occurs") impossible. Many runtimes throw an error of some sort, and I think that is reasonable behavior to standardize. To that end, [I have submitted a patch to the specification](https://github.com/tc39/ecma262/pull/319), and I have tagged a …
=> Add tests for tail-call optimization

CONSOLE-RUNNER.md, tools/packaging/test262.py
Adds a `-j`/`--workers-count` parameter to `tools/packaging/test262.py`, defaulting to `[number of cores] - 1`.
Speeds up running the test suite by about ~3x on my 4-core machine, with the SpiderMonkey shell. This could certainly be optimized more by just appending test results to per-thread lists and merging them at the end, but it's better than nothing.
=> Enable parallel test execution in console runner

test/built-ins/Object/prototype/extensibility.js, test/built-ins/Object/prototype/proto.js, test/built-ins/Object/prototype/setPrototypeOf-with-different-values.js, test/built-ins/Object/prototype/setPrototypeOf-with-same-value.js
Ref tc39/ecma262#308
The second commit covers the suggestion at https://github.com/tc39/ecma262/pull/308/files#r50536782 and it might be squashed or discarded regarding the discussion there.
This is an anticipated PR and needs to wait until the effective merge on the PR for tc39/ecma262.
cc @littledan
=> Add tests for [[SetPrototypeOf]] on immutable prototype exotic objects

test/built-ins/Promise/prototype/then/ctor-access-count.js
Assert that the `constructor` property of the "this" value of
`Promise.prototype.then` is accessed exactly once. This guards against
implementations where repeated access is used instead of reference
passing (possibly motivated by convenience).
Repeated access of this kind was demonstrated by V8's implementation of
the specification:
https://bugs.chromium.org/p/v8/issues/detail?id=4539
=> Promise: Add test for constructor access count

test/built-ins/Promise/prototype/then/resolve-pending-fulfilled-prms-cstm-then.js, test/built-ins/Promise/prototype/then/resolve-pending-rejected-prms-cstm-then.js, test/built-ins/Promise/prototype/then/resolve-settled-fulfilled-prms-cstm-then.js, test/built-ins/Promise/prototype/then/resolve-settled-rejected-prms-cstm-then.js, test/built-ins/Promise/race/resolve-prms-cstm-then.js, test/built-ins/Promise/resolve-prms-cstm-then-deferred.js, test/built-ins/Promise/resolve-prms-cstm-then-immed.js, test/built-ins/Promise/resolve/resolve-prms-cstm-then.js
Add tests that assert behavior when a Promise is resolved with another
Promise whose `then` method has been overridden. Because all objects
with a `then` method are treated equivalently, the presence of a
[[PromiseState]] internal slot should have no effect on program
behavior.
These tests guard against a faulty optimization originally implemented
in V8:
https://bugs.chromium.org/p/v8/issues/detail?id=3641
=> Promise: Add tests to disallow faulty optimization

tools/packaging/test262.py
Now that the test runner is capable of running tests in parallel using threads,
it's possible for race conditions to effect the output. Care was taken to
ensure that threads safely share access to the output file resource (when
specified), but there are some issues with text printed to standard output:
$ ./tools/packaging/test262.py --command d8 built-ins/undefined --full-summary -j 4
built-ins/undefined/S15.1.1.3_A1 passed in strict mode
built-ins/undefined/15.1.1.3-0 passed in non-strict mode
built-ins/undefined/15.1.1.3-2 passed in strict mode
=== Summary ===
- Ran 12 tests
- All tests succeeded
built-ins/undefined/S15.1.1.3_A3_T1 passed in non-strict mode
built-ins/undefined/S15.1.1.3_A1 passed in non-strict mode
built-ins/undefined/15.1.1.3-0 passed in strict mode …
=> Avoid Race Conditions in Test Runner

test/built-ins/TypedArrays/from/mapfn-is-not-callable.js
TypedArrays constructors are still callable even if they trigger a
TypeError Exception when a new target is not defined
=> Fix test for TypedArrays.from on callable function

harness/proxyTrapsHelper.js, test/built-ins/Object/entries/observable-operations.js, test/built-ins/Object/getOwnPropertyDescriptors/duplicate-keys.js, test/built-ins/Object/getOwnPropertyDescriptors/exception-not-object-coercible.js, test/built-ins/Object/getOwnPropertyDescriptors/function-length.js, test/built-ins/Object/getOwnPropertyDescriptors/function-name.js, test/built-ins/Object/getOwnPropertyDescriptors/function-property-descriptor.js, test/built-ins/Object/getOwnPropertyDescriptors/inherited-properties-omitted.js, test/built-ins/Object/getOwnPropertyDescriptors/normal-object.js, test/built-ins/Object/getOwnPropertyDescriptors/observable-operations.js, test/built-ins/Object/getOwnPropertyDescriptors/primitive-booleans.js, test/built-ins/Object/getOwnPropertyDescriptors/primitive-numbers.js, test/built-ins/Object/getOwnPropertyDescriptors/primitive-strings.js, test/built-ins/Object/getOwnPropertyDescriptors/primitive-symbols.js, test/built-ins/Object/getOwnPropertyDescriptors/symbols-included.js, test/built-ins/Object/getOwnPropertyDescriptors/symbols-omitted.js, test/built-ins/Object/getOwnPropertyDescriptors/tamper-with-global-object.js, test/built-ins/Object/getOwnPropertyDescriptors/tamper-with-object-keys.js, test/built-ins/Object/values/observable-operations.js, test/harness/proxytrapshelper-default.js, test/harness/proxytrapshelper-overrides.js
Tests for the stage 3 [proposal](https://github.com/tc39/proposal-object-getownpropertydescriptors) for `Object.getOwnPropertyDescriptors`.
=> Add Object.getOwnPropertyDescriptors tests

test/built-ins/TypedArrays/object-arg-throws-setting-obj-to-primitive-typeerror.js, test/built-ins/TypedArrays/object-arg-throws-setting-obj-to-primitive.js, test/built-ins/TypedArrays/object-arg-throws-setting-obj-tostring.js, test/built-ins/TypedArrays/object-arg-throws-setting-obj-valueof-typeerror.js, test/built-ins/TypedArrays/object-arg-throws-setting-obj-valueof.js, test/built-ins/TypedArrays/object-arg-throws-setting-typedarray-property.js
After [playing with some typedArray samples](https://gist.github.com/leobalter/a64665cd62490582f980) I found some runtimes accepting typedArrays as a property on the object argument, like: `new Int8Array([8, new Int8Array(1)])`.
Running through the specs it seems this is a bug on the runtimes, so here are some tests to prevent it, along with other tests covering extra toPrimitive and valueOf operations
=> Add tests for _TypedArrays_(object) using object properties

test/language/statements/class/subclass/builtin-objects/Date/regular-subclassing.js
Closes #489
After some quick searches through the repo, it seems that was the only case with this particular issue.
The tests for several Date.prototype methods needs improvement, as most of them does not have any tests for returned values.
=> Fix location based return value for Date on subclassing tests

CONSOLE-RUNNER.md, tools/CONSOLE-RUNNER.md, tools/packaging/test262.py
I've heard it mentioned that the Python "console runner" utility is deprecated,
but there is no documentation in this project to suggest this. If it is the
case, we should be more clear about it in order to better set expectations for
consumers and contributors.
A decision to deprecate would also motivate the removal of a recent feature
addition to the console runner--support for parallelization. To date, three
bugs have been found in that implementation. As an optimization to a deprecated
tool, the maintenance overhead is not justified.
Resolves gh-512.
=> Console Runner: Revert Parallelization and Formally Deprecate

test/language/asi/S7.9_A5.7_T1.js
V8 ran into an issue where the YAML parser our test setup is using
didn't understand the newline, and failed to parser the negative
test expectation below, causing the test to fail. This patch fixes
the issue.
=> Remove a blank line to stop confusing YAML parsers

test/built-ins/ThrowTypeError/extensible.js, test/built-ins/ThrowTypeError/forbidden-arguments.js, test/built-ins/ThrowTypeError/forbidden-caller.js, test/built-ins/ThrowTypeError/frozen.js, test/built-ins/ThrowTypeError/is-function.js, test/built-ins/ThrowTypeError/length.js, test/built-ins/ThrowTypeError/name.js, test/built-ins/ThrowTypeError/prototype.js, test/built-ins/ThrowTypeError/throws-type-error.js, test/built-ins/ThrowTypeError/unique-per-realm-function-proto.js, test/built-ins/ThrowTypeError/unique-per-realm-non-simple.js, test/built-ins/ThrowTypeError/unique-per-realm-unmapped-args.js, test/language/statements/class/subclass/default-constructor-spread-override.js
Increases the coverage for %ThrowTypeError% and adds an _interesting_ test case for default class constructors (https://bugzilla.mozilla.org/show_bug.cgi?id=1234702).
=> Improve coverage %ThrowTypeError% and default class constructors

test/language/statements/debugger/expression.js, test/language/statements/debugger/statement.js
The runtime semantics of this statement are host-defined and therefore
untestable, but the statement's affect on the formal grammar should be
consistent across all implementations.
=> Add tests for `debugger` statement

test/built-ins/Math/random/S15.8.2.14_A1.js
As written, the test for `Math.random` would pass if the runtime
erroneously produced a non-numeric value. Add the necessary assertions
to guard against this case.
=> Avoid false positives

CONTRIBUTING.md
As written, the example for asserting runtime errors is written with an
early error. Because the error is expected to be reported prior to
program execution, the `assert.throws` function cannot be used to detect
it.
Demonstrate the usage of the helper function with a runtime error.
=> Correct example in contribution guidelines

test/built-ins/System/System.js, test/built-ins/System/global/global-object.js, test/built-ins/System/global/property-descriptor.js, test/built-ins/System/object-prototype.js, test/built-ins/System/properties.js
(https://github.com/tc39/proposal-global/issues/12)
Since this proposal is stage 2, it's OK to hold off on merging these tests - I will seek stage 3 in May after which it would be ideal to have them merged :-)
=> Add `System.global` tests

test/language/literals/regexp/early-err-bad-flag.js, test/language/literals/regexp/early-err-dup-flag.js, test/language/literals/regexp/early-err-pattern.js
@littledan V8 fails `early-err-pattern.js`, previously reported at https://bugs.chromium.org/p/v8/issues/detail?id=896
=> Add tests for RegExp literal early errors

harness/simdUtilities.js, test/built-ins/Simd/AUTHORS, test/built-ins/Simd/all_true.js, test/built-ins/Simd/any_true.js, test/built-ins/Simd/bit_conversion.js, test/built-ins/Simd/bit_preservation.js, test/built-ins/Simd/check.js, test/built-ins/Simd/constructor.js, test/built-ins/Simd/float_operators.js, test/built-ins/Simd/from.js, test/built-ins/Simd/from_bits.js, test/built-ins/Simd/loadn.js, test/built-ins/Simd/logical_operators.js, test/built-ins/Simd/negate.js, test/built-ins/Simd/not.js, test/built-ins/Simd/numerical_operators.js, test/built-ins/Simd/operators.js, test/built-ins/Simd/replace_lane.js, test/built-ins/Simd/round_trip.js, test/built-ins/Simd/saturate.js, test/built-ins/Simd/select.js, test/built-ins/Simd/shift_operator.js, test/built-ins/Simd/shuffle.js, test/built-ins/Simd/storen.js, test/built-ins/Simd/swizzle.js
Add SIMD test suite - #441
Tests the SIMD operations as per the SIMD.js specification - http://tc39.github.io/ecmascript_simd/. 
Generic utility functions ported to harness/simdUtilities.js
Value semantics tests are not currently included as there has to be a way to disable them based on whether the tests are running with the polyfill.
=> Add SIMD test suite and utility functions.

INTERPRETING.md, README.md
I'm interested in formalizing the contract between Test262 and the implementors
who maintain harnesses to execute it. For instance, implementors currently have
to infer that:
- most tests rely on a file named `harness/sta.js`.
- some tests mutate global state so as to make realm sharing unacceptable
- test code must be evaluated in the global scope
I expect we will see more benefit from a document like this as we continue to
expand coverage in Test262, particularly for aspects of the environment which
cannot be directly controlled from ECMAScript code. For instance: 
- module resolution semantics
- cross-script concerns (e.g. a host-provided `$CREATESCRIPT` function)
- cross-realm concerns (e.g. a host-provided `$CREATEREALM` function)
...but I think I've covered all of the current …
=> Add documentation on interpreting tests

harness/assertRelativeDateMs.js, test/built-ins/Date/S15.9.3.1_A5_T1.js, test/built-ins/Date/S15.9.3.1_A5_T2.js, test/built-ins/Date/S15.9.3.1_A5_T3.js, test/built-ins/Date/S15.9.3.1_A5_T4.js, test/built-ins/Date/S15.9.3.1_A5_T5.js, test/built-ins/Date/S15.9.3.1_A5_T6.js, test/harness/assertRelativeDateMs.js
The millisecond representation of a given Date instance is dependent on
the local system's time zone settings. In order to pass consistently
across contexts, tests for this value must take the system configuration
into account.
Introduce a test harness utility function to encapsulate these concerns.
Re-use this function across all test files that assert the exact
millisecond representation of Date instances.
@littledan As noted in the original BugZilla report, this approach complicates
the tests, but it doesn't quite depend on the semantics under test, so it
should be "safe."
That said, another solution occurred to me while writing this: we could make a
specific time zone (say, Greenwich Mean Time) a formal requirement to executing
Test262. This seems like the same class of problems I am …
=> Correct invalid tests for the Date constructor

test/annexB/language/eval-code/direct/var-env-lower-lex-catch-non-strict.js, test/annexB/language/statements/try/catch-redeclared-for-in-var.js, test/annexB/language/statements/try/catch-redeclared-for-var.js, test/language/eval-code/direct/var-env-lower-lex-catch-non-strict.js, test/language/statements/try/early-catch-duplicates.js, test/language/statements/try/early-catch-lex.js, test/language/statements/try/early-catch-var.js
This changeset includes tests for early errors and those generated
dynamically by eval. It also accounts for relevant AnnexB extensions.
=> Add tests for TryStatement binding restrictions

harness/nativeFunctionMatcher.js, test/harness/nativeFunctionMatcher.js
Modify the regular expression for native functions' toString value to
satisfy all test cases. Correct the test file's reference to the harness
file. Re-format the test file's assertions to aid debugging in the event
of failure.
@michaelficarra Would you mind taking a look?
=> Correct tests for native functions' toString value

tools/generation/generator.py
When inspecting previously-generated files, a new `Test` instance should
be used. This avoids over-writing the in-memory representation of the
latest test, and allows previously-existing test files to be partially
updated according to subsequent changes in their respective source/case
files.
(I discovered this oversight while updating the yet-to-be-submitted first batch of procedurally-generated tests.)
=> [generation] Support changing to existing files

harness/nans.js, test/built-ins/TypedArray/prototype/fill/fill-values-conversion-operations-consistent-nan.js, test/built-ins/TypedArray/prototype/map/return-new-typedarray-conversion-operation-consistent-nan.js, test/built-ins/TypedArray/prototype/set/bit-precision.js, test/built-ins/TypedArray/prototype/slice/bit-precision.js, test/built-ins/TypedArrays/internals/DefineOwnProperty/conversion-operation-consistent-nan.js, test/built-ins/TypedArrays/internals/Set/conversion-operation-consistent-nan.js, test/built-ins/TypedArrays/object-arg-conversion-operation-consistent-nan.js
Given the highly technical nature of this aspect of the specification, the
chances that I have made a mistake here are higher than normal--I'm still a
little concerned that these tests are overly strict.
@littledan can you verify that these tests accurately demonstrate the
conditions required by the spec?
For context, SpiderMonkey fails:
- `built-ins/TypedArray/prototype/map/return-new-typedarray-conversion-operation-consistent-nan.js`
- `built-ins/TypedArray/prototype/slice/bit-precision.js`
while V8 fails:
- `built-ins/TypedArrays/internals/Set/conversion-operation-consistent-nan.js`
Commit message:
> Ensure that NaN values are canonicalized consistently by all invocations
> of SetValueInBuffer. Also ensure that `%TypedArray%.prototype.set` and
> `%TypedArray%.prototype.slice` preserve …
=> Add tests for NaN handling with Typed Arrays

test/annexB/built-ins/escape/empty-string.js, test/annexB/built-ins/escape/escape-above.js, test/annexB/built-ins/escape/escape-below.js, test/annexB/built-ins/escape/to-string-err-symbol.js, test/annexB/built-ins/escape/to-string-err.js, test/annexB/built-ins/escape/to-string-observe.js, test/annexB/built-ins/escape/unmodified.js, test/annexB/built-ins/unescape/empty-string.js, test/annexB/built-ins/unescape/four-ignore-bad-u.js, test/annexB/built-ins/unescape/four-ignore-end-str.js, test/annexB/built-ins/unescape/four-ignore-non-hex.js, test/annexB/built-ins/unescape/four.js, test/annexB/built-ins/unescape/to-string-err-symbol.js, test/annexB/built-ins/unescape/to-string-err.js, test/annexB/built-ins/unescape/to-string-observe.js, test/annexB/built-ins/unescape/two-ignore-end-str.js, test/annexB/built-ins/unescape/two-ignore-non-hex.js, test/annexB/built-ins/unescape/two.js
Extend tests for the `escape` and `unescape` built-ins to assert their
behavior. Rely on the latest ECMAScript draft, which specifies that
`escape` returns hexadecimal codes in upper case.
=> Add tests for Annex B extns to global object

test/built-ins/TypedArray/prototype/map/return-new-typedarray-conversion-operation-consistent-nan.js
Because implementations are free to select any valid NaN value during
GetValueFromBuffer, tests concerning semantics for consistent NaN value
encoding cannot rely on values returned from that abstract operation.
Update the test for `%TypedArray%.prototype.map` to set the same NaN
values via `map` as set in the "control" array.
This problem was [originally reported](https://github.com/tc39/test262/pull/623#discussion_r63443319) by @littledan. Dan: what do you think of this approach?
=> Correct test for NaN canonicalization

tools/packaging/monkeyYaml.py, tools/packaging/test/test_monkeyYaml.py
We recently began using the `|` character as a delimiter for YAML blocks in test files. The content of these blocks can confuse the custom YAML parser, disrupting test runs.
[It looks like TC-39 has reached consensus](https://github.com/tc39/agendas/commit/a2fa5e1444552954c06e76d5cc6f120a5fd8d32c) on gh-647 ("Definitive decision for Test262 console runner"), but I'm not sure what that decision was.
In any case, the code is still in use, and this is a blocking bug (no pun intended--honest). The fix was simple enough; we can either merge it to `master` here, or allow consumers to apply the patch to their forks of the runner.
=> [runner] Add support for "folding" block delimiter

test/language/types/reference/get-value-prop-base-primitive.js, test/language/types/reference/put-value-prop-base-primitive.js
These are kind of fundamental, and I expect that we implicitly test their concerns in other tests (well, GetValue, anyway). I'm working on related tests for realms, and it will be good to have some symmetry.
> Occurs that when a PutValue or GetValue operation is applied to a
> property reference with a primitive base, the base is first coerced to
> an Object.
=> Add tests for object coercion of Reference base

test/built-ins/ArrayBuffer/init-zero.js, test/built-ins/TypedArrays/length-arg-init-zeros.js
Ensure that all bytes of newly-created Data Block are initialized to
zero.
Resolves gh-579.
=> Add tests for CreateByteDataBlock

test/built-ins/Object/internals/DefineOwnProperty/nan-equivalence.js
These semantics are currently contested, but the test reflects the
intended behavior of the latest version of the specification.
Depending on the result of the following discussion, this test may need to be updated: https://github.com/tc39/ecma262/pull/353
=> Add test for NaN in OrdinaryDefineOwnProperty

test/built-ins/Array/isArray/proxy-revoked.js, test/built-ins/Array/isArray/proxy.js, test/built-ins/Array/prototype/concat/create-proxy.js, test/built-ins/Array/prototype/concat/is-concat-spreadable-is-array-proxy-revoked.js, test/built-ins/Array/prototype/concat/is-concat-spreadable-proxy-revoked.js, test/built-ins/Array/prototype/concat/is-concat-spreadable-proxy.js, test/built-ins/Array/prototype/filter/create-proxy.js, test/built-ins/Array/prototype/map/create-proxy.js, test/built-ins/Array/prototype/slice/create-proxy.js, test/built-ins/Array/prototype/splice/create-proxy.js, test/built-ins/JSON/parse/revived-proxy-revoked.js, test/built-ins/JSON/parse/revived-proxy.js, test/built-ins/JSON/stringify/replacer-proxy-revoked.js, test/built-ins/JSON/stringify/replacer-proxy.js, test/built-ins/JSON/stringify/value-proxy-revoked.js, test/built-ins/JSON/stringify/value-proxy.js, test/built-ins/Object/prototype/toString/proxy-revoked.js, test/built-ins/Object/prototype/toString/proxy.js
Interestingly, SpiderMonkey fails just one of these specific cases. The
following code is expected to throw a TypeError, but does not in SpiderMonkey:
var h = Proxy.revocable({}, {});
h.revoke();
Object.prototype.toString.call(h.proxy);
=> Add tests for usage of IsArray

test/language/statements/class/subclass/class-definition-null-proto-contains-return-override.js, test/language/statements/class/subclass/class-definition-null-proto-super.js, test/language/statements/class/subclass/class-definition-null-proto-this.js, test/language/statements/class/subclass/class-definition-null-proto.js
The latest revision of ECMA262 makes special provisions for classes
which extend the `null` value [1]. Update the relevant tests
accordingly.
[1] https://github.com/tc39/ecma262/issues/543
@bterlson I believe this fully addresses gh-588. As far as I can tell, there
are two observable difference for that change in the spec:
- There is no requirement for the constructor to return a value (ES2016
required a return value in this case, and I've updated the relevant test)
- `this` may be referenced from within the constructor (ES2016 does not allow
such a reference, but we previously had no test for that)
SuperCall continues to be invalid for the same reason. Despite the fact that
there was no change to that behavior, I added a test for good measure.
I'm reasonably confident that there are no …
=> Update tests concerning null-extending classes

INTERPRETING.md
@bterlson @domenic @littledan @caridy @dherman Between my fumbling with ECMA262
references, my (mis)use of [eshost's current API](https://github.com/bterlson/eshost#runtime-library), and my negligence of [the Realms proposal](https://github.com/caridy/proposal-realms), I expect I have stepped on *all* of your toes, collectively.  I'm submitting this naive draft to serve as a concrete basis for discussion.
Background: I am currently writing tests for cross-realm semantics, and either @leobalter or I will soon be writing tests for cross-script semantics as well. I'd like to define an API to enable this, and my goals are (1) ease of implementation (to encourage consumers to actually run those new tests), and (2) harmony with the Realms proposal (to limit friction when/if that is …
=> Document host-defined realm/script API

INTERPRETING.md
These instructions were mistakenly omitted from the recent patches that extended
coverage of ECMAScript modules (gh-560, gh-561, gh-562, gh-563, and gh-565).
The text was drafted and subsequently revised through the discussion in gh-519.
=> Document requirements for module tests

test/built-ins/Function/StrictFunction_restricted-properties.js
According to ES2015, functions created using the FunctionDeclaration
syntax may define "own" properties named "caller" and "arguments" as
long as this is done using the AddRestrictedFunctionProperties abstract
operation.
Remove the assertions that prohibit this extension.
@caitp Does this look okay to you?
=> Relax test for forbidden extension

test/language/statements/for-of/iterator-next-error.js, test/language/statements/for-of/iterator-next-result-value-attr-error.js
A subtle aspect of the for-of iteration protocol concerns abrupt
completions that do *not* trigger iterator closing. Although this detail
is implicit in the current structure of the specification text, some
hosts may violate the protocol by closing the iterator because later steps
*do* specify that behavior.
The V8 engine is one such host--as of this writing, it incorrectly
closes the iterator when accessing the `value` property of the iterator
result produces an abrupt completion.
Add tests verifying that the iterator protocol is not violated in this
way for abrupt completions during the semantics of for-of evaluation.
(I discovered this while writing tests for the iteration protocol as specified
by Promise.all and Promise.race see gh-701; V8 fails a handful of tests there
for the same …
=> Add tests ensuring iterator is not closed

tools/packaging/packager.py
Since the argument is required, we mark it as so. Using this approach
gives the user a much nicer error message, as compared to just the "not
enough args" message.
=> Switch to non-positional argument.

test/annexB/language/comments/multi-line-html-close.js
The V8 engine incorrectly requires a leading newline character for
MultiLineComments which contain the optional trailing HTMLCloseComment
[1]. Extend the current tests to fail when such an invalid restriction
is in place.
[1] https://bugs.chromium.org/p/v8/issues/detail?id=5142
=> Extend test for HTML comments

test/language/eval-code/direct/new.target-arrow.js, test/language/eval-code/direct/new.target-fn.js, test/language/eval-code/direct/new.target.js, test/language/eval-code/indirect/new.target.js, test/language/expressions/call/with-base-obj.js, test/language/expressions/conditional/in-branch-1.js, test/language/expressions/conditional/in-branch-2.js, test/language/expressions/conditional/in-condition.js, test/language/expressions/delete/super-property.js, test/language/expressions/new.target/asi.js, test/language/expressions/new.target/value-via-call.js, test/language/expressions/new.target/value-via-fpapply.js, test/language/expressions/new.target/value-via-fpcall.js, test/language/expressions/new.target/value-via-member.js, test/language/expressions/new.target/value-via-new.js, test/language/expressions/new.target/value-via-reflect-apply.js, test/language/expressions/new.target/value-via-reflect-construct.js, test/language/expressions/new.target/value-via-super-call.js, test/language/expressions/new.target/value-via-super-property.js, test/language/expressions/new.target/value-via-tagged-template.js, test/language/expressions/object/cover-initialized-name.js, test/language/global-code/new.target-arrow.js, test/language/global-code/new.target.js
Add miscellaneous tests for previously-untested details as discovered in a
recent coverage audit.
=> Improve coverage for section 12, "Expression"

test/built-ins/String/length.js, test/built-ins/String/prototype/charAt/pos-coerce-err.js, test/built-ins/String/prototype/charAt/pos-coerce-string.js, test/built-ins/String/prototype/charAt/pos-rounding.js, test/built-ins/String/prototype/charAt/this-value-not-obj-coercible.js, test/built-ins/String/prototype/charCodeAt/pos-coerce-err.js, test/built-ins/String/prototype/charCodeAt/pos-coerce-string.js, test/built-ins/String/prototype/charCodeAt/pos-rounding.js, test/built-ins/String/prototype/charCodeAt/this-value-not-obj-coercible.js, test/built-ins/String/prototype/concat/this-value-not-obj-coercible.js, test/built-ins/String/prototype/indexOf/this-value-not-obj-coercible.js, test/built-ins/String/prototype/lastIndexOf/this-value-not-obj-coercible.js, test/built-ins/String/prototype/localeCompare/this-value-not-obj-coercible.js, test/built-ins/String/prototype/match/this-value-not-obj-coercible.js, test/built-ins/String/prototype/replace/this-value-not-obj-coercible.js, test/built-ins/String/prototype/search/this-value-not-obj-coercible.js, test/built-ins/String/prototype/slice/this-value-not-obj-coercible.js, test/built-ins/String/prototype/split/this-value-not-obj-coercible.js, test/built-ins/String/prototype/substring/this-value-not-obj-coercible.js, test/built-ins/String/prototype/toLocaleLowerCase/this-value-not-obj-coercible.js, test/built-ins/String/prototype/toLocaleUpperCase/this-value-not-obj-coercible.js, test/built-ins/String/prototype/toLowerCase/this-value-not-obj-coercible.js, test/built-ins/String/prototype/toUpperCase/this-value-not-obj-coercible.js
This changeset increases coverage for section 22, specifically "21.1 String
Objects".
=> Improve coverage for section 22: String

test/language/expressions/typeof/number.js
This is a pure miscellaneous change to use global values of NaN and Infinity instead of their namespaced equivalents.
Ref https://github.com/tc39/test262/pull/690/files/9ae0567a50b4367cf0c692da947ed3613e2e35c3#r69049894
cc @suwc
=> Use global values on typeof tests for Number values

test/language/statements/class/subclass/bound-function.js
The semantics under test have been incorrectly implemented by the SpiderMonkey engine.
=> Add test for subclassing bound functions

README.md
As a returning contributor, I see that the old test262.py runner is officially deprecated -- good!
But I don't know the "official" way to run the test suite, using my default installed node.
Here's a stab at adding that information to the front page README.md.  Please correct me if I'm wrong.
=> Add "how to run" on front page

test/built-ins/JSON/parse/reviver-array-define-prop-err.js, test/built-ins/JSON/parse/reviver-array-delete-err.js, test/built-ins/JSON/parse/reviver-array-length-coerce-err.js, test/built-ins/JSON/parse/reviver-array-length-get-err.js, test/built-ins/JSON/parse/reviver-call-err.js, test/built-ins/JSON/parse/reviver-get-name-err.js, test/built-ins/JSON/parse/reviver-object-define-prop-err.js, test/built-ins/JSON/parse/reviver-object-delete-err.js, test/built-ins/JSON/parse/reviver-object-own-keys-err.js
Due to the use of the IsArray abstract operation, observing many of the
targeted semantics requires the use of a Proxy exotic object. Mark the
tests that require this unrelated ES2015 feature using a dedicated
"features" flag.
=> Add tests for abrupt completions during JSON.parse

test/language/global-code/decl-func-dup.js, test/language/global-code/decl-func.js, test/language/global-code/decl-lex-configurable-global.js, test/language/global-code/decl-lex-deletion.js, test/language/global-code/decl-lex-restricted-global.js, test/language/global-code/decl-lex.js, test/language/global-code/decl-var.js, test/language/global-code/script-decl-func-dups.js, test/language/global-code/script-decl-func-err-non-configurable.js, test/language/global-code/script-decl-func-err-non-extensible.js, test/language/global-code/script-decl-func.js, test/language/global-code/script-decl-lex-deletion.js, test/language/global-code/script-decl-lex-lex.js, test/language/global-code/script-decl-lex-restricted-global.js, test/language/global-code/script-decl-lex-var.js, test/language/global-code/script-decl-lex.js, test/language/global-code/script-decl-var-collision.js, test/language/global-code/script-decl-var-err.js, test/language/global-code/script-decl-var.js
ECMA262 allows for an arbitrary number of "ScriptJob"s to run in a given realm.
Although there is no standard mechanism for enqueuing these jobs, many
implementations offer this functionality through custom APIs. In those hosts,
the semantics describing script interactions are directly observable.
In order to guarantee conformance to the specification in advance of a
standardized API, Test262 now requires that hosts provide a `$.evalScript`
function whose behavior is defined in the project's "INTERPRETING.md" file.
Use this host-provided API to ensure that implementations correctly observe the
specification text that dictates script interactions.
(In writing these tests, I noticed some gaps in coverage that are observable
from a single script execution. This patch includes a dedicated …
=> Add tests for script interactions

test/language/eval-code/direct/super-call-arrow.js, test/language/eval-code/direct/super-call-fn.js, test/language/eval-code/direct/super-call.js, test/language/eval-code/direct/super-prop-arrow.js, test/language/eval-code/direct/super-prop-method.js, test/language/eval-code/direct/super-prop.js, test/language/eval-code/indirect/super-call.js, test/language/eval-code/indirect/super-prop.js, test/language/global-code/return.js, test/language/global-code/super-call-arrow.js, test/language/global-code/super-call.js, test/language/global-code/super-prop-arrow.js, test/language/global-code/super-prop.js, test/language/global-code/yield-non-strict.js, test/language/global-code/yield-strict.js, test/language/module-code/parse-err-return.js, test/language/module-code/parse-err-yield.js
This changeset increases test coverage for the semantics defined in [ECMA262 section 15](https://tc39.github.io/ecma262/#sec-ecmascript-language-scripts-and-modules).
=> Improve coverage for section 15: Scripts and Modules

test/intl402/DateTimeFormat/prototype/formatToParts/date-is-infinity-throws.js, test/intl402/DateTimeFormat/prototype/formatToParts/date-is-nan-throws.js, test/intl402/DateTimeFormat/prototype/formatToParts/formatToParts.js, test/intl402/DateTimeFormat/prototype/formatToParts/length.js, test/intl402/DateTimeFormat/prototype/formatToParts/main.js, test/intl402/DateTimeFormat/prototype/formatToParts/name.js, test/intl402/DateTimeFormat/prototype/formatToParts/return-abrupt-tonumber-date.js, test/intl402/DateTimeFormat/prototype/formatToParts/this-has-not-internal-throws.js, test/intl402/DateTimeFormat/prototype/formatToParts/this-is-not-object-throws.js
This is a set of tests for https://github.com/tc39/ecma402/pull/64 which we'd like to land in the spec soon.
I'd like to get the test262 tests for this change ready to land as part of the getting the proposal to stage 4.
I'm not sure how much more testing is required since most of the feature is tested in `DateTimeFormat.prototype.format` tests, and this is just a different representation of the output.
I'd like to get the PR to be ready to land once we land the feature in the spec, so would like to get it reviewed now.
@leobalter, @jugglinmike - can you review this?
=> Add DateTimeFormat.prototype.formatToParts tests

test/language/expressions/arrow-function/params-trailing-comma-length.js, test/language/expressions/arrow-function/params-trailing-comma.js, test/language/expressions/call/trailing-comma.js, test/language/expressions/function/params-trailing-comma-arguments.js, test/language/expressions/function/params-trailing-comma-length.js, test/language/expressions/function/params-trailing-comma.js, test/language/expressions/generators/params-trailing-comma-arguments.js, test/language/expressions/generators/params-trailing-comma-length.js, test/language/expressions/generators/params-trailing-comma.js, test/language/expressions/object/method-definition/params-trailing-comma-arguments.js, test/language/expressions/object/method-definition/params-trailing-comma-length.js, test/language/expressions/object/method-definition/params-trailing-comma-rest.js, test/language/expressions/object/method-definition/params-trailing-comma.js, test/language/rest-parameters/params-trailing-comma-rest.js, test/language/statements/class/definition/params-trailing-comma-arguments.js, test/language/statements/class/definition/params-trailing-comma-length.js, test/language/statements/class/definition/params-trailing-comma-rest.js, test/language/statements/class/definition/params-trailing-comma.js, test/language/statements/function/params-trailing-comma-arguments.js, test/language/statements/function/params-trailing-comma-length.js, test/language/statements/function/params-trailing-comma.js, test/language/statements/generators/params-trailing-comma-length.js, test/language/statements/generators/params-trailing-comma.js
Adds tests for the proposal as described here:
http://jeffmo.github.io/es-trailing-function-commas/
cc @bterlson @ljharb
=> Tests for trailing commas in function arg lists

test/built-ins/Object/getOwnPropertyDescriptors/duplicate-keys.js, test/built-ins/Object/getOwnPropertyDescriptors/proxy-undefined-descriptor.js
Per https://github.com/tc39/ecma262/pull/593
**NOTE**: do not merge yet, until TC39 consensus is reached and the above PR is also merged.
=> `Object.getOwnPropertyDescriptors`: add test to ensure undefined descriptors are not added

test/language/module-code/namespace/internals/get-own-property-str-found-init.js
Fix language/module-code/namespace/internals/get-own-property-str-found-init.js.
=> Fix incorrect value retrieving in module-code test

test/language/expressions/object/computed-property-evaluation-order.js
This test is being added because the committee is considering changing this evaluation order (as discussed at the May 2016 Munich meeting). The consequences of this spec change will be more clear as a test change than a simple test addition.
/cc @leobalter
=> add PropertyDefinitionList evaluation order test

test/intl402/NumberFormat/prototype/formatToParts/formatToParts.js, test/intl402/NumberFormat/prototype/formatToParts/length.js, test/intl402/NumberFormat/prototype/formatToParts/main.js, test/intl402/NumberFormat/prototype/formatToParts/name.js, test/intl402/NumberFormat/prototype/formatToParts/return-abrupt-tonumber.js, test/intl402/NumberFormat/prototype/formatToParts/this-has-not-internal-throws.js, test/intl402/NumberFormat/prototype/formatToParts/this-is-not-object-throws.js
This is an updated pull request based on https://github.com/tc39/test262/pull/736 - I added relevant tests from DTF.prototype.formatToParts tests.
@leobalter - can you take a look and tell me if that's enough?
=> NumberFormat.prototype.formatToParts tests

test/intl402/Intl/getCanonicalLocales/returned-object-is-an-array.js, test/intl402/Intl/getCanonicalLocales/returned-object-is-mutable.js
=> Test that getCanonicalLocales() returns a mutable array.

test/built-ins/Number/prototype/toExponential/return-values.js
extra values to test (without them Number#toExponential looks fine in Firefox)
=> Update return-values.js (Number#toExponential bug in Firefox)

CONTRIBUTING.md
Unlike PHP, in JavaScript `!` has higher precedence than `instanceof`, thus `!smth instanceof TypeError` will never (unless `@@hasInstance` is defined) be `true`.
=> Fix operator precedence

test/built-ins/RegExp/prototype/Symbol.match/builtin-coerce-lastindex.js, test/built-ins/RegExp/prototype/Symbol.match/builtin-failure-g-set-lastindex-err.js, test/built-ins/RegExp/prototype/Symbol.match/builtin-failure-g-set-lastindex.js, test/built-ins/RegExp/prototype/Symbol.match/builtin-y-coerce-lastindex-err.js, test/built-ins/RegExp/prototype/Symbol.search/lastindex-no-restore.js, test/built-ins/RegExp/prototype/Symbol.search/set-lastindex-restore-err.js, test/built-ins/RegExp/prototype/Symbol.search/set-lastindex-restore.js, test/built-ins/RegExp/prototype/exec/failure-g-lastindex-reset.js, test/built-ins/RegExp/prototype/exec/failure-lastindex-no-access.js, test/built-ins/RegExp/prototype/exec/success-g-lastindex-no-access.js, test/built-ins/RegExp/prototype/exec/success-lastindex-no-access.js
Add and update tests for the lastIndex semantic change introduced in
https://github.com/tc39/ecma262/pull/627. See also tc39/test262#749.
=> Tests for new lastIndex semantics

test/language/expressions/tagged-template/invalid-escape-sequences.js, test/language/expressions/template-literal/invalid-hexidecimal-character-escape-sequence-truncated-1.js, test/language/expressions/template-literal/invalid-hexidecimal-character-escape-sequence-truncated-2.js, test/language/expressions/template-literal/invalid-hexidecimal-character-escape-sequence-truncated-3.js, test/language/expressions/template-literal/invalid-unicode-escape-sequence-1.js, test/language/expressions/template-literal/invalid-unicode-escape-sequence-2.js, test/language/expressions/template-literal/invalid-unicode-escape-sequence-3.js, test/language/expressions/template-literal/invalid-unicode-escape-sequence-4.js, test/language/expressions/template-literal/invalid-unicode-escape-sequence-5.js, test/language/expressions/template-literal/invalid-unicode-escape-sequence-6.js, test/language/expressions/template-literal/invalid-unicode-escape-sequence-7.js, test/language/expressions/template-literal/invalid-unicode-escape-sequence-8.js
Add tests for the template literal revision [proposal](https://github.com/tc39/proposal-template-literal-revision) (the proposal is currently at stage 3). The proposal allows tagged template literals to use previously disallowed escape sequences.
=> Add tests to handle revised template literals

test/language/literals/regexp/inequality.js
We already have [a single test](https://github.com/bakkot/test262/blob/master/test/language/literals/regexp/S7.8.5_A4.2.js) (that I could find) which tests that two identical regular expression literals create distinct objects, but we don't test that the same literal source, evaluated at different times, creates distinct objects.
=> Add test for inequality of RegExps created from the same source

test/language/expressions/call/trailing-comma.js, test/language/statements/class/definition/params-trailing-comma-arguments.js, test/language/statements/class/definition/params-trailing-comma.js
* Method declarations should not be followed by a comma.
* A comma after a spread parameter is actually allowed.
=> fix incorrect tests for trailing commas

test/language/statements/function/S13.2.2_A5_T1.js, test/language/statements/function/S13.2.2_A5_T2.js
The HTML spec requires browsers to define a non-configurable property of the global (window) object named "top". (See [attributes of the window object](https://html.spec.whatwg.org/multipage/browsers.html#the-window-object) and [the definition of "[Unforgeable]"](https://www.w3.org/TR/WebIDL/#Unforgeable).) This makes it impossible for a browser to successfully run a test in strict mode (as is [required](https://github.com/tc39/test262/blob/master/INTERPRETING.md#strict-mode)) if said test attempts to write to a global variable named "top".
This patch switches variable names around in two tests so that they don't try to do that. It also incidentally fixes an off-by-one error which was only not causing failure due to two variables having the same value, and modifies those variables to be …
=> Avoid writing to top-level vars named "top", for browser compat

harness/detachArrayBuffer.js
INTERRPETING.md [requires](https://github.com/tc39/test262/blob/master/INTERPRETING.md#host-defined-functions) hosts to expose a `$.detachArrayBuffer` method, but nothing is using it; relevant tests call `$DETACHBUFFER`, which unconditionally throws. This PR simply modifies that function to defer to `$.detachArrayBuffer`.
If hosts don't have a way to expose the relevant abstract operation, they can choose to define `$.detachArrayBuffer` such that it throws. We don't need to decided that for them.
(They could of course also just monkey-patch `$DETACHBUFFER`, but that goes against INTERRPETING.md. The less special knowledge required the better, I should think.)
ref #784; ping @leobalter and @bterlson in light of that discussion.
=> Use $.detachArrayBuffer API instead of throwing

README.md
Page is [here](https://bakkot.github.io/test262-web-runner/), source is [here](https://github.com/bakkot/test262-web-runner).
This project is incidentally the origin of my recent handful of fixes.
=> Add link to web-based runner

test/built-ins/Function/prototype/bind/15.3.4.5.1-4-14.js
Automatic Semicolon Insertion hides an error here by transforming a long
ReturnStatement into a ReturnStatement followed by an ExpressionStatement
that is never reached. The conditions on the second line are thus never
tested.
=> Add missing operator in test

test/built-ins/Function/prototype/toString/Function.js, test/built-ins/Function/prototype/toString/GeneratorFunction.js
This aligns the tests with this recent change to the F.p.toString proposal:
https://github.com/tc39/Function-prototype-toString-revision/commit/7432ded0e6c465fb53a95fddc7a08608401bd413
=> add line feeds following `{` of F.p.toString output for dynamic functions

test/intl402/Intl/getCanonicalLocales/main.js
Per discussion in #743, it's implementation-dependent how ismalicc is
canonicalized. However, 'islamic-umalqura' should be treated the same
way by all implementations.
=> Replace islamicc with islamic-umalqura in getCanonicalLocales/main.js (Intl402)

test/language/statements/class/constructor-inferred-observable-iteration.js, test/language/statements/class/subclass/class-definition-null-proto-missing-return-override.js, test/language/statements/class/subclass/class-definition-null-proto-super.js, test/language/statements/class/subclass/class-definition-null-proto-this.js, test/language/statements/class/subclass/class-definition-null-proto.js, test/language/statements/class/subclass/class-definition-parent-proto-null.js
This tests for the behavior being proposed in https://github.com/tc39/ecma262/pull/755.
Don't merge until we have consensus to merge that PR.
=> Add test for extending a constructor with null .prototype

test/language/statements/class/strict-mode/arguments-callee.js
I missed this in https://github.com/tc39/test262/pull/797.
I've checked more thoroughly now; I think this was the only one overlooked.
=> Remove last usage of arguments.caller

test/language/module-code/namespace/internals/set-prototype-of-null.js
The behavior changed from returning false to true in
https://github.com/tc39/ecma262/commit/13906140a
=> Add test for setting a module namespace object's prototype to null

test/language/module-code/namespace/Symbol.toStringTag.js, test/language/module-code/namespace/internals/get-own-property-sym.js
It [was changed](https://github.com/tc39/ecma262/pull/747) from configurable to non-configurable at the November 2016 meeting.
=> Mark namespace object toStringTag as non-configurable

test/language/statements/class/subclass/class-definition-null-proto-missing-return-override.js
The sameValue assertion should be that the [[Prototype]] is
equal to the class's prototype, not the constructor.
=> Fix test for instantiating a class extending null

test/intl402/NumberFormat/11.1.1_20_c.js
As per https://bugzilla.mozilla.org/show_bug.cgi?id=843758#c12
> 11.1.1_20_c.js expects BYR (Belarusian ruble) is still a valid currency code, but the latest currency update removed BYR (cf. ISO 4217 AMENDMENT NUMBER 161).
=> Remove BYR currency code which has been removed from ISO 4217

test/language/expressions/async-generators/early-errors-expression-NSPL-with-USD.js, test/language/expressions/async-generators/early-errors-expression-arguments-in-formal-parameters.js, test/language/expressions/async-generators/early-errors-expression-await-as-function-binding-identifier.js, test/language/expressions/async-generators/early-errors-expression-binding-identifier-arguments.js, test/language/expressions/async-generators/early-errors-expression-binding-identifier-eval.js, test/language/expressions/async-generators/early-errors-expression-body-contains-super-call.js, test/language/expressions/async-generators/early-errors-expression-body-contains-super-property.js, test/language/expressions/async-generators/early-errors-expression-eval-in-formal-parameters.js, test/language/expressions/async-generators/early-errors-expression-formals-body-duplicate-const.js, test/language/expressions/async-generators/early-errors-expression-formals-body-duplicate-let.js, test/language/expressions/async-generators/early-errors-expression-formals-contains-await-expr.js, test/language/expressions/async-generators/early-errors-expression-formals-contains-await.js, test/language/expressions/async-generators/early-errors-expression-formals-contains-super-call.js, test/language/expressions/async-generators/early-errors-expression-formals-contains-super-property.js, test/language/expressions/async-generators/early-errors-expression-formals-contains-yield-expr.js, test/language/expressions/async-generators/early-errors-expression-formals-contains-yield.js, test/language/expressions/async-generators/early-errors-expression-label-name-await.js, test/language/expressions/async-generators/early-errors-expression-label-name-yield.js, test/language/expressions/async-generators/early-errors-expression-not-simple-assignment-target.js, test/language/expressions/async-generators/early-errors-expression-yield-as-function-binding-identifier.js, test/language/expressions/async-generators/early-errors-expression-yield-star-after-newline.js, test/language/expressions/async-generators/expression-await-as-yield-operand.js, test/language/expressions/async-generators/expression-await-promise-as-yield-operand.js, test/language/expressions/async-generators/expression-await-thenable-as-yield-operand.js, test/language/expressions/async-generators/expression-yield-as-operand.js, test/language/expressions/async-generators/expression-yield-as-statement.js, test/language/expressions/async-generators/expression-yield-newline.js, test/language/expressions/async-generators/expression-yield-star-before-newline.js
WIP tests for https://github.com/tc39/proposal-async-iteration/issues/69
=> Add tests for async generator function expressions

test/intl402/6.2.2_b.js
This patch adds a regression test for a previous V8 bug reported originally at
https://bugs.chromium.org/p/v8/issues/detail?id=4215
=> Test for case-insensitivity in invalid BCP 47 usage

test/built-ins/Date/UTC/infinity-make-day.js, test/built-ins/Date/UTC/nans.js, test/built-ins/Date/UTC/no-arg.js, test/built-ins/Date/UTC/return-value.js
Are these actually necessary? I'm tempted to add them just to be able to change them in the future (new default for month).
@bterlson
=> Add tests for non-optional arguments of Date.UTC()

test/built-ins/SharedArrayBuffer/prototype/slice/context-is-not-arraybuffer-object.js
This section is useless (and also trips up the YAML parser V8 uses)
cc @binji @syg
=> Remove empty info section from a SharedArrayBuffer test

test/built-ins/RegExp/prototype/exec/failure-lastindex-access.js, test/built-ins/RegExp/prototype/exec/success-lastindex-access.js
Spec change at https://github.com/tc39/ecma262/pull/798
Tested on V8's implementation of the new semantics.
cc @schuay @bterlson @anba @claudepache
=> Update RegExp tests for the semantics change

test/built-ins/Object/internals/DefineOwnProperty/consistent-value-function-arguments.js, test/built-ins/Object/internals/DefineOwnProperty/consistent-value-function-caller.js, test/built-ins/Object/internals/DefineOwnProperty/consistent-value-regexp-$1.js, test/built-ins/Object/internals/DefineOwnProperty/consistent-writable-regexp-$1.js
Subsumes #653 (issue with copyright/licence).
Resolves #649.
Also, add a test against a observed bug in Chakra: RegExp.$1 claims to successfully become non-writable, non-configurable, but remains writable.
=> Add tests for known violation of invariants v2

test/built-ins/TypedArray/prototype/copyWithin/negative-out-of-bounds-end.js, test/built-ins/TypedArray/prototype/copyWithin/negative-out-of-bounds-start.js, test/built-ins/TypedArray/prototype/set/typedarray-arg-set-values-diff-buffer-other-type-sab.js, test/intl402/DateTimeFormat/12.1.1_1.js, test/intl402/DateTimeFormat/prototype/format/12.3.2_1_a_L15.js, test/intl402/NumberFormat/11.1.1_1.js, test/language/expressions/object/method-definition/async-super-call-body.js, test/language/expressions/object/method-definition/async-super-call-param.js, test/language/statements/class/subclass/builtin-objects/Promise/regular-subclassing.js, test/language/statements/class/subclass/class-definition-null-proto-contains-return-override.js, test/language/statements/class/subclass/class-definition-null-proto-missing-return-override.js, test/language/statements/class/subclass/class-definition-null-proto-super.js, test/language/statements/class/subclass/class-definition-null-proto-this.js, test/language/statements/class/subclass/class-definition-null-proto.js
The main changes are for tc39/ecma262#781 and tc39/ecma402#84, plus some other small bug fixes. 
tc39/ecma402#84 also needs new tests, but I'd like to fix the failing tests first.
=> Change tests for `extends null` and Intl legacy constructor semantics

test/built-ins/RegExp/prototype/Symbol.split/str-adv-thru-empty-match.js, test/built-ins/RegExp/prototype/Symbol.split/u-lastindex-adv-thru-match.js, test/intl402/PluralRules/prototype/select/non-finite.js, test/intl402/PluralRules/prototype/select/tainting.js, test/language/module-code/instn-named-bndng-dflt-expr.js, test/language/module-code/instn-star-ambiguous.js, test/language/module-code/instn-star-props-circular.js, test/language/module-code/instn-star-props-dflt-keep-indirect.js, test/language/module-code/instn-star-props-dflt-keep-local.js, test/language/module-code/instn-star-props-dflt-skip.js, test/language/statements/for-of/array-contract.js, test/language/statements/if/cptn-else-false-abrupt-empty.js, test/language/statements/with/labelled-fn-stmt.js
MonkeyYaml can't parse the YAML meta data when the mapping value is written in the next line without either `>` or `|`.
=> Update YAML frontmatter of some tests to be compatible with monkeyYaml

test/intl402/NumberFormat/default-minimum-singificant-digits.js
Adds a test for NumberFormat default minimumSignificantDigits.
This originates from the V8 bugfix https://bugs.chromium.org/p/v8/issues/detail?id=5554.
=> NumberFormat default minimumSignificantDigits

test/language/module-code/instn-iee-star-cycle-indirect-x_FIXTURE.js, test/language/module-code/instn-iee-star-cycle.js, test/language/module-code/instn-named-star-cycle-indirect-x_FIXTURE.js, test/language/module-code/instn-named-star-cycle.js, test/language/module-code/instn-star-star-cycle-indirect-x_FIXTURE.js, test/language/module-code/instn-star-star-cycle.js
Cyclic dependencies are no longer an error per https://github.com/tc39/ecma262/pull/783.
=> Update tests for cyclic module dependencies through export*

harness/testAtomics.js
These test changes pertain to the spec change in https://github.com/tc39/ecma262/issues/807.
=> Account for the use of ToIndex in Atomic operations

test/language/global-code/decl-lex-restricted-global.js
The error occurs in [GlobalDeclarationInstantiation](https://tc39.github.io/ecma262/#sec-globaldeclarationinstantiation), which is runtime semantics.
INTERPRETING.md is kind of unclear on what phase GlobalDeclarationInstantiation corresponds to, so I'm not entirely sure if this change is correct.
Ping @jugglinmike
=> Top-level `let undefined` is a runtime error, not an early error.

test/language/expressions/async-generators/return-suspendedStart-promise.js, test/language/expressions/async-generators/return-suspendedStart.js, test/language/expressions/async-generators/return-suspendedYield-promise.js, test/language/expressions/async-generators/return-suspendedYield-try-finally-return.js, test/language/expressions/async-generators/return-suspendedYield-try-finally-throw.js, test/language/expressions/async-generators/return-suspendedYield-try-finally.js, test/language/expressions/async-generators/return-suspendedYield.js, test/language/expressions/async-generators/throw-suspendedStart-promise.js, test/language/expressions/async-generators/throw-suspendedStart.js, test/language/expressions/async-generators/throw-suspendedYield-promise.js, test/language/expressions/async-generators/throw-suspendedYield-try-catch.js, test/language/expressions/async-generators/throw-suspendedYield-try-finally-return.js, test/language/expressions/async-generators/throw-suspendedYield-try-finally-throw.js, test/language/expressions/async-generators/throw-suspendedYield-try-finally.js, test/language/expressions/async-generators/throw-suspendedYield.js
Here's a starter suite of tests for basic flow control in Async Generators.
This relates primarily to the behaviour of AsyncGeneratorResumeNext, AsyncGeneratorStart, AsyncGeneratorResolve and AsyncGeneratorReject, as well as some coverage of changes to GeneratorYield.
There is stuff missing, as I haven't exhaustively written tests for all of the variations that are necessary.
=> Async Generator flow control tests

src/accessor-names/literal-string-line-continuation.case, test/language/expressions/class/accessor-name-inst-literal-string-line-continuation.js, test/language/expressions/class/accessor-name-static-literal-string-line-continuation.js, test/language/expressions/object/accessor-name-literal-string-line-continuation.js, test/language/statements/class/accessor-name-inst-literal-string-line-continuation.js, test/language/statements/class/accessor-name-static-literal-string-line-continuation.js, tools/generation/lib/template.py, tools/generation/test/expected/indentation/spaces-indent-code.js, tools/generation/test/expected/indentation/spaces-indent-string-continuation.js, tools/generation/test/expected/indentation/spaces-indent-string-template.js, tools/generation/test/expected/indentation/tabs-indent-code.js, tools/generation/test/expected/indentation/tabs-indent-string-continuation.js, tools/generation/test/expected/indentation/tabs-indent-string-template.js, tools/generation/test/fixtures/indent-code.case, tools/generation/test/fixtures/indent-string-continuation.case, tools/generation/test/fixtures/indent-string-template.case, tools/generation/test/fixtures/indentation/spaces.template, tools/generation/test/fixtures/indentation/tabs.template, tools/generation/test/run.py
The test generation tool exhibited a bug that made it unable to produce valid
tests in some situations. I discovered this while working on a patch recently
and decided to manually duplicate tests as a short-term workaround. This patch
corrects the bug in the tool and re-formats those manually-duplicated tests to
a procedurally-generated form.
=> Extend test generation tool

src/annex-b-fns/func-skip-dft-param.case, test/annexB/language/function-code/block-decl-func-skip-dft-param.js, test/annexB/language/function-code/if-decl-else-decl-a-func-skip-dft-param.js, test/annexB/language/function-code/if-decl-else-decl-b-func-skip-dft-param.js, test/annexB/language/function-code/if-decl-else-stmt-func-skip-dft-param.js, test/annexB/language/function-code/if-decl-no-else-func-skip-dft-param.js, test/annexB/language/function-code/if-stmt-else-decl-func-skip-dft-param.js, test/annexB/language/function-code/switch-case-func-skip-dft-param.js, test/annexB/language/function-code/switch-dflt-func-skip-dft-param.js
Closes gh-860
cc @syg @jugglinmike 
This is my first try to fix #860 using the test generation tool.
As you can see in [the new code](https://github.com/tc39/test262/compare/master...leobalter:860-block-dft-params?expand=1#diff-44c8f167f3b6d4d7f5e745fa3727baaf), I used both the previous copyright from V8 and included an extra line for Mozilla for the new change.
I'm not sure this is the best way to handle this case (wrt copyrights) but I'm willing to fix it if necessary.
=> Test for parameters with default expressions in Annex B FiB tests

src/spread/mult-err-obj-getter-throws.case, src/spread/mult-err-obj-unresolvable.case, src/spread/mult-obj-base.case, src/spread/mult-obj-empty.case, src/spread/mult-obj-ident.case, src/spread/mult-obj-null-empty-undefined.case, src/spread/mult-obj-null.case, src/spread/mult-obj-undefined.case, src/spread/obj-getter-descriptor.case, src/spread/obj-getter-init.case, src/spread/obj-manipulate-outter-obj-in-getter.case, src/spread/obj-mult-spread-getter.case, src/spread/obj-mult-spread.case, src/spread/obj-null.case, src/spread/obj-override-immutable.case, src/spread/obj-overrides-prev-properties.case, src/spread/obj-setter-redef.case, src/spread/obj-skip-non-enumerable.case, src/spread/obj-spread-order.case, src/spread/obj-symbol-property.case, src/spread/obj-undefined.case, src/spread/obj-with-overrides.case, src/spread/sngl-err-obj-getter-throws.case, src/spread/sngl-err-obj-unresolvable.case, src/spread/sngl-obj-base.case, src/spread/sngl-obj-empty.case, src/spread/sngl-obj-ident.case
This is an initial set of tests for Object Spread proposal. It is fixing #865.
To run these tests it is necessary generate them using ```make.py``` script. I tested them using the following command:
```test262-harness --hostPath=`which d8` --hostType=d8 --hostArgs="--harmony_object_rest_spread"```
=> Initial set for Object Spread feature

test/annexB/built-ins/Object/prototype/__proto__/set-non-object.js
Fixes #887
Stolen from the sibling file `set-invalid-value.js`.
=> Add missing test cases for set __proto__

harness/propertyHelper.js
Ref https://github.com/tc39/test262/pull/879#discussion_r104128520
cc @anba 
For the piece of mind, I'm comparing tests results using a new compiled version of d8.
```
test262-harness --hostPath=`which d8` --hostType=d8 $(git grep --name-only --extended-regexp 'verify(Not)?Enumerable' test/built-ins)
```
=> Improve isEnumerable check with a for-in loop for string names

src/dstr-assignment/array-rest-nested-obj-undefined-hole.case, src/dstr-assignment/array-rest-nested-obj-undefined-own.case, src/dstr-assignment/array-rest-nested-obj-undefined.case, test/annexB/built-ins/String/prototype/substr/length-to-int-err.js, test/annexB/built-ins/String/prototype/substr/start-to-int-err.js, test/built-ins/Array/of/construct-this-with-the-number-of-arguments.js, test/built-ins/DataView/return-abrupt-tonumber-bytelength-symbol-sab.js, test/built-ins/DataView/return-abrupt-tonumber-bytelength-symbol.js, test/built-ins/Function/S15.3_A3_T2.js, test/built-ins/Object/internals/DefineOwnProperty/nan-equivalence.js, test/built-ins/TypedArrays/buffer-arg-length-access-throws-sab.js, test/built-ins/TypedArrays/buffer-arg-length-access-throws.js, test/built-ins/TypedArrays/buffer-arg-length-is-symbol-throws-sab.js, test/built-ins/TypedArrays/buffer-arg-length-is-symbol-throws.js, test/built-ins/TypedArrays/typedarray-arg-returns-new-instance.js, test/language/expressions/assignment/dstr-array-rest-nested-obj-undefined-hole.js, test/language/expressions/assignment/dstr-array-rest-nested-obj-undefined-own.js, test/language/expressions/assignment/dstr-array-rest-nested-obj-undefined.js, test/language/expressions/call/scope-lex-open.js, test/language/expressions/call/scope-var-open.js, test/language/expressions/object/method-definition/generator-name-prop-symbol.js, test/language/expressions/object/method-definition/name-name-prop-symbol.js, test/language/statements/for-of/dstr-array-rest-nested-obj-undefined-hole.js, test/language/statements/for-of/dstr-array-rest-nested-obj-undefined-own.js, test/language/statements/for-of/dstr-array-rest-nested-obj-undefined.js
Closes #850 
cc @syg, this is the best I could do to fix. We need to add this as soon as we have some code style document (#297)
=> Avoid top level name and length bindings

test/built-ins/TypedArray/prototype/fill/fill-values-conversion-once.js
The change is proposed in https://github.com/tc39/ecma262/pull/856
as a fix to https://github.com/tc39/ecma262/issues/855
Here, the ToNumber coercion is done only once, rather than on each
iteration. It does not appear that there were previously any
tests against repeated coercion for this parameter previously.
Tested this test against V8, which failed, as V8 implements the
current spec rather than the proposed one.
=> Test for TypedArray.prototype.fill semantics change

test/built-ins/RegExp/prototype/Symbol.replace/subst-capture-idx-1.js, test/built-ins/RegExp/prototype/Symbol.replace/subst-capture-idx-2.js
In https://github.com/tc39/ecma262/pull/853 , standard semantics
for this case are proposed. This patch tests the case.
This test was tested in V8 and passed there. The test should not
be merged until TC39 comes to agreement about the semantics change.
=> Tests for RegExp capture substitution out of bounds

test/annexB/built-ins/escape/escape-above-astral.js
This is more of an integration test because the semantics should be that the extended unicode escape is encoded in the string as two UTF-16 code units (surrogate pairs) which are then correctly decoded and escaped.
See also (should I include these in the test file itself in addition to the reference on escape?)
https://tc39.github.io/ecma262/#sec-static-semantics-sv
>The SV of UnicodeEscapeSequence::u{HexDigits} is the UTF16Encoding of the MV of HexDigits.
https://tc39.github.io/ecma262/#sec-utf16encoding
=> Add escape-above-astral.js to cover escaping code units as encoded from extended unicode escape.

test/built-ins/Number/prototype/toFixed/exactness.js
This test comes from a note in the specification under toFixed.
It fails in ChakraCore and passes in other engines that I tested.
=> Test for the difference between toFixed and toString

test/built-ins/TypedArray/prototype/set/typedarray-arg-src-byteoffset-internal.js, test/built-ins/TypedArray/prototype/set/typedarray-arg-target-byteoffset-internal.js
Tests for checking byteOffset usage in TypedArray.prototype.set. It was violated by V8
(https://crbug.com/v8/6120).
=> Tests for using internal byteOffset in TypedArray.prototype.set

test/built-ins/TypedArrays/buffer-arg-byteoffset-to-number-detachbuffer.js
Bug was reported by @anba at
https://github.com/tc39/ecma262/pull/852#issuecomment-291781031
Without this change, you'd expect a RangeError rather than a TypeError.
=> Fix offset for detached TypedArray test

test/built-ins/Function/prototype/bind/15.3.4.5-15-5.js
The `length` property should be [[Configurable]]
https://tc39.github.io/ecma262/#sec-function.prototype.bind
Also the test was testing deleting the wrong property.
Fixes #957.
=> Correct test/built-ins/Function/prototype/bind/15.3.4.5-15-5.js

.editorconfig, harness/Date_constants.js, harness/PromiseHelper.js, harness/arrayContains.js, harness/assert.js, harness/cth.js, harness/doneprintHandle.js, harness/fnGlobalObject.js, harness/propertyHelper.js, harness/proxyTrapsHelper.js, harness/simdUtilities.js, harness/sta.js, harness/testAtomics.js, harness/testBuiltInObject.js, harness/testIntl.js, harness/timer.js, tools/CoverageAnalyzer.py
Many different coding styles are being used across the various non-test files in this repository.
* For Python files, four-space indentation (per PEP 8) seemed to be the most common. However, some files were using two-space. I’ve changed them to use four spaces and codified this preference in `.editorconfig`.
* For JavaScript files, most of the tests, as well as most non-test files seemed to be using two-space indents. However, some files were using four-space indents, five-space indents (!), and a single file was using tabs. I’ve changed them to use two spaces and codified this preference in `.editorconfig`.
While going through the files, I noticed something odd. The indentation seems to imply that a brace is missing here: https://github.com/tc39/test262/blob/96aa8c77b33ef734d486fece1cf00 …
=> Unify indentation and add .editorconfig

harness/propertyHelper.js, test/harness/assert-throws-incorrect-ctor.js, test/harness/verifyProperty-arguments.js, test/harness/verifyProperty-desc-is-not-object.js, test/harness/verifyProperty-noproperty.js, test/harness/verifyProperty-restore-accessor-symbol.js, test/harness/verifyProperty-restore-accessor.js, test/harness/verifyProperty-restore-symbol.js, test/harness/verifyProperty-restore.js, test/harness/verifyProperty-string-prop.js, test/harness/verifyProperty-symbol-prop.js, test/harness/verifyProperty-undefined-desc.js
signature:
```js
verifyProperty(
Object obj,
String|Symbol name,
Object|undefined {
Boolean writable,
Boolean configurable,
Boolean enumerable
},
Object { Boolean restore }
);
```
You can set an expliecit `restore` option if you need to reuse the same property, works well for accessor descriptors too.
I've had to add a monkey patch to `$ERROR` in tests asserting negative effects, it is ugly, but it works.
cc @littledan;
=> Add Verify Property harness

.travis.yml
Installing dependencies using this file increases parity between the CI
and development environment. Because the file explicitly specifies a
version of the package to be installed, this approach also produces more
predictable results overall.
=> Reference `requirements.txt` file in CI

INTERPRETING.md
Everything is pointing to the latest draft avoiding 404s in the year-specified links
=> Update links to the specs

test/annexB/built-ins/RegExp/prototype/flags/order-after-compile.js, test/built-ins/RegExp/named-groups/lookbehind.js, test/built-ins/RegExp/named-groups/non-unicode-malformed.js, test/built-ins/RegExp/named-groups/non-unicode-match.js, test/built-ins/RegExp/named-groups/non-unicode-property-names.js, test/built-ins/RegExp/named-groups/non-unicode-references.js, test/built-ins/RegExp/named-groups/string-replace-nocaptures.js, test/built-ins/RegExp/named-groups/unicode-malformed.js, test/built-ins/RegExp/named-groups/unicode-match.js, test/built-ins/RegExp/named-groups/unicode-property-names.js
Ref #1008 
It does not address the `\k` parts as it's still being discussed there.
=> Update RegExp tests for named-capturing and dotAll

CONTRIBUTING.md, harness/assert.js, test/harness/assert-throws-early-incorrect-ctor.js, test/harness/assert-throws-early-not-early.js, test/harness/assert-throws-early-referenceerror.js, test/harness/assert-throws-early-syntaxerror.js, test/language/expressions/object/prop-def-invalid-async-prefix.js
I've been working over [an original patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1358246) from @anba to the SpiderMonkey tests suite, while I was trying to find a good way to port them here.
This approach is simple, fast, and allows a quick porting. 
The alternative is migrating each case to an individual file with the negative flag.
There are some trade offs for each option. The negative flag allows the purest form to verify an early error, nothing can beat it being the minimal unit part to assert.
In the meanwhile, this assert.throws.early api allows not only a quick port, but verifying the code being parsed internally as in `Function()`, `eval()`, and an indirect eval call.
I'm not silver into any of these forms, my preference is whatever communicates better with those …
=> Add early error cases for `async async` in property definitions

test/language/statements/async-function/cptn-decl.js, test/language/statements/class/cptn-decl.js, test/language/statements/function/cptn-decl.js, test/language/statements/generators/cptn-decl.js
Check completion value of more declarations are empty:
```js
eval(`1; function f(){}`) === 1
eval(`1; function* f(){}`) === 1
eval(`1; async function f(){}`) === 1
eval(`1; class C {}`) === 1
```
Browsers:
* Firefox passes all
* Chrome fails for `class` - [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=716715)
* WebKit fails for `class` - [bug](https://bugs.webkit.org/show_bug.cgi?id=171265)
* Edge fails for `class` - [bug](https://github.com/Microsoft/ChakraCore/issues/2890)
=> Add tests for completion value of function / class declaration statements

test/built-ins/Array/prototype/pop/clamps-to-integer-limit.js, test/built-ins/Array/prototype/pop/length-near-integer-limit.js, test/built-ins/Array/prototype/push/clamps-to-integer-limit.js, test/built-ins/Array/prototype/push/length-near-integer-limit.js, test/built-ins/Array/prototype/push/throws-if-integer-limit-exceeded.js, test/built-ins/Array/prototype/reverse/length-exceeding-integer-limit-with-object.js, test/built-ins/Array/prototype/reverse/length-exceeding-integer-limit-with-proxy.js, test/built-ins/Array/prototype/slice/create-proxied-array-invalid-len.js, test/built-ins/Array/prototype/slice/length-exceeding-integer-limit-proxied-array.js, test/built-ins/Array/prototype/slice/length-exceeding-integer-limit.js, test/built-ins/Array/prototype/splice/clamps-length-to-integer-limit.js, test/built-ins/Array/prototype/splice/create-species-length-exceeding-integer-limit.js, test/built-ins/Array/prototype/splice/length-and-deleteCount-exceeding-integer-limit.js, test/built-ins/Array/prototype/splice/length-exceeding-integer-limit-shrink-array.js, test/built-ins/Array/prototype/splice/length-near-integer-limit-grow-array.js, test/built-ins/Array/prototype/splice/throws-if-integer-limit-exceeded.js, test/built-ins/Array/prototype/unshift/clamps-to-integer-limit.js, test/built-ins/Array/prototype/unshift/length-near-integer-limit.js, test/built-ins/Array/prototype/unshift/throws-if-integer-limit-exceeded.js
New tests when Array.prototype methods are called with array-like objects whose length property is near or exceeds the safe integer limit 2<sup>53</sup>-1.
And I've renamed slice/create-species-undef-invalid-len.js to slice/create-proxied-array-invalid-len.js and updated its description to reflect the actual test behaviour.
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=924058
=> Add tests for Array.prototype methods when length property exceeds or is near integer limit

test/built-ins/Promise/reject-via-abrupt-queue.js, test/built-ins/Promise/reject-via-fn-deferred-queue.js, test/built-ins/Promise/reject-via-fn-immed-queue.js
These basic tests assert the rejection is captured but a later queued job
from a chain of then calls.
=> Add tests for Promises rejection queue

test/built-ins/RegExp/property-escapes/character-class.js
Thanks to @anba for spotting this: https://github.com/tc39/test262/pull/1014/files/4843f049fafb6cdd61e3be011e3701cc94a9fe46#r116528031
=> Fix test involving a Unicode property escape in a character class range

lint.whitelist
The referenced "AUTHORS" file was removed in https://github.com/tc39/test262/pull/1032.
=> Update lint "whitelist" file and document usage

test/built-ins/Array/prototype/sort/comparefn-nonfunction-call-throws.js, test/built-ins/TypedArray/prototype/sort/comparefn-nonfunction-call-throws.js
Per TC39 consensus on  https://github.com/tc39/ecma262/pull/785/
=> {Array,%TypedArray%}.prototype.sort should throw on a non-undefined non-function

src/dstr-assignment/obj-rest-computed-property.case, test/language/expressions/assignment/dstr-obj-rest-computed-property.js, test/language/statements/for-of/dstr-obj-rest-computed-property.js
I'm adding a missing case using computed properties.
It closes #1035.
=> Adding case to computed property

CONTRIBUTING.md
Per offline discussion with @ajklein today
=> CONTRIBUTING.md: Adds 'Source Material' section with 'needs tests' PR list

test/built-ins/Number/prototype/toExponential/range.js, test/built-ins/Number/prototype/toFixed/range.js, test/built-ins/Number/prototype/toPrecision/range.js
These tests are against the needs-consensus pull request at
https://github.com/tc39/ecma262/pull/857
=> Add tests for Number printing precision ranges

test/language/literals/string/legacy-non-octal-escape-sequence-strict.js
=> Add test that noctal escapes are forbidden in strings in strict code

test/built-ins/Date/prototype/toDateString/format.js, test/built-ins/Date/prototype/toDateString/invalid-date.js, test/built-ins/Date/prototype/toString/format.js, test/built-ins/Date/prototype/toTimeString/format.js, test/built-ins/Date/prototype/toTimeString/invalid-date.js, test/built-ins/Date/prototype/toUTCString/day-names.js, test/built-ins/Date/prototype/toUTCString/format.js, test/built-ins/Date/prototype/toUTCString/invalid-date.js, test/built-ins/Date/prototype/toUTCString/month-names.js
These tests check the semantics of Date.prototype.toString, Date.prototype.toTimeString,
Date.prototype.toDateString and Date.prototype.toUTCString. There are probably ways
to make the more specific, but this is a start. The semantics are currently implementation-defined,
but a spec pull request at https://github.com/tc39/ecma262/pull/848 gives them this behavior.
=> Date toString tests

test/built-ins/Symbol/length.js, test/built-ins/Symbol/name.js, test/built-ins/Symbol/symbol.js
Older V8s used to have wrong `Symbol.length` [bug tracker](https://bugs.chromium.org/p/v8/issues/detail?id=4882)
=> Add basic Symbol constructor tests

test/annexB/built-ins/RegExp/RegExp-control-escape-russian-letter.js
In order to get https://github.com/tc39/test262/pull/945 resolved, I discarded @leobalter's minor assertion API migration changes. This patch restores the semantics intended by @leobalter's original patch. 
@littledan might want to reword the messages... 
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>
=> Restore migration to assert.sameValue

test/built-ins/Number/prototype/toExponential/range.js, test/built-ins/Number/prototype/toFixed/range.js
toExponential had a typo, and toFixed was against an earlier version
of the specification proposal. The tests pass against a version of V8
which attempts to implement the new spec.
=> Fix tests for toFixed and toExponential

test/built-ins/Array/prototype/sort/comparefn-nonfunction-call-throws.js
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>
=> Adding Symbol to Array.prototype.sort "throws on a non-undefined non-function"

CONTRIBUTING.md
For an upcoming project, we need esid to consistently exist in the front matter. It can be set as `pending` for tests that do not have specs published on the site yet.
=> update contributing.md to make esid a required tag for new feature tests

test/built-ins/Date/prototype/toString/invalid-date.js, test/built-ins/Date/prototype/toString/non-date-receiver.js
Pending discussion of https://github.com/tc39/ecma262/issues/849. Not ready to merge yet!
Test passes in V8.
=> Test that Date.prototype.toString throws for non-Date receiver

test/built-ins/AsyncFunction/AsyncFunction-construct.js, test/built-ins/AsyncFunction/AsyncFunction-is-subclass.js, test/built-ins/AsyncFunction/AsyncFunction-length.js, test/built-ins/AsyncFunction/AsyncFunction-name.js, test/built-ins/AsyncFunction/AsyncFunction-prototype.js, test/built-ins/AsyncFunction/AsyncFunction.js, test/built-ins/AsyncFunction/AsyncFunctionPrototype-is-extensible.js, test/built-ins/AsyncFunction/AsyncFunctionPrototype-prototype.js, test/built-ins/AsyncFunction/AsyncFunctionPrototype-to-string.js, test/built-ins/AsyncFunction/instance-construct-throws.js, test/built-ins/AsyncFunction/instance-has-name.js, test/built-ins/AsyncFunction/instance-length.js, test/built-ins/AsyncFunction/instance-prototype-property.js, test/built-ins/AsyncFunction/is-not-a-global.js
@leobalter @rwaldron 
This is a case of where there was a "pending" esid that needed to be updated.  I tried to match as best I could to the docs. The only thing I couldn't match very well was for the test: "is not a global"
=> update pending esids in AsyncFunction tests

lint.whitelist, test/language/directive-prologue/10.1.1-2gs.js, test/language/directive-prologue/10.1.1-5gs.js, test/language/directive-prologue/10.1.1-8gs.js, test/language/directive-prologue/14.1-4gs.js, test/language/directive-prologue/14.1-5gs.js
This is intended to resolve gh-1085. I've manually verified the appropriateness
of the new `throw` statement for all "early error" tests that include a "use
strict" directive, as identified by the following UNIX command:
$ grep -E 'phase:\s*early' src/ test/ -rl --null | xargs -0 grep 'use strict' -l
test/language/directive-prologue/10.1.1-5gs.js
test/language/directive-prologue/10.1.1-2gs.js
test/language/directive-prologue/10.1.1-8gs.js
test/language/directive-prologue/14.1-5gs.js
test/language/directive-prologue/14.1-4gs.js
test/language/expressions/arrow-function/syntax/early-errors/use-strict-with-non-simple-param.js
test/language/expressions/object/method-definition/early-errors-object-method-NSPL-with-USD.js
test/language/expressions/object/method-definition/use-strict-with-non-simp …
=> Correct tests for strict mode early errors

test/language/module-code/namespace/internals/define-own-property.js
See https://github.com/tc39/ecma262/pull/858.
=> Relax [[DefineOwnProperty]] on module namespace exotic objects.

.gitignore, .npmrc, features.txt, test/built-ins/Promise/prototype/finally/invokes-then-with-function.js, test/built-ins/Promise/prototype/finally/invokes-then-with-non-function.js, test/built-ins/Promise/prototype/finally/is-a-function.js, test/built-ins/Promise/prototype/finally/is-a-method.js, test/built-ins/Promise/prototype/finally/length.js, test/built-ins/Promise/prototype/finally/name.js, test/built-ins/Promise/prototype/finally/prop-desc.js, test/built-ins/Promise/prototype/finally/rejected-observable-then-calls.js, test/built-ins/Promise/prototype/finally/rejection-reason-no-fulfill.js, test/built-ins/Promise/prototype/finally/rejection-reason-override-with-throw.js, test/built-ins/Promise/prototype/finally/resolution-value-no-override.js, test/built-ins/Promise/prototype/finally/resolved-observable-then-calls.js, test/built-ins/Promise/prototype/finally/this-value-non-object.js, test/built-ins/Promise/prototype/finally/this-value-then-not-callable.js, test/built-ins/Promise/prototype/finally/this-value-then-poisoned.js, test/built-ins/Promise/prototype/finally/this-value-then-throws.js
(The first two commits can and should be cherry-picked in separately; i'll rebase this PR ASAP if that happens)
`Promise.prototype.finally` reached stage 3 today at TC39; here's my first crack at the tests.
See https://github.com/tc39/proposal-promise-finally/issues/18, https://tc39.github.io/proposal-promise-finally/, and https://github.com/es-shims/Promise.prototype.finally/blob/master/test/tests.js for more info.
=> Promise.prototype.finally: add tests

test/language/literals/bigint/mv-is-not-integer-dil-dot-dds.js, test/language/literals/bigint/mv-is-not-integer-dot-dds.js
I also have tests on hold for valid literals but I want to wait until a final decision for https://github.com/tc39/proposal-bigint/issues/77 before releasing them.
cc @littledan (this is an easy one to review)
=> Add tests for invalid BigInt MVs

src/async-generators/yield-promise-reject-next-yield-star-async-iterator.case, src/dstr-assignment-for-await/array-elem-iter-rtrn-close-null.case, src/dstr-assignment-for-await/array-elem-put-const.case, src/dstr-assignment-for-await/array-elem-trlg-iter-elision-iter-nrml-close-null.case, src/dstr-assignment-for-await/array-elem-trlg-iter-rest-nrml-close-skip.case, test/language/expressions/async-generator/named-yield-promise-reject-next-yield-star-async-iterator.js, test/language/expressions/async-generator/yield-promise-reject-next-yield-star-async-iterator.js, test/language/expressions/class/async-gen-method-static-yield-promise-reject-next-yield-star-async-iterator.js, test/language/expressions/class/async-gen-method-yield-promise-reject-next-yield-star-async-iterator.js, test/language/expressions/object/method-definition/async-gen-yield-promise-reject-next-yield-star-async-iterator.js, test/language/statements/async-generator/yield-promise-reject-next-yield-star-async-iterator.js, test/language/statements/class/async-gen-method-static-yield-promise-reject-next-yield-star-async-iterator.js, test/language/statements/class/async-gen-method-yield-promise-reject-next-yield-star-async-iterator.js, test/language/statements/for-await-of/async-func-decl-dstr-array-elem-put-const.js, test/language/statements/for-await-of/async-func-decl-dstr-array-elem-trlg-iter-elision-iter-nrml-close-null.js, test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-iter-rtrn-close-null.js, test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-put-const.js, test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-trlg-iter-elision-iter-nrml-close-null.js, test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-trlg-iter-rest-nrml-close-skip.js
Note: The dstr-assignment-for-await/array-elem-iter-rtrn-close-null.case tests may not succeed in all engines, because some engines call IteratorNext before resolving the destructuring assignment target.
=> Fixes for async iteration tests

harness/assert.js
After conversations in #1215, we need to catch up with the code that was previously
produced before we set the features flags requirements.
=> Remove arrow function syntax from harness/assert.js

test/built-ins/Atomics/wait/did-timeout.js, test/built-ins/Atomics/wait/no-spurious-wakeup.js
We have a couple of tests that check that when we wait in Atomics.wait and the wait is either broken by a wakeup or by a timeout, then the time waited is within a fairly small window of the waiting/timeout time.  On slow or overloaded tests systems these tests will fail spuriously because the actual time waited is greater.
These changes therefore make sure that the time waited is at least the expected time (minus epsilon), but there is no longer an upper bound.
=> Make 'wait' tests resilient on slow test systems

test/annexB/built-ins/RegExp/named-groups/non-unicode-malformed.js, test/built-ins/RegExp/named-groups/non-unicode-malformed.js
Moves the tests using Annex-B identity escapes into the annexB folder.
=> Split Annex-B parts of non-unicode-malformed.js into annexB folder

src/dstr-assignment-for-await/array-elem-iter-rtrn-close-null.case, src/dstr-assignment/array-elem-iter-rtrn-close-null.case, src/dstr-assignment/array-elem-iter-rtrn-close.case, src/dstr-assignment/array-elem-trlg-iter-list-rtrn-close-err.case, src/dstr-assignment/array-elem-trlg-iter-list-rtrn-close-null.case, src/dstr-assignment/array-elem-trlg-iter-list-rtrn-close.case, test/language/expressions/assignment/destructuring/iterator-destructuring-property-reference-target-evaluation-order.js, test/language/expressions/assignment/destructuring/keyed-destructuring-property-reference-target-evaluation-order.js, test/language/expressions/assignment/dstr-array-elem-iter-rtrn-close-null.js, test/language/expressions/assignment/dstr-array-elem-iter-rtrn-close.js, test/language/expressions/assignment/dstr-array-elem-trlg-iter-list-rtrn-close-err.js, test/language/expressions/assignment/dstr-array-elem-trlg-iter-list-rtrn-close-null.js, test/language/expressions/assignment/dstr-array-elem-trlg-iter-list-rtrn-close.js, test/language/statements/for-await-of/async-gen-decl-dstr-array-elem-iter-rtrn-close-null.js, test/language/statements/for-of/dstr-array-elem-iter-rtrn-close-null.js, test/language/statements/for-of/dstr-array-elem-iter-rtrn-close.js, test/language/statements/for-of/dstr-array-elem-trlg-iter-list-rtrn-close-err.js, test/language/statements/for-of/dstr-array-elem-trlg-iter-list-rtrn-close-null.js, test/language/statements/for-of/dstr-array-elem-trlg-iter-list-rtrn-close.js
Follow-up from #1207.
86da17166310709aa0bd5d23ba2cb2cff13e87a9 and 58111fff7bcb385b53b0363ad0148de7944d64e7:
Changes `{}[yield]` into `{} = yield` in the case files, so engines can execute these tests even when they don't evaluate all parts of destructuring assignment in the exact spec-order. This requires adding `next()` methods to the iterators, because now IteratorStep is executed exactly once (validated by adding new `nextCounter` variables). I've also reordered the `iterable`, `iterator`, and `iter` variables, because the previous variable ordering was a bit confusing, at least to me.
87e259c6e50c0021b097b680ec0f5f54ee102362:
To ensure we don't lose test coverage for destructuring assignment evaluation order, I've added these two new tests. As usual for fine-grained reference …
=> Change destructuring tests to not rely on exact evaluation order for property references

src/dstr-assignment/obj-rest-order.case, test/language/expressions/assignment/dstr-obj-rest-order.js, test/language/statements/for-of/dstr-obj-rest-order.js
It closes #1132
We already have this test cases for Object Spread, and the same ordering needs to be tested on Object Rest Destructuring. I'm also sending generated tests.
=> Added test case to consider rest ordering field access

test/language/statements/for-of/iterator-next-reference.js
https://github.com/tc39/ecma262/pull/988 changes the iteration protocol
such that the "next" method is only loaded from the iterator object once
during the prologue of iteration, rather than during each step.
=> Update iteration tests with respect to spec changes

INTERPRETING.md, package.json
Every day, we're adding new tests that could cause new failures for the projects that run Test262. This means that whenever someone updates their copy of Test262, they may have to accept new failing tests. Projects generally maintain a list of "expected failures" for just this purpose.
Sometimes, we change the way we describe the tests themselves. When we do this, consumers will also run into new failures, but not because they have a bug in their project. They have to update the way they interpret the results to match our new organization.
We maintain a document called "INTERPRETING.md" to help folks understand how to run Test262, but this process is still kind of confusing. That's because consumers initially see new failures, and they have to work backwards to answer the question, "are …
=> Introduce version number

test/intl402/NumberFormat/prototype/formatToParts/length.js
As per https://github.com/tc39/ecma402/pull/160 the formatToParts.length is set to 1.
=> Update Intl.NumberFormat.prototype.formatToParts.length to expect 1

harness/typeCoercion.js
typeCoercion.js is included in several tests which are not marked as `features: [BigInt]`.
Since BigInt is new feature, we should not make the above unrelated tests failed due to
lack of BigInt syntax support.
Close #1252.
=> Do not use BigInt literal without `features: [BigInt]`

test/built-ins/JSON/stringify/bigint-order.js, test/built-ins/JSON/stringify/bigint-replacer.js, test/built-ins/JSON/stringify/bigint-tojson.js, test/built-ins/JSON/stringify/bigint.js
Additional JSON tests for BigInt, for JSON.stringify with a replacer function and the toJSON method.
=> additional BigInt JSON tests

tools/copy_tests.sh
I split this out of #1250. I think it's a nice thing to have, as it makes it very easy
to test changes in VMs before submitting them to test262.
A more portable version would be nice, but this is tested and working well on OSX and
the windows linux subsystem, which is good enough for me.
=> Add a little helper for convenience in testing changes

src/async-generators/yield-star-async-next.case, test/language/expressions/async-generator/named-yield-star-async-next.js, test/language/expressions/async-generator/yield-star-async-next.js, test/language/expressions/class/async-gen-method-static-yield-star-async-next.js, test/language/expressions/class/async-gen-method-yield-star-async-next.js, test/language/expressions/object/method-definition/async-gen-yield-star-async-next.js, test/language/statements/async-generator/yield-star-async-next.js, test/language/statements/class/async-gen-method-static-yield-star-async-next.js, test/language/statements/class/async-gen-method-yield-star-async-next.js
Update behaviour based on changes from
https://github.com/tc39/ecma262/pull/988. The actual spec change PR for
async iteration is not yet uploaded.
This does not include any changes to Async-from-Sync Iterator.
=> Update async iteration tests with respect to pending spec change

test/built-ins/RegExp/named-groups/string-replace-missing.js, test/built-ins/RegExp/named-groups/string-replace-nocaptures.js, test/built-ins/RegExp/named-groups/string-replace-unclosed.js
The RegExp named groups specification has changed to not throw
errors in certain cases. This patch updates the test262 tests to match
the new specification, and throws in an additional test that verifies
the interaction between named group syntax and other replacement.
The tests pass on a version of V8 which implements the new semantics.
https://github.com/tc39/proposal-regexp-named-groups/commit/92ceba518c2ab0d2811c2efa8248ed1b3f8b5506
=> Update RegExp named capture tests for spec change

test/language/expressions/equals/to-prim-hint.js
For non-strict equality, an object compared to a boolean should be coerced using ToPrimitive with no hint argument. (A "number" hint was used in an earlier version of the BigInt proposal, before [this commit](https://github.com/tc39/proposal-bigint/commit/79b27c6e53b53add64df3a795fe7f2e85dd8ec09).)
=> ToPrimitive called without hint for boolean equality

test/built-ins/Atomics/wake/wake-all-on-loc.js, test/built-ins/Atomics/wake/wake-all.js, test/built-ins/Atomics/wake/wake-in-order.js, test/built-ins/Atomics/wake/wake-one.js, test/built-ins/Atomics/wake/wake-two.js, test/built-ins/Atomics/wake/wake-zero.js
On slow and overloaded systems, it is possible for some of the fixed timeout limits in these tests to be insufficient because worker threads take a long time to become available and they can become available in weird orders.  I fixed some of these issues earlier; here are some more fixes.  The general theme is to always wait until all the worker threads have reported that they are available.  In addition I've cleaned up a little.
These tests are still not perfect, there is still a chance of timing out.  But making them even more robust than here makes it too likely that bugs will be hidden by the robustness mechanisms.
=> Make Atomics.wake test cases resilient on slow / overloaded systems

INTERPRETING.md, features.txt, test/annexB/language/expressions/yield/star-iterable-return-emulates-undefined-throws-when-called.js, test/annexB/language/statements/for-of/iterator-close-return-emulates-undefined-throws-when-called.js
This is generally very cheesy.  But it happens that if you slot in `$262.uncallableAndIsHTMLDDA = () => document.all` in SpiderMonkey, these tests fail right now, because we did a loose-equality check against `undefined` rather than a strict-equality check.  So, it would be nice to have upstream testing of that in case other implementations are similarly buggy.
Note that per the very peculiar requirements of `$262.uncallableAndIsHTMLDDA`, hosts that don't support `document.all` or anything stupid like it can just add
$262.uncallableAndIsHTMLDDA = function() { return {}; };
to their support files to run these tests.  The `[[IsHTMLDDA]]` aspects could be omitted from the object returned by this function, and it wouldn't change the tests' behaviors. …
=> Add tests for the case of `<iterator>.return` in the iteration protocol being an object that's uncallable and compares equal to `undefined`

src/async-generators/yield-star-sync-next.case, test/language/expressions/async-generator/named-yield-star-sync-next.js, test/language/expressions/async-generator/yield-star-sync-next.js, test/language/expressions/class/async-gen-method-static-yield-star-sync-next.js, test/language/expressions/class/async-gen-method-yield-star-sync-next.js, test/language/expressions/object/method-definition/async-gen-yield-star-sync-next.js, test/language/statements/async-generator/yield-star-sync-next.js, test/language/statements/class/async-gen-method-static-yield-star-sync-next.js, test/language/statements/class/async-gen-method-yield-star-sync-next.js
This change updates test cases to assume that the "next" method is only
loaded from a synchronous iterator once, and is re-used for each call to
Async-from-Sync Iterator.next(), based on tc39/ecma262#988
=> Fix Async-from-Sync Iterator tests

test/annexB/language/statements/for-await-of/iterator-close-return-emulates-undefined-throws-when-called.js
Just a replay of the same thing as #1287, in a different scenario.  Also another bug SpiderMonkey has until I land a patch for it.
=> Add a test for GetIterator(obj, ~async~) attempting to call obj[@@asyncIterator] even if that value is an object with an [[IsHTMLDDA]] internal slot

test/built-ins/TypedArrays/internals/DefineOwnProperty/tonumber-value-detached-buffer.js, test/built-ins/TypedArrays/internals/Set/tonumber-value-detached-buffer.js
The historical failure of implementations to throw when setting a typed array element backed by a detached buffer rears its ugly head when I try these tests in SpiderMonkey.  Other implementations probably suffer similarly, but I didn't test anyone else.  Probably good for someone else to verify correctness here by a separate inspection, or in an implementation that handles detached-sets correctly.
=> Test setting/defining a typed array element to a value, when ToNumber(value) detaches the underlying ArrayBuffer

test/language/function-code/each-param-has-own-non-shared-eval-scope.js, test/language/function-code/each-param-has-own-scope.js
Originally discovered by Cait Potter (@caitp), reported in irc.mozilla.org#jslang
@leobalter I need another critical look at this, I searched through _a lot_ of existing tests (thanks to detailed `info` frontmatter, I was able to search for tests with relevant spec prose!), but I'm afraid that I may have missed something—hopefully you can help me recheck. In the meantime, I will do another pass. It seems unlikely and would be very surprising that such a test doesn't already exist.
=> Let paramVarEnv be NewDeclarativeEnvironment(originalEnv).

test/built-ins/decodeURI/S15.1.3.1_A1.11_T2.js, test/built-ins/decodeURI/S15.1.3.1_A1.12_T2.js, test/built-ins/decodeURI/S15.1.3.1_A1.12_T3.js, test/built-ins/decodeURIComponent/S15.1.3.2_A1.11_T2.js, test/built-ins/decodeURIComponent/S15.1.3.2_A1.12_T2.js, test/built-ins/decodeURIComponent/S15.1.3.2_A1.12_T3.js
The tests are explicitly for bad hex chars at certain indexes, and that
rogue `%` was giving false positives.
I'm not super in favor of the string concats, but it's not affecting anything...
=> Fix several Decode tests

test/language/expressions/bitwise-and/bigint-non-primitive.js, test/language/expressions/bitwise-or/bigint-non-primitive.js, test/language/expressions/bitwise-xor/bigint-non-primitive.js
A few BigInt tests had a blank line in an inconvenient place which
breaks an old, possibly incorrect YAML parser used by V8's test262
test automation. The best fix is to deploy a new YAML parser, but
in the short term, this patch deletes the blank lines and lets
V8 understand the feature flags below. Related: #1370
=> Remove some spurious blank lines

CONTRIBUTING.md
[We changed the name of the `id` metadata to `esid`](https://github.com/tc39/test262/pull/516) [shortly after introducing it](https://github.com/tc39/test262/issues/477).
=> Correct metadata reference in "contributing" docs

harness/assert.js
The use of `let` is unnecessary here, particularly in a
file that is needed to run any of the tests, even the ES5 tests.
Removing it allows older engines to run older tests.
=> Remove unnecessary uses of let in harness.

test/built-ins/RegExp/named-groups/groups-object-subclass-sans.js, test/built-ins/RegExp/named-groups/groups-object-subclass.js, test/built-ins/RegExp/named-groups/groups-object-undefined.js, test/built-ins/RegExp/named-groups/groups-object-unmatched.js, test/built-ins/RegExp/named-groups/groups-object.js
The `groups` property must be created unconditionally per https://github.com/tc39/proposal-regexp-named-groups/pull/40.
This patch ports @schuay’s tests from https://chromium.googlesource.com/v8/v8.git/+/d2f95e189c3209408525c88e2893d16c09724159.
cc @littledan
=> [regexp-named-groups] Expand tests for `groups` property

CONTRIBUTING.md
Fix a small but rather confusing typo in the CONTRIBUTING.md file.
(I didn't find any commit message rules, so just followed the style of the most recent commit. I hope it's ok.)
=> Correct path to helper files directory in "contributing" docs

test/built-ins/BigInt/asIntN/bigint-tobigint-errors.js, test/built-ins/BigInt/asIntN/bigint-tobigint-toprimitive.js, test/built-ins/BigInt/asIntN/bigint-tobigint-wrapped-values.js, test/built-ins/BigInt/asIntN/bigint-tobigint.js, test/built-ins/BigInt/asIntN/bits-toindex-errors.js, test/built-ins/BigInt/asIntN/bits-toindex-toprimitive.js, test/built-ins/BigInt/asIntN/bits-toindex-wrapped-values.js, test/built-ins/BigInt/asIntN/bits-toindex.js, test/built-ins/BigInt/asUintN/bigint-tobigint-errors.js, test/built-ins/BigInt/asUintN/bigint-tobigint-toprimitive.js, test/built-ins/BigInt/asUintN/bigint-tobigint-wrapped-values.js, test/built-ins/BigInt/asUintN/bigint-tobigint.js, test/built-ins/BigInt/asUintN/bits-toindex-errors.js, test/built-ins/BigInt/asUintN/bits-toindex-toprimitive.js, test/built-ins/BigInt/asUintN/bits-toindex-wrapped-values.js, test/built-ins/BigInt/asUintN/bits-toindex.js, test/built-ins/String/prototype/indexOf/position-tointeger-bigint.js, test/built-ins/String/prototype/indexOf/position-tointeger-errors.js, test/built-ins/String/prototype/indexOf/position-tointeger-toprimitive.js, test/built-ins/String/prototype/indexOf/position-tointeger-wrapped-values.js, test/built-ins/String/prototype/indexOf/position-tointeger.js, test/built-ins/String/prototype/indexOf/searchstring-tostring-bigint.js, test/built-ins/String/prototype/indexOf/searchstring-tostring-errors.js, test/built-ins/String/prototype/indexOf/searchstring-tostring-toprimitive.js, test/built-ins/String/prototype/indexOf/searchstring-tostring-wrapped-values.js, test/built-ins/String/prototype/indexOf/searchstring-tostring.js
This removes some of the dependencies on `harness/typeCoercion.js`.
This is an iteration on the proposal in #1341 which does not include the generator code. For that, see https://github.com/thejoshwolfe/test262-generators .
I didn't touch the DataView tests yet. That will come in a follow up PR.
This code was formatted with `js-beautify -n -w 100 -s 2` (after [patching](https://github.com/beautify-web/js-beautify/pull/1303) it to support BigInt literal notation).
=> Inline typeCoercion.js for some tests

test/built-ins/DataView/prototype/getBigInt64/to-boolean-littleendian.js, test/built-ins/DataView/prototype/getBigInt64/toindex-byteoffset-errors.js, test/built-ins/DataView/prototype/getBigInt64/toindex-byteoffset-toprimitive.js, test/built-ins/DataView/prototype/getBigInt64/toindex-byteoffset-wrapped-values.js, test/built-ins/DataView/prototype/getBigInt64/toindex-byteoffset.js, test/built-ins/DataView/prototype/getBigUint64/to-boolean-littleendian.js, test/built-ins/DataView/prototype/getBigUint64/toindex-byteoffset-errors.js, test/built-ins/DataView/prototype/getBigUint64/toindex-byteoffset-toprimitive.js, test/built-ins/DataView/prototype/getBigUint64/toindex-byteoffset-wrapped-values.js, test/built-ins/DataView/prototype/getBigUint64/toindex-byteoffset.js
This is the remainder of the uses of `harness/typeCoercion.js`. That file can be removed in a follow up PR.
(This is an iteration on the proposal in #1341 which does not include the generator code. For that, see https://github.com/thejoshwolfe/test262-generators .)
*I do not have access to an implementation of the apis that are being tested in this PR. I would appreciate if someone could run these to make sure I didn't make any typos.*
(This code was formatted with `js-beautify -n -w 100 -s 2` (after [patching](https://github.com/beautify-web/js-beautify/pull/1303) it to support BigInt literal notation).)
=> Generate type coercion tests for DataView tests

test/built-ins/Number/string-binary-literal-invalid.js, test/built-ins/Number/string-hex-literal-invalid.js, test/built-ins/Number/string-octal-literal-invald.js
As far as I understand grammar in the [“ToNumber Applied to the String Type,”](https://tc39.github.io/ecma262/#sec-tonumber-applied-to-the-string-type) only StrDecimalLiteral may have a sign, fractional or exponent parts. Yet I couldn't find tests for BinaryIntegerLiteral, OctalIntegerLiteral, and HexIntegerLiteral that are invalid in this way, so decided to add them.
These checks apply (more or less) to anything that uses ToNumber, but it seems that the Number constructor is a place for most ToNumber tests, so I simply followed that. Also, for the same reason, I've used `esid` of [`Number(value)`](https://tc39.github.io/ecma262/#sec-number-constructor-number-value).
Note that because `0x1e10` is a valid HexIntegerLiteral there's no test for the unsigned exponent in hex literals.
I don't …
=> Add more tests for ToNumber conversion of invalid StringNumericLiterals

tools/lint/lib/checks/esid.py, tools/lint/lint.py
I can try to fix the malformed ids if these regular expressions seem agreeable. `es5id` is more complicated.
=> Add es[56]?id checks

test/language/expressions/addition/order-of-evaluation.js, test/language/expressions/bitwise-and/order-of-evaluation.js, test/language/expressions/bitwise-or/order-of-evaluation.js, test/language/expressions/bitwise-xor/order-of-evaluation.js, test/language/expressions/division/order-of-evaluation.js, test/language/expressions/exponentiation/order-of-evaluation.js, test/language/expressions/left-shift/order-of-evaluation.js, test/language/expressions/modulus/order-of-evaluation.js, test/language/expressions/multiplication/order-of-evaluation.js, test/language/expressions/right-shift/order-of-evaluation.js, test/language/expressions/subtraction/order-of-evaluation.js, test/language/expressions/unsigned-right-shift/order-of-evaluation.js
These tests use terminology from the BigInt proposal, such as ToNumeric, but do not functionally depend on anything from the BigInt proposal. The semantics tested in this PR are preserved by the BigInt proposal.
There is some overlap between these tests and existing tests such as:
* `language/expressions/unsigned-right-shift/S11.7.3_A2.3_T1.js`
* `language/expressions/unsigned-right-shift/S11.7.3_A2.4_T2.js`
I think the tests in this PR make sense as is, but they are quite long compared to other test262 tests. I would be happy to cut these tests up into smaller pieces, and/or cut out the parts that are already covered by other tests, such as the ones mentioned above. I'm using python to generate these, so it wouldn't be too much work to make changes like this.
I used shorthand in the …
=> Order of evaluation tests for infix numeric operators

test/language/expressions/object/11.1.5_4-4-d-1.js, test/language/expressions/object/getter-body-strict-inside.js, test/language/expressions/object/getter-body-strict-outside.js, test/language/expressions/object/prop-dup-data-data.js, test/language/expressions/object/prop-dup-data-set.js, test/language/expressions/object/prop-dup-get-data.js, test/language/expressions/object/prop-dup-get-get.js, test/language/expressions/object/prop-dup-get-set-get.js, test/language/expressions/object/prop-dup-set-data.js, test/language/expressions/object/prop-dup-set-get-set.js, test/language/expressions/object/prop-dup-set-set.js, test/language/expressions/object/setter-body-strict-inside.js, test/language/expressions/object/setter-body-strict-outside.js, test/language/expressions/object/setter-param-arguments-strict-inside.js, test/language/expressions/object/setter-param-arguments-strict-outside.js, test/language/expressions/object/setter-param-eval-strict-inside.js, test/language/expressions/object/setter-param-eval-strict-outside.js
A number of tests for the parsing of object initializers were expressed
using `eval`. This made the tests more complex than necessary and also
prevented the tests from providing value to ECMAScript parsers.
Remove the use of `eval` in the relevant tests and instead express the
expectations with literal source text.
---
This is in service of gh-1356
=> Refactor object initializer tests for parsers

test/built-ins/Atomics/add/bad-range.js, test/built-ins/Atomics/add/nonshared-int-views.js, test/built-ins/Atomics/and/bad-range.js, test/built-ins/Atomics/and/nonshared-int-views.js, test/built-ins/Atomics/compareExchange/bad-range.js, test/built-ins/Atomics/compareExchange/nonshared-int-views.js, test/built-ins/Atomics/exchange/bad-range.js, test/built-ins/Atomics/exchange/nonshared-int-views.js, test/built-ins/Atomics/load/bad-range.js, test/built-ins/Atomics/load/nonshared-int-views.js, test/built-ins/Atomics/or/bad-range.js, test/built-ins/Atomics/or/nonshared-int-views.js, test/built-ins/Atomics/store/bad-range.js, test/built-ins/Atomics/store/nonshared-int-views.js, test/built-ins/Atomics/sub/bad-range.js, test/built-ins/Atomics/sub/nonshared-int-views.js, test/built-ins/Atomics/wait/bad-range.js, test/built-ins/Atomics/wait/nonshared-int-views.js, test/built-ins/Atomics/wake/bad-range.js, test/built-ins/Atomics/wake/nonshared-int-views.js, test/built-ins/Atomics/xor/bad-range.js, test/built-ins/Atomics/xor/nonshared-int-views.js
This patch updates the Atomics "bad-range" and "nonshared-int-views" test cases to test BigInt atomic operations when the feature is available.
=> initial Atomics tests for BigInt

test/built-ins/Promise/prototype/finally/species-constructor.js, test/built-ins/Promise/prototype/finally/subclass-reject-count.js, test/built-ins/Promise/prototype/finally/subclass-resolve-count.js, test/built-ins/Promise/prototype/finally/subclass-species-constructor-reject-count.js, test/built-ins/Promise/prototype/finally/subclass-species-constructor-resolve-count.js, test/built-ins/Promise/prototype/finally/this-value-non-promise.js
Per:
- https://github.com/tc39/test262/issues/866#issuecomment-328565337
- https://github.com/tc39/test262/issues/866#issuecomment-359978873
Closes #866.
cc @gsathya, do you think these tests are correct? v8 fails 12 of them.
=> Promise.prototype.finally: add missing tests

test/built-ins/String/prototype/trimEnd/this-value-whitespace.js, test/built-ins/String/prototype/trimStart/this-value-whitespace.js
This patch fixes a typo (`\FEFF` → `\uFEFF`) and adds some missing whitespace symbols as a follow-up to https://github.com/tc39/test262/pull/1246.
=> [string-trimming] Fix whitespace tests

test/built-ins/Array/prototype/flatMap/depth-always-one.js, test/built-ins/Promise/prototype/finally/subclass-species-constructor-resolve-count.js
Array/prototype/flatMap/depth-always-one.js
- Someone forgot a closing parenthesis... 😇 
Promise/prototype/finally/subclass-species-constructor-resolve-count.js
- Was incorrectly marked as async.
=> Add missing closing parenthesis and remove invalid async flag

test/language/expressions/tagged-template/cache-different-functions-same-site.js, test/language/expressions/tagged-template/cache-differing-expressions-eval.js, test/language/expressions/tagged-template/cache-differing-expressions-new-function.js, test/language/expressions/tagged-template/cache-differing-expressions.js, test/language/expressions/tagged-template/cache-differing-raw-strings.js, test/language/expressions/tagged-template/cache-differing-string-count.js, test/language/expressions/tagged-template/cache-identical-source-eval.js, test/language/expressions/tagged-template/cache-identical-source-new-function.js, test/language/expressions/tagged-template/cache-identical-source.js, test/language/expressions/tagged-template/cache-realm.js, test/language/expressions/tagged-template/cache-same-site-top-level.js, test/language/expressions/tagged-template/cache-same-site.js
These tests are against a specification change based on discussion in
https://github.com/tc39/ecma262/issues/840
The tests here passed on SpiderMonkey but failed on other
implementations, which implement the current specification.
EDIT: They passed on a version of SpiderMonkey from February, and would likely fail on ToT.
=> Test for change to cache templates by site, not contents

test/built-ins/Atomics/wake/wake-all-on-loc.js, test/built-ins/Atomics/wake/wake-all.js, test/language/module-code/privatename-valid-no-earlyerr.js, test/language/statements/class/privatefieldget-typeerror-2.js, test/language/statements/class/privatefieldget-typeerror-5.js, test/language/statements/class/privatefieldset-typeerror-2.js, test/language/statements/class/privatefieldset-typeerror-5.js, test/language/statements/class/privatename-valid-no-earlyerr.js, test/language/statements/function/name-unicode.js
This patch changes tabs to spaces for newly added tests.
The motivation is that SVN of WebKit tree rejects files including tabs.
If we annotate files with `allow-tabs` SVN property, we can land it.
But unless tabs are intentionally used for parser tests, using spaces is a safer choice.
It removes additional steps when updating test262 in WebKit tree, and WebKit tree can quickly update test262.
=> Prefer spaces to tabs if it is not syntax related tests

test/built-ins/Math/pow/int32_min-exponent.js, test/language/expressions/exponentiation/int32_min-exponent.js
SpiderMonkey's implementation invokes signed integer overflow in this case.  It would have been nice if test262 had performed this operation and thus would have alerted us to the issue (even if, at least with the compilers we test with regularly, there might not have been an _observable_ deviation from the spec).
It's maybe a little silly having one test for operator, one for function, but this seems better for implementations that choose not to implement the behavior literally by shared function call as the spec does.
=> Add tests for the behavior of INT32_MIN (-2147483648) as exponent

harness/propertyHelper.js
Example:
Before: _descriptor value should be 42 Expected SameValue(«1», «0») to be true_
After: _descriptor value should be 42_
---
Note that `Expected SameValue(«1», «0»)` is for the list of failures while checking the descriptor, as each error adds up to the list. The error message is confusing if the expected value is similar, e.g. 1:
> descriptor value should be 42 Expected SameValue(«1», «0») to be true
=> improve propertyHelper for failure messages

features.txt, harness/features.yml, harness/testBigIntTypedArray.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/iterator-result-unwrap-promise.js, test/built-ins/AsyncGeneratorFunction/invoked-as-constructor-no-arguments.js, test/built-ins/AsyncGeneratorFunction/invoked-as-function-multiple-arguments.js, test/built-ins/AsyncGeneratorFunction/invoked-as-function-no-arguments.js, test/built-ins/Atomics/wait/cannot-suspend-throws.js, test/built-ins/Atomics/wait/non-int32-typedarray-throws.js, test/built-ins/Atomics/wait/undefined-index-defaults-to-zero.js, test/built-ins/Atomics/wait/wait-index-value-not-equal.js, test/built-ins/Atomics/wait/was-woken-before-timeout.js, test/built-ins/Promise/all/iter-arg-is-string-resolve.js, test/built-ins/Promise/all/iter-step-err-no-close.js, test/built-ins/Promise/race/iter-arg-is-string-resolve.js, test/built-ins/TypedArray/prototype/map/return-new-typedarray-conversion-operation-consistent-nan.js, test/harness/verifyProperty-value-error.js
I've changed harness/testBigIntTypedArray.js so it can be loaded in even if `BigInt64Array` is not defined. This makes it easier to process this file for SpiderMonkey's test262 importer.
Fixes #1492
=> Fix various test bugs

harness/nans.js, test/built-ins/Object/internals/DefineOwnProperty/nan-equivalence-define-own-property-reassign.js, test/built-ins/Object/internals/DefineOwnProperty/nan-equivalence-define-own-property-reconfigure.js, test/built-ins/TypedArray/prototype/copyWithin/bit-precision.js, test/built-ins/TypedArray/prototype/fill/fill-values-conversion-operations-consistent-nan.js, test/built-ins/TypedArray/prototype/map/return-new-typedarray-conversion-operation-consistent-nan.js, test/built-ins/TypedArray/prototype/set/bit-precision.js, test/built-ins/TypedArray/prototype/slice/bit-precision.js, test/built-ins/TypedArrayConstructors/ctors/object-arg/conversion-operation-consistent-nan.js, test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/conversion-operation-consistent-nan.js, test/built-ins/TypedArrayConstructors/internals/Set/conversion-operation-consistent-nan.js, test/built-ins/isNaN/return-true-nan.js, test/harness/nans.js
`function nan() { return /* expression to compute NaN */ }` may not return the same implementation-distinguishable NaN value before and after JIT compilation. As observed here: https://treeherder.mozilla.org/#/jobs?repo=try&revision=cb26ed14f1a42ae9a70b516ecc22046c3ce9c8fa
=> Don't compute NaN values in functions

test/language/expressions/class/constructor-this-tdz-during-initializers.js, test/language/expressions/class/fields-run-once-on-double-super.js
This adds a test for the change in https://github.com/tc39/proposal-class-fields/pull/92. At a glance I don't believe the previous behavior was tested (it is _very_ edge-case-y), but the important part of the change for the old-vs-new behavior in this would look like
```diff
-  field = (thisDuringField = this, assert.throws(ReferenceError, probeCtorThis));
+  field = (thisDuringField = this, thisFromProbe = probeCtorThis());
```
cc @littledan
=> Add test for proposal-class-fields#92

test/built-ins/BigInt/prototype/valueOf/cross-realm.js
Check that valueOf works on a BigInt object from another realm
This is intended to be a simple test for BigInt methods unwrapping objects from other globals correctly; there might be a better way to test this functionality.
=> cross-realm test for BigInt.prototype.valueOf

tools/packaging/monkeyYaml.py, tools/packaging/parseTestRecord.py
Two small changes to allow monkeyYaml.py and parseTestRecord.py to run under Python 3.
=> Make parseTestRecord.py python3 compatible

test/language/asi/S7.9_A11_T8.js, test/language/asi/S7.9_A4.js, test/language/asi/S7.9_A5.1_T1.js, test/language/asi/S7.9_A5.3_T1.js, test/language/module-code/early-strict-mode.js, test/language/statements/break/S12.8_A8_T1.js, test/language/statements/break/S12.8_A8_T2.js, test/language/statements/continue/S12.7_A8_T1.js, test/language/statements/continue/S12.7_A8_T2.js
@rwaldon gh-1534 got me thinking about other places where `$ERROR` was being used unnecessarily. I'm sure there are plenty more overly-complicated "negative syntax" tests, but we'll leave those for another day.
---
Because these files contain syntax errors, the code they contain is not
intended to be executed, and the runtime semantics are therefore
irrelevant. Simplify the files by removing the unnecessary code.
=> Remove superfluous code from negative syntax tests

test/language/expressions/greater-than/bigint-and-symbol.js, test/language/expressions/less-than/bigint-and-symbol.js
These tests are important too check if evaluation ordering are being respected when some of the operands are BigInt. It closes #1542
=> Added tests for relational comparison among BigInt and Symbol

INTERPRETING.md, harness/doneprintHandle.js
Previously, the error message generated by failed asynchronous tests was
generic and underspecified. Improve the format and explicitly document
it in project's interpreting guidelines.
=> Formalize asynchronous failure conditions

test/language/literals/string/line-continuation-double.js, test/language/literals/string/line-continuation-single.js
Gap discovered in https://github.com/babel/babel/pull/7985#discussion_r189419983 (implementing https://github.com/tc39/proposal-json-superset ).
=> Add tests for LineContinuation in StringLiteral

test/built-ins/Object/prototype/toString/symbol-tag-non-str-bigint.js, test/built-ins/Object/prototype/toString/symbol-tag-override-bigint.js
Reported by André Bargull in
<https://bugzilla.mozilla.org/show_bug.cgi?id=1464758>.
=> Add Object.prototype.toString tests for BigInt.

test/built-ins/Date/parse/time-value-maximum-range.js, test/built-ins/Date/parse/zero.js
The specification directly calls out the parse identity of a `Date` `x` where `x.valueOf() === 0`. This adds a basic test for that base case and then adds an additional test for the maximum allowable *time value* range as stated in the spec.
The latter issue was raised in tc39/ecma262#1145, and currently Firefox (SpiderMonkey) is the only engine returning `NaN` for values outside of the *time value* range. This test is intended to bring the other engines in line with SM behavior.
=> Date.parse breathing test, time value maximum range test

features.txt, test/built-ins/Symbol/prototype/description/descriptor.js, test/built-ins/Symbol/prototype/description/get.js, test/built-ins/Symbol/prototype/description/this-val-non-symbol.js, test/built-ins/Symbol/prototype/description/this-val-symbol.js, test/built-ins/Symbol/prototype/description/wrapper.js
Refs: https://github.com/tc39/proposal-Symbol-description/issues/5
V8 implementation in https://chromium-review.googlesource.com/c/v8/v8/+/1088871
=> Add tests for Symbol.prototype.description

test/language/expressions/tagged-template/template-object.js
While Firefox never behaved as such, the specifications are clear and Chrome, Safari, and Edge always respected specifications [here](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-gettemplateobject):
> Each TemplateLiteral in the program code of a realm is associated with a unique template object that is used in the evaluation of tagged Templates (12.2.9.5). The template objects are frozen and the same template object is used each time a specific tagged Template is evaluated.
However, since there are no tests around that little details that has a lot of libraries built around such assumption, it's easy to break the web like [this Chrome 67 bug](https://bugs.chromium.org/p/chromium/issues/detail?id=848999) demonstrates.
Please note that behavior is so trusted that even …
=> GetTemplateObject with a unique template object

test/intl402/Locale/constructor-options-collation-invalid.js, test/intl402/Locale/constructor-options-collation-valid.js, test/intl402/Locale/constructor-options-numberingsystem-invalid.js, test/intl402/Locale/constructor-options-numberingsystem-valid.js
The spec changed in https://github.com/tc39/proposal-intl-locale/pull/47.
The tests for calendar were already correct.
=> Intl.Locale: Update expectation for empty values for collation and numberingSystem.

tools/lint/lib/checks/harness.py
This prevents failures in the CI for logs > 4MB.
=> Avoid printing tests source in the lint script

harness/atomicsHelper.js, harness/detachArrayBuffer.js, harness/nans.js, harness/nativeFunctionMatcher.js, harness/proxyTrapsHelper.js, harness/regExpUtils.js, harness/tcoHelper.js
In order to satisfy the project's formatting rules, license information
was inserted into a number of files where it had been mistakenly omitted
by the original contributors [1]. In many cases, the license information
did not accurately describe the contributor or the time of contribution.
Update the information according to the information provided by the
contributors at the time each file was authored:
- atomicsHelper.js - a72ee6d91275aa6524e84a9b7070103411ef2689
- detachArrayBuffer.js - 70c7375be83137015da2c5d6d29a3c40ad3cb5b1
- nans.js - b17ffc029850e3c32d51c68e0281ab7b1a4c193b
- nativeFunctionMatcher.js - 6b7cbb50350e478a543da40d02492aa8f45a792d
- proxyTrapsHelper.js d530c87b41584d47d95bb78dccf592c9c5c8f7b1
- regexpUtils.js - 44b40e083ec851cd8448d5fe4755bdfc9f0dc14c
- tcoHelper.js - …
=> Correct licensing

test/annexB/language/comments/single-line-html-close-unicode-separators.js
SpiderMonkey tip has a bug in this regard, might as well have everyone be correct about this inanity.
Might be to properly review this you need to hexdump the relevant parts, seeing as GitHub seems to fail to display the relevant separator code points, somewhat unsurprisingly.
=> Add a test covering the behavior of SingleLineHTMLCloseComment that uses either Unicode separator

test/intl402/RelativeTimeFormat/prototype/toStringTag/toString.js, test/intl402/RelativeTimeFormat/prototype/toStringTag/toStringTag.js
The specification changed in https://github.com/tc39/proposal-intl-relative-time/pull/77.
=> Update expectation for Intl.RelativeTimeFormat.prototype[@@toStringTag].

test/intl402/RelativeTimeFormat/constructor/constructor/options-proto.js
The specification was changed in https://github.com/tc39/proposal-intl-relative-time/pull/79.
=> Add tests for objects created in the RelativeTimeFormat constructor.

tools/lint/lib/checks/esid.py, tools/lint/test/fixtures/esid_invalid.js, tools/lint/test/fixtures/valid_esid_alternate.js
The document fragments used by the ECMAScript specification do not
conform to any particular pattern beyond the grammar defined by the URL
standard [1]. Relax the linting rule to enforce a simplified version of
that grammar.
[1] https://url.spec.whatwg.org/#fragment-state
=> Relax linting rules for `esid` metadata

test/built-ins/Proxy/deleteProperty/boolean-trap-result-boolean-true.js
`built-ins/Proxy/deleteProperty/boolean-trap-result-boolean-true.js` was missing a feature flag for the Reflect library.
=> Add a missing Reflect feature flag

test/built-ins/Proxy/ownKeys/return-duplicate-entries-throws.js, test/built-ins/Proxy/ownKeys/return-duplicate-symbol-entries-throws.js, test/built-ins/Proxy/ownKeys/return-type-throws-array.js, test/built-ins/Proxy/ownKeys/return-type-throws-boolean.js, test/built-ins/Proxy/ownKeys/return-type-throws-null.js, test/built-ins/Proxy/ownKeys/return-type-throws-number.js, test/built-ins/Proxy/ownKeys/return-type-throws-object.js, test/built-ins/Proxy/ownKeys/return-type-throws-undefined.js
All other Proxy tests use the syntax `attr: function() {...}` for defining traps, ownKeys was unique in using the shorthand syntax `attr() {..}`. Change to longhand syntax for back-compat for partial implementations.
=> Make Proxy/ownKeys tests ES5-parsable

INTERPRETING.md
=> Documentation: $262.agent.report() is expected to convert its argument to a string. Fixes gh-1640

test/intl402/RelativeTimeFormat/prototype/format/en-us-numeric-always.js, test/intl402/RelativeTimeFormat/prototype/format/en-us-numeric-auto.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/en-us-numeric-always.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/en-us-numeric-auto.js
The specification was changed to remove the useGrouping option in
<https://github.com/tc39/proposal-intl-relative-time/pull/81>.
The change to remove the minimumIntegerDigits option in that PR was already
taken into account; this commit also removes the reference to the issue.
This also removes some commented-out code that was left in by accident.
=> Intl.RelativeTimeFormat: Test for grouping in long numbers.

test/intl402/DateTimeFormat/prototype/formatToParts/main.js
Chrome uses dayperiod while the specification says dayPeriod. :(
https://crbug.com/865351
This should prevent such mistakes in the future.
I am surprised such a basic test was not added until now... Is there a reason, or am I simply bad at searching?
=> Added a legal part types test

test/intl402/RelativeTimeFormat/constructor/supportedLocalesOf/basic.js
This is based on test/intl402/NumberFormat/supportedLocalesOf/basic.js.
=> Intl.RelativeTimeFormat: Add a basic test for the functionality of supportedLocalesOf().

implementation-contributed/curation_logs/javascriptcore.json, implementation-contributed/javascriptcore/stress/date-utc-optional.js
Changes imported in this pull request include all changes made since
[b69d88687a](https://github.com///github/blob/b69d88687a) in JavaScriptCore and all changes made since [93b2865ca](../blob/93b2865ca) in
test262.
These are new files added in JavaScriptCore and have been synced to the
`implementation-contributed/javascriptcore` directory.
- [implementation-contributed/javascriptcore/stress/date-utc-optional.js](../blob/javascriptcore-test262-automation-export-93b2865ca/implementation-contributed/javascriptcore/stress/date-utc-optional.js)
=> Import test changes from JavaScriptCore

features.txt, test/built-ins/Object/fromEntries/empty-iterable.js, test/built-ins/Object/fromEntries/evaluation-order.js, test/built-ins/Object/fromEntries/iterator-closed-for-null-entry.js.js, test/built-ins/Object/fromEntries/iterator-closed-for-string-entry.js.js, test/built-ins/Object/fromEntries/iterator-closed-for-throwing-entry-accessor.js, test/built-ins/Object/fromEntries/iterator-closed-for-throwing-entry-key-tostring.js, test/built-ins/Object/fromEntries/iterator-not-closed-for-next-returning-non-object.js, test/built-ins/Object/fromEntries/iterator-not-closed-for-throwing-done-accessor.js, test/built-ins/Object/fromEntries/iterator-not-closed-for-throwing-next.js, test/built-ins/Object/fromEntries/iterator-not-closed-for-uncallable-next.js, test/built-ins/Object/fromEntries/key-order.js, test/built-ins/Object/fromEntries/length.js, test/built-ins/Object/fromEntries/name.js, test/built-ins/Object/fromEntries/prototype.js, test/built-ins/Object/fromEntries/requires-argument.js, test/built-ins/Object/fromEntries/simple-properties.js, test/built-ins/Object/fromEntries/string-entry-object-succeeds.js, test/built-ins/Object/fromEntries/string-entry-primitive-throws.js, test/built-ins/Object/fromEntries/supports-symbols.js, test/built-ins/Object/fromEntries/to-property-key.js, test/built-ins/Object/fromEntries/uses-define-semantics.js, test/built-ins/Object/fromEntries/uses-keys-not-iterator.js
See https://github.com/tc39/proposal-object-from-entries. This proposal is stage 3, so these tests should be good to merge.
The [reference implementation](https://github.com/tc39/proposal-object-from-entries/blob/2ccf4e528b441d8da308b76f7db465edcb6803a6/polyfill.js) passes all of these tests.
cc @ljharb
=> Object.fromEntries: add basic tests

harness/regExpUtils.js, test/built-ins/Atomics/wait/no-spurious-wakeup-no-operation.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-digit-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-digit-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-digit-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-digit-class-escape.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-digit-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-digit-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-digit-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-digit-class-escape.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-whitespace-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-whitespace-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-whitespace-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-whitespace-class-escape.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-word-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-word-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-word-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-word-class-escape.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-whitespace-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-whitespace-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-whitespace-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-whitespace-class-escape.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-word-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-word-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-word-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-word-class-escape.js, test/intl402/RelativeTimeFormat/prototype/format/en-us-numeric-auto.js, test/intl402/RelativeTimeFormat/prototype/format/en-us-style-short.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/en-us-numeric-auto.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/en-us-style-short.js
8879820a8f475feb6355c9d496d4481689ca7542
- Reduce time needed for RegExp tests by constructing only one string covering the whole code point range.
- The current approach is too slow in some test configurations, see <https://bugzilla.mozilla.org/show_bug.cgi?id=1483380>.
- With the changes to the test files and the `buildString` helper, the tests run now much faster. For example "character-class-word-class-escape-flags-u.js":
<table>
<tr><td>Engine<td>Before (ms)<td>After (ms)
<tr><td>SpiderMonkey (opt)<td>260<td>55
<tr><td>SpiderMonkey (opt-debug-cgc)<td>~437800 (!!!)<td>90
<tr><td>ChakraCore (opt)<td>370<td>75
<tr><td>V8 (opt)<td>500<td>75
<tr><td>JSC (opt)<td>800<td>80
</table>
0aa1f70c141173d7a4383edd3dd5671068279b31
- Simple typo fix
ab42bd8237ecfc9bab2474d969e4dc0cb1d164bb
- …
=> Reduce time needed in RegExp tests and test fixes

harness/atomicsHelper.js, test/built-ins/Atomics/wait/bigint/false-for-timeout-agent.js, test/built-ins/Atomics/wait/false-for-timeout-agent.js, test/built-ins/Atomics/wait/null-for-timeout-agent.js, test/built-ins/Atomics/wait/object-for-timeout-agent.js, test/built-ins/Atomics/wait/poisoned-object-for-timeout-throws-agent.js, test/built-ins/Atomics/wait/symbol-for-index-throws-agent.js, test/built-ins/Atomics/wait/symbol-for-timeout-throws-agent.js, test/built-ins/Atomics/wait/symbol-for-value-throws-agent.js, test/built-ins/Atomics/wait/true-for-timeout-agent.js
$262.agent.MAX_TIME_EPSILON was intended to be used for callers like `Atomics.wait(typedArray, indexNumber, valueNumber, timeoutNumber)` where all parameters with the `Number` suffix denote values which are already Number values. It should not be used for `Atomics.wait(typedArray, indexObject, valueObject, timeoutObject)` where all parameters with the `Object` suffix denote values which are Object values, because in that case we'd require that `ToNumber(objectValue)` (potentially invoked multiple times) completes in less than 100 milliseconds (the default value for MAX_TIME_EPSILON).
Also removes $262.agent.MAX_TIME_EPSILON because it is now no longer used.
=> Remove requirement that ToNumber(value) completes in less than $262.agent.MAX_TIME_EPSILON

test/built-ins/Array/prototype/flat/proxy-access-count.js, test/built-ins/Array/prototype/flatMap/proxy-access-count.js
Tests for the number of has/get property accesses that occur when using Array.prototype.flat/flatMap.
@ljharb asked me to submit these after my initial implementation of flat and flatMap for chakracore was wrong on this point.
(I haven't signed a CLA here yet so assume I'll need to do that before this is merged)
EDIT: I have now completed a CLA
=> Array.prototype.{flat,flatMap} property access count

test/built-ins/TypedArray/prototype/sort/sort-tonumber.js
This was originally a [bug in spidermonkey](https://bugzilla.mozilla.org/show_bug.cgi?id=1456973).
In it, the result of comparefn was only ran through `ToNumber` upon comparing it to -1/0/1, which has an observable difference in behavior (as this test indicates).
=> TypedArray.prototype.sort: check result of compareFn is immediately converted ToNumber

.travis.yml, CONTRIBUTING.md
Update the recommended invocation of `pip` to use the `python` command,
avoiding discrepancies on systems where the `pip` and `python` commands
are not provided by the same Python installation. In the interest of
consistency, also update the configuration for the project's continuous
integration service.
Recommend additional tooling for users with more advanced needs.
=> Improve documentation for Python usage

implementation-contributed/javascriptcore/stress/regress-189186.js, test/built-ins/DataView/instance-extensibility-sab.js, test/built-ins/DataView/instance-extensibility.js
This adds assertions to confirm extensibility of dataview objects, based on the contributed test from JSC.
See implementation-contributed/javascriptcore/stress/regress-189186.js
=> Assert extensibility of dataview objects

tools/lint/lint.py
Update the lint.py script to work with pip 10+ as pip.req was moved to
pip._internal.req in version 10 onwards and the existing code only works
on versions of pip under or equal to 9.0.3
=> tools: update lint.py to work with pip 10+

test/intl402/NumberFormat/prototype/this-value-not-numberformat.js
Add Intl.NumberFormat.prototype.formatToParts to the test
this-value-not-numberformat.js to check if a TypeError is thrown if the
"this" value for the function call isn't a valid NumberFormat object.
/cc @gsathya @littledan @anba
=> intl: improve coverage for Intl.NumberFormat

implementation-contributed/curation_logs/v8.json, implementation-contributed/v8/mjsunit/compiler/regress-884052.js, implementation-contributed/v8/mjsunit/regress/regress-crbug-884933.js
Changes imported in this pull request include all changes made since
[ceacdcd0](https://github.com///github/blob/ceacdcd0) in V8 and all changes made since [55d559e57](../blob/55d559e57) in
test262.
These are new files added in V8 and have been synced to the
`implementation-contributed/v8` directory.
- [implementation-contributed/v8/mjsunit/compiler/regress-884052.js](../blob/v8-test262-automation-export-55d559e57/implementation-contributed/v8/mjsunit/compiler/regress-884052.js)
- [implementation-contributed/v8/mjsunit/regress/regress-crbug-884933.js](../blob/v8-test262-automation-export-55d559e57/implementation-contributed/v8/mjsunit/regress/regress-crbug-884933.js)
=> Import test changes from V8

test/built-ins/Atomics/notify/undefined-index-defaults-to-zero.js, test/built-ins/String/prototype/trimEnd/this-value-line-terminator.js, test/built-ins/String/prototype/trimEnd/this-value-object-cannot-convert-to-primitive-err.js, test/built-ins/String/prototype/trimEnd/this-value-object-toprimitive-meth-priority.js, test/built-ins/String/prototype/trimEnd/this-value-object-tostring-meth-priority.js, test/built-ins/String/prototype/trimEnd/this-value-object-valueof-meth-priority.js, test/built-ins/String/prototype/trimEnd/this-value-whitespace.js, test/built-ins/String/prototype/trimStart/this-value-line-terminator.js, test/built-ins/String/prototype/trimStart/this-value-object-cannot-convert-to-primitive-err.js, test/built-ins/String/prototype/trimStart/this-value-object-toprimitive-meth-priority.js, test/built-ins/String/prototype/trimStart/this-value-object-tostring-meth-priority.js, test/built-ins/String/prototype/trimStart/this-value-object-valueof-meth-priority.js, test/built-ins/String/prototype/trimStart/this-value-whitespace.js, test/intl402/Locale/constructor-options-casefirst-valid.js, test/intl402/Locale/constructor-options-numeric-valid.js
This doesn't affect correctness, but makes the tests more broadly useful. Also, this is generally a step in the direction of more consistent style (even within individual files, in several cases).
=> Remove some trailing commas in calls

test/intl402/NumberFormat/prototype/formatToParts/default-parameter.js
Add an assertion to the test for default parameters in Intl.NumberFormat's
method formatToParts checking that both the values are equal to the correct
result.
/cc @rwaldron @gsathya
=> intl: add assertion to test that the result for default parameter

test/intl402/NumberFormat/constructor-options-toobject.js
Increase coverage for the Intl.NumberFormat class contructor by adding
tests for checking that it calls ToObject on the options argument.
/cc @rwaldron @gsathya @littledan @anba
=> intl: increase coverage for NumberFormat constructor

test/intl402/Locale/constructor-tag.js
Same as https://github.com/tc39/test262/pull/789
remove "ar-ma-u-ca-islamicc" from test.
=> Remove "ar-ma-u-ca-islamicc" from Locale/constructor-tag.js (Intl402)

test/intl402/NumberFormat/constructor-locales-string.js
Increase coverage for the Intl.NumberFormat constructor by testing that
passing a string value to the Intl.NumberFormat constructor is
equivalent to passing an Array containing the same string value.
=> intl: increase coverage for the NumberFormat constructor

test/intl402/NumberFormat/constructor-locales-arraylike.js
Improve coverage for the Intl.NumberFormat constructor by testing that
it accepts Array-like objects and handles them properly.
/cc @gsathya @rwaldron @littledan @anba
=> intl: increase coverage from the NumberFormat constructor

test/language/reserved-words/unreserved-words.js
I'm not an expert on this, but I'm pretty sure this is supposed to be "undefined" not "undefiend".
=> Fix "undefiend" typo in unreserved-words.js

test/intl402/NumberFormat/constructor-locales-get-tostring.js
Increase coverge for the Intl.NumberFormat constructor by testing that
Get(O, P) and ToString(arg) are properly called.
/cc @gsathya @rwaldron @littledan @anba
=> intl: increase coverage for the Intl.NumberFormat constructor

test/intl402/Locale/constructor-tag-tostring.js
This was introduced in 6581e84949eb0db1a97513098c1413be433419ee.
=> Fix syntax in test

tools/scripts/ci_build.sh
This makes it possible to run the script locally even if `TRAVIS_PULL_REQUEST` is not set.
Currently, it results in an error:
tools/scripts/ci_build.sh: line 2: [: !=: unary operator expected
=> Quote variables in ci_build.sh

test/intl402/ListFormat/constructor/constructor/options-localeMatcher-invalid.js, test/intl402/ListFormat/constructor/constructor/options-order.js
This was added in https://github.com/tc39/proposal-intl-list-format/pull/25.
I don't know how to test that the option has any effect, so this just checks
that it is read and verified.
=> Intl.ListFormat: Add some tests for the localeMatcher constructor option.

src/class-elements/super-private-access-invalid.case
Tracking issues #1343 
Summary of changes:
1. Add test for super property private name early syntax error
=> test: syntax error if superproperty private name access

test/intl402/ListFormat/constructor/constructor/options-style-valid.js, test/intl402/ListFormat/prototype/format/en-us-narrow.js, test/intl402/ListFormat/prototype/formatToParts/en-us-narrow.js
Based on 
https://github.com/tc39/proposal-intl-list-format/issues/16
https://github.com/tc39/proposal-intl-list-format/pull/27 change the spec so we need to change the test that 
1) either assert the throws of RangeError if 'style' is 'narrow' but 'type' is not set to 'unit', OR
2) change the test for 'style': 'narrow' for 'type':'unit'
=> Change tests to reflect https://github.com/tc39/proposal-intl-list-format/pull/27 

test/intl402/ListFormat/constructor/constructor/options-bad-combinations.js
This was changed in https://github.com/tc39/proposal-intl-list-format/pull/27.
=> Intl.ListFormat: Add a test for unsupported options combinations.

test/intl402/ListFormat/constructor/constructor/locales-valid.js, test/intl402/RelativeTimeFormat/constructor/constructor/locales-valid.js
=> Intl.ListFormat / Intl.RelativeTimeFormat: Add some basic tests for CanonicalizeLocaleList.

tools/generation/lib/template.py
This applies the fix from #1821 to the remaining frontmatter properties that consist of lists.
Ref. https://github.com/tc39/test262/pull/1821/files#r222811633.
Ref. #1817.
=> Generation: fix more YAML frontmatter writer to eliminate errant newlines from yaml.dump()

test/intl402/Collator/prototype/resolvedOptions/order.js, test/intl402/DateTimeFormat/constructor-options-order.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/order.js, test/intl402/NumberFormat/prototype/resolvedOptions/order.js, test/intl402/PluralRules/prototype/resolvedOptions/order.js
The order was defined in <https://github.com/tc39/ecma402/pull/279>.
=> Intl: Add tests for table iteration order.

features.txt, test/language/expressions/import.meta/distinct-for-each-module.js, test/language/expressions/import.meta/distinct-for-each-module_FIXTURE.js, test/language/expressions/import.meta/import-meta-is-an-ordinary-object.js, test/language/expressions/import.meta/not-accessible-from-direct-eval.js, test/language/expressions/import.meta/same-object-returned.js, test/language/expressions/import.meta/syntax/escape-sequence-import.js, test/language/expressions/import.meta/syntax/escape-sequence-meta.js, test/language/expressions/import.meta/syntax/goal-async-function-params-or-body.js, test/language/expressions/import.meta/syntax/goal-async-generator-params-or-body.js, test/language/expressions/import.meta/syntax/goal-function-params-or-body.js, test/language/expressions/import.meta/syntax/goal-generator-params-or-body.js, test/language/expressions/import.meta/syntax/goal-module-nested-function.js, test/language/expressions/import.meta/syntax/goal-module.js, test/language/expressions/import.meta/syntax/goal-script.js, test/language/expressions/import.meta/syntax/invalid-assignment-target-array-destructuring-expr.js, test/language/expressions/import.meta/syntax/invalid-assignment-target-array-rest-destructuring-expr.js, test/language/expressions/import.meta/syntax/invalid-assignment-target-assignment-expr.js, test/language/expressions/import.meta/syntax/invalid-assignment-target-for-await-of-loop.js, test/language/expressions/import.meta/syntax/invalid-assignment-target-for-in-loop.js, test/language/expressions/import.meta/syntax/invalid-assignment-target-for-of-loop.js, test/language/expressions/import.meta/syntax/invalid-assignment-target-object-destructuring-expr.js, test/language/expressions/import.meta/syntax/invalid-assignment-target-object-rest-destructuring-expr.js, test/language/expressions/import.meta/syntax/invalid-assignment-target-update-expr.js
Fixes #1342 
For the most part syntax tests, because the properties, prototype, and extensibility state of the `import.meta` object is implementation-dependent.
=> Add initial tests for import.meta

test/intl402/RelativeTimeFormat/prototype/formatToParts/en-us-numeric-always.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/en-us-numeric-auto.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/en-us-style-short.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/pl-pl-style-long.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/pl-pl-style-narrow.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/pl-pl-style-short.js
Fix wrong expectations of
Intl.RelativeTimeFormat.prototype.formatToParts
Add tests to cover "group", "decimal" and "fraction".
Close https://github.com/tc39/test262/issues/1910
=> Fix formatToParts expectation @ RelativeTimeFormat

test/intl402/Segmenter/prototype/segment/segment-line-following-modes.js
@jungshik @Ms2ger @littledan  This test is based on my work in v8 but my original expectation is too restrict to icu62 and not general enough for newer version of CLDR pull int by icu63
=> In en/ko/fr 'loose' may break more than normal in new CLDR version

test/built-ins/RegExp/CharacterClassEscapes/character-class-digit-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-digit-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-digit-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-digit-class-escape.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-digit-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-digit-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-digit-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-digit-class-escape.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-whitespace-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-whitespace-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-whitespace-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-whitespace-class-escape.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-word-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-word-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-word-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-non-word-class-escape.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-whitespace-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-whitespace-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-whitespace-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-whitespace-class-escape.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-word-class-escape-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-word-class-escape-plus-quantifier-flags-u.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-word-class-escape-plus-quantifier.js, test/built-ins/RegExp/CharacterClassEscapes/character-class-word-class-escape.js
Previously, these tests simply compared against an equivalent regular expression pattern by generating a large string containing either all code points up to U+FFFF or U+10FFFF, depending on the `u` flag, and then performing:
```js
str.replace(re, '') === str.replace(otherRe, '');
```
These two `String#replace` calls can be optimized into a single `RegExp#test` call by following the pattern used in the property escapes tests at https://github.com/mathiasbynens/unicode-property-escapes-tests. Furthermore, the strings to be tested can be made smaller by only testing the relevant characters for the particular pattern; the inverse pattern is tested separately anyhow.
--- 
```sh
time test262-harness --test262Dir="$HOME/projects/test262" --hostPath="$HOME/.jsvu/v8" --hostType=d8 …
```
=> Optimize RegExp character class escape tests

test/intl402/DateTimeFormat/constructor-default-value.js
Increase coverage for the Intl.DateTimeFormat constructor by adding a
test that checks for the default values.
/cc @gsathya @rwaldron @littledan
=> intl: increase coverage for DateTimeFormat

test/built-ins/Function/prototype/toString/proxy-async-generator-function.js, test/built-ins/Function/prototype/toString/proxy-async-generator-method-definition.js, test/language/expressions/await/async-generator-interleaved.js
These tests use async generators, which I understand are meant to be included in the `async-iteration` flag.
=> add async-iteration flag

test/built-ins/Proxy/getOwnPropertyDescriptor/call-parameters.js, test/built-ins/Proxy/getOwnPropertyDescriptor/result-type-is-not-object-nor-undefined.js
- `Proxy/getOwnPropertyDescriptor/call-parameters.js`
Fixes a call to `Object.getOwnPropertyDescriptor` without the prop
param. Not actually a huge problem, as the test wasn't depending on
it.
- `Proxy/getOwnPropertyDescriptor/result-type-is-not-object-nor-undefined`
This test asserted that `function() {}` should throw with the
following spec step, which is incorrect, as functions are typed as
`Object` in the spec.
`1. If Type(trapResultObj) is neither Object nor Undefined, throw a
TypeError exception.`
=> Fix some proxy tests

test/language/expressions/dynamic-import/indirect-resolution-1_FIXTURE.js, test/language/expressions/dynamic-import/namespace/default-property-not-set-own.js
Hi,
This is to fix what I think are a couple of minor issues in the new dynamic import tests:
- indirect-resolution-1_FIXTURE.js has a bare import specifier.  This should be a relative specifier to find the indirect-resolution-2_FIXTURE.js module.
- default-property-not-set-own.js should be marked as a module, so that when it imports itself it doesn't get run again.  If this happens $DONE will complain about being called twice.
=> Fix a couple of minor issues in dynamic-import tests

src/class-elements/prod-private-async-method.case, test/built-ins/Array/prototype/flatMap/non-callable-argument-throws.js, test/built-ins/Reflect/ownKeys/return-on-corresponding-order-large-index.js, test/intl402/NumberFormat/currencyDisplay-unit.js, test/intl402/NumberFormat/style-unit.js, test/intl402/Segmenter/iterator/following.js, test/intl402/Segmenter/iterator/granularity.js, test/intl402/Segmenter/iterator/preceding.js, test/intl402/Segmenter/prototype/segment/segment-line.js, test/intl402/Segmenter/prototype/segment/segment-sentence.js, test/intl402/Segmenter/prototype/segment/segment-word.js, test/language/expressions/class/private-methods/prod-private-async-method.js, test/language/statements/class/private-methods/prod-private-async-method.js
- src/class-elements/prod-private-async-method.case
- test/language/expressions/class/private-methods/prod-private-async-method.js
- test/language/statements/class/private-methods/prod-private-async-method.js
- Use the `value` argument instead of calling `#m()` again, because the latter returns a new Promise object.
- test/built-ins/Array/prototype/flatMap/non-callable-argument-throws.js
- `assert(...)` requires a boolean argument, switch to `assert.sameValue(...)`
- test/built-ins/Reflect/ownKeys/return-on-corresponding-order-large-index.js
- Update test case per https://github.com/tc39/ecma262/pull/1242
- Also add `4294967294` (maximum array index) and `4294967295` (not an array index) while there.
- test/intl402/NumberFormat/currencyDisplay-unit.js
- The option value is "narrow-symbol" …
=> Fix various bugs in test cases

test/built-ins/String/prototype/matchAll/regexp-is-undefined-or-null-invokes-matchAll.js, test/built-ins/String/prototype/matchAll/regexp-matchAll-is-undefined-or-null.js, test/built-ins/String/prototype/matchAll/regexp-matchAll-not-callable.js, test/built-ins/String/prototype/matchAll/toString-this-val.js
- Changes associated with spec changes (tc39/proposal-string-matchall#41)
- Update spec comments
- Added test verifying error thrown when `regexp[Symbol.matchAll]` is not callable
- Added test verifying `ToString` is called on `receiver`
=> Update tests for String.prototype.matchAll

test/language/expressions/object/method-definition/generator-super-prop-param.js
This broke my (admittedly terrible) feature parser. Although I guess the requirement is that it is valid YAML, which it currently is. Still, the formatting is very consistent except for this case.
=> Remove extra spaces from features list

test/built-ins/Object/fromEntries/requires-argument.js
This makes v8's _monkeyYaml happy --- without it, the info block never ends, and we fail to parse the `features` key.
An explicit indentation marker isn't used because monkeyYaml doesn't supported it, and adding it might slightly slow things down.
Using PyYAML instead was considered, but after trying it, I don't think it looks viable. [simple test cases](https://gist.github.com/caitp/4a59a67f671907c11051a1b7bd5fdaae)
=> Get rid of the leading empty line in info block

src/class-elements/prod-private-method-initialize-order.case, test/language/expressions/class/private-methods/prod-private-method-initialize-order.js, test/language/statements/class/private-methods/prod-private-method-initialize-order.js
Adds a test calling private methods from field initializers – according to the test plan posted in #1343.
> Execution order -- private methods are added before any field initializer is run, even if they appear textually later
I will commit the generated tests once the PR is approved.
cc: @littledan @jbhoosreddy
=> test: Ensure private methods are visible from all initializers

test/annexB/built-ins/String/prototype/trimLeft/name.js, test/annexB/built-ins/String/prototype/trimRight/name.js, test/built-ins/ArrayBuffer/Symbol.species/symbol-species.js, test/built-ins/Object/is/symbol-object-is-same-value.js, test/language/statements/for-of/body-dstr-assign-error.js, test/language/statements/for-of/body-dstr-assign.js, test/language/statements/for-of/body-put-error.js
I think this is all of the tests now - they all work with my really basic parser:
`line[len("features: ["):-2].split(", ")`
=> Consistently use spaces in features lists

test/intl402/RelativeTimeFormat/constructor/constructor/locales-invalid.js
Fix "TypeError: Cannot convert a Symbol value to a string" problem caused by 
printing ${String(locales)}
in https://github.com/tc39/test262/pull/2001
@leobalter @rwaldron
=> remove "TypeError: Cannot convert a Symbol value to a string"

test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-ctor-abrupt.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-ctor-inherited.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-ctor-returns-throws.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-ctor.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-species-abrupt.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-species-custom-ctor-invocation.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-species-custom-ctor-length-throws.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-species-custom-ctor-length.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-species-custom-ctor-returns-another-instance.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-species-custom-ctor-throws.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-species-custom-ctor.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-species-returns-throws.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-species-use-default-ctor.js, test/built-ins/TypedArray/prototype/map/BigInt/speciesctor-get-species.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-ctor-abrupt.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-ctor-inherited.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-ctor-returns-throws.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-ctor.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-species-abrupt.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-species-custom-ctor-invocation.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-species-custom-ctor-length-throws.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-species-custom-ctor-length.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-species-custom-ctor-returns-another-instance.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-species-custom-ctor-throws.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-species-custom-ctor.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-species-returns-throws.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-species-use-default-ctor.js, test/built-ins/TypedArray/prototype/map/speciesctor-get-species.js
When comparing test coverage between `%TypedArray%.prototype.filter`, I noticed `%TypedArray%.prototype.map` tests didn't cover species constructors.
This PR essentially ports over the test coverage for species constructor from `%TypedArray%.prototype.filter`.
=> Increase coverage for %TypedArray%.prototype.map with species constructor

test/language/expressions/arrow-function/params-duplicate.js, test/language/expressions/async-arrow-function/early-errors-arrow-duplicate-parameters.js, test/language/expressions/object/method-definition/early-errors-object-async-method-duplicate-parameters.js, test/language/expressions/object/method-definition/early-errors-object-method-duplicate-parameters.js, test/language/statements/class/definition/early-errors-class-async-method-duplicate-parameters.js
Previously, the early error prohibiting duplicate entries in
UniqueFormalParameters was only tested in terms of async functions. In
one case, this was misattributed to UniqeFormalParameters and only
enforced for strict mode code.
Extend coverage to the other function-creating productions which include
UniqueFormalParameters (i.e. method definitions and non-async arrow
functions), and update the existing tests to more accurately describe
the source of the error.
---
Found some missing coverage while implementing some of this for JSHint. @bterlson might want to take a look.
=> Improve coverage for UniqueFormalParameters

test/intl402/Locale/constructor-options-language-valid-undefined.js, test/intl402/Locale/constructor-options-language-valid.js
Per https://github.com/tc39/proposal-intl-locale/pull/66 we switch to support Unicode Locale Identifier. And therefore the following in RFC 5646 are no longer supportive:
2*3ALPHA "-" extlang           ; shortest ISO 639 code followed by extended language subtags
and
4ALPHA
in "langage"
While "extlang" is 
" extlang       = 3ALPHA              ; selected ISO 639 codes
*2("-" 3ALPHA)      ; permanently reserved"
in UTS35, unicode_language_subtag is only
unicode_language_subtag = alpha{2,3} | alpha{5,8};
So this PR remove the test of language as 2*3ALPHA "-" extlang  or 4ALPHA
=> Remove test of extlang and 4 letter language

test/intl402/Collator/missing-unicode-ext-value-defaults-to-true.js
Add test for case of -kn-true
Verify no -kn-true nor -kn-false in the returned locale.
Change expectation per 
@littledan @anba @Ms2ger @gsathya @zbraniecki
=> Change test for -kn

test/language/expressions/postfix-decrement/arguments-nostrict.js, test/language/expressions/postfix-decrement/eval-nostrict.js, test/language/expressions/postfix-increment/arguments-nostrict.js, test/language/expressions/postfix-increment/eval-nostrict.js, test/language/expressions/prefix-decrement/arguments-nostrict.js, test/language/expressions/prefix-decrement/eval-nostrict.js, test/language/expressions/prefix-increment/arguments-nostrict.js, test/language/expressions/prefix-increment/eval-nostrict.js
According to sec-identifiers-static-semantics-assignmenttargettype,
`AssignmentTargetType` of `arguments` and `eval` in non-strict mode code is
`simple`.
sec-update-expressions-static-semantics-early-errors mandates early errors for
`UpdateExpression` if `AssignmentTargetType` is `invalid` or `strict`.
These were introduced in #2005.
=> UpdateExpressions: No early error for arguments and eval in non-strict mode

test/intl402/Intl/getCanonicalLocales/Locale-object.js
To sync with the latest spec which referring to UTS35
=> change irregular grandfather tag to it's canonical

test/built-ins/Array/prototype/Symbol.unscopables/value.js
This implements the change to `Array.prototype[@@unscopables]` in the flat/flatMap proposal (stage 4). Relevant spec PR: https://github.com/tc39/ecma262/pull/1309
=> add flat/flatMap to Array unscopables

test/intl402/Locale/extensions-grandfathered.js, test/intl402/Locale/getters-grandfathered.js, test/intl402/Locale/likely-subtags-grandfathered.js
'cel-gaulish', according to https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
is 
"
Type: grandfathered
Tag: cel-gaulish
Description: Gaulish
Added: 2001-05-25
Deprecated: 2015-03-29
Comments: see xcg, xga, xtg
"
I think there are no point to test a deprecated + grandfathered tag regardless what behavior it should be. It is pointless to assure the quality of ECMA toward a deprecated grandfathered tag.
=> Remove 'cel-gaulish' from test

test/language/computed-property-names/class/static/method-number.js, test/language/computed-property-names/class/static/method-string.js, test/language/computed-property-names/class/static/method-symbol.js, test/language/expressions/class/elements/class-name-static-initializer-anonymous.js, test/language/expressions/class/elements/class-name-static-initializer-decl.js, test/language/expressions/class/elements/class-name-static-initializer-default-export.js, test/language/expressions/class/elements/class-name-static-initializer-expr.js
- Updates three existing tests now that "name" is added directly after "prototype".
- Adds new tests for the case which motivated the spec change.
Spec PR: tc39/ecma262#1372
=> Add tests for setting class-name in ClassDefinitionEvaluation

test/language/expressions/object/prop-def-invalid-star-prefix.js
Counterpart to language/expressions/object/prop-def-invalid-async-prefix.js.
=> Add test for ({* identifier})

test/intl402/Locale/constructor-tag.js
WebKit SVN choked on this as I was performing a test import today.
=> Remove errant tab character.

test/intl402/Intl/getCanonicalLocales/grandfathered.js, test/intl402/Intl/getCanonicalLocales/non-iana-canon.js, test/intl402/Locale/constructor-non-iana-canon.js, test/intl402/Locale/likely-subtags-grandfathered.js
I found some of our tests for Locale failed on the result of Intl.getCanonicalLocales which should not be part of the verification for Locale but instead for getCanonicalLocales so I MOVE these test from Locale under Intl/getCanonicalLocales to make us have better picture which PART is failing.
=> Split Intl.getCanonicalLocales from Locale

test/intl402/Locale/constructor-non-iana-canon.js
Per  https://tc39.github.io/ecma402/#sec-canonicalizelanguagetag
*6.2.3 CanonicalizeLanguageTag ( locale )*
```
The CanonicalizeLanguageTag abstract operation returns the canonical and 
case-regularized form of the locale argument (which must be a String value that is a 
structurally valid Unicode BCP 47 Locale Identifier as verified by the 
IsStructurallyValidLanguageTag abstract operation). A conforming implementation 
shall take the steps specified in the “BCP 47 Language Tag to Unicode BCP 47 
Locale Identifier” algorithm, from Unicode Technical Standard #35 LDML § 3.3.1 
BCP 47 Language Tag Conversion.
```
And
http://unicode.org/reports/tr35/#BCP_47_Language_Tag_Conversion
```
2. If the BCP 47 primary language subtag matches the type attribute of a 
languageAlias element in …
```
=> correct value that matches languageAlias 

src/class-elements/grammar-private-field-on-object-destructuring.case, test/language/expressions/class/elements/syntax/early-errors/grammar-private-field-on-object-destructuring.js, test/language/statements/class/elements/syntax/early-errors/grammar-private-field-on-object-destructuring.js
=> Added case to verify invalid syntax when using private field on object destructuring

test/built-ins/RegExp/regexp-class-chars.js
This was the source of a regression in a parser I maintain. It was a pretty naive mistake to make, but I think it's reasonable to expect Test262 to cover this case.
=> Test forward slash in RegularExpressionClassChar

test/intl402/Locale/likely-subtags-grandfathered.js
The regular grandfather tag will be canonicalized to something else so such check is not reasonable.
"art-lojban-fonipa" will be canonicalized to "jbo-fonipa"
"art-lojban-a-not-assigned" will be canonicalized to "jbo-a-not-assigned"
"art-lojban-u-attr" will be canonicalized to "jbo-u-attr"
"art-lojban-u-co" will be canonicalized to "jbo-u-co"
"art-lojban-u-co-phonebk" will be canonicalized to "jbo-u-co-phonebk"
"art-lojban-x-private" will be canonicalized to "jbo-x-private"
so we should remove the 
assert.sameValue(loc.toString(), tag + "-" + extra);  check.
=> Remove unreasonable expectation

test/built-ins/JSON/stringify/bigint-tojson-receiver.js
Spec link:
https://tc39.github.io/proposal-bigint/#sec-serializejsonproperty
Thanks to André Bargull for the test:
https://bugzilla.mozilla.org/show_bug.cgi?id=1528784
=> Add new test for receiver of toJSON on bigint values

test/built-ins/BigInt/asIntN/bigint-tobigint-errors.js, test/built-ins/BigInt/asUintN/bigint-tobigint-errors.js
BigInt.asIntN and BigInt.asUintN should throw TypeErrors when the required bigint argument is not present
See https://bugzilla.mozilla.org/show_bug.cgi?id=1526279
=> Add tests for calling BigInt functions with fewer arguments than required

tools/packaging/parseTestRecord.py, tools/packaging/test/fixtures/test262-yaml-headers-no-cr.js, tools/packaging/test/test_common.py, tools/packaging/test/test_parseTestRecord.py
This should work for the hashbang tests.
Note that this is legacy code and I'm first trying to implement a fix and we can later improve this script. The change is conservative to preserve legacy functionality as I'm avoiding breaking other things.
Fixes #2080 
cc @caitp @gsathya I appreciate if you could take a look on this one, thanks.
=> Fix parseTestRecord.py for optional top license header

test/language/statements/async-generator/return-undefined-implicit-and-explicit.js, test/language/statements/async-generator/yield-return-then-getter-ticks.js, test/language/statements/async-generator/yield-star-async-from-sync-iterator-inaccessible.js, test/language/statements/async-generator/yield-star-normal-notdone-iter-value-throws.js, test/language/statements/async-generator/yield-star-return-notdone-iter-value-throws.js, test/language/statements/async-generator/yield-star-return-then-getter-ticks.js, test/language/statements/async-generator/yield-star-throw-notdone-iter-value-throws.js, test/language/statements/for-await-of/async-from-sync-iterator-continuation-abrupt-completion-get-constructor.js, test/language/statements/for-await-of/ticks-with-async-iter-resolved-promise-and-constructor-lookup-two.js, test/language/statements/for-await-of/ticks-with-async-iter-resolved-promise-and-constructor-lookup.js, test/language/statements/for-await-of/ticks-with-sync-iter-resolved-promise-and-constructor-lookup.js
Test cases for <https://bugzilla.mozilla.org/show_bug.cgi?id=1530754> and other related issues I found (or found again), like tc39/ecma262#1474 and tc39/ecma262#1470, while working on that bug. 
SpiderMonkey passes these tests locally with <https://bugzilla.mozilla.org/show_bug.cgi?id=1530754> fixed. (Some of the tests fail on V8/JSC, so don't be surprised if you see any errors.)
=> Test cases for async function and async generator edge-cases

CONTRIBUTING.md
* Use consistent ordering for documenting test frontmatter keys
* Update vocabulary for consistency with [YAML](https://yaml.org/spec/1.2/spec.html#id2761292)
* Improve formatting
* Provide more useful and realistic test examples (with format derived from test/language/expressions/dynamic-import)
Best viewed as a rich diff.
=> Improve content and style of contribution guidelines

test/intl402/ListFormat/prototype/format/en-us-short.js, test/intl402/ListFormat/prototype/formatToParts/en-us-short.js
update list pattern to sync with CLDR 35
CLDR 35 change "and" to "&" for the list form pattern "short"
see https://unicode.org/cldr/trac/ticket/11520
Also compare
https://www.unicode.org/repos/cldr/tags/release-34/common/main/en.xml
against
https://www.unicode.org/repos/cldr/tags/release-35-beta/common/main/en.xml
Notice the addition of
```
<listPattern type="standard-short">
<listPatternPart type="start">{0}, {1}</listPatternPart>
<listPatternPart type="middle">{0}, {1}</listPatternPart>
<listPatternPart type="end">{0}, & {1}</listPatternPart>
<listPatternPart type="2">{0} & {1}</listPatternPart>
</listPattern>
```
=> Update list pattern to sync with CLDR 35

test/built-ins/Proxy/getPrototypeOf/instanceof-return-true.js
Note: V8 currently fails the test.
See https://bugs.chromium.org/p/v8/issues/detail?id=9036
=> Add test that a Proxy instance with getPrototypeOf trap use instanceof operator on a function

test/intl402/BigInt/prototype/toLocaleString/builtin.js, test/intl402/BigInt/prototype/toLocaleString/default-options-object-prototype.js, test/intl402/BigInt/prototype/toLocaleString/en-US.js, test/intl402/BigInt/prototype/toLocaleString/length.js, test/intl402/BigInt/prototype/toLocaleString/name.js, test/intl402/BigInt/prototype/toLocaleString/prop-desc.js, test/intl402/BigInt/prototype/toLocaleString/returns-same-results-as-NumberFormat.js, test/intl402/BigInt/prototype/toLocaleString/taint-Intl-NumberFormat.js, test/intl402/BigInt/prototype/toLocaleString/this-value-invalid.js, test/intl402/BigInt/prototype/toLocaleString/throws-same-exceptions-as-NumberFormat.js
Many of these tests are heavily based on the tests for
Number.prototype.toLocaleString().
=> Initial tests for BigInt.prototype.toLocaleString().

test/language/module-code/instn-iee-bndng-cls.js, test/language/module-code/instn-iee-bndng-cls_FIXTURE.js, test/language/module-code/instn-iee-bndng-const.js, test/language/module-code/instn-iee-bndng-const_FIXTURE.js, test/language/module-code/instn-iee-bndng-fun.js, test/language/module-code/instn-iee-bndng-fun_FIXTURE.js, test/language/module-code/instn-iee-bndng-gen.js, test/language/module-code/instn-iee-bndng-gen_FIXTURE.js, test/language/module-code/instn-iee-bndng-let.js, test/language/module-code/instn-iee-bndng-let_FIXTURE.js, test/language/module-code/instn-iee-bndng-var.js, test/language/module-code/instn-iee-bndng-var_FIXTURE.js
```
rwaldron in ~/clonez/test262 on master
$ test262_runner test/language/module-code/instn-iee-bndng-{cls,const,fun,gen,let,var}.js
-----------------------------------------------------------------------------------------
V8 (jsvu)
test262-harness --hostArgs='' --hostType=d8 --hostPath=/Users/rwaldron/.jsvu/v8 test/language/module-code/instn-iee-bndng-cls.js test/language/module-code/instn-iee-bndng-const.js test/language/module-code/instn-iee-bndng-fun.js test/language/module-code/instn-iee-bndng-gen.js test/language/module-code/instn-iee-bndng-let.js test/language/module-code/instn-iee-bndng-var.js
Ran 12 tests
12 passed
0 failed
-----------------------------------------------------------------------------------------
ChakraCore (jsvu)
test262-harness --hostArgs='' --hostType=ch …
```
=> Refactor module _FIXTURE.js to have no harness dependencies

INTERPRETING.md
@jugglinmike @leobalter This change simply codifies the predominant pattern in Test262. There were 6 total _FIXTURE.js files that used assertions, but those have been updated in #2129.
=> INTERPRETING.md: explicitly disallow use of Test262-Defined Bindings and Host-Defined Functions in _FIXTURE.js files

test/built-ins/Promise/all/capability-executor-called-twice.js, test/built-ins/Promise/all/capability-executor-not-callable.js, test/built-ins/Promise/all/capability-resolve-throws-no-close.js, test/built-ins/Promise/all/capability-resolve-throws-reject.js, test/built-ins/Promise/all/invoke-resolve-error-close.js, test/built-ins/Promise/all/invoke-resolve-get-error-close.js, test/built-ins/Promise/all/invoke-resolve-get-error-reject.js, test/built-ins/Promise/all/invoke-resolve-get-once-multiple-calls.js, test/built-ins/Promise/all/invoke-resolve-get-once-no-calls.js, test/built-ins/Promise/all/species-get-error.js, test/built-ins/Promise/allSettled/capability-executor-called-twice.js, test/built-ins/Promise/allSettled/capability-executor-not-callable.js, test/built-ins/Promise/allSettled/capability-resolve-throws-no-close.js, test/built-ins/Promise/allSettled/capability-resolve-throws-reject.js, test/built-ins/Promise/allSettled/invoke-resolve-get-error-close.js, test/built-ins/Promise/allSettled/species-get-error.js, test/built-ins/Promise/race/capability-executor-called-twice.js, test/built-ins/Promise/race/invoke-resolve-get-error-close.js, test/built-ins/Promise/race/invoke-resolve-get-once-multiple-calls.js, test/built-ins/Promise/race/invoke-resolve-get-once-no-calls.js, test/built-ins/Promise/race/species-get-error.js
Ref tc39/ecma262#1506
The proposed spec needs consensus, please don't merge this yet.
=> Add tests for Promise.all|race resolve lookup

tools/scripts/ci_lint.sh, tools/scripts/ci_test.sh
the double dot gets only commits not in the left side of the double dot.
The right side assumes HEAD.
This will allow us to fetch the correct list of new or modified files in the current branch.
Ref #2137
=> Use .. for git diffs in the CI routines

.circleci/config.yml, package.json
This is just helper scripts with parts I use everyday.
@mathiasbynens Ideally I'd love to set jsvu to use a custom folder inside my project's path. This would be very helpful for the CI tools as well as CircleCI's docker get's bonkers with the current path outside, regardless I add anything to the PATH for jsvu.
the `npm test` is literally just a shortcut for the local test262-harness.
=> Set npm scripts to run tests

test/built-ins/Proxy/defineProperty/targetdesc-not-configurable-writable-desc-not-writable.js, test/built-ins/Proxy/deleteProperty/targetdesc-is-configurable-target-is-not-extensible.js, test/built-ins/Proxy/getOwnPropertyDescriptor/resultdesc-is-not-configurable-not-writable-targetdesc-is-writable.js
Spec PR: tc39/ecma262#666.
Closes #2142.
=> Add tests for Proxy semantics change

src/class-elements/grammar-private-environment-on-class-heritage-array-literal.case, src/class-elements/grammar-private-environment-on-class-heritage-chained-usage.case, src/class-elements/grammar-private-environment-on-class-heritage-function-expression.case, src/class-elements/grammar-private-environment-on-class-heritage-obj-literal.case, src/class-elements/grammar-private-environment-on-class-heritage-recursive.case, src/class-elements/grammar-private-environment-on-class-heritage.case, test/language/expressions/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage-array-literal.js, test/language/expressions/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage-chained-usage.js, test/language/expressions/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage-function-expression.js, test/language/expressions/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage-obj-literal.js, test/language/expressions/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage-recursive.js, test/language/expressions/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage.js, test/language/statements/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage-array-literal.js, test/language/statements/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage-chained-usage.js, test/language/statements/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage-function-expression.js, test/language/statements/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage-obj-literal.js, test/language/statements/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage-recursive.js, test/language/statements/class/elements/syntax/early-errors/grammar-private-environment-on-class-heritage.js
It closes #2141.
This case is relevant because implementors can misunderstand how to properly set `PrivateEnvironment` when evaluating classes, since it differs from `LexicalEnvironment`.
=> Adding case to verify if PrivateEnvironment is properly set when evaluating 'ClassHeritage'

test/language/statements/class/elements/private-getter-brand-check-multiple-evaluations-of-class.js, test/language/statements/class/elements/private-getter-brand-check-super-class.js, test/language/statements/class/elements/private-getter-brand-check.js, test/language/statements/class/elements/private-method-brand-check-multiple-evaluations-of-class.js, test/language/statements/class/elements/private-method-brand-check-super-class.js, test/language/statements/class/elements/private-method-brand-check.js, test/language/statements/class/elements/private-setter-brand-check-multiple-evaluations-of-class.js, test/language/statements/class/elements/private-setter-brand-check-super-class.js, test/language/statements/class/elements/private-setter-brand-check.js
It closes #2151.
Cases we are adding:
1. Try to access a private method with an object that is not instance of the class where method/accessor is defined.
2. Multiple evaluations of a `class` generates different PrivateNames.
3. Super class private methods are accessible by subclass's object.
=> Adding private brand check cases for private methods, getters and setters.

test/built-ins/Proxy/apply/call-parameters.js, test/built-ins/Proxy/apply/call-result.js, test/built-ins/Proxy/apply/null-handler-realm.js, test/built-ins/Proxy/apply/null-handler.js, test/built-ins/Proxy/apply/return-abrupt.js, test/built-ins/Proxy/apply/trap-is-not-callable.js, test/built-ins/Proxy/apply/trap-is-null.js, test/built-ins/Proxy/apply/trap-is-undefined-no-property.js, test/built-ins/Proxy/apply/trap-is-undefined.js
I would really love feedback on 2a65c06: I assert that [`[[Call]]`](https://tc39.github.io/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-call-thisargument-argumentslist) method of proxies does `.[[Call]]` on the target, not just making ordinary [`[[Call]`](https://tc39.github.io/ecma262/#sec-ecmascript-function-objects-call-thisargument-argumentslist).
There are [similar tests](https://github.com/tc39/test262/blob/2682ab57cf61796b503575b81bd73dc69c10e372/implementation-contributed/javascriptcore/stress/proxy-get-set-correct-receiver.js#L94) for `[[Get]]` and `[[Set]]`, contributed by JSC team.
Follow-up of #1075.
=> Improve Proxy/apply coverage

test/intl402/NumberFormat/style-unit.js
https://github.com/tc39/proposal-unified-intl-numberformat/pull/42 removed 'generic'. So we need to change the value to a still valid unit.
@sffc @littledan @leobalter
=> change the removed unit 'generic' to 'gigabit'

test/intl402/DateTimeFormat/numbering-system-calendar-options.js, test/intl402/NumberFormat/numbering-system-options.js
This patch implements tests for the ECMA 402 PR at
https://github.com/tc39/ecma402/pull/175 . It should not land until that spec patch lands.
It is based on the test test/intl402/Collator/10.1.1_19_c.js
=> intl tests for proposed additional options in options bag

tools/generation/generator.py
PEP-8 formatted.
<details>
<summary>macOS stack trace (running make.py)</summary>
```
Running target: build
> /usr/bin/python tools/generation/generator.py create --out test src
Traceback (most recent call last):
File "tools/generation/generator.py", line 95, in <module>
args.func(args)
File "tools/generation/generator.py", line 49, in create
for test in exp.expand('utf-8', caseFile):
File "/Users/admin/test262/tools/generation/lib/expander.py", line 49, in expand
for case_file in case_files:
File "/Users/admin/test262/tools/generation/lib/expander.py", line 38, in list_cases
for name in os.listdir(self.case_dir):
OSError: [Errno 20] Not a directory: 'src/.DS_Store'
Traceback (most recent call last):
File "./make.py", line 78, in <module>
targets['build']()
File "./make.py", line 34, in …
```
=> Skip hidden files in generator.py

src/class-elements/prod-private-getter-before-super-return-in-constructor.case, src/class-elements/prod-private-getter-before-super-return-in-field-initializer.case, src/class-elements/prod-private-method-before-super-return-in-constructor.case, src/class-elements/prod-private-method-before-super-return-in-field-initializer.case, src/class-elements/prod-private-setter-before-super-return-in-constructor.case, src/class-elements/prod-private-setter-before-super-return-in-field-initializer.case, test/language/expressions/class/elements/prod-private-getter-before-super-return-in-constructor.js, test/language/expressions/class/elements/prod-private-getter-before-super-return-in-field-initializer.js, test/language/expressions/class/elements/prod-private-method-before-super-return-in-constructor.js, test/language/expressions/class/elements/prod-private-method-before-super-return-in-field-initializer.js, test/language/expressions/class/elements/prod-private-setter-before-super-return-in-constructor.js, test/language/expressions/class/elements/prod-private-setter-before-super-return-in-field-initializer.js, test/language/statements/class/elements/prod-private-getter-before-super-return-in-constructor.js, test/language/statements/class/elements/prod-private-getter-before-super-return-in-field-initializer.js, test/language/statements/class/elements/prod-private-method-before-super-return-in-constructor.js, test/language/statements/class/elements/prod-private-method-before-super-return-in-field-initializer.js, test/language/statements/class/elements/prod-private-setter-before-super-return-in-constructor.js, test/language/statements/class/elements/prod-private-setter-before-super-return-in-field-initializer.js
Adds tests calling private methods before super is constructed - according to the test plan posted in #1343.
>  Private methods are installed "when super returns" and no earlier. A similar test is possible with field initializers instead of code called in the constructor.
I will commit the generated tests once the PR is approved.
cc: @littledan @jbhoosreddy @caiolima
=> Check private methods are not installed before super returns

test/language/statements/class/elements/class-field-is-observable-by-proxy.js, test/language/statements/class/elements/class-field-on-frozen-objects.js, test/language/statements/class/elements/private-class-field-on-frozen-objects.js, test/language/statements/class/elements/public-class-field-initialization-is-visible-to-proxy.js, test/language/statements/class/elements/public-class-field-initialization-on-super-class-with-setter.js
This PR is adding following missing cases:
1. Following the Spec, `DefineField(receiver, fieldRecord)` calls `CreateDataPropertyOrThrow(receiver, fieldName, initValue)` and this operation can be user observable.
2. Frozen objects can't be changed.
3. `[[DefineOwnProperty]]` is used to define a public field, and it doesn't call setter of `Super`.
CC: @leobalter @caitp @xanlpz
=> Adding new test cases to validate public class fields initialization.

test/intl402/NumberFormat/prototype/resolvedOptions/order.js
Per change in https://tc39.github.io/proposal-unified-intl-numberformat/section11/numberformat_diff_out.html
we should not output minimumFractionDigits and maximumFractionDigits if minimumSignificantDigits or maximumSignificantDigits are set.
=> remove (min|max)imumFractionDigits w/ significant

test/built-ins/Object/subclass-object-arg.js
[Matthew's tweet](https://twitter.com/matthewcp/status/1131328938347773952).
This is definitely `Object`-specific issue.
<details>
<summary>Extending user-defined constructors that return objects works as expected across browsers.</summary>
```js
class A {
constructor(arg) {
return arg;
}
}
class B extends A {}
let b = new B({a: 1});
b.a // => 1
```
</details>
=> Add Object subclass test

test/intl402/RelativeTimeFormat/prototype/format/en-us-numeric-auto.js
As of CLDR v34 this seems to be the case.
=> add exceptions for hour & minute in Intl.RelativeTimeFormat numeric auto

test/language/identifiers/vals-cjk-escaped.js, test/language/identifiers/vals-cjk.js
Add test to ensure CJK character is fully included.
Some parser only included first and last character in CJK, maybe caused by confusion in UnicodeData.txt:
```
4DFE;HEXAGRAM FOR AFTER COMPLETION;So;0;ON;;;;;N;;;;;
4DFF;HEXAGRAM FOR BEFORE COMPLETION;So;0;ON;;;;;N;;;;;
4E00;<CJK Ideograph, First>;Lo;0;L;;;;;N;;;;;
9FEF;<CJK Ideograph, Last>;Lo;0;L;;;;;N;;;;;
A000;YI SYLLABLE IT;Lo;0;L;;;;;N;;;;;
A001;YI SYLLABLE IX;Lo;0;L;;;;;N;;;;;
```
=> Add test case for CJK Unified Ideograph range.

test/language/expressions/class/poisoned-underscore-proto.js, test/language/expressions/super/call-poisoned-underscore-proto.js, test/language/expressions/super/prop-poisoned-underscore-proto.js, test/language/statements/class/poisoned-underscore-proto.js
JSC bug: [super should not depend on `__proto__`](https://bugs.webkit.org/show_bug.cgi?id=157972).
=> Add poisoned __proto__ tests

test/built-ins/Function/StrictFunction_restricted-properties.js, test/built-ins/Function/prototype/bind/BoundFunction_restricted-properties.js, test/built-ins/Function/prototype/restricted-property-arguments.js, test/built-ins/Function/prototype/restricted-property-caller.js, test/language/expressions/arrow-function/ArrowFunction_restricted-properties.js, test/language/statements/function/13.2-30-s.js
This makes 7 tests pass in JSC:
```yaml
test/built-ins/Function/StrictFunction_restricted-properties.js:
default: 'Test262Error: Expected a TypeError to be thrown but no exception was thrown at all'
test/built-ins/Function/prototype/restricted-property-arguments.js:
default: "ReferenceError: Can't find variable: verifyNotEnumerable"
strict mode: "ReferenceError: Can't find variable: verifyNotEnumerable"
test/built-ins/Function/prototype/restricted-property-caller.js:
default: "ReferenceError: Can't find variable: verifyNotEnumerable"
strict mode: "ReferenceError: Can't find variable: verifyNotEnumerable"
```
JSC issue: [test262-runner misbehaves when test file YAML has a trailing space](https://bugs.webkit.org/show_bug.cgi?id=193053).
Ref #1997.
Follow-up of #2018.
=> Remove trailing spaces from YAML blocks

test/intl402/RelativeTimeFormat/prototype/format/en-us-numeric-auto.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/en-us-numeric-auto.js
The following lines expect each unit has property "-1" and "1" 
```
const expected = unit in exceptions
? [exceptions[unit]["1"], exceptions[unit]["0"], exceptions[unit]["0"], exceptions[unit]["-1"]]
: [`in 1 ${unit}`, `in 0 ${unit}s`, `0 ${unit}s ago`, `1 ${unit} ago`];
```
@Ms2ger @leobalter
=> Fixes {format,formatToParts}/en-us-numeric-auto.js

test/built-ins/FinalizationGroup/FinalizationGroupCleanupIteratorPrototype/Symbol.toStringTag.js, test/built-ins/FinalizationGroup/FinalizationGroupCleanupIteratorPrototype/next-job-not-active-throws.js, test/built-ins/FinalizationGroup/FinalizationGroupCleanupIteratorPrototype/next-length.js, test/built-ins/FinalizationGroup/FinalizationGroupCleanupIteratorPrototype/next-missing-internal-throws.js, test/built-ins/FinalizationGroup/FinalizationGroupCleanupIteratorPrototype/next-name.js, test/built-ins/FinalizationGroup/FinalizationGroupCleanupIteratorPrototype/next-not-object-throws.js, test/built-ins/FinalizationGroup/FinalizationGroupCleanupIteratorPrototype/next-prop-desc.js, test/built-ins/FinalizationGroup/FinalizationGroupCleanupIteratorPrototype/proto.js, test/built-ins/FinalizationGroup/prototype/cleanupSome/callback-iterator-proto.js, test/built-ins/FinalizationGroup/prototype/cleanupSome/cleanupcallback-iterator-proto.js, test/built-ins/FinalizationGroup/prototype/cleanupSome/iterator-dynamic.js, test/built-ins/FinalizationGroup/prototype/cleanupSome/iterator-holdings-multiple-values.js, test/built-ins/FinalizationGroup/prototype/cleanupSome/return-undefined-with-gc.js
Also includes related tests for FinalizationGroup#cleanupSome
I plan to add more tests but these are ready to review. 
The %FinalizationGroupCleanupIteratorPrototype% Object
https://tc39.github.io/proposal-weakrefs/#sec-%finalizationgroupcleanupiterator%-object
%FinalizationGroupCleanupIteratorPrototype%.next ( )
https://tc39.github.io/proposal-weakrefs/#sec-%finalizationgroupcleanupiterator%.next
1. Let iterator be the this value.
2. [x] If Type(iterator) is not Object, throw a TypeError exception.
3. [x] If iterator does not have a [[FinalizationGroup]] internal slot, throw a TypeError exception.
4. Let finalizationGroup be iterator.[[FinalizationGroup]].
5. If finalizationGroup is undefined, then
a. [x] Return CreateIterResultObject(undefined, true).
6. Assert: finalizationGroup has …
=> Add a test for FinalizationGroupCleanupIteratorPrototype

test/language/expressions/new.target/unary-expr.js
JSC bug: [Early error on ANY operator before new.target](https://bugs.webkit.org/show_bug.cgi?id=157970).
=> Add unary operators with NewTarget test

test/language/statements/class/elements/super-access-inside-a-private-getter.js, test/language/statements/class/elements/super-access-inside-a-private-method.js, test/language/statements/class/elements/super-access-inside-a-private-setter.js
Those tests are adding tests to verify if private methods and accessors have `[[HomeObject]]` configured correctly.
Cc. @jbhoosreddy @mkubilayk
=> Adding tests to validate HomeObject setup on private methods and accessors

test/built-ins/Promise/all/resolve-element-function-name.js, test/built-ins/Promise/allSettled/reject-element-function-name.js, test/built-ins/Promise/allSettled/resolve-element-function-name.js, test/built-ins/Promise/executor-function-name.js, test/built-ins/Promise/reject-function-name.js, test/built-ins/Promise/resolve-function-name.js
| Engine              | `name`  | `Promise.allSettled` | CI |
| -------------- | --------- | -------------------- | -- |
| ChakraCore     | 👌          | ❌                               | ❌|
| JSC                  | 👌          | ❌                               | ❌|
| SpiderMonkey | ❌          | ❌                              | ❌|
| V8                    | ❌          | 👌                               | ❌|
Closes #1752.
=> Improve "name" tests of Promise built-in functions

src/class-elements/private-getter-is-not-a-own-property.case, src/class-elements/private-method-is-not-a-own-property.case, src/class-elements/private-setter-is-not-a-own-property.case, test/language/expressions/class/elements/private-getter-is-not-a-own-property.js, test/language/expressions/class/elements/private-method-is-not-a-own-property.js, test/language/expressions/class/elements/private-setter-is-not-a-own-property.js, test/language/statements/class/elements/private-field-is-not-clobbered-by-computed-property.js, test/language/statements/class/elements/private-getter-is-not-a-own-property.js, test/language/statements/class/elements/private-getter-is-not-clobbered-by-computed-property.js, test/language/statements/class/elements/private-method-is-not-a-own-property.js, test/language/statements/class/elements/private-method-is-not-clobbered-by-computed-property.js, test/language/statements/class/elements/private-setter-is-not-a-own-property.js, test/language/statements/class/elements/private-setter-is-not-clobbered-by-computed-property.js
It closes #2187.
I'm not sure if I should consider `__lookupGetter__` and `__lookupSetter__` on those tests, since it is deprecated.
CC: @leobalter @jbhoosreddy @mkubilayk
=> Verify that private methods and accessors aren't visible to [[GetOwnProperty]] and [[HasProperty]].

test/language/statements/class/elements/private-field-visible-to-direct-eval-on-initializer.js, test/language/statements/class/elements/private-field-visible-to-direct-eval.js, test/language/statements/class/elements/private-getter-visible-to-direct-eval-on-initializer.js, test/language/statements/class/elements/private-getter-visible-to-direct-eval.js, test/language/statements/class/elements/private-method-visible-to-direct-eval-on-initializer.js, test/language/statements/class/elements/private-method-visible-to-direct-eval.js, test/language/statements/class/elements/private-setter-visible-to-direct-eval-on-initializer.js, test/language/statements/class/elements/private-setter-visible-to-direct-eval.js
As direct eval's scope is the same as caller's scope, private names are available on those calls as well. It also includes direct eval used on class field initialization.
It is covering some cases of #1343.
Cc.: @jbhoosreddy, @mkubilayk and @leobalter.
=> Adding cases where private names are used on direct eval calls

package.json
* Include untracked files in `npm run diff`
* Suppress non-file output from nested `npm run diff`
=> Fix test:diff npm scripts

test/built-ins/Object/prototype/toString/proxy-function-async.js, test/built-ins/Object/prototype/toString/proxy-function.js, test/built-ins/Object/prototype/toString/symbol-tag-non-str-builtin.js, test/built-ins/Object/prototype/toString/symbol-tag-non-str-proxy-function.js
JSC issues:
* [toString called on proxies returns incorrect tag](https://bugs.webkit.org/show_bug.cgi?id=161111)
* [Object.prototype.toString is not spec-perfect](https://bugs.webkit.org/show_bug.cgi?id=199138)
Follow-up of #755.
=> Improve Object#toString coverage

src/class-elements/private-field-access-on-inner-arrow-function.case, src/class-elements/private-field-access-on-inner-function.case, src/class-elements/private-getter-access-on-inner-arrow-function.case, src/class-elements/private-getter-access-on-inner-function.case, src/class-elements/private-method-access-on-inner-arrow-function.case, src/class-elements/private-method-access-on-inner-function.case, src/class-elements/private-setter-access-on-inner-arrow-function.case, src/class-elements/private-setter-access-on-inner-function.case, test/language/expressions/class/elements/private-field-access-on-inner-arrow-function.js, test/language/expressions/class/elements/private-field-access-on-inner-function.js, test/language/expressions/class/elements/private-getter-access-on-inner-arrow-function.js, test/language/expressions/class/elements/private-getter-access-on-inner-function.js, test/language/expressions/class/elements/private-method-access-on-inner-arrow-function.js, test/language/expressions/class/elements/private-method-access-on-inner-function.js, test/language/expressions/class/elements/private-setter-access-on-inner-arrow-function.js, test/language/expressions/class/elements/private-setter-access-on-inner-function.js, test/language/statements/class/elements/private-field-access-on-inner-arrow-function.js, test/language/statements/class/elements/private-field-access-on-inner-function.js, test/language/statements/class/elements/private-getter-access-on-inner-arrow-function.js, test/language/statements/class/elements/private-getter-access-on-inner-function.js, test/language/statements/class/elements/private-method-access-on-inner-arrow-function.js, test/language/statements/class/elements/private-method-access-on-inner-function.js, test/language/statements/class/elements/private-setter-access-on-inner-arrow-function.js, test/language/statements/class/elements/private-setter-access-on-inner-function.js
We are adding test cases to verify that private members(fields, methods and accessors) are visible on scope of inner functions and arrow functions.
=> Added tests to cover access of private members on inner functions

test/built-ins/FinalizationGroup/gc-has-one-chance-to-call-cleanupCallback.js, test/built-ins/FinalizationGroup/prototype/cleanupSome/cleanup-prevented-with-unregister.js, test/built-ins/FinalizationGroup/prototype/cleanupSome/gc-cleanup-not-prevented-with-wr-deref.js, test/built-ins/WeakRef/prototype/deref/gc-cleanup-not-prevented-with-wr-deref.js
I believe this ends the coverage for WeakRef and FinalizationGroup in Test262.
=> Some edgy cases for weakrefs/finalizationgroups

test/language/statements/class/elements/get-access-of-missing-private-getter.js, test/language/statements/class/elements/get-access-of-missing-shadowed-private-getter.js, test/language/statements/class/elements/set-access-of-missing-private-setter.js, test/language/statements/class/elements/set-access-of-missing-shadowed-private-setter.js, test/language/statements/class/elements/set-access-of-private-method.js, test/language/statements/class/elements/set-access-of-shadowed-private-method.js
According to [spec text](https://tc39.es/proposal-private-methods/#sec-privatefieldget), `PrivateFieldGet` and `PrivateFieldSet` should throw `TypeError` in some cases where we have invalid kind of access. This applies on following cases:
1. Tyring to get from a `PrivateName` without `[[Get]]` internal slot (i.e a private accessor with a setter, but not a getter).
2.  Tyring to set in a `PrivateName` without `[[Set]]` internal slot (i.e a private accessor with a getter, but not a setter).
3. Tyring to set in a `PrivateName` that is a method.
It is also adding cases to validate that shadowed private accessors/methods are thread as different `PrivateNames`.
=> Adding tests to verify cases on PrivateFieldSet and PrivateFieldGet

src/class-elements/syntax/valid/cls-decl-elements-valid-syntax-export-default.template, test/language/statements/class/elements/syntax/valid/export-default-grammar-class-body-ctor-no-heritage.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-field-classelementname-initializer-alt.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-field-classelementname-initializer.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-field-identifier-alt.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-field-identifier.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-fields-multi-line.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-privatemeth-duplicate-get-set.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-privatemeth-duplicate-meth-nestedclassmeth.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-privatename-classelementname-initializer-alt.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-privatename-classelementname-initializer.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-privatename-identifier.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-privatename-no-initializer-with-method.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-privatenames-multi-line.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-static-ctor-accessor-meth-valid.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-static-ctor-async-gen-meth-valid.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-static-ctor-async-meth-valid.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-static-ctor-gen-meth-valid.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-static-ctor-meth-valid.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-static-private-async-gen-meth-prototype.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-static-private-async-meth-prototype.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-static-private-gen-meth-prototype.js, test/language/statements/class/elements/syntax/valid/export-default-grammar-static-private-meth-prototype.js
Related Issue: https://github.com/tc39/test262/issues/1343#issuecomment-446225159
This PR attempts to adds additional class declaration formations as per @littledan's test plan
In particular:
=> Add more class declaration formations

test/built-ins/Number/bigint-conversion.js
There is an infinite set of `BigInt` values that can be represented as Numbers. This is the case when a `BigInt` is out of safe integer range, for example. This PR is adding such cases to `Number(BigInt)` constructor case. Some [bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1558538) with those edge cases were reported on implementations already.
P.S.: This PR is inspired by the bug mentioned above.
=> Add missing BigInt to Number conversion case

src/class-elements/static-private-method-subclass-receiver.case, test/language/expressions/class/elements/static-private-method-subclass-receiver.js, test/language/statements/class/elements/static-private-method-subclass-receiver.js
Adds coverage for (static) private methods according to the test plan posted in #1343.
> Semantics > Error on missing method
> - Subclass receiver for static private
cc: @caiolima @jbhoosreddy
=> Check static private methods on super class are called with correct receiver

test/language/literals/bigint/legacy-octal-like-invalid-00n.js, test/language/literals/bigint/legacy-octal-like-invalid-01n.js, test/language/literals/bigint/legacy-octal-like-invalid-07n.js, test/language/literals/bigint/non-octal-like-invalid-0008n.js, test/language/literals/bigint/non-octal-like-invalid-012348n.js, test/language/literals/bigint/non-octal-like-invalid-08n.js, test/language/literals/bigint/non-octal-like-invalid-09n.js
Ref https://github.com/tc39/proposal-bigint/issues/208
cc @rkirsling
=> Add tests for BigInt disallowed in LegacyOctalLike and NonOctal literals

test/intl402/Intl/getCanonicalLocales/non-iana-canon.js, test/intl402/Locale/getters.js
These two slipped through the cracks in #2097:
test/intl402/Intl/getCanonicalLocales/non-iana-canon.js
- Variant subtag canonicalisation is currrently not allowed.
test/intl402/Locale/getters.js
- Only the first "loc.caseFirst" test in this file was updated in #2097.
=> Fix expected test values

test/language/expressions/class/private-getter-brand-check-multiple-evaluations-of-class-realm-function-ctor.js, test/language/expressions/class/private-getter-brand-check-multiple-evaluations-of-class-realm.js, test/language/expressions/class/private-method-brand-check-multiple-evaluations-of-class-realm-function-ctor.js, test/language/expressions/class/private-method-brand-check-multiple-evaluations-of-class-realm.js, test/language/expressions/class/private-setter-brand-check-multiple-evaluations-of-class-realm-function-ctor.js, test/language/expressions/class/private-setter-brand-check-multiple-evaluations-of-class-realm.js
It closes #2257.
We need to check the correct `TypeError` when asserting private access from functions evaluated in another real.
=> Fixing tests that access PrivateNames from another realm

test/language/expressions/class/private-getter-brand-check-multiple-evaluations-of-class-function-ctor.js
This is just fixing a test to use private getter instead of regular getter.
=> Fixing private-getter-brand-check-multiple-evaluations-of-class-function-ctor to use private getter.

src/class-elements/grammar-privatename-in-computed-property-missing.case, test/language/expressions/class/elements/syntax/early-errors/grammar-privatename-in-computed-property-missing.js, test/language/statements/class/elements/prviate-accessor-is-visible-in-computed-properties.js, test/language/statements/class/elements/prviate-field-is-visible-in-computed-properties.js, test/language/statements/class/elements/prviate-method-is-visible-in-computed-properties.js, test/language/statements/class/elements/syntax/early-errors/grammar-privatename-in-computed-property-missing.js
PrivateNames are visible on `ComputedProperty` evaluation of classes. This PR is adding tests to verify those cases for private fields, methods and accessors.
=> Adding case where PrivateName is used inside computed property.

test/built-ins/Function/prototype/toString/private-method-class-expression.js, test/built-ins/Function/prototype/toString/private-method-class-statement.js, test/built-ins/Function/prototype/toString/private-static-method-class-expression.js, test/built-ins/Function/prototype/toString/private-static-method-class-statement.js
Adds coverage for (static) private methods according to the test plan posted in #1343.
> Usage > The `.toString()` of the private method is the exact string of its declaration
cc: @caiolima @jbhoosreddy
=> Add tests for .toString() of private methods

tools/lint/lint.py
main() and InstallRequirement were also removed from the public API.
=> tools: update lint.py to work with pip 10+ some more

lint.exceptions
These became unnecessary at some point.
=> Remove obsolete lint exceptions.

.circleci/config.yml, tools/lint/lib/checks/harnessfeatures.py, tools/lint/lib/checks/negative.py, tools/lint/lint.py, tools/lint/test/fixtures/harness_features_multiple_includes.js, tools/lint/test/run.py
In light of the planned end-of-life of Python 2 at the end of the year, this ensures that the lint tool supports Python 3 as well. The CI continues running the lint using Python 2, while the unit tests for the lint tool itself are run using both Python 2 and 3, to avoid regressions.
=> Lint: Support Python 3

src/class-elements/static-field-init-this-inside-arrow-function.case, src/class-elements/static-field-init-with-this.case, src/class-elements/static-field-redeclaration.case, test/language/expressions/class/elements/static-field-init-this-inside-arrow-function.js, test/language/expressions/class/elements/static-field-init-with-this.js, test/language/expressions/class/elements/static-field-redeclaration.js, test/language/statements/class/elements/static-field-init-this-inside-arrow-function.js, test/language/statements/class/elements/static-field-init-with-this.js, test/language/statements/class/elements/static-field-initializer-error.js, test/language/statements/class/elements/static-field-redeclaration.js
Following the spec, `this` is referring to class constructor when used into static field initializer. We are adding tests with this usage to validate such behavior. It also includes tests of:
- `this` referenve inside direct eval;
- Redeclaration;
- Initialization that throws exception;
-  `this` reference inside arrow function;
=> Added cases to cover public static field initializer operations with 'this' biding.

test/language/expressions/optional-chaining/call-expression-super-no-base.js, test/language/expressions/optional-chaining/call-expression.js, test/language/expressions/optional-chaining/member-expression.js, test/language/expressions/optional-chaining/optional-chain.js, test/language/expressions/optional-chaining/optional-expression.js, test/language/expressions/optional-chaining/update-expression-postfix.js, test/language/expressions/optional-chaining/update-expression-prefix.js
continuing to add tests for optional chaining, working from [this gist](https://gist.github.com/bcoe/b0e6ae3f93f8c8b8f8559f4428187f25).
see: https://github.com/tc39/test262/issues/2263
=> test: continuing to flesh out optional chaining tests

test/language/statements/class/elements/private-field-is-visible-in-computed-properties.js
When accessing a private field that is declared afterwards in a computed property name, it is similar to accessing a variable in TDZ.
cc @caiolima
=> accessing private fields in TDZ should throw a ReferenceError

test/language/statements/class/elements/private-static-field-visible-to-direct-eval.js, test/language/statements/class/elements/private-static-method-visible-to-direct-eval.js
Adding missing case where private static fields/methods are accessed through direct eval inside class scope. We already have those cases for instance private fields, methods and accessors.
Cc. @spectranaut @leobalter
=> Adding cases of access private static fields/methods through direct eval

test/built-ins/Promise/all/resolve-element-function-name.js, test/built-ins/Promise/allSettled/reject-element-function-name.js, test/built-ins/Promise/allSettled/resolve-element-function-name.js, test/built-ins/Promise/executor-function-name.js, test/built-ins/Promise/reject-function-name.js, test/built-ins/Promise/resolve-function-name.js, test/built-ins/Proxy/revocable/revocation-function-name.js, test/built-ins/ThrowTypeError/name.js, test/intl402/Collator/prototype/compare/compare-function-name.js, test/intl402/DateTimeFormat/prototype/format/format-function-name.js, test/intl402/NumberFormat/prototype/format/format-function-name.js, test/language/computed-property-names/class/static/method-number.js, test/language/computed-property-names/class/static/method-string.js, test/language/computed-property-names/class/static/method-symbol.js, test/language/expressions/arrow-function/name.js, test/language/expressions/assignment/fn-name-lhs-cover.js, test/language/expressions/assignment/fn-name-lhs-member.js, test/language/expressions/async-arrow-function/name.js, test/language/expressions/async-function/name.js, test/language/expressions/async-generator/name.js, test/language/expressions/class/name.js, test/language/expressions/function/name.js, test/language/expressions/generators/name.js
Implements the changes from <https://github.com/tc39/ecma262/pull/1490>.
=> Assign "name" property to all anonymous functions

src/class-elements/grammar-privatemeth-duplicate-async-gen.case, src/class-elements/grammar-privatemeth-duplicate-async.case, src/class-elements/grammar-privatemeth-duplicate-gen.case, test/language/expressions/class/elements/syntax/early-errors/grammar-privatemeth-duplicate-async-gen.js, test/language/expressions/class/elements/syntax/early-errors/grammar-privatemeth-duplicate-async.js, test/language/expressions/class/elements/syntax/early-errors/grammar-privatemeth-duplicate-gen.js, test/language/statements/class/elements/syntax/early-errors/grammar-privatemeth-duplicate-async-gen.js, test/language/statements/class/elements/syntax/early-errors/grammar-privatemeth-duplicate-async.js, test/language/statements/class/elements/syntax/early-errors/grammar-privatemeth-duplicate-gen.js
This PR is for https://github.com/tc39/test262/issues/1343
> Static Semantics: Early Errors
> ClassBody : ClassElementList - It is a Syntax Error if PrivateBoundNames of ClassBody contains any duplicate entries, unless the name is used once for a getter and once for a setter and in no other entries.
We are currently missing test coverage for async functions, generators and async generators. This PR adds coverage for those.
=> Add tests for duplicate private methods (early-error)

src/class-elements/private-field-on-nested-class.case, test/language/expressions/class/elements/private-field-on-nested-class.js, test/language/statements/class/elements/private-field-on-nested-class.js
This came up with a V8 bug where private fields weren't resolved properly from nested classes where both the inner and the outer class had private fields.
=> Add tests for nested private fields

src/class-elements/intercalated-static-non-static-computed-fields.case, test/language/expressions/class/elements/intercalated-static-non-static-computed-fields.js, test/language/statements/class/elements/intercalated-static-non-static-computed-fields.js
According to spec, the execution of computed property fields follow their order of declaration.
Cc @leobalter @spectranaut
=> Added case file to intercalated static/non-static computed fields

test/built-ins/TypedArray/prototype/sort/sorted-values.js
```js
[
Uint8Array, Uint32Array, Uint8ClampedArray, Uint16Array,
Uint32Array, Int8Array, Int16Array, Int32Array, Float32Array, Float64Array
]
.map((x) => new x([1, 0, -0, 2]).sort())
.map((x) => x.constructor.name + ' ' + [...x]
.map((n) => Object.is(n, -0) ? '-0' : n))
.join('\n');
```
```
┌────────────────┬───────────────────────────┐
│ ChakraCore     │ Uint8Array 0,0,1,2        │
│ XS             │ Uint32Array 0,0,1,2       │
│                │ Uint8ClampedArray 0,0,1,2 │
│                │ Uint16Array 0,0,1,2       │
│                │ Uint32Array 0,0,1,2       │
│                │ Int8Array 0,0,1,2         │
│                │ Int16Array 0,0,1,2        │
│                │ Int32Array 0,0,1,2        │
│                │ Float32Array 0,-0,1,2     │
│                │ Float64Array …
```
=> fix TypedArray.prototype.sort test

test/language/statements/class/elements/abrupt-completition-on-field-initializer.js, test/language/statements/class/elements/computed-property-abrupt-completition.js, test/language/statements/class/elements/private-static-getter-abrupt-completition.js, test/language/statements/class/elements/private-static-setter-abrupt-completition.js
We are adding cases where we have abrupt completion for computed properties and field initializers. We are also adding cases where accessors returns abrupt completion.
Cc @leobalter @spectranaut
=>  Abrupt completion cases

test/language/expressions/async-generator/default-proto.js, test/language/expressions/async-generator/eval-body-proto-realm.js
Similar tests for regular generators:
* [default-proto.js](https://github.com/tc39/test262/blob/master/test/language/expressions/generators/default-proto.js)
* [eval-body-proto-realm.js](https://github.com/tc39/test262/blob/master/test/language/expressions/generators/eval-body-proto-realm.js)
Related: #2334, #2335.
=> Add async generator default prototype tests

harness/assert.js, test/harness/assert-notsamevalue-tostring.js, test/harness/assert-samevalue-tostring.js, test/harness/assert-tostring.js
[Motivation](https://github.com/tc39/test262/pull/2342#issuecomment-530604306).
Follow-up of #2342.
=> Gracefully handle errors from ToString in harness/assert

test/language/expressions/optional-chaining/member-expression-async-identifier.js, test/language/expressions/optional-chaining/member-expression-async-literal.js, test/language/expressions/optional-chaining/member-expression-async-this.js, test/language/expressions/optional-chaining/optional-chain-async-optional-chain-square-brackets.js, test/language/expressions/optional-chaining/optional-chain-async-square-brackets.js
CC: @leobalter, @rkirsling 
see: #2263
=> test: adding async optional chaining tests

test/language/statements/class/private-non-static-getter-static-setter-early-error.js, test/language/statements/class/private-non-static-setter-static-getter-early-error.js, test/language/statements/class/private-static-getter-non-static-setter-early-error.js, test/language/statements/class/private-static-setter-non-static-getter-early-error.js
This is not defined into the spec yet, but it seems to be a bug, according to [https://github.com/tc39/proposal-static-class-features/issues/48](https://github.com/tc39/proposal-static-class-features/issues/48). Maybe this PR needs to wait until this issue is fixed.
Cc @leobalter @littledan
=> Adding tests to verify early error when mixing private static and instance accessors

harness/async-gc.js
Ref #2353
This uncomment lines meant to be in the code for the graceful end of the async GC executions.
=> Uncomment lines

src/class-elements/super-private-access-invalid.case, test/language/expressions/class/elements/syntax/early-errors/super-private-access-invalid.js, test/language/statements/class/elements/syntax/early-errors/super-private-access-invalid.js
Without declaring `#x` in the class body, the thrown error could have been about the undeclared private name rather than about the SuperProperty.
=> Test specific error in super-private-access-invalid.case

harness/propertyHelper.js, test/harness/propertyhelper-verifyconfigurable-configurable-object.js, test/harness/verifyProperty-configurable-object.js
Allow the property helper to be used to verify the configurability of
the global "Object" property.
=> Correct bug in property helper

src/dstr-assignment-for-await/error-async-function-syntax/async-func-decl.template, test/language/statements/for-await-of/async-func-decl-dstr-array-elem-init-yield-ident-invalid.js, test/language/statements/for-await-of/async-func-decl-dstr-array-elem-nested-array-invalid.js, test/language/statements/for-await-of/async-func-decl-dstr-array-elem-nested-array-yield-ident-invalid.js, test/language/statements/for-await-of/async-func-decl-dstr-array-elem-nested-obj-invalid.js, test/language/statements/for-await-of/async-func-decl-dstr-array-elem-nested-obj-yield-ident-invalid.js, test/language/statements/for-await-of/async-func-decl-dstr-array-elem-target-simple-strict.js, test/language/statements/for-await-of/async-func-decl-dstr-array-elem-target-yield-invalid.js
Prior to the application of this patch, the modified test template
included an unintentional syntax error. This caused all generated tests
to spuriously satisfy the expectation for an error.
Correct the syntax in the test template and regenerate the tests,
ensuring that when engines report a syntax error, they are demonstrating
the behavior which the tests were designed to verify.
=> Correct syntax in generated tests

test/built-ins/Object/defineProperty/15.2.3.6-4-243-2.js
Prior to this patch, the modified test would pass if no exception was
produced. Use the `assert.throws` utility function to concisely express
the expectation more completely.
=> Avoid false positive

test/built-ins/String/prototype/matchAll/flags-nonglobal-throws.js, test/built-ins/String/prototype/matchAll/flags-undefined-throws.js
Per https://github.com/tc39/ecma262/pull/1716
cc @mathiasbynens
=> tests for String.prototype.matchAll changes

test/built-ins/Promise/executor-function-nonconstructor.js
This test case was giving false-positive in JSC: [`GetCapabilitiesExecutor`](https://tc39.es/ecma262/#sec-getcapabilitiesexecutor-functions) throws `TypeError` when called second time (steps 4 and 5).
=> Use isConstructor in "executor-function-nonconstructor.js"

test/intl402/DateTimeFormat/prototype/formatToParts/related-year.js
Test DateTimeFormat change pattern based on calendar and output relatedYear and yearName
based on the assumption that "en-u-ca-chinese" will output 'relatedYear' and 'yearName'.
https://github.com/tc39/ecma402/pull/349
https://github.com/tc39/ecma402/pull/351
@rwaldron @leobalter @Ms2ger @littledan
To address https://github.com/tc39/test262/issues/2332 and https://github.com/tc39/test262/issues/2333
=> Add test for #349 and #351 PR

harness/assert.js, harness/compareArray.js, harness/deepEqual.js
Also remove assert._formatValue
Fixes #2372
To confirm this patch is good enough, I ran the tests on the following folders/files:
- 'test/harness/**/*'
- 'test/built-ins/RegExp/match-indices/**/*' // also using V8 with the match-indices flag
- test/built-ins/Array/prototype/flatMap/array-like-objects-nested.js // from #2372
=> Cleanup compareArray and deepEqual assertions

src/class-elements/grammar-private-field-optional-chaining.case, test/language/expressions/class/elements/syntax/early-errors/grammar-private-field-optional-chaining.js, test/language/statements/class/elements/syntax/early-errors/grammar-private-field-optional-chaining.js
=> Adding case to test invalid syntax when using PrivateName after '?.'

test/built-ins/Proxy/has/call-in-prototype-index.js, test/built-ins/Proxy/has/call-in-prototype.js, test/built-ins/Proxy/set/call-parameters-prototype-index.js
Motivation: JSC has distinct code paths for integer index property names.
As an example, please see [the fix of `OrdinaryHasProperty` to handle Proxy in prototype](https://trac.webkit.org/changeset/251940/webkit).
Follow-up of #2347 and #2382.
=> Add integer index tests for Proxy "set" and "has" traps

test/built-ins/Object/getOwnPropertyNames/proxy-invariant-absent-not-configurable-symbol-key.js, test/built-ins/Object/getOwnPropertyNames/proxy-invariant-duplicate-symbol-entry.js, test/built-ins/Object/getOwnPropertyNames/proxy-invariant-not-extensible-absent-symbol-key.js, test/built-ins/Object/getOwnPropertyNames/proxy-invariant-not-extensible-extra-symbol-key.js, test/built-ins/Object/getOwnPropertySymbols/length.js, test/built-ins/Object/getOwnPropertySymbols/name.js, test/built-ins/Object/getOwnPropertySymbols/object-contains-symbol-property-with-description.js, test/built-ins/Object/getOwnPropertySymbols/object-contains-symbol-property-without-description.js, test/built-ins/Object/getOwnPropertySymbols/proxy-invariant-absent-not-configurable-string-key.js, test/built-ins/Object/getOwnPropertySymbols/proxy-invariant-duplicate-string-entry.js, test/built-ins/Object/getOwnPropertySymbols/proxy-invariant-not-extensible-absent-string-key.js, test/built-ins/Object/getOwnPropertySymbols/proxy-invariant-not-extensible-extra-string-key.js, test/built-ins/Object/keys/proxy-non-enumerable-prop-invariant-2.js, test/built-ins/Object/keys/proxy-non-enumerable-prop-invariant-3.js, test/built-ins/Proxy/ownKeys/call-parameters-object-keys.js
JSC issues:
* [Proxy's `[[OwnPropertyKeys]]` is incorrect in `DontEnumPropertiesMode::Exclude`](https://bugs.webkit.org/show_bug.cgi?id=203818)
Follow-up of #2384.
=> Add some more Proxy/ownKeys invariants tests

test/language/statements/class/subclass/builtin-objects/WeakMap/regular-subclassing.js, test/language/statements/class/subclass/builtin-objects/WeakMap/super-must-be-called.js, test/language/statements/class/subclass/builtin-objects/WeakSet/regular-subclassing.js, test/language/statements/class/subclass/builtin-objects/WeakSet/super-must-be-called.js
should the tests in `built-ins/WeakMap` and `built-ins/WeakSet` also be tagged? If so I can address that in a separate PR.
=> tag subclass tests with WeakSet and WeakMap

test/built-ins/JSON/parse/reviver-array-get-prop-from-prototype.js, test/built-ins/JSON/parse/reviver-array-non-configurable-prop-create.js, test/built-ins/JSON/parse/reviver-array-non-configurable-prop-delete.js, test/built-ins/JSON/parse/reviver-object-get-prop-from-prototype.js, test/built-ins/JSON/parse/reviver-object-non-configurable-prop-create.js, test/built-ins/JSON/parse/reviver-object-non-configurable-prop-delete.js, test/built-ins/JSON/parse/reviver-wrapper.js
JSC issues:
* [JSON.parse should not modify non-configurable properties](https://bugs.webkit.org/show_bug.cgi?id=163446)
Follow-up of #2196.
=> Improve JSON.parse reviver parameter coverage

test/language/expressions/optional-chaining/iteration-statement-do.js, test/language/expressions/optional-chaining/iteration-statement-for-await-of.js, test/language/expressions/optional-chaining/iteration-statement-for-in.js, test/language/expressions/optional-chaining/iteration-statement-for-of-type-error.js, test/language/expressions/optional-chaining/iteration-statement-for.js, test/language/expressions/optional-chaining/iteration-statement-while.js
Adds tests for IterationStatements, which we were lacking.
Brings up the somewhat interesting case of the production:
```js
const obj = undefined;
for (const key of obj?.a) {
str += key;
}
```
Which will throw a `TypeError` if `obj` happens to be `undefined` or `null` ... I think this falls into a similar category to:
```
class Foo extends obj?.Base {
// method bodies.
}
```
i.e., ☝️ don't do this.
see:  #2263
=> feat(optional-chaining): add tests for IterationStatement

features.txt, test/built-ins/JSON/parse/reviver-call-order.js, test/built-ins/JSON/stringify/property-order.js, test/built-ins/Object/entries/return-order.js, test/built-ins/Object/keys/return-order.js, test/built-ins/Object/values/return-order.js, test/language/statements/for-in/order-enumerable-shadowed.js, test/language/statements/for-in/order-property-added.js, test/language/statements/for-in/order-property-on-prototype.js, test/language/statements/for-in/order-simple-object.js
This adds some simple tests for the stage 3 [for-in ordering proposal](https://github.com/tc39/proposal-for-in-order/).
I am happy to make changes as necessary, or you are welcome to push them to this branch yourselves.
=> Add test for for-in order

test/built-ins/Array/prototype/copyWithin/coerced-values-start-change-start.js, test/built-ins/Array/prototype/copyWithin/coerced-values-start-change-target.js
A security test for copyWithin. This checks that Array.prototype.copyWithin behaves correctly in the case that converting the start parameter to an integer has side effects. This caused a security bug in Moddable https://github.com/Moddable-OpenSource/moddable/issues/123
=> Adding tests for Array.prototype.copyWithin

test/built-ins/FinalizationGroup/prototype/cleanupSome/cleanup-prevented-with-unregister.js, test/built-ins/FinalizationGroup/prototype/unregister/unregister-cleaned-up-cell.js
Add cleanup test for unregister: should return false when the cell has already been cleaned up
Change test for unregister preventing cleanup to call unregister after gc is performed.
These [issues were found in SpiderMonkey](https://bugzilla.mozilla.org/show_bug.cgi?id=1600488)'s implementation but not caught by test262.
=> FinalizationGroup: Improve tests for cleanupSome/unregister interactions

test/built-ins/Array/prototype/copyWithin/coerced-values-start-change-start.js, test/built-ins/Array/prototype/copyWithin/coerced-values-start-change-target.js, test/built-ins/TypedArray/prototype/copyWithin/coerced-values-end-detached-prototype.js, test/built-ins/TypedArray/prototype/copyWithin/coerced-values-end-detached.js, test/built-ins/TypedArray/prototype/copyWithin/coerced-values-start-detached.js
Adding tests for TypedArray.prototype.copyWithin, as it has had security issues in the past, for example https://bugs.chromium.org/p/project-zero/issues/detail?id=862
All three tests behave inconsistently on the browser JS engines.
test262/test/built-ins/TypedArray/prototype/copyWithin/coerced-values-end-detached.js
Passes on v8, fails on SpiderMonkey and JSC
test262/test/built-ins/TypedArray/prototype/copyWithin/coerced-values-end-detached-prototype.js
Passes on SpiderMonkey and JSC, fails on v8
test262/test/built-ins/TypedArray/prototype/copyWithin/coerced-values-start-detached.js
Passes on v8, fails on SpiderMonkey and JSC
I believe the behavior in the tests is correct according to the specification, but I would appreciate if someone else could check, as the method is fairly …
=> TypedArray copyWithin security tests

test/built-ins/Date/parse/without-utc-offset.js
=> Add test verifying offsetless date-time string is local time.

test/intl402/NumberFormat/prototype/formatToParts/value-tonumber.js
As per https://tc39.es/ecma262/#table-11 `toNumber(false)` is supposed to be `+0`
=> Fix toNumber issue with boolean

test/intl402/DateTimeFormat/prototype/format/related-year-zh.js, test/intl402/DateTimeFormat/prototype/formatToParts/related-year-zh.js
Based on <https://cs.chromium.org/chromium/src/v8/test/intl/date-format/related-year.js>.
Fixes #2332.
=> Add a specific test for relatedYear output.

test/built-ins/Object/freeze/abrupt-completion.js, test/built-ins/Object/preventExtensions/abrupt-completion.js, test/built-ins/Object/seal/abrupt-completion.js
Follow-up of #2453.
JSC bug: [`Object.preventExtensions` should throw if not successful](https://bugs.webkit.org/show_bug.cgi?id=206131).
=> Add Object.{freeze,preventExtensions,seal} abrupt completion tests

test/language/expressions/optional-chaining/call-expression.js
- Add missing `?` in unit test
It requires the question mark as it is part of the "optional chaining operator" `?.`
=> Fix typo from optional chaining test

test/built-ins/TypedArray/prototype/buffer/this-inherits-typedarray.js
Test that TypedArray internal slots are not inherited. This test passes everywhere.
=> Test that TypedArray internal slots are not inherited

test/built-ins/TypedArray/prototype/fill/coerced-end-detach.js, test/built-ins/TypedArray/prototype/fill/coerced-start-detach.js, test/built-ins/TypedArray/prototype/fill/coerced-value-detach.js
Adding security tests for TypedArray.prototype.fill based on CVE-2016-4734. These fail on V8 right now.
=> Adding security tests for TypedArray.prototype.fill

test/built-ins/Promise/create-resolving-functions-reject.js, test/built-ins/Promise/create-resolving-functions-resolve.js, test/built-ins/Promise/prototype/finally/invokes-then-with-function.js, test/built-ins/Promise/prototype/finally/rejected-observable-then-calls-argument.js, test/built-ins/Promise/prototype/finally/resolved-observable-then-calls-argument.js
JSC bug: [Anonymous built-in functions should have empty string for a name](https://bugs.webkit.org/show_bug.cgi?id=204214).
=> Add length/name/isConstructor tests for Promise built-in functions

test/built-ins/TypedArray/prototype/sort/detached-buffer-comparefn-coerce.js
Security test for TypedArray.prototype.sort based on CVE-2016-7288. This passes on all the major engines except for Chakra.
=> Security test for TypedArray.prototype.sort based on CVE-2016-7288

test/built-ins/Atomics/store/expected-return-value-negative-zero.js
Per https://github.com/tc39/ecma262/pull/1827
=> `Atomics.store` now normalizes -0 to +0

test/built-ins/TypedArray/prototype/fill/coerced-end-detach.js, test/built-ins/TypedArray/prototype/fill/coerced-start-detach.js, test/built-ins/TypedArray/prototype/fill/coerced-value-detach.js, test/built-ins/TypedArray/prototype/sort/detached-buffer-comparefn-coerce.js
The tests added in PRs #2470 and #2474 have invalid YAML (according to perl5/YAML/Loader.pm), which prevents JSC from importing the latest changes.
=> Fix invalid YAML from #2470 and #2474.

test/intl402/DateTimeFormat/casing-numbering-system-calendar-options.js, test/intl402/NumberFormat/casing-numbering-system-options.js
According to [PR #175](https://github.com/tc39/ecma402/pull/175) on ECMA402, `numberingSystem` and `calendar` options should always be transformed to lower case. We are tests to cover this part of spec.
=> Adding test cases to verify 'numberingSystem' and 'calendar' lower casing

.circleci/config.yml, package.json
removes engine specific bin paths and gets rid of needing to build engine262 from scratch
=> switch to esvu to streamline engine installs

test/built-ins/Date/parse/without-utc-offset.js
Addresses https://github.com/tc39/test262/pull/2461#issuecomment-596199997.
(CC @anba)
=> Fix DST sensitivity in Date/parse/without-utc-offset.js.

test/built-ins/Array/prototype/indexOf/15.4.4.14-4-4.js
Looks like a cut-n-paste error; a test in the `indexOf` subtree was actually testing the `lastIndexOf` function. Now pointing where it should.
Fixes #2520.
=> Repair indexOf test that was testing lastIndexOf

test/built-ins/Array/prototype/filter/create-proto-from-ctor-realm-array.js
Looks like a cut-n-paste error. A test in the `built-ins/Array/prototype/filter` subtree was exercising the `concat` function.
Fixes #2519.
=> Repair filter test that was testing concat

test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js, test/built-ins/Array/prototype/concat/arg-length-near-integer-limit.js, test/built-ins/Array/prototype/copyWithin/length-near-integer-limit.js, test/built-ins/Array/prototype/fill/length-near-integer-limit.js, test/built-ins/Array/prototype/indexOf/length-near-integer-limit.js, test/built-ins/Array/prototype/lastIndexOf/length-near-integer-limit.js, test/built-ins/Array/prototype/reduceRight/length-near-integer-limit.js
JSC implements `Array.prototype.{copyWithin,fill,reduceRight}` methods in JavaScript.
=> Test Array methods with "length" of MAX_SAFE_INTEGER

test/language/literals/regexp/u-astral-char-class-invert.js
JSC bug: [Unicode Regex with Emojis corrupts string replacement](https://bugs.webkit.org/show_bug.cgi?id=205477).
=> Test astral literals within inverted CharacterClass

test/built-ins/RegExp/prototype/Symbol.search/set-lastindex-init-samevalue.js, test/built-ins/RegExp/prototype/Symbol.search/set-lastindex-restore-samevalue.js
JSC bug: [Add op_same_value bytecode, intrinsic, JIT supports](https://bugs.webkit.org/show_bug.cgi?id=173226).
=> Add RegExp.prototype[@@search] SameValue tests

test/built-ins/JSON/stringify/replacer-function-object-deleted-property.js, test/built-ins/JSON/stringify/replacer-function-stack-overflow.js, test/built-ins/JSON/stringify/value-tojson-stack-overflow.js
JSC bug: [JSON.stringify hanging WebKit on a cyclic structure](https://bugs.webkit.org/show_bug.cgi?id=143511).
Follow-up of #2315.
//cc @leobalter
=> Add JSON.stringify stack overflow tests

test/built-ins/Object/entries/order-after-define-property.js, test/built-ins/Object/getOwnPropertyDescriptors/order-after-define-property.js, test/built-ins/Object/getOwnPropertyNames/order-after-define-property.js, test/built-ins/Object/getOwnPropertySymbols/order-after-define-property.js, test/built-ins/Object/keys/order-after-define-property.js, test/built-ins/Object/values/order-after-define-property.js, test/built-ins/Reflect/ownKeys/order-after-define-property.js, test/language/statements/for-in/order-after-define-property.js
JSC bug: [Redefining a property should not change its insertion index](https://bugs.webkit.org/show_bug.cgi?id=142933).
=> Add property order after [[DefineOwnProperty]] tests

harness/propertyHelper.js
This reverts 2abfc8cf9dd20636c999c459d48bd562553e8f76.
Reason: breaks multiple tests.
//cc @rwaldron
=> Revert "Remove unused `verifyProp` parameter from `isWritable`"

src/class-elements/private-field-after-optional-chain.case, test/language/expressions/class/elements/private-field-after-optional-chain.js, test/language/statements/class/elements/private-field-after-optional-chain.js
Test to add coverage to changes proposed at https://github.com/tc39/proposal-class-fields/pull/301. This should only merge after we get consensus on merging changes on that PR.
=> Adding test coverage for 'OptionalChain'.PrivateIdentifier case

harness/assert.js, test/harness/assert-samevalue-zeros.js
`test262-runner` output:
```
! NEW FAIL test/built-ins/RegExp/prototype/Symbol.search/set-lastindex-init-samevalue.js (default)
Exception: Test262Error: Expected SameValue(«0», «0») to be true
```
Follow-up of #2539.
=> Harness: properly format negative zero

test/built-ins/Proxy/create-handler-is-revoked-proxy.js, test/built-ins/Proxy/create-target-is-not-callable.js, test/built-ins/Proxy/create-target-is-revoked-function-proxy.js, test/built-ins/Proxy/create-target-is-revoked-proxy.js
Ref. https://github.com/tc39/ecma262/pull/1814
=> Test ProxyCreate with revoked target and handler

test/built-ins/AsyncFromSyncIteratorPrototype/next/absent-value-not-passed.js, test/built-ins/AsyncFromSyncIteratorPrototype/return/absent-value-not-passed.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/absent-value-not-passed.js
Ref. https://github.com/tc39/ecma262/pull/1776.
//cc @ljharb @spectranaut
=> Test that async iterator methods don't pass absent values

test/language/expressions/template-literal/unicode-escape-no-hex-err.js, test/language/literals/string/unicode-escape-no-hex-err-double.js, test/language/literals/string/unicode-escape-no-hex-err-single.js
JSC bug: ['\u' should throw an early SyntaxError exception, but instead evaluates to 'u'](https://bugs.webkit.org/show_bug.cgi?id=198790).
//cc @mathiasbynens
=> Test unicode escapes without Hex4Digits in strings

test/annexB/language/literals/regexp/legacy-octal-escape.js
JSC bug: [Octal escapes in strings and regexes should be max 3 digits, but leading zeros are allowed](https://bugs.webkit.org/show_bug.cgi?id=167067).
=> Improve RegExp LegacyOctalEscapeSequence coverage

test/language/statements/for-await-of/iterator-close-non-throw-get-method-abrupt.js, test/language/statements/for-await-of/iterator-close-non-throw-get-method-non-callable.js, test/language/statements/for-await-of/iterator-close-throw-get-method-abrupt.js, test/language/statements/for-await-of/iterator-close-throw-get-method-non-callable.js, test/language/statements/for-of/iterator-close-non-throw-get-method-abrupt.js, test/language/statements/for-of/iterator-close-non-throw-get-method-non-callable.js, test/language/statements/for-of/iterator-close-throw-get-method-abrupt.js, test/language/statements/for-of/iterator-close-throw-get-method-non-callable.js
Ref. https://github.com/tc39/ecma262/pull/1408
//cc @zenparsing @LeszekSwirski
=> Test that IteratorClose suppresses GetMethod errors

harness/testIntl.js, test/intl402/Intl/getCanonicalLocales/complex-language-subtag-replacement.js, test/intl402/Intl/getCanonicalLocales/complex-region-subtag-replacement.js, test/intl402/Intl/getCanonicalLocales/non-iana-canon.js, test/intl402/Intl/getCanonicalLocales/preferred-variant.js, test/intl402/Intl/getCanonicalLocales/transformed-ext-canonical.js, test/intl402/Intl/getCanonicalLocales/transformed-ext-invalid.js, test/intl402/Intl/getCanonicalLocales/transformed-ext-valid.js, test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-calendar.js, test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-col-strength.js, test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-measurement-system.js, test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-region.js, test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-subdivision.js, test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-timezone.js, test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-yes-to-true.js, test/intl402/Intl/getCanonicalLocales/unicode-ext-key-with-digit.js, test/intl402/Locale/constructor-apply-options-canonicalizes-twice.js, test/intl402/Locale/constructor-non-iana-canon.js, test/intl402/Locale/extensions-grandfathered.js, test/intl402/Locale/getters-grandfathered.js, test/intl402/Locale/likely-subtags-grandfathered.js, test/intl402/Locale/likely-subtags.js, test/intl402/Locale/prototype/minimize/removing-likely-subtags-first-adds-likely-subtags.js, tools/misc/make_intl_data.py
5663696:
- Updates the list of Intl service constructors to ensure existing tests are also run with RelativeTimeFormat, ListFormat, and DisplayNames.
f2fc3af:
- Updates the list of numbering systems to match current CLDR.
15db7f1:
- Python script used for the next two commits.
79524bf and 32fd063:
- Update the language tag canonicalisation to match UTS 35.
2a7c9f8:
- Variant subtags need to be canonicalised (again).
2e32d50:
- Using UTS 35 means "cel-gaulish" can now be canonicalised consistently across implementations, so we can revert #2054.
cce81ab:
- Additional canonicalisation and Intl.Locale tests from SpiderMonkey.
=> Upstream language tag canonicalisation and Intl.Locale tests from SpiderMonkey

test/built-ins/String/prototype/match/cstm-matcher-is-null.js, test/built-ins/String/prototype/replace/cstm-replace-is-null.js, test/built-ins/String/prototype/replaceAll/searchValue-replacer-is-null.js, test/built-ins/String/prototype/replaceAll/searchValue-replacer-method-abrupt.js, test/built-ins/String/prototype/search/cstm-search-is-null.js, test/built-ins/String/prototype/split/cstm-split-is-null.js
[`String.prototype.matchAll`](https://tc39.es/ecma262/#sec-string.prototype.matchall) case is covered by [`/test/built-ins/String/prototype/matchAll/regexp-is-undefined-or-null-invokes-matchAll.js`](https://github.com/tc39/test262/blob/master/test/built-ins/String/prototype/matchAll/regexp-is-undefined-or-null-invokes-matchAll.js).
=> Improve GetMethod coverage in String.prototype methods

test/annexB/built-ins/RegExp/named-groups/non-unicode-malformed-lookbehind.js, test/annexB/built-ins/RegExp/named-groups/non-unicode-malformed.js
This change:
a) Moves named references with look-behind tests to separate file, allowing engines without look-behind assertions support (JSC) to run them.
b) Adds a few tests with both malformed named and **numeric** references, as they both require reparsing and may interfere with each other.
JSC bug: [Invalid numeric and named references should be early syntax errors](https://bugs.webkit.org/show_bug.cgi?id=178175).
//cc @mathiasbynens
=> Improve malformed RegExp named groups coverage

test/language/literals/regexp/u-null-character-escape.js
JSC bug: [Octal escapes should be max 3 digits and syntax errors in Unicode patterns](https://bugs.webkit.org/show_bug.cgi?id=167067).
When fixing [test/built-ins/RegExp/unicode_restricted_octal_escape.js](https://github.com/tc39/test262/blob/master/test/built-ins/RegExp/unicode_restricted_octal_escape.js) it was quite easy to miss `\0` case and no tests were failing.
//cc @mathiasbynens
=> Add test for \0 in Unicode patterns

test/built-ins/Promise/all/invoke-resolve-get-once-no-calls.js
I found a minor bug in `esid` and `features` of the test
`test/built-ins/Promise/all/invoke-resolve-get-once-no-calls.js`.
I revised the `esid` and `features` to use `Promise.all` instead of `Promise.allSettled`.
=> Fixed wrong `esid` and `features` in a Promise.all test

test/built-ins/RegExp/lookBehind/sliced-strings.js
This change allows the test to be run on engines that do not implement Annex B
=> Use slice in RegExp lookBehind test

test/built-ins/Function/prototype/bind/get-fn-realm-recursive.js, test/built-ins/Function/prototype/bind/get-fn-realm.js, test/built-ins/Proxy/get-fn-realm-recursive.js, test/built-ins/Proxy/get-fn-realm.js
JSC bug: [InternalFunction::createSubclassStructure should use newTarget's globalObject](https://bugs.webkit.org/show_bug.cgi?id=202599).
Follow-up of #2155.
=> Make GetFunctionRealm tests useful

test/annexB/built-ins/Proxy/set/call-parameters-prototype-dunder-proto.js
Follow-up of https://github.com/tc39/test262/pull/2576#discussion_r407205359.
_cc_ @devsnek
=> Bring back accidentally removed __proto__ test

test/built-ins/Proxy/revocable/handler-is-revoked-proxy.js, test/built-ins/Proxy/revocable/target-is-revoked-function-proxy.js, test/built-ins/Proxy/revocable/target-is-revoked-proxy.js
Since runtimes are not required to implement abstract ops as they are specified, revoked Proxy checks of [`ProxyCreate`](https://tc39.es/ecma262/#sec-proxycreate) may be inlined in [`Proxy.revocable`](https://tc39.es/ecma262/#sec-proxy.revocable).
Follow-up of #2548
Ref. tc39/ecma262#1814
=> Test Proxy.revocable with revoked target and handler

harness/testIntl.js
JSC is currently [mishandling](https://bugs.webkit.org/show_bug.cgi?id=210576) the duplicate variant regex in testIntl.js.
That isn't test262's problem, but it's still incredibly silly that we're treating every `alphanum` subexpression as a capture group, so let's fix this.
=> Simplify alphanum regex in testIntl.js

test/built-ins/RegExp/prototype/Symbol.replace/named-groups-fn.js, test/built-ins/RegExp/prototype/Symbol.replace/named-groups.js, test/built-ins/RegExp/prototype/Symbol.replace/result-coerce-groups-prop.js
While we have a bit more extensive coverage for named capture groups with `String.prototype.replace` in [`/test/built-ins/RegExp/named-groups`](https://github.com/tc39/test262/tree/master/test/built-ins/RegExp/named-groups), JSC has `RegExp.prototype[@@replace]` as slow path for RegExp subclasses and it lacked named groups support until [recently](https://trac.webkit.org/changeset/254195). Please also see [engine262 coverage report](https://coveralls.io/builds/29870435/source?filename=src/runtime-semantics/GetSubstitution.mjs).
JSC bug: [RegExp.prototype[Symbol.replace] does not support named capture groups](https://bugs.webkit.org/show_bug.cgi?id=205783).
Follow-up of #2481.
//cc @mathiasbynens
=> Improve coverage of RegExp.prototype[@@replace] with named groups

test/intl402/Locale/constructor-options-canonicalized.js
This adds a test for https://github.com/tc39/ecma402/issues/413 for the "calendar" part of it.  I can't readily find a `nu`/`numberingSystem` that has an alias, so there doesn't seem to be a way to test that aspect of the change.  If one ever manifests, it ought be easy to slot it into this test.
This test as written depends upon particular TR35 canonicalization, which the base-most Intl spec doesn't technically guarantee.  If that isn't acceptable, we could more minimally test that `new Intl.Locale("en-u-ca-islamicc").calendar === new Intl.Locale("en", { calendar: "islamicc" })` to detect dissimilar canonicalization actions being taken, even if we aren't requiring an exact result.
=> Add a test for Unicode key-type pairs being canonicalized by Intl.Locale when passed in options

test/intl402/DateTimeFormat/prototype/resolvedOptions/order-dayPeriod.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/order-fractionalSecondDigits.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/order-style.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/order.js
This fix the conflict with the https://github.com/tc39/ecma402/pull/347 
so the resolvedOptions contains fractionalSecondDigits even it is undefined in the input, except the cases which dateStyle or timeStyle is specified.
close #2591
=> Allow new property such as fractionalSecondDigits present in resolvedOptions result

test/intl402/RelativeTimeFormat/prototype/format/pl-pl-style-long.js, test/intl402/RelativeTimeFormat/prototype/format/pl-pl-style-narrow.js, test/intl402/RelativeTimeFormat/prototype/format/pl-pl-style-short.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/pl-pl-style-long.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/pl-pl-style-narrow.js, test/intl402/RelativeTimeFormat/prototype/formatToParts/pl-pl-style-short.js
Correct tests landed in https://github.com/tc39/test262/pull/1669
to close https://github.com/tc39/test262/issues/2589
pl locale has minimumGroupingDigits{"2"}  and should not place \u00a0 if there are only 4 digits (since  minimumGroupingDigits{"2"}   means it require at least 2 digits on the left of the grouping separator)
@Ms2ger @leobalter @rkirsling
=> Correct pull/1669 for pl

test/built-ins/NativeErrors/AggregateError/proto-from-ctor-realm.js
It'd be nice to have a CI hook that enforces presence of feature tags for all tests in a built-in directory.
=> Correctly tag AggregateError proto-from-ctor-realm test

test/intl402/Locale/prototype/minimize/removing-likely-subtags-first-adds-likely-subtags.js
It is incorrect to expect the minimize result of "zh-Hant" to be "zh-TW". It should be "zh-Hant". Why?
first, what we have in input for zh-Hant
lang = zh
region = [none]
script = Hant 
Now, look at the AddLikelySubtags algorithm in http://www.unicode.org/reports/tr35/#Likely_Subtags
```
Remove Likely Subtags: Given a locale, remove any fields that Add Likely Subtags would add.
The reverse operation removes fields that would be added by the first operation.
1. First get max = AddLikelySubtags(inputLocale). If an error is signaled, return it.
2. Remove the variants from max.
3. Then for trial in {language, language _ region, language _ script}
3-* If AddLikelySubtags(trial) = max, then return trial + variants.
4. If you do not get a match, return max + variants.
```
after 1 and 2, max = …
=> Correct the expectation of zh-Hant for Locale.minimize

test/built-ins/AsyncGeneratorFunction/proto-from-ctor-realm-prototype.js, test/built-ins/Function/proto-from-ctor-realm-prototype.js, test/built-ins/GeneratorFunction/proto-from-ctor-realm-prototype.js
JSC bug: [InternalFunction::createSubclassStructure should use newTarget's globalObject](https://bugs.webkit.org/show_bug.cgi?id=202599).
Follow-up of #2342.
=> CreateDynamicFunction: test Realm of "prototype" object

harness/testIntl.js
This PR reverts `i` flag change per https://github.com/tc39/test262/pull/2581#issuecomment-619856574, but keeps unnecessary capture group removal since JSC currently [fails to match it correctly](https://bugs.webkit.org/show_bug.cgi?id=210576).
_cc_ @anba @rkirsling
=> Partly revert "Simplify alphanum regex in testIntl.js"

src/async-generators/yield-star-sync-return.case, src/async-generators/yield-star-sync-throw.case, test/language/expressions/async-generator/named-yield-star-sync-return.js, test/language/expressions/async-generator/named-yield-star-sync-throw.js, test/language/expressions/async-generator/yield-star-sync-return.js, test/language/expressions/async-generator/yield-star-sync-throw.js, test/language/expressions/class/async-gen-method-static/yield-star-sync-return.js, test/language/expressions/class/async-gen-method-static/yield-star-sync-throw.js, test/language/expressions/class/async-gen-method/yield-star-sync-return.js, test/language/expressions/class/async-gen-method/yield-star-sync-throw.js, test/language/expressions/class/elements/async-gen-private-method-static/yield-star-sync-return.js, test/language/expressions/class/elements/async-gen-private-method-static/yield-star-sync-throw.js, test/language/expressions/class/elements/async-gen-private-method/yield-star-sync-return.js, test/language/expressions/class/elements/async-gen-private-method/yield-star-sync-throw.js, test/language/expressions/object/method-definition/async-gen-yield-star-sync-return.js, test/language/expressions/object/method-definition/async-gen-yield-star-sync-throw.js, test/language/statements/async-generator/yield-star-sync-return.js, test/language/statements/async-generator/yield-star-sync-throw.js, test/language/statements/class/async-gen-method-static/yield-star-sync-return.js, test/language/statements/class/async-gen-method-static/yield-star-sync-throw.js, test/language/statements/class/async-gen-method/yield-star-sync-return.js, test/language/statements/class/async-gen-method/yield-star-sync-throw.js, test/language/statements/class/elements/async-gen-private-method-static/yield-star-sync-return.js, test/language/statements/class/elements/async-gen-private-method-static/yield-star-sync-throw.js, test/language/statements/class/elements/async-gen-private-method/yield-star-sync-return.js, test/language/statements/class/elements/async-gen-private-method/yield-star-sync-throw.js
I've modified existing templates instead of adding new test files because string as `throw`/`return` argument is already covered a few lines above, and by testing `undefined` case we make sure that "is present" check of https://github.com/tc39/ecma262/pull/1776 is implemented correctly. This PR also aligns `throw` and `return` templates with `next`, which already covers `undefined` case.
Follow-up of #2571.
JSC bug: [AsyncFromSyncIterator methods should not pass absent values](https://bugs.webkit.org/show_bug.cgi?id=211147).
=> Test AsyncFromSyncIterator methods with `undefined` values

test/built-ins/Number/isSafeInteger/safe-integers.js
The folder and file name implies it should be using isSafeInteger rather
than isInteger which it was using.
=> Fix #2605; make safe-integer.js call isSafeInteger

test/built-ins/Object/prototype/toString/proxy-revoked-during-get-call.js
JSC bug: [Object.prototype.toString is not spec-perfect](https://bugs.webkit.org/show_bug.cgi?id=199138).
=> Object.prototype.toString: Improve revoked Proxy coverage

test/language/module-code/eval-rqstd-once.js, test/language/module-code/export-star-as-dflt.js, test/language/module-code/export-star-as-dflt_FIXTURE.js
As I suggested in #1498 these are positive tests for `export * as [keyword]` and `export * as default`.
=> Add missing tests for export-star-as-ns-from-module

test/annexB/language/expressions/yield/star-iterable-throw-emulates-undefined-throws-when-called.js
IsHTMLDDA is specified in INTERPRETING.md to return null on [[Call]]
when called with no arguments or with single argument "". Returning null
causes the iterator protocol to throw.
Also see star-iterable-return-emulates-undefined-throws-when-called.js
=> Fix testing for throw in an iterator via yield* throws

test/annexB/built-ins/Array/from/iterator-method-emulates-undefined.js, test/annexB/built-ins/String/prototype/match/custom-matcher-emulates-undefined.js, test/annexB/built-ins/String/prototype/matchAll/custom-matcher-emulates-undefined.js, test/annexB/built-ins/String/prototype/replace/custom-replacer-emulates-undefined.js, test/annexB/built-ins/String/prototype/replaceAll/custom-replacer-emulates-undefined.js, test/annexB/built-ins/String/prototype/search/custom-searcher-emulates-undefined.js, test/annexB/built-ins/String/prototype/split/custom-splitter-emulates-undefined.js, test/annexB/built-ins/TypedArrayConstructors/from/iterator-method-emulates-undefined.js
JSC bug: [Use @isUndefinedOrNull instead of abstract equality with null](https://bugs.webkit.org/show_bug.cgi?id=210954).
Follow-up of #2579.
=> Improve [[IsHTMLDDA]] coverage for built-ins

src/class-elements/field-declaration.case, test/language/expressions/class/elements/field-declaration.js, test/language/statements/class/elements/field-declaration.js
Copied from #2282. Numeric literal as field name wasn't covered so far.
=> Cover simple declaration of instance fields

test/built-ins/TypedArray/prototype/set/BigInt/array-arg-primitive-toobject.js, test/built-ins/TypedArray/prototype/set/array-arg-primitive-toobject.js
JSC bug: [TypedArray.prototype.set is incorrect with primitives](https://bugs.webkit.org/show_bug.cgi?id=212730).
=> Test %TypedArray%.prototype.set with primitives

test/language/expressions/optional-chaining/eval-optional-call.js
This PR adds a test for `eval?.(code)`. It's indirect eval.
> ```
>   12.3.9.2 Runtime Semantics: ChainEvaluation
>     OptionalChain: ?. Arguments
>       1. Let thisChain be this OptionalChain.
>       2. Let tailCall be IsInTailPosition(thisChain).
>       3. Return ? EvaluateCall(baseValue, baseReference, Arguments, tailCall).
> ```
> https://tc39.es/ecma262/#sec-optional-chaining-chain-evaluation
=> add a test for `eval?.(code)`

INTERPRETING.md
The following tests call `IsHTMLDDA` with more than one argument:
- annexB/built-ins/String/prototype/split/custom-splitter-emulates-undefined.js
- annexB/built-ins/String/prototype/replaceAll/custom-replacer-emulates-undefined
- annexB/built-ins/String/prototype/replace/custom-replacer-emulates-undefined.js
=> Adjust description for IsHTMLDDA to allow more than one argument

test/built-ins/Array/prototype/indexOf/length-zero-returns-minus-one.js, test/built-ins/Array/prototype/lastIndexOf/length-zero-returns-minus-one.js
`TypedArray` methods have similar tests, as well as `Array.prototype.includes`.
`String` methods don't perform zero length check.
=> Test that length check is performed before ToInteger

test/built-ins/Promise/prototype/then/S25.4.4_A2.1_T3.js
Reverts the change from 040eb5393a6c3e854a7ab5e86b54f3dac841162e to avoid calling $DONE twice in the test file.
From <https://github.com/tc39/test262/blob/master/CONTRIBUTING.md#writing-asynchronous-tests>:
> When executing such tests, the runner expects that the global `$DONE()` function will be called **exactly once** to signal test completion.
=> Don't call $DONE twice in S25.4.4_A2.1_T3.js

test/built-ins/Atomics/exchange/nonshared-int-views.js
Follow-up for: https://github.com/tc39/test262/pull/2633
=> Update Atomics.exchange to allow non-shared buffers

test/intl402/DateTimeFormat/prototype/formatRange/date-undefined-throws.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-undefined-throws.js
http://tc39.es/proposal-intl-DateTimeFormat-formatRange/
The spec draft throws TypeError instead of RangeError.
1.4.5 Intl.DateTimeFormat.prototype.formatRange ( startDate , endDate )
...
4. If startDate is undefined or endDate is undefined, throw a TypeError exception.
1.4.6 Intl.DateTimeFormat.prototype.formatRangeToParts ( startDate , endDate )
...
4. If startDate is undefined or endDate is undefined, throw a TypeError exception.
=> Intl.DateTimeFormat.{formatRange,formatRangeToParts} should throw TypeError instead of RangeError if either of parameter is undefined

test/intl402/DateTimeFormat/constructor-options-fractionalSecondDigits-valid.js, test/intl402/DateTimeFormat/prototype/format/fractionalSecondDigits.js, test/intl402/DateTimeFormat/prototype/formatRange/fractionalSecondDigits.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/fractionalSecondDigits.js, test/intl402/DateTimeFormat/prototype/formatToParts/fractionalSecondDigits.js
Update the test to sync with the least version of https://github.com/tc39/ecma402/pull/347
and remove 0 from the range of fractionalSecondDigits and just use undefined for that.
=> Remove 0 from the range of fractionalSecondDigits 
