tc39/test262

test/language/computed-property-names/class/static/method-number.js, test/language/computed-property-names/class/static/method-string.js, test/language/computed-property-names/class/static/method-symbol.js
Ref #2504
Ref https://github.com/tc39/ecma262/pull/1490
@scole66 The tests are now correct with the current specs since https://github.com/tc39/ecma262/pull/1490 has been merged.
There wasn't much to change I added some info content to help clarifying how the properties are set during the class evaluation and fetched from `Object.getOwnPropertyNames` and `Object.getOwnPropertySymbols`.
I also removed the assert messages as `compareArray` does a good job showing the actual and expected values if anything fails.
For the current tests failures, let's ping @codehag @anba @syg.
=> Refactor tests for static methods creation and fetching

test/language/expressions/template-literal/invalid-legacy-octal-escape-sequence-8.js, test/language/literals/string/legacy-non-octal-escape-sequence-8-strict.js
=> Add tests for \8 in template/strict strings.

test/intl402/DisplayNames/length.js
`locales` and `options` are not optional parameters. So the length should be 2.
=> Intl.DisplayNames.length should be 2

features.txt, harness/async-gc.js, test/built-ins/FinalizationRegistry/gc-has-one-chance-to-call-cleanupCallback.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/callback-not-callable-throws.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/cleanup-prevented-with-reference.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/cleanup-prevented-with-unregister.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/custom-this.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/holdings-multiple-values.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/length.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/name.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/prop-desc.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/reentrancy.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/return-undefined-with-gc.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/return-undefined.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/this-does-not-have-internal-cells-throws.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/this-not-object-throws.js, test/built-ins/FinalizationRegistry/prototype/unregister/unregister-cleaned-up-cell.js, test/built-ins/WeakRef/prototype/deref/gc-cleanup-not-prevented-with-wr-deref.js
The WeakRefs proposal advanced to Stage 4 but cleanupSome moved back to a Stage 2 status.
The tests should remain in Test262 for now but this feature flag should help users to filter tests out.
=> Add feature tag for cleanupSome

test/intl402/Segmenter/prototype/segment/segment-grapheme-iterable.js, test/intl402/Segmenter/prototype/segment/segment-sentence-iterable.js, test/intl402/Segmenter/prototype/segment/segment-word-iterable.js
Update according to https://github.com/tc39/proposal-intl-segmenter/pull/128.
=> Intl.Segmenter iterator result should have isWordLike only if type is "word"

test/intl402/DateTimeFormat/prototype/format/related-year-zh.js, test/intl402/DateTimeFormat/prototype/formatToParts/related-year-zh.js
Apple ICU team is shipping macOS system ICU with newer CLDR, but it has many overrides on the top of it to make the formatted output suitable for the rest of the system (entire macOS components are using this system ICU).
So this is not using raw CLDR data.
In related-year-zh.js tests, Apple ICU intentionally overrides the CLDR data with the different format.
This change modifies the test to accept that alternative output.
I think this is OK since test262 is not a test for CLDR/ICU and the different output is OK so long as it is intentional :)
And formatToParts is showing right results for the generated output.
=> related-year-zh.js may not contain years

README.md
Currently, we direct the readers to `compare` page. Which is odd, since readers
hope to land on the branch's page. Let's fix this by changing the link to point
to the branch's page.
=> fix link to branch `preserved-website-directory`

test/language/expressions/tagged-template/invalid-escape-sequences.js, test/language/expressions/template-literal/invalid-legacy-octal-escape-sequence-9.js, test/language/literals/string/legacy-non-octal-escape-sequence-9-strict.js
Supplement to #2654, per @syg's request.
I just included tests for \8 in that PR but we really should check \9 as well for completeness.
=> Add tests for \9 in template/strict strings.

src/class-elements/grammar-special-prototype-accessor-meth-valid.case, src/class-elements/grammar-special-prototype-async-gen-meth-valid.case, src/class-elements/grammar-special-prototype-async-meth-valid.case, src/class-elements/grammar-special-prototype-gen-meth-valid.case, src/class-elements/grammar-special-prototype-meth-valid.case, test/language/expressions/class/elements/syntax/valid/grammar-special-prototype-accessor-meth-valid.js, test/language/expressions/class/elements/syntax/valid/grammar-special-prototype-async-gen-meth-valid.js, test/language/expressions/class/elements/syntax/valid/grammar-special-prototype-async-meth-valid.js, test/language/expressions/class/elements/syntax/valid/grammar-special-prototype-gen-meth-valid.js, test/language/expressions/class/elements/syntax/valid/grammar-special-prototype-meth-valid.js, test/language/statements/class/elements/syntax/valid/grammar-special-prototype-accessor-meth-valid.js, test/language/statements/class/elements/syntax/valid/grammar-special-prototype-async-gen-meth-valid.js, test/language/statements/class/elements/syntax/valid/grammar-special-prototype-async-meth-valid.js, test/language/statements/class/elements/syntax/valid/grammar-special-prototype-gen-meth-valid.js, test/language/statements/class/elements/syntax/valid/grammar-special-prototype-meth-valid.js
JSC bug: [Incorrect early errors for class methods named `"constructor"` and `"prototype"`](https://bugs.webkit.org/show_bug.cgi?id=215413).
=> Assert that instance methods can be named "prototype"

test/annexB/built-ins/Object/is/emulates-undefined.js, test/annexB/language/expressions/does-not-equals/emulates-undefined.js, test/annexB/language/expressions/equals/emulates-undefined.js, test/annexB/language/expressions/strict-does-not-equals/emulates-undefined.js, test/annexB/language/expressions/strict-equals/emulates-undefined.js, test/annexB/language/statements/switch/emulates-undefined.js
Closes #1372.
Related: #2726, #2706.
Tested manually in FF 81 and Chrome 86: all tests pass.
=> Test [[IsHTMLDDA]] object with equality operations

test/intl402/NumberFormat/dft-currency-mnfd-range-check-mxfd.js
The other test that was affected by the change was one of V8's local tests.
Refs: https://github.com/tc39/ecma402/pull/471
/cc @littledan @sffc
=> Update tests for tc39/ecma402#471

harness/compareArray.js, test/harness/compare-array-falsy-arguments.js
Quite a few tests, including ones in `test/built-ins/RegExp/lookBehind`, pass result of `RegExp.prototype.exec` to `assert.compareArray`. Without this change & stack trace, it is impossible to figure out which test case is failing:
```diff
test/built-ins/RegExp/lookBehind/simple-fixed-length.js:
-  default: "TypeError: null is not an object (evaluating 'a.length')"
-  strict mode: "TypeError: null is not an object (evaluating 'a.length')"
+  default: "Test262Error: First argument shouldn't be nullish. #5"
+  strict mode: "Test262Error: First argument shouldn't be nullish. #5"
```
=> Gracefully handle nullish arguments in harness/compareArray

test/intl402/DateTimeFormat/constructor-options-order-fractionalSecondDigits.js
In this PR[1], fractionalSecondDigits is listed earlier than timeZoneName in table 6[2].
So, accessing order of fractionalSecondDigits in [3]'s step-29 should be earlier than timeZoneName.
[1]: https://github.com/tc39/ecma402/pull/347
[2]: https://tc39.es/ecma402/#sec-datetimeformat-abstracts
[3]: https://tc39.es/ecma402/#sec-initializedatetimeformat
=> Accessing order of fractionalSecondDigits should be earlier than timeZoneName

test/annexB/language/expressions/object/__proto__-poisoned-object-prototype.js, test/language/expressions/object/__proto__-permitted-dup-shorthand.js, test/language/expressions/object/__proto__-permitted-dup.js
JSC bugs:
* [`__proto__` shorthand property should not modify prototype in Object Literal construction](https://bugs.webkit.org/show_bug.cgi?id=142382).
* [`__proto__` in object literal should perform `[[SetPrototypeOf]]` directly](https://bugs.webkit.org/show_bug.cgi?id=215769).
* [Invalid early error for object literal method named `"__proto__"`](https://bugs.webkit.org/show_bug.cgi?id=215760).
=> Improve coverage for __proto__ in object literals

harness/testIntl.js
This code is setting values to $1 etc., which can be non-writable or accessors.
For example, https://github.com/tc39/proposal-regexp-legacy-features/ is specifying them as accessors, and they should throw an error when
it is done in strict code. We should execute `(/(?:)/).test("");` to clear them.
=> Property clearing code of RegExp constructor is wrong

test/built-ins/Array/prototype/methods-called-as-functions.js, test/built-ins/Date/prototype/Symbol.toPrimitive/called-as-function.js, test/built-ins/Date/prototype/toJSON/called-as-function.js, test/built-ins/Error/prototype/toString/called-as-function.js, test/built-ins/RegExp/prototype/toString/called-as-function.js
While there are way more built-ins to cover, namely `String.prototype` methods, I would appreciate this merged as-is for JSC to be fixed soonish.
=> Test generic methods called as top-level functions

test/built-ins/Date/prototype/no-date-value.js, test/built-ins/Error/prototype/no-error-data.js
Similar test for [`RegExp.prototype`](https://tc39.es/ecma262/#sec-properties-of-the-regexp-prototype-object): [`/test/built-ins/RegExp/prototype/no-regexp-matcher.js`](https://github.com/tc39/test262/blob/main/test/built-ins/RegExp/prototype/no-regexp-matcher.js).
JSC bug: [For many `X`, `X.prototype` is an `X` when it must be a plain object](https://bugs.webkit.org/show_bug.cgi?id=141610).
=> Test that pre-ES6 built-in prototypes are not instances

features.txt, test/annexB/built-ins/RegExp/legacy-accessors/index/prop-desc.js, test/annexB/built-ins/RegExp/legacy-accessors/index/this-cross-realm-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/index/this-not-regexp-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/index/this-subclass-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/input/prop-desc.js, test/annexB/built-ins/RegExp/legacy-accessors/input/this-cross-realm-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/input/this-not-regexp-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/input/this-subclass-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/lastMatch/prop-desc.js, test/annexB/built-ins/RegExp/legacy-accessors/lastMatch/this-cross-realm-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/lastMatch/this-not-regexp-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/lastMatch/this-subclass-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/lastParen/prop-desc.js, test/annexB/built-ins/RegExp/legacy-accessors/lastParen/this-cross-realm-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/lastParen/this-not-regexp-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/lastParen/this-subclass-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/leftContext/prop-desc.js, test/annexB/built-ins/RegExp/legacy-accessors/leftContext/this-cross-realm-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/leftContext/this-not-regexp-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/leftContext/this-subclass-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/rightContext/prop-desc.js, test/annexB/built-ins/RegExp/legacy-accessors/rightContext/this-cross-realm-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/rightContext/this-not-regexp-constructor.js, test/annexB/built-ins/RegExp/legacy-accessors/rightContext/this-subclass-constructor.js, test/annexB/built-ins/RegExp/prototype/compile/this-cross-realm-instance.js, test/annexB/built-ins/RegExp/prototype/compile/this-subclass-instance.js
This adds tests for [the legacy RegExp features proposal](https://github.com/tc39/proposal-regexp-legacy-features):
---
Resolves <https://github.com/tc39/test262/issues/2371>
Resolves <https://github.com/tc39/proposal-regexp-legacy-features/issues/15>
=> Add tests for legacy RegExp features

test/built-ins/RegExp/prototype/Symbol.replace/poisoned-stdlib.js
JSC bug: [Use `@putByValDirect` instead `Array.prototype.@push` in builtins](https://bugs.webkit.org/show_bug.cgi?id=175432).
Follow-up of #2481.
=> Improve RegExp.prototype[@@replace] poisoned stdlib test

test/intl402/NumberFormat/dft-currency-mnfd-range-check-mxfd.js
In 12.1.1 SetNumberFormatDigitOptions step 12.d[1], mnfd (minimum fraction digits) becomes the same to currencyDigits (mxfdDefault in this case).
It is 2 for USD, 4 for CLF. So, if maximumFractionDigits is less than that, we should throw RangeError.
[1]: https://tc39.es/ecma402/#sec-setnfdigitoptions
=> Intl.NumberFormat + currency will throw an error if maximumFractionDigits is less than currencyDigits

test/intl402/DateTimeFormat/prototype/format/timedatestyle-en.js
macOS system ICU is shipping new CLDR, but it has many overrides on the top of it to make the formatted output suitable for the system.
And in timedatestyle-en.js tests, we intentionally override the CLDR data with the different format.
This change modifies the test to accept that alternative output.
=> Connector of date and time style can be " at " or ", "

test/intl402/Segmenter/constructor/constructor/options-granularity-abrupt-throws.js, test/intl402/Segmenter/constructor/constructor/options-granularity-toString-abrupt-throws.js
=> Perl YAML parser cannot parse documents in options-granularity-abrupt-throws.js and options-granularity-toString-abrupt-throws.js

test/built-ins/String/prototype/replace/replaceValue-evaluation-order-regexp-object.js
New test that ensures a regexp object that appears as the replaceValue of String.prototype.replace has its toString method called.
=> Coverage: String.prototype.replace method calls toString on replaceValue (regexp object). Fixes gh-2797

test/intl402/NumberFormat/dft-currency-mnfd-range-check-mxfd.js
This reverts commit a7b9067fe129b8ded01a4b86f8295ed40fe2d9e5.
I fixed the test with a7b9067fe129b8ded01a4b86f8295ed40fe2d9e5 based on the current spec, but this test was based on WIP spec change.
=> Revert "Intl.NumberFormat + currency will throw an error if maximumFractionDigits is less than currencyDigits"

test/intl402/NumberFormat/dft-currency-mnfd-range-check-mxfd.js
This test is checking maximumSignificantDigits, but this is wrong. We should check maximumFractionDigits.
=> dft-currency-mnfd-range-check-mxfd.js should check maximumFractionDigits, not maximumSignificantDigits

test/intl402/Locale/reject-duplicate-variants-in-tlang.js, test/intl402/Locale/reject-duplicate-variants.js
(This is currently un-exercised so may contain tpyos or similar -- posting so I can test that it works correctly against SM by importing it.)
=> Add a test verifying that duplicate variants in the tlang component of a language tag make it structurally invalid

test/language/statements/class/elements/privatefieldget-primitive-receiver.js, test/language/statements/class/elements/privatefieldput-primitive-receiver.js
It closes #2852.
The test was originally proposed by @rwaldron and I extended to test multiple type of primitives.
=> Adding test cases to validate private field access with primitive receivers. Fixes gh-2852

test/intl402/DateTimeFormat/intl-legacy-constructed-symbol-on-unwrap.js, test/intl402/DateTimeFormat/intl-legacy-constructed-symbol.js, test/intl402/NumberFormat/intl-legacy-constructed-symbol-on-unwrap.js, test/intl402/NumberFormat/intl-legacy-constructed-symbol.js
If normative optional is implemented and [[FallbackSymbol]] is used, its description should be "IntlLegacyConstructedSymbol"
https://tc39.es/ecma402/#intl-object
> The Intl object has an internal slot, [[FallbackSymbol]], which is a new %Symbol% in the current realm with the [[Description]] "IntlLegacyConstructedSymbol".
Tests for https://trac.webkit.org/changeset/266655/webkit change.
=> Add tests for [[Description]] of Intl [[FallbackSymbol]]

test/built-ins/TypedArrayConstructors/internals/GetOwnProperty/index-prop-desc.js
Since the 1's value is 43, 43 should be populated in a descriptor.
=> Fix test/built-ins/TypedArrayConstructors/internals/GetOwnProperty/index-prop-desc.js's value

test/built-ins/String/prototype/at/prop-desc.js, test/built-ins/TypedArray/prototype/at/prop-desc.js
Fix for copy-paste errors in the verifyProperty change of #2907.
@leobalter @rwaldron
=> Fix typos for at/prop-desc tests.

test/built-ins/parseInt/S15.1.2.2_A2_T2.js
The script that we use for updating SpiderMonkey's copy of test262 doesn't like this.
@rwaldron r?
=> Remove test code between license and front matter

test/intl402/DateTimeFormat/prototype/formatRange/date-same-returns-single-date.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-same-returns-single-date.js
Add tests for Intl.DateTimeFormat formatRange(ToParts) to check the behavior when startDate is the same as endDate.
This is based on the discussion and conclusion on tc39/proposal-intl-DateTimeFormat-formatRange#19.
=> Add tests for intl402 formatRange(ToParts) to check the behavior when startDate is the same as endDate.

test/intl402/DateTimeFormat/prototype/formatRange/date-same-returns-single-date.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-same-returns-single-date.js
intl402/DateTimeFormat/prototype/formatRangeToParts/date-same-returns-single-date.js is using `formatRange` and `format`.
Fix this test to use `formatRangeToParts` and `formatToParts` since it is the intention of this test.
This patch adds additional tests to intl402/DateTimeFormat/prototype/formatRangeToParts/date-same-returns-single-date.js and
intl402/DateTimeFormat/prototype/formatRange/date-same-returns-single-date.js. The new test uses two dates that are practially-equal,
and ensures the implementation uses `format` or `formatToParts` by detecting they are practically-equal.
=> Fix formatRangeToParts/date-same-returns-single-date.js and add tests using practically-equal two dates

test/language/export/escaped-as-export-specifier.js, test/language/export/escaped-default.js, test/language/export/escaped-from.js, test/language/expressions/async-arrow-function/escaped-async-line-terminator.js, test/language/expressions/async-arrow-function/escaped-async.js, test/language/expressions/async-function/escaped-async.js, test/language/expressions/async-generator/escaped-async.js, test/language/expressions/dynamic-import/escape-sequence-import.js, test/language/expressions/import.meta/syntax/escape-sequence-import.js, test/language/expressions/import.meta/syntax/escape-sequence-meta.js, test/language/expressions/new.target/escaped-new.js, test/language/expressions/new.target/escaped-target.js, test/language/expressions/object/method-definition/async-gen-meth-escaped-async.js, test/language/expressions/object/method-definition/async-meth-escaped-async.js, test/language/expressions/object/method-definition/escaped-get.js, test/language/expressions/object/method-definition/escaped-set.js, test/language/import/escaped-as-import-specifier.js, test/language/import/escaped-as-namespace-import.js, test/language/import/escaped-from.js, test/language/statements/async-function/escaped-async.js, test/language/statements/async-generator/escaped-async.js, test/language/statements/class/async-gen-meth-escaped-async.js, test/language/statements/class/async-meth-escaped-async.js, test/language/statements/class/syntax/escaped-static.js, test/language/statements/for-await-of/escaped-of.js, test/language/statements/for-of/escaped-of.js, test/language/statements/let/syntax/escaped-let.js
The quoted spec wording changed in tc39/ecma262#1694.
(Note that the former wording, referring to "terminal symbols of the lexical, RegExp, and numeric string grammars" wasn't actually relevant to these tests, because each test hinges on a terminal symbol of the *syntactic* grammar.)
=> Update "info" field

test/built-ins/Function/property-order.js, test/built-ins/Function/prototype/property-order.js, test/built-ins/Object/property-order.js, test/built-ins/Promise/all/resolve-element-function-property-order.js, test/built-ins/Promise/allSettled/reject-element-function-property-order.js, test/built-ins/Promise/allSettled/resolve-element-function-property-order.js, test/built-ins/Promise/any/reject-element-function-property-order.js, test/built-ins/Promise/executor-function-property-order.js, test/built-ins/Promise/property-order.js, test/built-ins/Promise/reject-function-property-order.js, test/built-ins/Promise/resolve-function-property-order.js, test/built-ins/Proxy/property-order.js, test/built-ins/Proxy/revocable/revocation-function-property-order.js, test/built-ins/ThrowTypeError/property-order.js, test/intl402/Collator/prototype/compare/compare-function-property-order.js, test/intl402/DateTimeFormat/prototype/format/format-function-property-order.js, test/intl402/NumberFormat/prototype/format/format-function-property-order.js
**Spec:** <https://github.com/tc39/ecma262/pull/2116>
---
I’ve also added tests for all built‑in functions that had their tests updated in <https://github.com/tc39/test262/pull/2299>.
---
/cc @bakkot @ljharb @michaelficarra @syg
=> Set function `length` and `name` in `CreateBuiltinFunction`

test/built-ins/TypedArray/prototype/filter/BigInt/callbackfn-detachbuffer.js, test/built-ins/TypedArray/prototype/findIndex/BigInt/predicate-may-detach-buffer.js
WebKit implemented `BigInt64Array` and `BigUint64Array` in https://github.com/WebKit/WebKit/commit/5a13e56ddd882124c0803939f4ba08f1c1f16a18 and found two test262 issues.
1. test/built-ins/TypedArray/prototype/findIndex/BigInt/predicate-may-detach-buffer.js
It is not updated when a60a67ea880bb4b5de849ee8f7676a475f60c85f is landed. This patch fixes it.
2. test/built-ins/TypedArray/prototype/filter/BigInt/callbackfn-detachbuffer.js
After detaching, BigInt64Array/BigUint64Array will produce undefined for indexed access. And
if `filter`'s callback says `true` for these results, we need to store `ToBigInt(undefined)`
to a newly resulted BigInt64Array/BigUint64Array and this will throw an error. But this test
assumed it does not throw. This patch fixes flag so that we do not throw that error …
=> Fix BigInt TypedArrays tests

INTERPRETING.md
(It was folded into "phase: parse" in PR #1366.)
=> Remove mention of "phase: early", since it's never used

test/built-ins/Object/assign/target-is-frozen-accessor-property-set-succeeds.js, test/built-ins/Object/assign/target-is-frozen-data-property-set-throws.js, test/built-ins/Object/assign/target-is-non-extensible-existing-accessor-property.js, test/built-ins/Object/assign/target-is-non-extensible-existing-data-property.js, test/built-ins/Object/assign/target-is-non-extensible-property-creation-throws.js, test/built-ins/Object/assign/target-is-sealed-existing-accessor-property.js, test/built-ins/Object/assign/target-is-sealed-existing-data-property.js, test/built-ins/Object/assign/target-is-sealed-property-creation-throws.js
JSC bug: [`Object.assign` should throw for property creation on non-extensible `target`](https://bugs.webkit.org/show_bug.cgi?id=220712).
=> Test Object.assign with non-extensible/sealed/frozen targets

test/built-ins/Object/freeze/proxy-with-defineProperty-handler.js, test/built-ins/Object/seal/proxy-with-defineProperty-handler.js
JSC bug: [`SetIntegrityLevel` should call `[[DefineOwnProperty]]` with partial descriptor](https://bugs.webkit.org/show_bug.cgi?id=221497).
=> Test SetIntegrityLevel on Proxy with "defineProperty" trap

test/intl402/DateTimeFormat/constructor-no-instanceof.js, test/intl402/DateTimeFormat/prototype/format/no-instanceof.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/no-instanceof.js, test/intl402/NumberFormat/constructor-no-instanceof.js, test/intl402/NumberFormat/prototype/format/no-instanceof.js, test/intl402/NumberFormat/prototype/resolvedOptions/no-instanceof.js
Add tests to make sure `NumberFormat` and `DateTimeFormat` do not call the `instanceof` operator and call `OrdinaryHasInstance` instead.
Refs: https://github.com/tc39/ecma402/pull/500
=> Add NumberFormat and DateTimeFormat tests for OrdinaryHasInstance

test/built-ins/Array/prototype/sort/call-with-primitive.js
V8 bug: [Array.prototype.sort should not skip ToObject for primitive `this` values](https://bugs.chromium.org/p/v8/issues/detail?id=11362).
Discovered in https://github.com/tc39/test262/pull/2807#discussion_r492844425.
=> Test Array.prototype.sort called with a primitive

INTERPRETING.md
Prior to this commit, the implementation of Markdown on GitHub.com
caused the contents of two list items to be rendered outside of their
containing list. Update the indentation so that the structure of the
rendered output matches the structure implied by the text.
=> Correct formatting in INTERPRETING.md

test/language/statements/class/private-non-static-getter-static-setter-early-error.js, test/language/statements/class/private-non-static-setter-static-getter-early-error.js, test/language/statements/class/private-static-getter-non-static-setter-early-error.js, test/language/statements/class/private-static-setter-non-static-getter-early-error.js
Several tests for getters and setters claim to check for an early
SyntaxError regarding mixing static and non-static propeties with the
same name. However, the tests trigger another issue: the getters have no
method body; they're missing curlies.
Fix the tests to test only the intended SyntaxError, not unrelated
SyntaxError-s.
=> Fix typo in private getter/setter tests

test/built-ins/Array/prototype/toString/non-callable-join-string-tag.js
JSC bug: [Array's `toString()` is incorrect if `join()` is non-callable](https://bugs.webkit.org/show_bug.cgi?id=224215).
=> Test Array's toString() with non-callable "join"

test/language/future-reserved-words/implements.js, test/language/future-reserved-words/interface.js, test/language/future-reserved-words/package.js, test/language/future-reserved-words/private.js, test/language/future-reserved-words/protected.js, test/language/future-reserved-words/public.js, test/language/future-reserved-words/static.js
I noticed while fixing test failures in JSC that V8 exhibits the following surprising behavior in sloppy mode:
```js
// OK
var st\u0061tic = 3;
// should be OK but throws
let st\u0061tic = 3;
// OK
const st\u0061tic = 3;
```
This PR adds coverage such that the issue can be detected.
=> Strengthen sloppy-mode tests for future reserved words.

test/built-ins/BigInt/wrapper-object-ordinary-toprimitive.js, test/built-ins/Symbol/prototype/Symbol.toPrimitive/redefined-symbol-wrapper-ordinary-toprimitive.js, test/built-ins/Symbol/prototype/Symbol.toPrimitive/removed-symbol-wrapper-ordinary-toprimitive.js
JSC bug: [`Symbol` and `BigInt` wrapper objects should perform `OrdinaryToPrimitive`](https://bugs.webkit.org/show_bug.cgi?id=224208).
`BigInt` test is passing on V8 7.5.288.22.
=> Test that Symbol / BigInt wrapper objects perform OrdinaryToPrimitive

test/language/module-code/export-expname-binding-index.js, test/language/module-code/export-expname-binding-index_FIXTURE.js
JSC bug: [Add `JSModuleNamespaceObject::deletePropertyByIndex()` method](https://bugs.webkit.org/show_bug.cgi?id=222611).
=> Test internal methods of module namespace objects with indices

test/built-ins/Error/cause_abrupt.js, test/built-ins/Error/cause_property.js, test/built-ins/Error/constructor.js, test/built-ins/NativeErrors/AggregateError/cause-property.js, test/built-ins/NativeErrors/cause_property_native_error.js
Implementation Status:
- ChakraCore: https://github.com/chakra-core/ChakraCore/commit/b992a5d1092cb978a70e873e0ae661c835f05c8c
- JSC: https://github.com/WebKit/WebKit/commit/b03c4f4dada2c477376b9275332e08a3d08eba5f
=> Add tests for stage 3 proposal error cause

features.txt, test/built-ins/Error/cause_abrupt.js, test/built-ins/Error/cause_property.js, test/built-ins/Error/constructor.js, test/built-ins/NativeErrors/AggregateError/cause-property.js, test/built-ins/NativeErrors/cause_property_native_error.js
In general new features need a features tag for V8 so that the proper shell flags can be passed to the runner to turn on the feature for testing.
=> Give Error cause tests the error-cause feature tag

test/language/statements/for-await-of/head-lhs-async.js
This adds a test for `for await (async of`, since the identifier `async` is legal here.
Fixes #2979; motivated by https://github.com/babel/babel/issues/13235.
=> Add a test for `for await (async of`

test/language/statements/for-of/head-lhs-async-escaped.js, test/language/statements/for-of/head-lhs-async-parens.js
This adds tests for two more edge-cases related to the `for (async of` restriction (https://github.com/tc39/ecma262/pull/2256):
```js
for (\u0061sync of [7]);
```
In this case, the identifier `async` is written with an escape sequence. This avoids the `async of` lookahead, which only considers non-escaped words.
This detects implementations that check for an `async` token without considering whether it was escaped.
Recently fixed in V8: https://bugs.chromium.org/p/v8/issues/detail?id=11722
```js
for ((async) of [7]);
```
In this case, the identifier token `async` is preceded by a `(` token, which avoids the `async of` lookahead because `async` is no longer the first token in the head.
This detects implementations that check whether the LHS is an identifier at the AST level, without …
=> Add more tests for `for (async of` edge-cases

test/built-ins/Error/cause_abrupt.js
Minimize the code provided to the `assert.throws` utility in order to
reduce the possibility of false positives and to improve failure
messages in non-conforming runtimes.
---
@legendecas here's the improvement that [I mentioned earlier](https://github.com/tc39/test262/pull/2965#pullrequestreview-643575028).
=> Increase precision of assertions for Error Cause

test/built-ins/Symbol/for/description.js
Resolves gh-2967. I reviewed the project's coverage for the rest of this algorithm, and it looks okay to me.
=> Add test for [[Description]] from `Symbol.for`

test/language/module-code/top-level-await/dfs-invariant-async_FIXTURE.js, test/language/module-code/top-level-await/dfs-invariant-direct-1_FIXTURE.js, test/language/module-code/top-level-await/dfs-invariant-direct-2_FIXTURE.js, test/language/module-code/top-level-await/dfs-invariant-indirect_FIXTURE.js, test/language/module-code/top-level-await/dfs-invariant.js
This behavior was introduced after the Top-Level Await proposal reached
stage 3: https://github.com/tc39/proposal-top-level-await/pull/159
=> Add test for TLA DFS invariant

test/rejected.js
@rwaldron I can't figure out how this test made it to `main`. We definitely removed it from gh-2980 via 92cf109, but it's somehow present in the final commit, 5ae04619a9348f9156382eb412e7b8458b8d3d30. Hinky
=> Remove invalid test

features.txt, test/intl402/Locale/prototype/calendars/branding.js, test/intl402/Locale/prototype/calendars/name.js, test/intl402/Locale/prototype/calendars/prop-desc.js, test/intl402/Locale/prototype/collations/branding.js, test/intl402/Locale/prototype/collations/name.js, test/intl402/Locale/prototype/collations/prop-desc.js, test/intl402/Locale/prototype/hourCycles/branding.js, test/intl402/Locale/prototype/hourCycles/name.js, test/intl402/Locale/prototype/hourCycles/prop-desc.js, test/intl402/Locale/prototype/numberingSystems/branding.js, test/intl402/Locale/prototype/numberingSystems/name.js, test/intl402/Locale/prototype/numberingSystems/prop-desc.js, test/intl402/Locale/prototype/textInfo/branding.js, test/intl402/Locale/prototype/textInfo/name.js, test/intl402/Locale/prototype/textInfo/prop-desc.js, test/intl402/Locale/prototype/timeZones/branding.js, test/intl402/Locale/prototype/timeZones/name.js, test/intl402/Locale/prototype/timeZones/prop-desc.js, test/intl402/Locale/prototype/weekInfo/branding.js, test/intl402/Locale/prototype/weekInfo/name.js, test/intl402/Locale/prototype/weekInfo/prop-desc.js
Add the basic tests (`name.js`, `branding.js` and `prop-desc.js`) for the Intl LocaleInfo proposal.
The existing getters on the `Intl.Locale` prototype only have these basic tests as well, so I think this should be sufficient for unblocking implementations. That said, I will try to add more comprehensive tests for these getters.
/cc @FrankYFTang
Fixes: #2984
=> Add basic tests for proposal-intl-locale-info

test/annexB/language/literals/regexp/legacy-octal-escape.js, test/language/expressions/template-literal/invalid-legacy-octal-escape-sequence-8.js, test/language/expressions/template-literal/invalid-legacy-octal-escape-sequence-9.js, test/language/expressions/template-literal/invalid-legacy-octal-escape-sequence.js, test/language/literals/numeric/legacy-octal-integer-strict.js, test/language/literals/numeric/legacy-octal-integer.js, test/language/literals/numeric/non-octal-decimal-integer-strict.js, test/language/literals/numeric/non-octal-decimal-integer.js, test/language/literals/string/legacy-non-octal-escape-sequence-1-strict-explicit-pragma.js, test/language/literals/string/legacy-non-octal-escape-sequence-2-strict-explicit-pragma.js, test/language/literals/string/legacy-non-octal-escape-sequence-3-strict-explicit-pragma.js, test/language/literals/string/legacy-non-octal-escape-sequence-4-strict-explicit-pragma.js, test/language/literals/string/legacy-non-octal-escape-sequence-5-strict-explicit-pragma.js, test/language/literals/string/legacy-non-octal-escape-sequence-6-strict-explicit-pragma.js, test/language/literals/string/legacy-non-octal-escape-sequence-7-strict-explicit-pragma.js, test/language/literals/string/legacy-non-octal-escape-sequence-8-non-strict.js, test/language/literals/string/legacy-non-octal-escape-sequence-8-strict-explicit-pragma.js, test/language/literals/string/legacy-non-octal-escape-sequence-8-strict.js, test/language/literals/string/legacy-non-octal-escape-sequence-9-non-strict.js, test/language/literals/string/legacy-non-octal-escape-sequence-9-strict-explicit-pragma.js, test/language/literals/string/legacy-non-octal-escape-sequence-9-strict.js, test/language/literals/string/legacy-non-octal-escape-sequence-strict.js, test/language/literals/string/legacy-octal-escape-sequence-strict.js, test/language/literals/string/legacy-octal-escape-sequence.js
Additionally, update test metadata and introduce two new tests to
complete coverage.
Reference: "Normative: Make B.1.{1,2} normative"
https://github.com/tc39/ecma262/pull/1867
=> Move some AnnexB tests per proposed spec change

package.json, tools/scripts/ci_test.sh
Prior to this patch, the CircleCI continuous integration environment was
configured to report test failures in a negative light, displaying red
cross-marks and reporting that "some checks were not successful" in
commits and GitHub Pull Requests which included them.
The passing/failing status of tests does not influence their
desirability for Test262. (In practice, engines very commonly fail
newly-contributed tests.)
Although these conflicting interpretations does not technically
interfere with the maintainers' ability to merge new contributions, it
does create confusion for many contributors who interpreted the UI as a
rejection of their work.
In addition, this behavior made it impossible to distinguish between the
benign test failures and disruptive infrastructural problems (e.g. the …
=> CI: Do not report test failures as errors

harness/regExpUtils.js
This increases compatibility with less advanced engines that only have partial support for recent language features like assignment patterns.
=> Don't use function argument destructuring in regExpUtils.js

test/language/expressions/delete/super-property-null-base.js
SpiderMonkey and Engine262 exhibit the expected behavior, while V8 and JSC throw a ReferenceError. The expected behavior may be changed by a spec patch which is currently under review, [Normative: Allow null or undefined in Reference Records](https://github.com/tc39/ecma262/pull/2267).
=> Test sequence during deletion of SuperProperty

harness/testIntl.js, test/intl402/Segmenter/constructor/supportedLocalesOf/locales-specific.js, test/intl402/fallback-locales-are-supported.js, test/intl402/supportedLocalesOf-consistent-with-resolvedOptions.js, test/intl402/supportedLocalesOf-unicode-extensions-ignored.js
This PR fix the harness by passing the option for getLocaleSupportInfo instead of an internal hard coded {localeMatcher:  "lookup"} . It also fix 3 tests which have strong assumption based on only "lookup" localeMatcher
1. intl402/Segmenter/constructor/supportedLocalesOf/locales-specific.js
The expectation that "sr-Thai-RS" would be returned is only true with the 
9.2.2 BestAvailableLocale ( availableLocales, locale )
https://tc39.es/ecma402/#sec-bestavailablelocale
algorithm used by 9.2.3 LookupMatcher ( availableLocales, requestedLocales )
https://tc39.es/ecma402/#sec-lookupmatcher
The default for localeMatcher is "best fit" but not "lookup" for all Intl objects.
And for 9.2.4 BestFitMatcher ( availableLocales, requestedLocales )
https://tc39.es/ecma402/#sec-bestfitmatcher
It may not …
=> Fix tests on {localeMatcher: "lookup"}

tools/lint/lib/checks/negative.py, tools/lint/test/fixtures/test/negative_extra_fields.js
As highlighted by gh-3006. cc @jmdyck
=> lint: disallow extra fields in "negative" metadata

test/language/import/json-extensibility-array.js, test/language/import/json-extensibility-object.js, test/language/import/json-idempotency.js, test/language/import/json-invalid.js, test/language/import/json-named-bindings.js, test/language/import/json-value-array.js, test/language/import/json-value-boolean.js, test/language/import/json-value-null.js, test/language/import/json-value-number.js, test/language/import/json-value-object.js, test/language/import/json-value-string.js, test/language/import/json-via-namespace.js
The language/import/json-* tests depend on syntax from the Stage 3 import assertions proposal, so these tests should have the import-assertions feature tag.
Add it to the tests where it was missing.
=> Add 'import-assertions' feature tag to json modules tests

features.txt, test/built-ins/DataView/prototype/getBigInt64/resizable-buffer.js, test/built-ins/DataView/prototype/getBigUint64/resizable-buffer.js, test/built-ins/DataView/prototype/getFloat32/resizable-buffer.js, test/built-ins/DataView/prototype/getFloat64/resizable-buffer.js, test/built-ins/DataView/prototype/getInt16/resizable-buffer.js, test/built-ins/DataView/prototype/getInt32/resizable-buffer.js, test/built-ins/DataView/prototype/getInt8/resizable-buffer.js, test/built-ins/DataView/prototype/getUint16/resizable-buffer.js, test/built-ins/DataView/prototype/getUint32/resizable-buffer.js, test/built-ins/DataView/prototype/getUint8/resizable-buffer.js, test/built-ins/DataView/prototype/setBigInt64/resizable-buffer.js, test/built-ins/DataView/prototype/setBigUint64/resizable-buffer.js, test/built-ins/DataView/prototype/setFloat32/resizable-buffer.js, test/built-ins/DataView/prototype/setFloat64/resizable-buffer.js, test/built-ins/DataView/prototype/setInt16/resizable-buffer.js, test/built-ins/DataView/prototype/setInt32/resizable-buffer.js, test/built-ins/DataView/prototype/setInt8/resizable-buffer.js, test/built-ins/DataView/prototype/setUint16/resizable-buffer.js, test/built-ins/DataView/prototype/setUint32/resizable-buffer.js, test/built-ins/DataView/prototype/setUint8/resizable-buffer.js
The files in this patch are highly similar. Only the test for
`DataView.prototype.getBigInt64` and `DataView.prototype.setBigInt64`
were written manually. The others were generated from those files via
the following script:
#!/bin/bash
set -eu
names='
BigUint64
Float32
Float64
Int16
Int32
Int8
Uint16
Uint32
Uint8
'
for name in ${names}; do
lower=$(echo ${name} | tr '[:upper:]' '[:lower:]')
if [ ${name} == 'BigUint64' ]; then
replace_bigints=''
else
replace_bigints='-e s/\b\([0-9]\+\)n\b/\1/g'
fi
sed \
-e "s/getbigint64/get${lower}/g" \
-e "s/getBigInt64/get${name}/g" \
${replace_bigints} \
./test/built-ins/DataView/prototype/getBigInt64/resizable-buffer.js \
> ./test/built-ins/DataView/prototype/get${name}/resizable-buffer.js
sed \
-e "s/setbigint64/set${lower}/g" \
-e …
=> Resizable ArrayBuffer: DataView methods

test/built-ins/TypedArray/prototype/at/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/copyWithin/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/entries/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/every/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/fill/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/filter/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/find/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/findIndex/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/forEach/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/includes/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/indexOf/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/join/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/keys/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/lastIndexOf/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/map/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/reduce/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/reduceRight/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/reverse/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/set/typedarray-arg-set-values-same-buffer-same-type-resized.js, test/built-ins/TypedArray/prototype/set/typedarray-arg-target-out-of-bounds.js, test/built-ins/TypedArray/prototype/slice/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/some/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/sort/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/toLocaleString/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/values/return-abrupt-from-this-out-of-bounds.js
The files in the second commit are highly similar. Only the test for
`TypedArray.prototype.copyWithin` was written manually. The others were
generated from that test via the following script:
#!/bin/bash
set -eu
names_cb='
every
filter
find
findIndex
forEach
map
reduce
reduceRight
some
'
names_num='
at
fill
includes
indexOf
join
lastIndexOf
slice
'
names_none='
entries
values
keys
reverse
sort
toLocaleString
values
'
for name in $(printf "${names_cb} ${names_num} ${names_none}"); do
lower=$(echo ${name} | tr '[:upper:]' '[:lower:]')
if echo "$names_cb" | grep -xq $name; then
value='() => {}'
elif echo "$names_num" | grep -xq $name; then
value='0'
else
value=''
fi
sed \
-e "s/copywithin/${lower}/g" \
-e "s/copyWithin/${name}/g" \
-e …
=> Resizable ArrayBuffer: TypedArray methods

test/built-ins/Temporal/now/instant/extensible.js, test/built-ins/Temporal/now/instant/length.js, test/built-ins/Temporal/now/instant/name.js, test/built-ins/Temporal/now/instant/not-a-constructor.js, test/built-ins/Temporal/now/instant/prop-desc.js, test/built-ins/Temporal/now/instant/return-value-distinct.js, test/built-ins/Temporal/now/instant/return-value-prototype.js, test/built-ins/Temporal/now/instant/return-value-value.js
=> Add tests for Temporal.now.instant

test/language/statements/class/definition/fn-length-static-precedence.js
Since https://github.com/tc39/ecma262/pull/1490, the "length" and "name" properties of a class are defined before any static methods. This is tested by #2057, in test/language/computed-property-names of all places.
At the same time, static methods with "name" as the name would overwrite the original property, but retain the original property enumeration order. This was not previously tested. In fact, the overwriting behavior was not tested at all for the "length" property.
This commit mends both holes in test coverage.
=> Add more static class property ordering tests

test/language/expressions/delete/super-property-null-base.js
The following proposed change modifies the semantics this test was
originally written to verify:
Normative: Allow null or undefined in Reference Records
https://github.com/tc39/ecma262/pull/2267
=> Update test for deletion of SuperProperty

test/language/expressions/delete/identifier-strict-recursive.js
i noticed this was missing after seeing all the tests for `delete ((this.#field))`
=> add test that delete early error is recursive

harness/temporalHelpers.js
Per suggestion by https://github.com/tc39/test262/pull/3049#discussion_r672675461
@ptomato @rwaldron @Ms2ger @jugglinmike
=> Port the Temporal asserts to temporalHelpers.js

test/built-ins/Temporal/Calendar/prototype/fields/long-input.js, test/intl402/DateTimeFormat/constructor-options-timeZoneName-invalid.js, test/intl402/DateTimeFormat/constructor-options-timeZoneName-valid.js
In each case, it's the scalar value associated with the "description" key.
Normally in test262, this is written in either:
- block notation (indicated by '>' or '|'), or
- flow notation, single-line, on the same line as the key.
In the cases addressed by this PR, the value is instead written in:
- (1x) flow notation, *multi*-line, or
- (2x) flow notation, single-line, on the line *after* the key.
These are valid YAML, but they're styles that test262 doesn't otherwise use,
so could conceivably confuse people or harnesses.
This PR changes them to block notation.
=> "Normalize" some YAML

tools/generation/generator.py, tools/generation/lib/expander.py, tools/generation/lib/template.py, tools/generation/lib/test.py
This reduces the time of `./make.py` by  an order of magnitude for me, from 110 seconds to 6.
=> Default to not regenerate test files that are already newer than their case and template

test/built-ins/TypedArray/prototype/findLast/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/findLastIndex/return-abrupt-from-this-out-of-bounds.js
The tests for the "Array findFromLast" proposal were originally authored
based on related tests that had already been merged to the repository's
`main` branch [1]. While those new tests were under review, a number of
tests for the Resizable ArrayBuffer proposal were found to be incorrect
[2]. The problem was fixed for the tests in `main`, but because the
corresponding tests for "Array findFromLast" were not yet merged, the
error persisted there [3].
Apply the same correction to the new tests.
[1] https://github.com/tc39/test262/issues/3111
[2] https://github.com/tc39/test262/pull/3113
[3] https://github.com/tc39/test262/pull/3045
=> Correct tests and improve documentation

test/language/statements/class/subclass/derived-class-return-override-catch-finally-arrow.js, test/language/statements/class/subclass/derived-class-return-override-catch-finally.js, test/language/statements/class/subclass/derived-class-return-override-catch-super-arrow.js, test/language/statements/class/subclass/derived-class-return-override-catch-super.js, test/language/statements/class/subclass/derived-class-return-override-catch.js, test/language/statements/class/subclass/derived-class-return-override-finally-super-arrow.js, test/language/statements/class/subclass/derived-class-return-override-finally-super.js, test/language/statements/class/subclass/derived-class-return-override-for-of-arrow.js, test/language/statements/class/subclass/derived-class-return-override-for-of.js
Upstreams the tests for <https://bugzilla.mozilla.org/show_bug.cgi?id=1722269>, because some of the tests also fail in JSC and V8.
=> Derived class constructor checks are executed after leaving the function body

test/language/module-code/early-dup-lex.js, test/language/module-code/early-dup-top-function-async-generator.js, test/language/module-code/early-dup-top-function-async.js, test/language/module-code/early-dup-top-function-generator.js, test/language/module-code/early-dup-top-function.js
In https://tc39.es/ecma262/#sec-static-semantics-lexicallydeclarednames 
>  ModuleItem : StatementListItem
> > Note 3 At the top level of a Module, function declarations are treated like lexical declarations rather than like var declarations.
Static Early Errors for Modules (https://tc39.es/ecma262/#sec-module-semantics-static-semantics-early-errors):
> It is a Syntax Error if the LexicallyDeclaredNames of ModuleItemList contains any duplicate entries. 
v8:  ✅
SpiderMonkey: ✅
JSC: ❌
Hermes:  ❌
=> Add test for duplicated top level function declarations in modules

test/built-ins/Temporal/Now/plainDateTime/calendar-object.js
Resolves gh-3133. This change makes for a larger test than I'm accustomed to writing, but the amount of "set up" logic may warrant that. I'm happy to refactor into two files if anyone would prefer!
=> Fix error in test for Temporal.now.plainDateTime

test/intl402/DisplayNames/prototype/of/type-calendar-invalid.js, test/intl402/DisplayNames/prototype/of/type-calendar-valid.js
The underscore character "_" is only accepted for the sep production [1]
when the backwards-compatibility extensions [2] are enabled. However,
ECMA-402 only accepts Unicode BCP 47 locale identifiers [3], meaning
identifiers *without* the backwards-compatibility extensions.
[1] https://unicode.org/reports/tr35/#Unicode_language_identifier
[2] https://unicode.org/reports/tr35/#BCP_47_Conformance
[3] https://tc39.es/ecma402/#sec-language-tags
---
Resolves gh-3139. /cc @anba
=> Correct tests for Unicode Language Identifier

test/built-ins/decodeURI/S15.1.3.1_A2.1_T1.js, test/built-ins/decodeURIComponent/S15.1.3.2_A2.1_T1.js, test/language/comments/S7.4_A6.js
Prior to this patch, two distinct failure cases would produce the same
generic error message. Refactor the test logic to report the specific
condition which trigger failure.
---
Building on @lightmare's work in gh-3170.
=> Throw distinctive errors for different failures

test/built-ins/Error/prototype/S15.11.4_A3.js, test/built-ins/Error/prototype/S15.11.4_A4.js
This should be 'assert.throws()', otherwise these fail unexpectedly.
Fixes #3184.
=> Fix 'asserts.throws()' typo in two tests

CONTRIBUTING.md, tools/lint/lib/checks/frontmatter.py, tools/lint/lib/frontmatter.py, tools/lint/test/fixtures/test/frontmatter_multiline_scalar_flow.js
Some consumers have reported difficulty parsing an uncommon YAML
construction [1] [2] [3]. Extend the linter to help ensure that
construction is not used in future contributions.
[1] https://github.com/tc39/test262/issues/1997
[2] https://github.com/tc39/test262/pull/2505
[3] https://github.com/tc39/test262/issues/3171
---
This change increases the time to lint all of Test262 by 6% on my machine. That might seem a little drastic for such a subtle detail, but given how this has come up multiple times over the years, I think it's warranted.
<details>
<summary>Running time experiments</summary>
$ time ./tools/lint/lint.py --exceptions lint.exceptions test/
Linting 42096 files
Linting complete. 0 errors found.
real    0m49.812s
user    0m49.312s
sys     0m0.496s
$ git checkout …
=> tools: enforce restriction on YAML

test/language/statements/block/labeled-continue.js
Normative: continue labels should not pass through blocks
https://github.com/tc39/ecma262/pull/2482
=> Add test for normative change to BlockStatement

test/built-ins/Proxy/revocable/tco-fn-realm.js
Normative: phrase tail calls as discarding resources rather than popping
execution context stack
https://github.com/tc39/ecma262/pull/2495
=> Add test for normative change to TCO&revoked Proxy

test/annexB/built-ins/RegExp/prototype/compile/this-cross-realm-instance.js
This PR fixes the second test-case in `annexB/built-ins/RegExp/prototype/compile/this-cross-realm-instance.js` test. It is a symmetric test-case to the first test-case, i.e., the `TypeError` should come from the realm of the invoked built-in (not from the realm of the argument).
=> RegExp.prototype.compile from other realm should throw TypeError from other realm

CONTRIBUTING.md
The convention in some testing libraries is an explanation of what went wrong;
in this one it is an explanation of what should happen.
=> Explain the purpose of `assert` helper message parameters

test/built-ins/Date/prototype/valueOf/S9.4_A3_T1.js, test/built-ins/Date/prototype/valueOf/S9.4_A3_T2.js
Fixes test regressions introduced by https://github.com/tc39/test262/pull/3144 (1c24e4b915a090ae1878da606a9cd1e62ca815ca) which changed:
```diff
var d5 = new Date(-0);
-if (d5.valueOf() !== -0) {
-  throw new Test262Error('#5: var d5 = new Date(-0); d5.valueOf() === -0;');
-}
+assert.sameValue(d5.valueOf(), -0, 'd5.valueOf() must return -0');
```
and
```diff
var d12 = new Date(-1.23e-15);
-if (d12.valueOf() !== -0) {
-  throw new Test262Error('#12: var d12 = new Date(-1.23e-15); d12.valueOf() === -0;');
-}
+assert.sameValue(d12.valueOf(), -0, 'd12.valueOf() must return -0');
```
This is wrong. The correct result is positive 0. (See [TimeClip](https://tc39.es/ecma262/#sec-timeclip) and [ToIntegerOrInfinity](https://tc39.es/ecma262/#sec-tointegerorinfinity) which returns either an integer …
=> Fix incorrect tests: new Date(-0).valueOf() and new Date(-1.23e-15).valueOf() should return +0.

test/language/expressions/division/S11.5.2_A4_T8.js
Prior to this commit, the modified test included two different
expressions in positions that were meant to describe the same
expression. This meant that the value of the intended expression was
only partially verified.
Correct the test to fully verify the value of the expression.
=> Correct typo to improve coverage

test/language/expressions/exponentiation/applying-the-exp-operator_A15.js, test/language/expressions/exponentiation/applying-the-exp-operator_A19.js, test/language/statements/throw/S12.13_A2_T5.js, test/language/statements/try/S12.14_A18_T5.js
Prior to this commit, the modified tests used the strict equality
operator to compare computed values with negative zero. Due to the
semantics of that operator, these tests would spuriously pass if the
value under test was in fact positive zero.
Update the tests to be more precise by instead asserting equality with
the `assert.sameValue` utility method (since that method correctly
distinguishes between negative zero and positive zero).
Thanks to @woess for helping uncover this by [identifying a related problem](https://github.com/tc39/test262/pull/3201).
=> Improve coverage for ops involving negative zero

test/built-ins/TypedArray/prototype/byteOffset/BigInt/resizable-array-buffer-auto.js, test/built-ins/TypedArray/prototype/byteOffset/resizable-array-buffer-auto.js
Ensure that when the ArrayBuffer of a length-tracking TypedArray is
resized to the address matching the TypedArray's byte offset, the
TypedArray is *not* considered "out of bounds."
Resolves gh-3206 (my thanks to @marjakh for reporting)
=> Correct mistakes in support of proposal change

test/built-ins/TypedArray/prototype/byteLength/BigInt/resizable-array-buffer-auto.js, test/built-ins/TypedArray/prototype/length/BigInt/resizable-array-buffer-auto.js
Following a recent normative change to the Resizable ArrayBuffer
proposal [1], the term "out of bounds" no longer applies to
"length-tracking" TypedArrays whose underlying ArrayBuffer has been
resized to match their byte offset.
Reflect this in the tests by renaming the condition from "out of bounds"
to "on boundary" and by adding new assertions for true "out of bounds"
conditions.
[1] https://github.com/tc39/proposal-resizablearraybuffer/pull/70
=> Correct assertion messages and improve coverage

test/built-ins/Array/prototype/copyWithin/coerced-values-target.js, test/built-ins/TypedArray/prototype/copyWithin/coerced-values-target.js, test/built-ins/TypedArray/prototype/copyWithin/return-abrupt-from-this-out-of-bounds.js
Prior to this commit, a test for %TypedArray%.prototype.copyWithin
provided a TypedArray instance as the first argument. That argument that
is interpreted as a number, so in relying on the conversion, the test
verified behavior beyond what it purported to test.
Simplify the test by using the desired number value directly, and extend
the tests for type coercion to cover object values.
Resolves gh-3207.
=> Focus tests for `copyWithin` methods

test/language/module-code/namespace/internals/define-own-property.js
Attempting to freeze the module namespace exotic object should not affect the `writable`-ity of the properties as that exercises the same `DefineOwnProperty` operation according to [`SetIntegrityLevel`](https://tc39.es/ecma262/#sec-setintegritylevel).
@erights discovered a [bug in v8](https://bugs.chromium.org/p/v8/issues/detail?id=12240) where, while the `Object.freeze` operation throws, it actually makes exported properties non-writable one by one.
At the request of @syg, I'm contributing a test against this behavior. The bug in v8 actually leads to a breakage of the objects invariants, however I'm not testing for that here as the root cause is the illegal freezing of the export.
=> Add test for freezing of module namespace object

test/built-ins/TypedArray/prototype/includes/BigInt/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/indexOf/BigInt/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/join/BigInt/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/lastIndexOf/BigInt/return-abrupt-from-this-out-of-bounds.js, test/built-ins/TypedArray/prototype/map/BigInt/return-abrupt-from-this-out-of-bounds.js
Prior to this commit, a number of tests used non-BigInt values where
BigInt value are commonly used. Although this was technically
permissible to validate the behavior under test, the atypical usage
patterns tended to obscure the tests' purpose. Replace with more
appropriate values.
@rwaldron Unlike gh-3216, this patch is a subjective improvement to test clarity. You can take it or leave it.
=> Use BigInt values idiomatically

test/built-ins/TypedArray/prototype/copyWithin/BigInt/return-abrupt-from-this-out-of-bounds.js
Prior to this commit, a test for %TypedArray%.prototype.copyWithin
provided a TypedArray instance as the first argument. That argument that
is interpreted as a number, so in relying on the conversion, the test
verified behavior beyond what it purported to test.
Simplify the test by using the desired number value directly.
@rwaldron This should have been included in gh-3215. Sorry for drawing this out!
=> Focus test for BigInt v. of `copyWithin` method

test/built-ins/ShadowRealm/prototype/evaluate/returns-proxy-callable-object.js
- I don't think `... instanceof Proxy` ([which is performed here](https://github.com/tc39/test262/pull/3210/files#diff-0dfc4b1a2e48f81f61b8ecf92f9aa16d306256682d107203c4372d4037b11beaR25)) is a valid check in JS; it throws an error on non-realm expressions as well
- Add some additional coverage over proxy-ing wrapped functions to show that the underlying boundary checks are still made. Perhaps this is obvious and not worth having in the suite, so happy to remove it
=> Adapt ShadowRealm proxy coverage

test/built-ins/ShadowRealm/prototype/evaluate/returns-proxy-callable-object.js, test/built-ins/ShadowRealm/prototype/evaluate/wrapped-function-proxied-observes-boundary.js
cc @philomates @rwaldron I did split this test file to separate the different goals of each test.
I did some other minor tweaks such as removing a false positive where the handler was calling `target(args)` and args is an array despite the `secretObj` sent and I avoided too much code inside the assert.throws function.
=> Split tests and fix false positive (ShadowRealms)

harness/compareArray.js, test/harness/compare-array-arguments.js, test/harness/compare-array-arraylike.js, test/harness/compare-array-different-elements.js, test/harness/compare-array-different-length.js, test/harness/compare-array-empty.js, test/harness/compare-array-same-elements-different-order.js, test/harness/compare-array-same-elements-same-order.js, test/harness/compare-array-samevalue.js, test/harness/compare-array-sparse.js, test/harness/compare-array-symbol.js
This is the just the updates assert.compareArray and assert.compareArray.format, extracted to a standalone commit
=> fix: corrections to assert.compareArray and assert.compareArray.format

test/built-ins/Promise/race/resolved-sequence-with-rejections.js, test/built-ins/Promise/race/resolved-sequence.js
The `compareArray` utility function returns a boolean value describing
whether or not the input arrays are equivalent--it does not throw an
exception when invoked with non-equivalent arrays. Prior to this commit,
however, two tests invoked `compareArray` without inspecting its return
value, so it had no impact on the result of the test.
Update the tests to fail when the "expected" and "actual" arrays are not
equivalent.
=> Assert array equivalency

src/computed-property-names/computed-property-name-from-yield-expression.case, test/built-ins/Array/prototype/reduce/15.4.4.21-9-8.js, test/built-ins/Array/prototype/reduceRight/15.4.4.22-9-8.js, test/language/expressions/await/await-throws-rejections.js, test/language/expressions/class/cpn-class-expr-accessors-computed-property-name-from-yield-expression.js, test/language/expressions/class/cpn-class-expr-computed-property-name-from-yield-expression.js, test/language/expressions/class/cpn-class-expr-fields-computed-property-name-from-yield-expression.js, test/language/expressions/class/cpn-class-expr-fields-methods-computed-property-name-from-yield-expression.js, test/language/expressions/object/cpn-obj-lit-computed-property-name-from-yield-expression.js, test/language/statements/class/cpn-class-decl-accessors-computed-property-name-from-yield-expression.js, test/language/statements/class/cpn-class-decl-computed-property-name-from-yield-expression.js, test/language/statements/class/cpn-class-decl-fields-computed-property-name-from-yield-expression.js, test/language/statements/class/cpn-class-decl-fields-methods-computed-property-name-from-yield-expression.js
Some tests which include function declarations designed to verify
behavior do not reference those functions. Insert the references
necessary for those functions to serve their intended purpose.
Resolves gh-3229 along with a handful of other previously-unreported instances of this bug.
=> Improve coverage by invoking functions as intended

test/built-ins/Temporal/Instant/prototype/toString/timezone-string-datetime.js
Prior to this patch, the modified test invoked the `arrayContains`
utility function without referencing its return value. Unlike Test262's
assertion functions, `arrayContains` does not throw an error when the
expectation is violated, so the prior usage did not influence test
results.
Additionally, the prior version of this test documented incorrect
expectations regarding the expected value produced by the method under
test. Due to the above, these expectations were not enforced.
Correct the test's expectations and enforce those expectations with a
function that will reliably produce an exception if violated.
/cc @ptomato
=> Correct test for Temporal.Instant#toString

test/intl402/Collator/prototype/resolvedOptions/order.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/order-dayPeriod.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/order-fractionalSecondDigits.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/order-style.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/order.js, test/intl402/ListFormat/prototype/resolvedOptions/order.js, test/intl402/NumberFormat/prototype/resolvedOptions/order.js, test/intl402/PluralRules/prototype/resolvedOptions/order.js, test/intl402/RelativeTimeFormat/prototype/resolvedOptions/order.js, test/intl402/Segmenter/prototype/resolvedOptions/order.js
A number of tests for ECMA402 asserted the exact contents of the array
returned by various `resolvedOptions` methods. This conflicted with the
expectation that more options will be introduced by future editions of
the specification.
Update these tests to assert property order more generically in order to
accommodate implementation of future language proposals and more closely
align with similar tests.
Update all `resolvedOptions` tests to produce more meaningful error
messages (including replacing the generic `arrayContains` assertion with
a specific assertion regarding the value of the first array element).
---
This supports gh-3132
=> Relax tests for resolvedOptions property ordering

features.txt, test/intl402/NumberFormat/constructor-options-roundingMode-invalid.js, test/intl402/NumberFormat/constructor-options-throwing-getters-rounding-mode.js, test/intl402/NumberFormat/prototype/format/format-rounding-mode-ceil.js, test/intl402/NumberFormat/prototype/format/format-rounding-mode-expand.js, test/intl402/NumberFormat/prototype/format/format-rounding-mode-floor.js, test/intl402/NumberFormat/prototype/format/format-rounding-mode-half-ceil.js, test/intl402/NumberFormat/prototype/format/format-rounding-mode-half-even.js, test/intl402/NumberFormat/prototype/format/format-rounding-mode-half-expand.js, test/intl402/NumberFormat/prototype/format/format-rounding-mode-half-floor.js, test/intl402/NumberFormat/prototype/format/format-rounding-mode-half-trunc.js, test/intl402/NumberFormat/prototype/format/format-rounding-mode-trunc.js, test/intl402/NumberFormat/prototype/resolvedOptions/roundingMode.js
This patch is intended to cover only one aspect of the proposal for
ECMA402: the "rounding mode" feature.
This is in service of gh-3132.
=> Add tests for "Intl NumberFormat v3" proposal

test/built-ins/Temporal/PlainDate/prototype/since/largestunit-higher-units.js
Fixes #3272 by reverting a change to tests of`Temporal.PlainDateTime.prototype.since()`.
See tc39/proposal-temporal#1878 for details.
=> Revert #3250

features.txt, harness/async-gc.js, test/built-ins/FinalizationRegistry/gc-has-one-chance-to-call-cleanupCallback.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/callback-not-callable-throws.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/cleanup-prevented-with-reference.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/cleanup-prevented-with-unregister.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/custom-this.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/holdings-multiple-values.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/length.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/name.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/prop-desc.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/reentrancy.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/return-undefined-with-gc.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/return-undefined.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/this-does-not-have-internal-cells-throws.js, test/built-ins/FinalizationRegistry/prototype/cleanupSome/this-not-object-throws.js, test/built-ins/FinalizationRegistry/prototype/unregister/unregister-cleaned-up-cell.js, test/built-ins/WeakRef/prototype/deref/gc-cleanup-not-prevented-with-wr-deref.js
@devsnek looks like engine262 is using this form of the feature flag—let me know when you've switched to `FinalizationRegistry.prototype.cleanupSome`. Thanks!
=> Features: remove duplicate "cleanupSome" feature

test/built-ins/Array/prototype/every/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/filter/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/find/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/findIndex/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/findLast/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/findLastIndex/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/forEach/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/map/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/reduce/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/reduceRight/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/some/callbackfn-resize-arraybuffer.js, test/built-ins/TypedArray/prototype/every/callbackfn-resize.js, test/built-ins/TypedArray/prototype/filter/callbackfn-resize.js, test/built-ins/TypedArray/prototype/find/callbackfn-resize.js, test/built-ins/TypedArray/prototype/findIndex/callbackfn-resize.js, test/built-ins/TypedArray/prototype/findLast/callbackfn-resize.js, test/built-ins/TypedArray/prototype/findLastIndex/callbackfn-resize.js, test/built-ins/TypedArray/prototype/forEach/callbackfn-resize.js, test/built-ins/TypedArray/prototype/map/callbackfn-resize.js, test/built-ins/TypedArray/prototype/reduce/callbackfn-resize.js, test/built-ins/TypedArray/prototype/reduceRight/callbackfn-resize.js, test/built-ins/TypedArray/prototype/some/callbackfn-resize.js
The Resizable ArrayBuffer proposal allows implementations to reject any
resize operation, so the tests must accommodate that possibility.
Mitigate the complexity this entails by minimizing branches and by
deferring assertions to locations with shallow call stacks.
---
Resolves gh-3245
I tested this using V8's in-progress implementation (version 9.8.1). More on V8's behavior below.
As noted in the commit message, these tests are much more complex than what we typically accept in Test262 because they have to accommodate the proposal's optional behavior. Each test includes two invocations of `ArrayBuffer.prototype.resize`, and because each invocation may succeed or throw an error, they support a total of four paths of execution. I've simulated those by running these tests an additional three …
=> Add tests: resizing ArrayBuffer during iteration

test/built-ins/ShadowRealm/prototype/evaluate/wrapped-function-throws-typeerror-on-non-primitive-arguments.js
When the `wrappedFunction` is not a function, the TypeError thrown on calling on `wrappedFunction` can unexpectedly pass the test.
=> Fix unexpected pass on ShadowRealm wrapped function

CONTRIBUTING.md
Clarify that helper functions aren't available if `raw` flag is specified.
=> Mention raw flag in test environment section (fixes #3310)

test/intl402/NumberFormat/prototype/resolvedOptions/roundingMode.js
The test was using "halfExpand (default)".
=> Intl.NumberFormat v3's default roundingMode should be "halfExpand"

test/intl402/NumberFormat/prototype/format/signDisplay-negative-currency-de-DE.js, test/intl402/NumberFormat/prototype/format/signDisplay-negative-currency-en-US.js, test/intl402/NumberFormat/prototype/format/signDisplay-negative-currency-ja-JP.js, test/intl402/NumberFormat/prototype/format/signDisplay-negative-currency-ko-KR.js, test/intl402/NumberFormat/prototype/format/signDisplay-negative-currency-zh-TW.js, test/intl402/NumberFormat/prototype/format/signDisplay-negative-de-DE.js, test/intl402/NumberFormat/prototype/format/signDisplay-negative-en-US.js, test/intl402/NumberFormat/prototype/format/signDisplay-negative-ja-JP.js, test/intl402/NumberFormat/prototype/format/signDisplay-negative-ko-KR.js, test/intl402/NumberFormat/prototype/format/signDisplay-negative-zh-TW.js, test/intl402/NumberFormat/prototype/formatToParts/signDisplay-negative-currency-de-DE.js, test/intl402/NumberFormat/prototype/formatToParts/signDisplay-negative-currency-en-US.js, test/intl402/NumberFormat/prototype/formatToParts/signDisplay-negative-currency-ja-JP.js, test/intl402/NumberFormat/prototype/formatToParts/signDisplay-negative-currency-ko-KR.js, test/intl402/NumberFormat/prototype/formatToParts/signDisplay-negative-currency-zh-TW.js, test/intl402/NumberFormat/prototype/formatToParts/signDisplay-negative-de-DE.js, test/intl402/NumberFormat/prototype/formatToParts/signDisplay-negative-en-US.js, test/intl402/NumberFormat/prototype/formatToParts/signDisplay-negative-ja-JP.js, test/intl402/NumberFormat/prototype/formatToParts/signDisplay-negative-ko-KR.js, test/intl402/NumberFormat/prototype/formatToParts/signDisplay-negative-zh-TW.js
The negative sign is computed after rounding, so when the input `-0.0001` is
rounded to `-0`, the expected result should be `"0"` instead of `"-0"`.
=> Correct negative-zero sign display tests

test/built-ins/Temporal/Now/plainDateTimeISO/timezone-string-datetime.js, test/built-ins/Temporal/Now/zonedDateTime/timezone-string-datetime.js, test/built-ins/Temporal/Now/zonedDateTimeISO/timezone-string-datetime.js, test/intl402/Temporal/Now/plainDateTimeISO/timezone-string-datetime.js, test/intl402/Temporal/Now/zonedDateTime/timezone-string-datetime.js, test/intl402/Temporal/Now/zonedDateTimeISO/timezone-string-datetime.js
IANA TimeZone name other than "UTC" is only required if the implementation " includes the ECMA-402 Internationalization API"
https://tc39.es/proposal-temporal/#sec-isvalidtimezonename
Therefore, we need to split the test and keep this one  without checking "America/Vancouver" and move those test on IATA timezone name other than UTC to under intl402
Add test cases to test withtout the ":" between TimeZoneUTCOffsetHour and TimeZoneUTCOffsetMinute
in the TimeZoneNumericUTCOffset string see https://tc39.es/proposal-temporal/#prod-TimeZoneNumericUTCOffset
=> Move IANA TimeZone tests to intl402

CONTRIBUTING.md, INTERPRETING.md, README.md
Prior to this commit, the term "harness" was used to refer both to the
like-named directory in the repository and the external projects which
consume the tests. Reserve the term "harness" to refer solely to the
files maintained within this project's `harness/` directory, and use
the term "runner" to refer to the external projects.
Prior to this commit, the term "helper" was not defined and therefore
introduced ambiguity in text that described harness files. Replace the
term with more explicit wording in terms of the harness files.
Because test runners have some leeway in how they include harness files,
the requirement that "[t]he test source code must not be modified in any
way" does not necessarily preclude the use of harness files. Update the
instructions for interpreting the `raw` …
=> Improve documentation of harness files & raw flag

test/intl402/DurationFormat/prototype/toStringTag.js
The last five lines below are simply WRONG and not according to the spec. 
```
const durationFormat = new Intl.DurationFormat();
verifyNotEnumerable(durationFormat, Symbol.toStringTag);
verifyNotWritable(durationFormat, Symbol.toStringTag);
verifyConfigurable(durationFormat, Symbol.toStringTag);
```
=> Simplify and correct testing of Intl.DurationFormat toStringTag

test/built-ins/Temporal/Calendar/prototype/prop-desc.js, test/built-ins/Temporal/Duration/prototype/prop-desc.js, test/built-ins/Temporal/Instant/prototype/prop-desc.js, test/built-ins/Temporal/PlainDate/prototype/prop-desc.js, test/built-ins/Temporal/PlainDateTime/prototype/prop-desc.js, test/built-ins/Temporal/PlainMonthDay/prototype/prop-desc.js, test/built-ins/Temporal/PlainTime/prototype/prop-desc.js, test/built-ins/Temporal/PlainYearMonth/prototype/prop-desc.js, test/built-ins/Temporal/TimeZone/prototype/prop-desc.js, test/built-ins/Temporal/ZonedDateTime/prototype/prop-desc.js
This PR verifies that the `prototype` property of Temporal class constructors is not writeable, not configurable, and not enumerable.
Context: https://github.com/tc39/proposal-temporal/issues/1965.
Note that `verifyProperty()` removes the property being tested, so the `prototype` prop needs to be tested before testing the constructor itself.
=> Verify that `Temporal.*.prototype` isn't writeable

test/built-ins/ShadowRealm/prototype/evaluate/wrapped-function-throws-typeerror-on-exceptional-exit.js
There was already existing coverage for when `evaluate`'d code directly throws, but not for wrapped functions; TypeError from the destination realm should be thrown whenever the a wrapped function throws, so cover that.
I signed the CLA--let me know if anything is missing : )
=> Add test for shadow realms wrapped function behavior on throw

test/built-ins/Array/prototype/every/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/filter/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/forEach/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/map/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/reduce/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/reduceRight/callbackfn-resize-arraybuffer.js, test/built-ins/Array/prototype/some/callbackfn-resize-arraybuffer.js
Prior to this patch, the tests for certain Array prototype methods
incorrectly expected all elements to be "visited" even when a given
property was not present according to HasProperty.
Update the tests to reflect the fact that under such conditions, the
removed element is not visited.
@marjakh  @phoddie Since I authored the mistaken tests, it's particularly important that someone closer to an implementation reviews this patch. Would you mind taking a look?
=> Fix: correct Resizable ArrayBuffer/Array tests

test/intl402/PluralRules/prototype/selectRange/default-en-us.js
en-US's Intl.PluralRules.selectRange(102, 201) is "other", not "few".
=> Fix Intl.PluralRules.selectRange test

CONTRIBUTING.md, test/built-ins/Array/from/Array.from-descriptor.js, test/built-ins/Array/isArray/descriptor.js, test/built-ins/Function/prototype/restricted-property-arguments.js, test/built-ins/Function/prototype/restricted-property-caller.js, test/built-ins/Object/assign/assign-descriptor.js, test/built-ins/Object/defineProperties/15.2.3.7-6-a-36.js, test/built-ins/Object/hasOwn/descriptor.js, test/built-ins/Promise/Symbol.species/symbol-species.js, test/built-ins/Symbol/species/basic.js, tools/lint/lib/checks/includes.py, tools/lint/test/fixtures/test/includes_invalid_non_flow_list.js
Includes key should use flow notation to be able parsed easier
as suggested in https://github.com/tc39/test262/issues/1997
Added this check to the linting script and updated tests accordingly.
=> tools: enforce restriction on YAML includes key

test/intl402/NumberFormat/constructor-roundingIncrement.js
I do not believe this setup is correct if we use notation: "compact". 
in https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/diff.html#sec-setnfdigitoptions
notation is "compact"
mnsd is undefined
mxsd is undefined
mnfd is undefined
mxfd is undefined
hasSd is false
hasFd is false
needSd is false
needFd is false
so step 23 else block will be run
Set intlObj.[[RoundingType]] to morePrecision.
then in step 23 of https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/diff.html#sec-initializenumberformat
```
If roundingIncrement is not 1 and numberFormat.[[RoundingType]] is not fractionDigits, throw a RangeError exception.
```
@sffc @jugglinmike
=> change notation to "standard"

test/intl402/NumberFormat/constructor-roundingIncrement-invalid.js
roundingIncrement: 1.1 will not throw RangeError because
1.  roundingIncrement is read by calling GetNumberOption in step 21 of https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/diff.html#sec-initializenumberformat
2. GetNumberOption https://tc39.es/ecma402/#sec-getnumberoption will call DefaultNumberOption https://tc39.es/ecma402/#sec-defaultnumberoption and 
3. DefaultNumberOption will call floor() in step 3. so roundingIncrement will be 1 if the option bag has {roundingIncrement: 1.1}
=> Remove roundingIncrement: 1.1 case which should NOT throw RangeError

test/intl402/NumberFormat/prototype/format/format-rounding-increment-25.js, test/intl402/NumberFormat/prototype/format/format-rounding-increment-250.js, test/intl402/NumberFormat/prototype/format/format-rounding-increment-2500.js, test/intl402/NumberFormat/prototype/format/format-rounding-increment-5.js, test/intl402/NumberFormat/prototype/format/format-rounding-increment-50.js, test/intl402/NumberFormat/prototype/format/format-rounding-increment-500.js, test/intl402/NumberFormat/prototype/format/format-rounding-increment-5000.js, test/intl402/NumberFormat/prototype/format/format-rounding-priority-less-precision.js, test/intl402/NumberFormat/prototype/format/format-rounding-priority-more-precision.js
We need to set minimumFractionDigits: 1 for the case of {roundingIncrement: 5, maximumFractionDigits: 1} and also adjust the test expectation. 
Otherwise, inside testNumberFormat , it will call   getPatternParts to format 1.1 and -1.1 and cause pattern mismatch (because the result will be "1" instead of "1.1" in that configuration)
https://github.com/tc39/test262/blob/main/harness/testIntl.js#L2369
=> set minimumFractionDigits: 1 in format-rounding-increment- test

test/intl402/NumberFormat/prototype/formatRangeToParts/en-US.js
1.  add includes: [propertyHelper.js]
2. "–" => " – "
3.  Move verifyProperty to the end of the loop because it has the side effect of removing the property while testing on writable: true
=> Fix test of intl402/NumberFormat/prototype/formatRangeToParts/en-US.js 

test/intl402/NumberFormat/prototype/formatRange/pt-PT.js
the " " before the currency symbol and between group are actually nbsp not SPACE.
@jugglinmike
=> Replace SPACE with NBSP in expectation

test/built-ins/Object/seal/seal-aggregateerror.js
Test case `seal-aggregateerror.js` cannot work without `AggregateError` being implemented.
=> Add AggregateError as feature to seal-aggregateerror.js

test/intl402/NumberFormat/prototype/resolvedOptions/basic.js, test/intl402/NumberFormat/test-option-useGrouping.js
After Intl.NumberFormat v3, default useGrouping is "auto".
=> Intl.NumberFormat default useGrouping value is "auto"

test/intl402/DurationFormat/instance/length.js, test/intl402/DurationFormat/instance/name.js, test/intl402/DurationFormat/instance/prop-desc.js, test/intl402/DurationFormat/prototype/format/length.js, test/intl402/DurationFormat/prototype/formatToParts/length.js, test/intl402/DurationFormat/prototype/resolvedOptions/length.js
Summary:
- Amend missing feature fields in test description 
- Update code style to use `verifyProperty` instead of method for each `Writable` , `Configurable` , `Enumerable`
- Also solves comments https://github.com/tc39/test262/pull/3378#discussion_r791500096 and https://github.com/tc39/test262/pull/3378#discussion_r791499618
=> Update DurationFormat tests

test/built-ins/ShadowRealm/WrappedFunction/length.js, test/built-ins/ShadowRealm/WrappedFunction/name.js
`verifyProperty` needs to be included.
cc @legendecas @leobalter
=> Add missing propertyHelper.js include to WrappedFunction tests

test/built-ins/Array/prototype/pop/set-length-array-is-frozen.js, test/built-ins/Array/prototype/pop/set-length-array-length-is-non-writable.js, test/built-ins/Array/prototype/pop/set-length-zero-array-is-frozen.js, test/built-ins/Array/prototype/pop/set-length-zero-array-length-is-non-writable.js, test/built-ins/Array/prototype/push/set-length-array-is-frozen.js, test/built-ins/Array/prototype/push/set-length-array-length-is-non-writable.js, test/built-ins/Array/prototype/push/set-length-zero-array-is-frozen.js, test/built-ins/Array/prototype/push/set-length-zero-array-length-is-non-writable.js, test/built-ins/Array/prototype/shift/set-length-array-is-frozen.js, test/built-ins/Array/prototype/shift/set-length-array-length-is-non-writable.js, test/built-ins/Array/prototype/shift/set-length-zero-array-is-frozen.js, test/built-ins/Array/prototype/shift/set-length-zero-array-length-is-non-writable.js, test/built-ins/Array/prototype/unshift/set-length-array-is-frozen.js, test/built-ins/Array/prototype/unshift/set-length-array-length-is-non-writable.js, test/built-ins/Array/prototype/unshift/set-length-zero-array-is-frozen.js, test/built-ins/Array/prototype/unshift/set-length-zero-array-length-is-non-writable.js
JSC bug: [Attempting to `[[Set]]` `JSArray`'s read-only `"length"` should throw even with current `[[Value]]`](https://bugs.webkit.org/show_bug.cgi?id=221177).
=> Test that `Array.prototype` methods throw on attempt to `[[Set]]` read-only `"length"`

.jshintrc
Some IDEs (e.g., WebStorm) consult the `.jshintrc` file to figure out what "language level" they should use. It seems that we're using ECMAScript 6 pretty consistently, if not uniformly. This change makes that information explicit.
=> Use ECMAScript 6

test/built-ins/Temporal/PlainDate/prototype/toPlainDateTime/argument-string-time-designator-required-for-disambiguation.js, test/built-ins/Temporal/PlainDate/prototype/toZonedDateTime/argument-string-time-designator-required-for-disambiguation.js, test/built-ins/Temporal/PlainDateTime/prototype/withPlainTime/argument-string-time-designator-required-for-disambiguation.js, test/built-ins/Temporal/PlainTime/compare/argument-string-time-designator-required-for-disambiguation.js, test/built-ins/Temporal/PlainTime/from/argument-string-time-designator-required-for-disambiguation.js, test/built-ins/Temporal/PlainTime/prototype/equals/argument-string-time-designator-required-for-disambiguation.js, test/built-ins/Temporal/PlainTime/prototype/since/argument-string-time-designator-required-for-disambiguation.js, test/built-ins/Temporal/PlainTime/prototype/until/argument-string-time-designator-required-for-disambiguation.js, test/built-ins/Temporal/ZonedDateTime/prototype/withPlainTime/argument-string-time-designator-required-for-disambiguation.js
Here's a test I should have included in #3395. It's allowed to replace the
"T" in the middle of an ISO string with a space, but not when the "T" is a
time designator prefix. This assertion ensures that implementations make
this distinction correctly.
=> Add tests for T time designator prefix not allowing space

test/built-ins/Temporal/Instant/prototype/add/basic.js, test/built-ins/Temporal/Instant/prototype/add/branding.js, test/built-ins/Temporal/Instant/prototype/add/disallowed-duration-units.js, test/built-ins/Temporal/Instant/prototype/add/result-out-of-range.js, test/built-ins/Temporal/Instant/prototype/subtract/basic.js, test/built-ins/Temporal/Instant/prototype/subtract/branding.js, test/built-ins/Temporal/Instant/prototype/subtract/disallowed-duration-units.js, test/built-ins/Temporal/Instant/prototype/subtract/result-out-of-range.js
This was originally @FrankYFTang's PR #3076 which was closed without being merged. I'm following up as promised. I rebased it, added assertion messages, did some reformatting, and combined with some existing tests.
=> Add tests for Temporal.Instant.p*.subtract

test/intl402/NumberFormat/prototype/format/format-max-min-fraction-significant-digits.js
Summary : 
WIP updating https://github.com/tc39/test262/issues/3364 
Will be draft PR depending on: https://github.com/tc39/proposal-intl-numberformat-v3/issues/81 that could also affect the tests
=> use all values max and min fraction and significant digits

.jshintrc
We use BigInt syntax in a bunch of tests. This change
registers that fact with linters that use `.jshintrc`.
=> Use ECMAScript version 11

test/built-ins/ShadowRealm/WrappedFunction/throws-typeerror-on-revoked-proxy.js, test/built-ins/ShadowRealm/prototype/evaluate/throws-typeerror-wrap-throwing.js
This closes #3451.
It coverts the tab character to spaces to avoid YAML parsing errors.
=> Fixed YAML in some new test metadata

test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/basic.js, test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/branding.js, test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/fields-missing-properties.js, test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/fields-not-object.js, test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/monthcode-invalid.js, test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/options-not-object.js, test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/overflow-constrain.js, test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/overflow-reject.js, test/built-ins/Temporal/Duration/prototype/abs/basic.js, test/built-ins/Temporal/Duration/prototype/negated/basic.js, test/built-ins/Temporal/Duration/prototype/toJSON/basic.js, test/built-ins/Temporal/Duration/prototype/with/all-negative.js, test/built-ins/Temporal/Duration/prototype/with/all-positive.js, test/built-ins/Temporal/Duration/prototype/with/argument-object-wrong-shape.js, test/built-ins/Temporal/Duration/prototype/with/argument-wrong-type.js, test/built-ins/Temporal/Duration/prototype/with/branding.js, test/built-ins/Temporal/Duration/prototype/with/partial-positive.js, test/built-ins/Temporal/Duration/prototype/with/sign-conflict-throws-rangeerror.js
This was originally PRs #3061, #3062, #3063, #3064, #3065 by @FrankYFTang which were closed without being merged. I'm following up as promised. I rebased the PRs, added assertion messages, did some reformatting, and combined with some existing tests.
=> Follow-up on closed Temporal tests PRs

test/built-ins/String/prototype/localeCompare/15.5.4.9_CE.js
Checking for canonical equivalence is now **required**, cf. https://tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.localecompare
I'd also like to add some tests verifying that _non_-zero output is not affected by changing between canonically equivalent sequences in a substring, but I'm not sure where to add them. And at any rate, they can be introduced in a followup.
=> Require String.prototype.localeCompare to check for canonical equivalence

test/intl402/Temporal/TimeZone/etc-timezone.js
It looks like the reference polyfill already does what we expect: these tests all pass. If we work on cleaning up the grammar for the various Etc/GMT timezones [as suggested](https://github.com/tc39/proposal-temporal/issues/1993), these tests might be handy.
=> Check a variety of offset Etc/GMT timezones

test/intl402/NumberFormat/constructor-roundingIncrement-invalid.js
Update test for NumberFormat v3 according to : 
https://github.com/tc39/proposal-intl-numberformat-v3/issues/81  and https://github.com/tc39/proposal-intl-numberformat-v3/issues/68 reflecting the  [spec update on L23 and L24](https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/proposed.html#sec-initializenumberformat)
=> update nfv3 test for roundingIncrement

test/built-ins/Temporal/Calendar/prototype/inLeapYear/argument-string.js, test/built-ins/Temporal/Calendar/prototype/inLeapYear/basic.js, test/built-ins/Temporal/Calendar/prototype/inLeapYear/branding.js, test/built-ins/Temporal/Calendar/prototype/mergeFields/basic.js, test/built-ins/Temporal/Calendar/prototype/mergeFields/iso8601-calendar-month-monthCode.js, test/built-ins/Temporal/Calendar/prototype/mergeFields/non-string-properties.js, test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/basic.js, test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/fields-missing-properties.js, test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/fields-not-object.js, test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/monthcode-invalid.js, test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/overflow-constrain.js, test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/overflow-reject.js, test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/reference-year-1972.js, test/built-ins/Temporal/Calendar/prototype/monthsInYear/argument-string.js, test/built-ins/Temporal/Calendar/prototype/monthsInYear/basic.js, test/built-ins/Temporal/Calendar/prototype/monthsInYear/branding.js, test/built-ins/Temporal/Calendar/prototype/weekOfYear/argument-plaindate.js, test/built-ins/Temporal/Calendar/prototype/weekOfYear/argument-plaindatetime.js, test/built-ins/Temporal/Calendar/prototype/weekOfYear/argument-string.js, test/built-ins/Temporal/Calendar/prototype/weekOfYear/branding.js
Similar to #3438, this was originally PRs #3056, #3057, #3058, #3059, #3060 by @FrankYFTang which were closed without being merged. I'm following up as promised. I rebased the PRs, added assertion messages, did some reformatting, and combined with some existing tests. In a few places I added more test cases.
=> More follow-up on closed Temporal tests PRs

test/built-ins/Temporal/Instant/prototype/toJSON/year-format.js, test/built-ins/Temporal/Instant/prototype/toString/year-format.js, test/built-ins/Temporal/PlainDate/prototype/toJSON/year-format.js, test/built-ins/Temporal/PlainDate/prototype/toString/year-format.js, test/built-ins/Temporal/PlainDateTime/prototype/toJSON/year-format.js, test/built-ins/Temporal/PlainDateTime/prototype/toString/year-format.js, test/built-ins/Temporal/PlainMonthDay/prototype/toJSON/year-format.js, test/built-ins/Temporal/PlainMonthDay/prototype/toString/year-format.js, test/built-ins/Temporal/PlainYearMonth/prototype/toJSON/year-format.js, test/built-ins/Temporal/PlainYearMonth/prototype/toString/year-format.js, test/built-ins/Temporal/ZonedDateTime/prototype/toJSON/year-format.js, test/built-ins/Temporal/ZonedDateTime/prototype/toString/year-format.js
https://github.com/tc39/proposal-temporal/pull/2090 is a normative change
that reached consensus at the March 2022 TC39 plenary meeting. This adds
tests that verify the change made to the formatting of years between 0 and
999 inclusive in all toString and toJSON methods of Temporal types that
can output an ISO year number in their return value.
=> Tests for Temporal formatting the year appropriately as 4 or 6 digits

test/built-ins/Temporal/PlainYearMonth/prototype/add/calendar-datefromfields-called.js, test/built-ins/Temporal/PlainYearMonth/prototype/subtract/calendar-datefromfields-called.js
https://github.com/tc39/proposal-temporal/pull/2003 is a normative change
that reached consensus at the March 2022 TC39 plenary meeting. This adds
tests that verify the new spec text is implemented correctly, performing
arithmetic on a PlainYearMonth instance that would previously have thrown
an error if it was implemented as written.
=> Tests for computing PlainYearMonth addition and subtraction in correct calendar space

test/language/statements/for-in/S12.6.4_A7_T2.js
As originally written, this test would spuriously pass when the deleted
property was incorrectly visited by enumation but correctly removed from
the object. In such cases, the accumulator string would take the form
"aa1baundefinedca3"
And satisfy all conditions intended to highlight implementation errors.
Refactor the test to avoid false negative by using an object with a null
prototype and verifying the exact contents of the accumulator string.
=> Fix false negative in for-in test

test/built-ins/Function/prototype/bind/instance-length-tointeger.js
A prior version of ECMA262 described invalid mathematical operations
with infinite values [1]. Update the test metadata to reflect the
corrected specification text, and add two assertions for the obsolete
conditions.
[1] ".bind on a function with infinite length has imprecise spec and
engine divergences"
https://github.com/tc39/ecma262/issues/2170
=> Add assertions for functions with infinite length

test/built-ins/Error/constructor.js
Here is one place where compareArray is better fit for purpose, because we
are comparing an array.
=> Replace deepEqual with compareArray

test/built-ins/Temporal/PlainDate/prototype/toPlainDateTime/limits.js, test/built-ins/Temporal/PlainDateTime/from/limits.js, test/built-ins/Temporal/PlainDateTime/limits.js, test/built-ins/Temporal/PlainDateTime/prototype/add/limits.js, test/built-ins/Temporal/PlainDateTime/prototype/round/limits.js, test/built-ins/Temporal/PlainDateTime/prototype/subtract/limits.js, test/built-ins/Temporal/PlainTime/prototype/toPlainDateTime/limits.js, test/built-ins/Temporal/TimeZone/prototype/getPlainDateTimeFor/limits.js
Goes along with [this](https://github.com/tc39/proposal-temporal/pull/2149) PR on the proposal-temporal side.
=> Temporal: `PlainDateTime`: Port Demitasse tests for bounds

test/built-ins/Date/parse/year-zero.js, test/built-ins/Date/year-zero.js
In Date.parse() and new Date(), representations of the year 0 as -000000
must not be accepted. In the case of Date.parse(), they should yield NaN,
and in the case of new Date(), they should yield an invalid Date object,
whose valueOf() is NaN.
See https://github.com/tc39/ecma262/pull/2550
=> Test ISO strings with extended year -000000

test/built-ins/Array/prototype/concat/create-species-non-ctor.js, test/built-ins/Array/prototype/filter/create-species-non-ctor.js, test/built-ins/Array/prototype/map/create-species-non-ctor.js, test/built-ins/Array/prototype/slice/create-species-non-ctor.js, test/built-ins/Array/prototype/splice/create-species-non-ctor.js, test/built-ins/RegExp/prototype/toString/S15.10.6.4_A6.js, test/built-ins/RegExp/prototype/toString/S15.10.6.4_A7.js
A few of the "not constructor" tests weren't using isConstructor, and thus lacked the `Reflect.construct` feature flag.
At first I tried to make a new "non-constructor" feature flag, but it would change hundreds of files - and since these tests were missing an `isConstructor` precondition assertion anyways, this seemed more expedient.
=> use `isConstructor` assertion in "non-constructor" tests

test/built-ins/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar-noniso.js, test/built-ins/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar-same-id.js, test/built-ins/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar-same-object.js, test/built-ins/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar.js, test/built-ins/Temporal/PlainDateTime/prototype/withPlainDate/argument-string-iso-calendar.js, test/intl402/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar-noniso.js, test/intl402/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar-same-id.js, test/intl402/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar-same-object.js, test/intl402/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar.js, test/intl402/Temporal/PlainDateTime/prototype/withPlainDate/argument-string-iso-calendar.js
Temporal.PlainDateTime.prototype.ear and earYear are not defined in first 14 chapters and only defined under Chapter 15. Therefore they should always return undefined unless it is an intl implementation.
Copy the same test to intl402 and remove the non undefined value of era/eraYear from the built-ints version of test. 
Fix https://github.com/tc39/test262/issues/3516 
Also see https://github.com/tc39/proposal-temporal/issues/2169
=> Move testing of era/eraYear under intl402

test/intl402/NumberFormat/prototype/format/format-rounding-priority-more-precision.js
=> Fix Intl.NumberFormat roundingPriority test to reflect default values for min/max digits

test/built-ins/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar-noniso.js, test/built-ins/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar-same-id.js, test/built-ins/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar-same-object.js, test/built-ins/Temporal/PlainDateTime/prototype/withPlainDate/argument-plaindate-calendar.js, test/built-ins/Temporal/PlainDateTime/prototype/withPlainDate/argument-string-iso-calendar.js
I suggested in #3517 that these lines should be removed but didn't realize
they must be present because TemporalHelpers.assertPlainDateTime is going
to access the 'era' and 'eraYear' properties.
=> Fix Temporal.PlainDateTime.withPlainDate tests

test/language/statements/for-in/S12.6.4_A7_T2.js
This test currently has some tabs. Clean this up and make it use spaces instead.
=> Turn unimportant tabs into spaces in S12.6.4_A7_T2.js

test/built-ins/ShadowRealm/prototype/importValue/throws-if-exportname-not-string.js
Fixes: https://github.com/tc39/test262/issues/3509
Normative Change: https://github.com/tc39/proposal-shadowrealm/pull/352
=> ShadowRealm: exportName is no longer be coerced to a string

tools/generation/generator.py
.DS_Store is not a utf8 encoded text file. Reading it in utf8 encoding makes `./make.py clean` abort with the following exception:
```
./make.py clean
Running target: clean
> /bin/python tools/generation/generator.py clean test
Traceback (most recent call last):
File "/workspace/tc39/test262/tools/generation/generator.py", line 103, in <module>
args.func(args)
File "/workspace/tc39/test262/tools/generation/generator.py", line 39, in clean
test.load()
File "/workspace/tc39/test262/tools/generation/lib/test.py", line 29, in load
self.source = handle.read()
File "/workspace/.pyenv/versions/3.10.3/lib/python3.10/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 1097: invalid …
```
=> Fix generator clean fail on .DS_Store

test/built-ins/AsyncGeneratorPrototype/return/return-blocked-broken-promise.js, test/built-ins/AsyncGeneratorPrototype/return/return-state-completed-broken-promise.js, test/built-ins/AsyncGeneratorPrototype/return/return-suspendedStart-broken-promise.js, test/built-ins/AsyncGeneratorPrototype/return/return-suspendedYield-broken-promise-try-catch.js
Tests for https://github.com/tc39/ecma262/pull/2683.
=> Add test on handling broken promises in AsyncGenerator.prototype.return

features.txt, src/class-elements/field-definition-accessor-no-line-terminator.case, src/class-elements/grammar-field-accessor.case, src/decorator/decorator-call-expr-identifier-reference.case, src/decorator/decorator-member-expr-decorator-member-expr.case, src/decorator/decorator-member-expr-identifier-reference.case, src/decorator/decorator-member-expr-private-identifier.case, src/decorator/decorator-parenthesized-expr-identifier-reference.case, src/decorator/syntax/class-valid/cls-decl-decorators-valid-syntax.template, src/decorator/syntax/class-valid/cls-expr-decorators-valid-syntax.template, src/decorator/syntax/valid/cls-decl-decorators-valid-syntax.template, src/decorator/syntax/valid/cls-element-decorators-valid-syntax.template, src/decorator/syntax/valid/cls-expr-decorators-valid-syntax.template, test/language/expressions/class/decorator/syntax/class-valid/decorator-member-expr-private-identifier.js, test/language/expressions/class/decorator/syntax/valid/decorator-call-expr-identifier-reference.js, test/language/expressions/class/decorator/syntax/valid/decorator-member-expr-decorator-member-expr.js, test/language/expressions/class/decorator/syntax/valid/decorator-member-expr-identifier-reference.js, test/language/expressions/class/decorator/syntax/valid/decorator-parenthesized-expr-identifier-reference.js, test/language/expressions/class/elements/field-definition-accessor-no-line-terminator.js, test/language/expressions/class/elements/syntax/valid/grammar-field-accessor.js, test/language/statements/class/decorator/syntax/class-valid/decorator-member-expr-private-identifier.js, test/language/statements/class/decorator/syntax/valid/decorator-call-expr-identifier-reference.js, test/language/statements/class/decorator/syntax/valid/decorator-member-expr-decorator-member-expr.js, test/language/statements/class/decorator/syntax/valid/decorator-member-expr-identifier-reference.js, test/language/statements/class/decorator/syntax/valid/decorator-parenthesized-expr-identifier-reference.js, test/language/statements/class/elements/field-definition-accessor-no-line-terminator.js, test/language/statements/class/elements/syntax/valid/grammar-field-accessor.js
This PR adds initial decorator syntax tests on:
- ClassDeclaration
- ClassExpression
- ClassElement
- FieldDefinition accessor
=> Decorators: add initial tests on class

test/intl402/NumberFormat/test-option-roundingPriority-mixed-options.js
https://github.com/tc39/test262/issues/3508#issue-1221898118
Todo's  for other tests files:
The goal's to have correct matrix results aligned with spec
cc @sffc @FrankYFTang
=> Tests combinations max-min fractionDigits and Significant digits

test/built-ins/Temporal/Calendar/subclass.js, test/built-ins/Temporal/Duration/subclass.js, test/built-ins/Temporal/Instant/subclass.js, test/built-ins/Temporal/PlainDate/subclass.js, test/built-ins/Temporal/PlainDateTime/subclass.js, test/built-ins/Temporal/PlainMonthDay/subclass.js, test/built-ins/Temporal/PlainTime/subclass.js, test/built-ins/Temporal/PlainYearMonth/subclass.js, test/built-ins/Temporal/TimeZone/subclass.js, test/built-ins/Temporal/ZonedDateTime/subclass.js
This pull request fixes #3545. It changes the typo of `flags: [Temporal]` to `features: [Temporal]`, added in https://github.com/tc39/test262/commit/6573cf954b81171b00b55bb7404d1ee46b5b0db6.
=> Fixed #3545

README.md
I've developed a library for running and generating (currently) NUnit based test suites for test262. This is already being successfully used in two .NET projects, [Jint](https://github.com/sebastienros/jint) (JS interpreter) and [esprima-dotnet](https://github.com/sebastienros/esprima-dotnet) (JS parsing library).
=> Add test262-harness-dotnet to README

src/decorator/decorator-call-expr-identifier-reference-yield.case, src/decorator/decorator-call-expr-identifier-reference.case, src/decorator/decorator-member-expr-identifier-reference-yield.case, src/decorator/decorator-member-expr-identifier-reference.case, src/decorator/decorator-parenthesized-expr-identifier-reference-yield.case, src/decorator/decorator-parenthesized-expr-identifier-reference.case, test/language/expressions/class/decorator/syntax/valid/decorator-call-expr-identifier-reference-yield.js, test/language/expressions/class/decorator/syntax/valid/decorator-call-expr-identifier-reference.js, test/language/expressions/class/decorator/syntax/valid/decorator-member-expr-identifier-reference-yield.js, test/language/expressions/class/decorator/syntax/valid/decorator-member-expr-identifier-reference.js, test/language/expressions/class/decorator/syntax/valid/decorator-parenthesized-expr-identifier-reference-yield.js, test/language/expressions/class/decorator/syntax/valid/decorator-parenthesized-expr-identifier-reference.js, test/language/statements/class/decorator/syntax/valid/decorator-call-expr-identifier-reference-yield.js, test/language/statements/class/decorator/syntax/valid/decorator-call-expr-identifier-reference.js, test/language/statements/class/decorator/syntax/valid/decorator-member-expr-identifier-reference-yield.js, test/language/statements/class/decorator/syntax/valid/decorator-member-expr-identifier-reference.js, test/language/statements/class/decorator/syntax/valid/decorator-parenthesized-expr-identifier-reference-yield.js, test/language/statements/class/decorator/syntax/valid/decorator-parenthesized-expr-identifier-reference.js
The test preparation code in recently added decorator tests contains `var yield` and `function yield() {}`. However, a BindingIdentifier must not be `yield` in strict mode, so I add `noStrict` flag to these cases.
Context: https://github.com/babel/babel/pull/14638
=> add noStrict flag to yield-as-binding-id cases

test/built-ins/Temporal/Calendar/prototype/dateFromFields/missing-properties.js, test/built-ins/Temporal/Calendar/prototype/dateFromFields/order-of-operations.js, test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/missing-properties.js, test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/order-of-operations.js, test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/missing-properties.js, test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/order-of-operations.js, test/intl402/Temporal/Calendar/prototype/dateFromFields/order-of-operations.js, test/intl402/Temporal/Calendar/prototype/monthDayFromFields/order-of-operations.js, test/intl402/Temporal/Calendar/prototype/yearMonthFromFields/order-of-operations.js
This adds tests for https://github.com/tc39/proposal-temporal/pull/2203
which was a normative change that reached consensus in the June 2022 TC39
plenary meeting.
=> Temporal: Add tests for order of observable operations in *FromFields methods

test/built-ins/Temporal/Instant/compare/argument-string-invalid.js, test/built-ins/Temporal/Instant/from/argument-string-invalid.js, test/built-ins/Temporal/Instant/prototype/equals/argument-string-invalid.js, test/built-ins/Temporal/Instant/prototype/since/argument-string-invalid.js, test/built-ins/Temporal/Instant/prototype/until/argument-string-invalid.js, test/built-ins/Temporal/TimeZone/prototype/getNextTransition/argument-string-invalid.js, test/built-ins/Temporal/TimeZone/prototype/getOffsetNanosecondsFor/argument-string-invalid.js, test/built-ins/Temporal/TimeZone/prototype/getOffsetStringFor/argument-string-invalid.js, test/built-ins/Temporal/TimeZone/prototype/getPlainDateTimeFor/argument-string-invalid.js, test/built-ins/Temporal/TimeZone/prototype/getPreviousTransition/argument-string-invalid.js
This adds tests to all entry points where an ISO string is converted to a
Temporal.Instant. The tests exercise various invalid ISO strings to make
sure that they throw a RangeError.
=> Temporal: Add tests for invalid Temporal.Instant strings

test/language/statements/for/head-const-bound-names-in-stmt.js
The test as originally specified fails in all compatible parsers, but for the wrong reason. Below is an excerpt from V8, but all parser I tested behave the same:
```js
for (const x; false; ) {
^
SyntaxError: Missing initializer in const declaration
```
After the change the error is the assumed:
```js
var x;
^
SyntaxError: Identifier 'x' has already been declared
```
=> Fix wrong error for a lexical redeclaration test

test/built-ins/Temporal/Calendar/prototype/constructor.js, test/built-ins/Temporal/Duration/prototype/constructor.js, test/built-ins/Temporal/Instant/prototype/constructor.js, test/built-ins/Temporal/PlainDate/prototype/constructor.js, test/built-ins/Temporal/PlainDateTime/prototype/constructor.js, test/built-ins/Temporal/PlainMonthDay/prototype/constructor.js, test/built-ins/Temporal/PlainTime/prototype/constructor.js, test/built-ins/Temporal/PlainYearMonth/prototype/constructor.js, test/built-ins/Temporal/TimeZone/prototype/constructor.js, test/built-ins/Temporal/ZonedDateTime/prototype/constructor.js
Fix for #3538. Temporal tests will immediately ReferenceError out without a feature flag.
@Ms2ger @ptomato
=> Temporal: Add missing feature flag for prototype.constructor tests.

test/language/module-code/early-dup-lex.js, test/language/statements/for/labelled-fn-stmt-const.js
Prior to this commit, two tests for specific early errors also included
syntactically invalid `const` declarations. Implementations which
produced the expected syntax error due to these invalid declarations
would pass the tests regardless of whether they produced the early
errors that the tests were written to verify.
Correct the `const` declarations so that the tests verify the parsing
rule that they were designed to verify.
---
Hat tip to @grassator for recognizing this problem in another test (see gh-3575).
=> Correct spurious syntax errors

test/built-ins/Temporal/Instant/compare/instant-string-limits.js, test/built-ins/Temporal/Instant/from/instant-string-limits.js, test/built-ins/Temporal/Instant/prototype/equals/instant-string-limits.js, test/built-ins/Temporal/Instant/prototype/since/instant-string-limits.js, test/built-ins/Temporal/Instant/prototype/until/instant-string-limits.js, test/built-ins/Temporal/TimeZone/prototype/getNextTransition/instant-string-limits.js, test/built-ins/Temporal/TimeZone/prototype/getOffsetNanosecondsFor/instant-string-limits.js, test/built-ins/Temporal/TimeZone/prototype/getOffsetStringFor/instant-string-limits.js, test/built-ins/Temporal/TimeZone/prototype/getPlainDateTimeFor/instant-string-limits.js, test/built-ins/Temporal/TimeZone/prototype/getPreviousTransition/instant-string-limits.js
This adds tests for a normative change which reached consensus in the June
2022 TC39 meeting, ensuring that the representable range of
Temporal.Instant is always the same regardless of which time zone offset
is used when converting from a string.
See: https://github.com/tc39/proposal-temporal/pull/2189
=> Add tests for Temporal.Instant strings at the edge of the range

test/built-ins/Temporal/PlainDate/from/overflow-invalid-string.js, test/built-ins/Temporal/PlainDateTime/from/overflow-invalid-string.js
A normative change that reached consensus at the June 2022 TC39 meeting
was this small change to throw on an invalid value for the overflow option
in PlainDate.from() and PlainDateTime.from(), in the case of a fast-path
conversion.
See https://github.com/tc39/proposal-temporal/pull/2225
=> Temporal: Test validation of overflow option for conversion fast paths

test/intl402/NumberFormat/test-option-useGrouping-extended.js
Based on discussion[1], useGrouping computation in Intl.NumberFormat v3 is updated[2] to keep web compatibility.
This change fixes the existing test which is testing the previous behavior.
[1]: https://github.com/tc39/proposal-intl-numberformat-v3/issues/74
[2]: https://github.com/tc39/proposal-intl-numberformat-v3/commit/d13bd63f8fdf3f00c0a2ec15a235f34cc0fcbb08
=> Fix useGrouping tests based on the latest Intl.NumberFormat v3 change

test/intl402/NumberFormat/test-option-useGrouping-extended.js, test/intl402/NumberFormat/test-option-useGrouping.js
Sync the test to
https://github.com/tc39/proposal-intl-numberformat-v3/pull/92 and remove unnecessary wording no longer true after that PR landed.
=> Sync test to PR29 of numberformat-v3

test/built-ins/AsyncIteratorPrototype/Symbol.asyncIterator/return-val.js, test/built-ins/IteratorPrototype/Symbol.iterator/return-val.js
The existing test passed an object for a `this` value. This commit checks that
primitive values are returned verbatim, without any conversion.
Resolve #3489.
=> Test primitive retval of Iterator and AsyncIterator getters

test/intl402/Temporal/TimeZone/prototype/getNextTransition/transition-at-instant-boundaries.js, test/intl402/Temporal/TimeZone/prototype/getPreviousTransition/transition-at-instant-boundaries.js
This normative change reached consensus in the July 2022 TC39 meeting:
https://github.com/tc39/proposal-temporal/pull/2351
(Taken from @anba's tests in #3599)
=> Temporal: tests for out-of-range time zone transitions

test/built-ins/Temporal/PlainMonthDay/refisoyear-out-of-range.js
The refISOYear argument in the Temporal.PlainMonthDay constructor can
cause a RangeError if it is outside the supported range for PlainDate.
This is part of a normative PR that reached consensus at the July 2022
TC39 plenary:
https://github.com/tc39/proposal-temporal/pull/2266
=> Temporal: test for out-of-range in Temporal.PlainMonthDay constructor

test/built-ins/RegExp/prototype/flags/this-val-regexp.js, test/built-ins/RegExp/prototype/unicodeSets/cross-realm.js, test/built-ins/RegExp/prototype/unicodeSets/length.js, test/built-ins/RegExp/prototype/unicodeSets/name.js, test/built-ins/RegExp/prototype/unicodeSets/prop-desc.js, test/built-ins/RegExp/prototype/unicodeSets/this-val-invalid-obj.js, test/built-ins/RegExp/prototype/unicodeSets/this-val-non-obj.js, test/built-ins/RegExp/prototype/unicodeSets/this-val-regexp-prototype.js, test/built-ins/RegExp/prototype/unicodeSets/this-val-regexp.js, test/built-ins/RegExp/prototype/unicodeSets/uv-flags-constructor.js, test/built-ins/RegExp/prototype/unicodeSets/uv-flags.js
This functionality is part of the RegExp `v` flag proposal: https://github.com/tc39/proposal-regexp-v-flag
Issue: #3496, https://github.com/tc39/proposal-regexp-v-flag/issues/52
=> Add manually written tests for RegExp `v` flag proposal

test/built-ins/Temporal/ZonedDateTime/prototype/round/smallest-unit-day-daylength-too-large.js, test/built-ins/Temporal/ZonedDateTime/prototype/round/smallest-unit-day-daylength-zero-or-negative.js
Negative day lengths are no longer valid after <https://github.com/tc39/proposal-temporal/pull/2261>.
=> Update tests which used negative day lengths

test/intl402/Temporal/TimeZone/from/etc-timezone.js, test/intl402/Temporal/TimeZone/from/iana-legacy-names.js, test/intl402/Temporal/TimeZone/iana-legacy-names.js
This adds tests for https://github.com/tc39/proposal-temporal/pull/2292 which is a normative change to the Temporal proposal that reached consensus at the July 2022 TC39 meeting.
=> Tests for Temporal time zones with legacy IANA names

test/built-ins/Temporal/Duration/prototype/toString/fractionalseconddigits-non-integer.js, test/built-ins/Temporal/Instant/prototype/toString/fractionalseconddigits-non-integer.js, test/built-ins/Temporal/PlainDateTime/prototype/toString/fractionalseconddigits-non-integer.js, test/built-ins/Temporal/PlainTime/prototype/toString/fractionalseconddigits-non-integer.js, test/built-ins/Temporal/ZonedDateTime/prototype/toString/fractionalseconddigits-non-integer.js
This implements the normative change in
https://github.com/tc39/proposal-temporal/pull/2297 which reached
consensus at the July 2022 TC39 meeting.
Values given as the fractionalSecondDigits option are now truncated to
integers before they are compared to the allowable range.
=> Temporal: Adjust tests for non-integer/out-of-range values of fractionalSecondDigits

test/built-ins/Temporal/Duration/prototype/total/total-value-infinity.js
This adds test for https://github.com/tc39/proposal-temporal/pull/2298 which is a normative change to the Temporal proposal that reached consensus at the July 2022 TC39 meeting.
=> Temporal: Add test for Temporal.Duration.prototype.total

test/built-ins/BigInt/constructor-coercion.js
This adds a test for https://github.com/tc39/ecma262/pull/2812. I didn't find any tests for the previous behavior.
=> add tests for "only coerce once in BigInt constructor"

package.json
1.2.8 does not install graaljs correctly.
=> CI: Bump esvu to 1.2.9

test/built-ins/Temporal/PlainDateTime/prototype/toString/calendar-tostring.js, test/built-ins/Temporal/ZonedDateTime/prototype/toString/calendar-tostring.js
This implements the normative change in
https://github.com/tc39/proposal-temporal/pull/2269 which reached
consensus at the July 2022 TC39 meeting.
There was already a test for PlainDate for this topic, which needs to be
adjusted to accommodate the normative change. Tests for PlainDateTime and
ZonedDateTime did not yet exist, so add new ones based on the PlainDate
test.
=> Temporal: Adjust and expand tests for observable calls to ToString(calendar)

features.txt, test/built-ins/Array/prototype/Symbol.unscopables/array-grouping.js
TC39 decided to rename them to avoid web-compat issue[1].
This change follows to it.
[1]: https://github.com/tc39/proposal-array-grouping/pull/39
=> Rename Array#groupBy and Array#groupByToMap to Array#group and Array#groupToMap

test/built-ins/ShadowRealm/prototype/evaluate/globalthis-available-properties.js
The intention of this test is to ensure that all built-in properties of the global object are also exposed on the `ShadowRealm`'s global object, without penalizing implementations that don't have all of them implemented.
Notably, `SharedArrayBuffer` may still not be (re-)enabled in all circumstances.
cc @leobalter (original author of this test)
=> ShadowRealm: Relax requirements of globalThis available properties test

CODEOWNERS
This requires @tc39/test262-maintainers approval for everything, but also allows @tc39/test262-staging approval for the `test/staging` directory.
=> Meta: add CODEOWNERS

implementation-contributed/javascriptcore/es6/Proxy_internal_get_calls_RegExp.prototype[Symbol.match].js, implementation-contributed/javascriptcore/es6/Proxy_internal_get_calls_RegExp.prototype[Symbol.replace].js, implementation-contributed/v8/mjsunit/regress/regress-799813.js, test/built-ins/RegExp/prototype/Symbol.match/flags-tostring-error.js, test/built-ins/RegExp/prototype/Symbol.match/g-get-exec-err.js, test/built-ins/RegExp/prototype/Symbol.match/get-flags-err.js, test/built-ins/RegExp/prototype/Symbol.match/get-global-err.js, test/built-ins/RegExp/prototype/Symbol.match/get-unicode-error.js, test/built-ins/RegExp/prototype/Symbol.replace/flags-tostring-error.js, test/built-ins/RegExp/prototype/Symbol.replace/get-exec-err.js, test/built-ins/RegExp/prototype/Symbol.replace/get-flags-err.js, test/built-ins/RegExp/prototype/Symbol.replace/get-unicode-error.js
This adds tests for https://github.com/tc39/ecma262/pull/2791 , which reached consensus at the July 2022 TC39 meeting.
=> Update RegExp.prototype.{match,replace} tests to expect Get(rx, "flags")

test/built-ins/RegExp/prototype/dotAll/this-val-invalid-obj.js, test/built-ins/RegExp/prototype/dotAll/this-val-non-obj.js, test/built-ins/RegExp/prototype/flags/this-val-non-obj.js, test/built-ins/RegExp/prototype/global/this-val-invalid-obj.js, test/built-ins/RegExp/prototype/global/this-val-non-obj.js, test/built-ins/RegExp/prototype/hasIndices/this-val-invalid-obj.js, test/built-ins/RegExp/prototype/hasIndices/this-val-non-obj.js, test/built-ins/RegExp/prototype/ignoreCase/this-val-invalid-obj.js, test/built-ins/RegExp/prototype/ignoreCase/this-val-non-obj.js, test/built-ins/RegExp/prototype/multiline/this-val-invalid-obj.js, test/built-ins/RegExp/prototype/multiline/this-val-non-obj.js, test/built-ins/RegExp/prototype/source/this-val-invalid-obj.js, test/built-ins/RegExp/prototype/source/this-val-non-obj.js, test/built-ins/RegExp/prototype/sticky/this-val-invalid-obj.js, test/built-ins/RegExp/prototype/sticky/this-val-non-obj.js, test/built-ins/RegExp/prototype/unicode/this-val-invalid-obj.js, test/built-ins/RegExp/prototype/unicode/this-val-non-obj.js
For completeness, as we are doing in newer brand checking tests such as
those of Temporal, call these getters with a function object and a bigint
as the receiver.
Suggested in https://github.com/tc39/test262/pull/3614/files#r929662337
=> Add cases to RegExp.prototype flags brand checking tests

features.txt, test/built-ins/RegExp/named-groups/duplicate-names-group-property-enumeration-order.js, test/built-ins/RegExp/named-groups/duplicate-names-match-indices.js, test/built-ins/RegExp/named-groups/duplicate-names-replace.js, test/built-ins/RegExp/named-groups/duplicate-names.js, test/language/literals/regexp/named-groups/invalid-duplicate-groupspecifier-2-u.js, test/language/literals/regexp/named-groups/invalid-duplicate-groupspecifier-2.js, test/language/literals/regexp/named-groups/invalid-duplicate-groupspecifier-u.js, test/language/literals/regexp/named-groups/invalid-duplicate-groupspecifier.js
This adds simple tests for https://github.com/tc39/proposal-duplicate-named-capturing-groups, which achieved stage 3 at the July 2022 meeting. No existing tests were invalidated, but some needed their descriptions updated.
=> Add tests for proposal-duplicate-named-capturing-groups

test/built-ins/Temporal/Duration/prototype/round/february-leap-year.js
This implements the normative change in
https://github.com/tc39/proposal-temporal/pull/2344 which reached
consensus at the July 2022 TC39 meeting.
It adds a test that catches a corner case in Duration.prototype.round().
=> Temporal: Add test for rounding Duration relative to Feb 1 in a leap year

test/built-ins/Temporal/Instant/compare/instant-string.js, test/built-ins/Temporal/Instant/from/instant-string.js, test/built-ins/Temporal/Instant/prototype/equals/instant-string.js, test/built-ins/Temporal/Instant/prototype/since/instant-string.js, test/built-ins/Temporal/Instant/prototype/until/instant-string.js, test/built-ins/Temporal/TimeZone/prototype/getNextTransition/instant-string.js, test/built-ins/Temporal/TimeZone/prototype/getOffsetNanosecondsFor/instant-string.js, test/built-ins/Temporal/TimeZone/prototype/getOffsetStringFor/instant-string.js, test/built-ins/Temporal/TimeZone/prototype/getPlainDateTimeFor/instant-string.js, test/built-ins/Temporal/TimeZone/prototype/getPreviousTransition/instant-string.js
This adds tests for the normative change: https://github.com/tc39/proposal-temporal/pull/2345
These tests ensure that while parsing an Instant string, calendar annotation is ignored.
=> Temporal: Add calendar strings to instant string tests

test/intl402/NumberFormat/test-option-useGrouping-extended.js, test/intl402/NumberFormat/test-option-useGrouping.js
Update test to be aligned with spec changes on https://github.com/tc39/proposal-intl-numberformat-v3/pull/107
cc @sffc
=> Update Tests NumberFormat V3 spec changes

test/staging/Temporal/TimeZone/old/subminute-offset.js
Due to the TZDB's recent merging of time zones whose pre-1970 data was different but post-1970 have been the same, this test is going to start failing on implementations with up-to-date time zone data (because the Europe/Amsterdam time zone was absorbed into Europe/Brussels in the latest update.)
It's on our to-do list to remove all dependencies on IANA time zones from the Temporal tests in staging/,
(see https://github.com/tc39/test262/issues/3649#issuecomment-1232326175) but this one is more urgent.
=> Temporal: Fix test that depends on pre-1970 time zone data

test/intl402/DurationFormat/constructor-options-fractionalDigits-valid.js
undefined is no longer value output for resolvedOptions().fractionalDigits
https://github.com/tc39/proposal-intl-duration-format/pull/113
=> Remove undefined to sync to PR 113 of proposal-intl-duration-format

test/intl402/DurationFormat/constructor-options-defaults.js, test/intl402/DurationFormat/constructor-options-style-valid.js, test/intl402/DurationFormat/prototype/format/basic-format-en.js
1. add the test for "seconds"
2. since the default value for "style" is "long", baseStyle for GetDurationUnitOptions is "long" and therefore the 
last argument in testOption should be "long"
3. the valid values for "days" does not contains  "numeric", and "2-digit". remove them. 
4. the valid values for "milliseconds", "microseconds" and "nanoseconds" does not contains "2-digit". remove it.
See https://tc39.es/proposal-intl-duration-format/#table-duration-components about the valid value
notice the last colum is for "Digital Default" while the baseStyle is "digital" but the set up does not set it that way, the default value for "style" is "long" as in
```
13. Let style be ? GetOption(options, "style", "string", « "long", "short", "narrow", "digital" », "long").
```
of …
=> Fix DurationFormat default tests

test/built-ins/Temporal/Calendar/prototype/dateFromFields/order-of-operations.js, test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/order-of-operations.js, test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/order-of-operations.js, test/intl402/Temporal/Calendar/prototype/dateFromFields/order-of-operations.js, test/intl402/Temporal/Calendar/prototype/monthDayFromFields/order-of-operations.js, test/intl402/Temporal/Calendar/prototype/yearMonthFromFields/order-of-operations.js
This implements the normative change in
https://github.com/tc39/proposal-temporal/pull/2377 which reached consensus at the September 2022 TC39 meeting.
It changes the order in which observable operations are performed on the values passed to the ___fromFields methods of Calendar.
=> Temporal: Adjust order of operations in Calendar.___fromFields

test/staging/Temporal/Duration/old/limits.js
The doAsserts is not correct for case like "P100000000000000000000000000Y" If we test "P100000000000000000000000000Y" because the filed in Duration is only required to  "A float64-representable integer is an integer that is exactly representable as a Number value. That is, for a float64-representable integer x, it must hold that ℝ(𝔽(x)) = x." per  https://tc39.es/proposal-temporal/#sec-properties-of-temporal-duration-instances
If there is a positive numeric error, the string will be like "P100000000000000000000001234Y" but we ma also have a negative numeric error, which will have the string be something like "P99999999999999987584860160Y" 
.  
Even the test() only test the first 10 digits ( log(10^10)/log(2) = 33 bits) of the formated the string, this will still not match. In this PR, I …
=> Fix limit test

test/staging/ArrayBuffer/resizable/subarray-parameter-conversion-grows.js, test/staging/ArrayBuffer/resizable/subarray-parameter-conversion-shrinks.js
This is from the normative change in
https://github.com/tc39/proposal-resizablearraybuffer/pull/93, which got consensus in the March 2022 TC39.
=> Fix resizable ArrayBuffer subarray tests

.circleci/config.yml
CircleCI reports: "You’re using a [deprecated Docker convenience image.](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) Upgrade to a next-gen Docker convenience image."
=> CI: Update CircleCI Docker images.

test/built-ins/Temporal/Duration/compare/precision-exact-mathematical-values-1.js, test/built-ins/Temporal/Duration/compare/precision-exact-mathematical-values-2.js, test/built-ins/Temporal/Duration/from/argument-string-fractional-precision.js, test/built-ins/Temporal/Duration/from/argument-string-fractional-with-zero-subparts.js, test/built-ins/Temporal/Duration/prototype/add/nanoseconds-is-number-max-safe-integer.js, test/built-ins/Temporal/Duration/prototype/add/nanoseconds-is-number-max-value-2.js, test/built-ins/Temporal/Duration/prototype/add/precision-exact-mathematical-values.js, test/built-ins/Temporal/Duration/prototype/round/precision-exact-in-balance-duration-relative-months.js, test/built-ins/Temporal/Duration/prototype/round/precision-exact-in-balance-duration-relative-weeks.js, test/built-ins/Temporal/Duration/prototype/round/precision-exact-in-balance-duration-relative-years-days.js, test/built-ins/Temporal/Duration/prototype/round/precision-exact-in-balance-duration-relative-years-months.js, test/built-ins/Temporal/Duration/prototype/round/precision-exact-in-balance-duration-relative-years-with-calendar.js, test/built-ins/Temporal/Duration/prototype/round/precision-exact-in-round-duration.js, test/built-ins/Temporal/Duration/prototype/subtract/nanoseconds-is-number-max-safe-integer.js, test/built-ins/Temporal/Duration/prototype/subtract/nanoseconds-is-number-max-value-2.js, test/built-ins/Temporal/Duration/prototype/subtract/precision-exact-mathematical-values.js, test/built-ins/Temporal/Duration/prototype/toString/precision-exact-mathematical-values.js, test/built-ins/Temporal/PlainTime/prototype/add/argument-object.js, test/built-ins/Temporal/PlainTime/prototype/add/precision-exact-mathematical-values-1.js, test/built-ins/Temporal/PlainTime/prototype/add/precision-exact-mathematical-values-2.js, test/built-ins/Temporal/PlainTime/prototype/add/precision-exact-mathematical-values-3.js, test/built-ins/Temporal/PlainTime/prototype/subtract/argument-object.js, test/built-ins/Temporal/PlainTime/prototype/subtract/precision-exact-mathematical-values-1.js, test/built-ins/Temporal/PlainTime/prototype/subtract/precision-exact-mathematical-values-2.js, test/built-ins/Temporal/PlainTime/prototype/subtract/precision-exact-mathematical-values-3.js, test/intl402/Temporal/TimeZone/non-canonical-utc.js
Here's another batch of @anba's Temporal tests from #3599. These are ones that I've reviewed myself and are ready to land, they just need a rubber stamp so that I can land them in advance of reviewing the rest of #3599. There's also a minor commit adding assertion messages to a test.
=> Anba's Temporal tests, batch 3

harness/temporalHelpers.js, test/built-ins/Temporal/Duration/compare/order-of-operations.js, test/built-ins/Temporal/Duration/prototype/round/order-of-operations.js, test/built-ins/Temporal/Duration/prototype/total/order-of-operations.js, test/built-ins/Temporal/Instant/prototype/toString/timezone.js, test/built-ins/Temporal/Instant/prototype/toZonedDateTime/plain-custom-timezone.js, test/built-ins/Temporal/Now/plainDate/toPlainDate-override.js, test/built-ins/Temporal/Now/plainDateTime/calendar-function.js, test/built-ins/Temporal/Now/plainDateTime/calendar-object.js, test/built-ins/Temporal/Now/plainDateTime/timezone-object.js, test/built-ins/Temporal/Now/plainDateTime/timezone.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-object.js, test/built-ins/Temporal/Now/plainTimeISO/timezone.js, test/built-ins/Temporal/Now/plainTimeISO/toPlainTime-override.js, test/built-ins/Temporal/Now/zonedDateTime/calendar-function.js, test/built-ins/Temporal/Now/zonedDateTime/calendar-object.js, test/built-ins/Temporal/Now/zonedDateTime/timezone-object.js, test/built-ins/Temporal/Now/zonedDateTimeISO/timezone-object.js, test/built-ins/Temporal/PlainDate/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainDate/prototype/until/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/toZonedDateTime/plain-custom-timezone.js, test/built-ins/Temporal/PlainDateTime/prototype/until/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/until/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/toPlainDateTime/plain-custom-timezone.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/order-of-operations.js
See https://github.com/tc39/proposal-temporal/pull/2267 which eliminated some unnecessary lookups of the calendar's dateAdd method from the MoveRelativeDate AO, which is called in the calendar types' since() and until() methods, Duration.p.round(), and Duration.p.total().
This adds tests for the order of all observable operations for these 10 methods, not just the lookups of dateAdd on the calendar. (These methods needed to have their order of observable operations tested anyway.)
They heavily use the TemporalHelpers.calendarObserver and TemporalHelpers.timeZoneObserver added in the first two commits of this PR.
https://github.com/tc39/proposal-temporal/pull/2267 included changes to several code paths, not all of which are reachable through every method tested here; only …
=> Temporal: Add tests for observable operations in MoveRelativeDate

test/built-ins/Temporal/Duration/prototype/round/order-of-operations.js
I had missed that there's an early return step from [UnbalanceDurationRelative](https://tc39.es/proposal-temporal/#sec-temporal-unbalancedurationrelative) if years, months, weeks, and days are all 0.
Closes: #3684
=> Temporal: Fix expectation for observable operations in Duration.p.round()

harness/temporalHelpers.js, test/built-ins/Temporal/Calendar/prototype/mergeFields/non-string-properties.js, test/built-ins/Temporal/Calendar/prototype/mergeFields/order-of-operations.js, test/built-ins/Temporal/PlainDate/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainDate/prototype/until/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/until/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/add/calendar-arguments-extra-options.js, test/built-ins/Temporal/PlainYearMonth/prototype/add/calendar-arguments.js, test/built-ins/Temporal/PlainYearMonth/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/subtract/calendar-arguments-extra-options.js, test/built-ins/Temporal/PlainYearMonth/prototype/subtract/calendar-arguments.js, test/built-ins/Temporal/PlainYearMonth/prototype/until/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/order-of-operations.js
This consists of tests for the normative change https://github.com/tc39/proposal-temporal/pull/2245 which achieved consensus at the July 2022 TC39 meeting.
Also contains a bug fix for an existing test (it ought to have been invalidated by this normative change, but spuriously passed.)
=> Temporal: Test use of CopyDataProperties 

test/built-ins/Array/prototype/toSpliced/mutate-while-iterating.js
The `arr[0] = 17` throws in strict mode. I'm not sure what that line is supposed to be testing. This can be either fixed per this PR or by adding a `flags: [noStrict]`.
=> Fix toSpliced mutate-while-iterating test

test/intl402/Temporal/PlainDateTime/compare/infinity-throws-rangeerror.js, test/intl402/Temporal/PlainDateTime/prototype/equals/infinity-throws-rangeerror.js, test/intl402/Temporal/PlainDateTime/prototype/since/infinity-throws-rangeerror.js, test/intl402/Temporal/PlainDateTime/prototype/until/infinity-throws-rangeerror.js, test/intl402/Temporal/PlainDateTime/prototype/withPlainDate/infinity-throws-rangeerror.js
I discovered these tests had omitted some arguments to the PlainDateTime constructor, leaving the calendar in the wrong position.
The tests were technically not incorrect, since the operation ToIntegerThrowOnInfinity on the string "gregory" gives 0. But they could spuriously pass if the implementation didn't do argument conversion correctly, failed to throw on eraYear being ±Infinity, but subsequently threw RangeError anyway because the calendars of the arguments didn't match.
=> Temporal: Fix PlainDateTime construct args

CONTRIBUTING.md, INTERPRETING.md
This intends to make explicit in the contributor and interpreter docs, the intention of the staging folder and how implementations should handle it in their test262 interpreters.
Also adds a note about the `test/intl402/` folder since there wasn't one previously.
Closes: #3649
=> Document staging folder

test/annexB/built-ins/RegExp/prototype/compile/duplicate-named-capturing-groups-syntax.js, test/built-ins/RegExp/duplicate-named-capturing-groups-syntax.js, test/built-ins/RegExp/named-groups/duplicate-names.js, test/built-ins/RegExp/prototype/exec/duplicate-named-groups-properties.js, test/built-ins/RegExp/prototype/exec/duplicate-named-indices-groups-properties.js, test/built-ins/String/prototype/match/duplicate-named-groups-properties.js, test/built-ins/String/prototype/match/duplicate-named-indices-groups-properties.js
See #3704. This covers the first and third tables in that issue: syntax tests, and tests covering the functionality of the `.groups` and `.indices.groups` objects.
=> More tests for duplicate named capturing groups

test/built-ins/RegExp/unicode_full_case_folding.js
Adds a test similar to the one in #3697, but in the main tree.
The six code points in this test have an "F" for full case mapping in CaseFolding.txt, and so they should not be considered in the Canonicalize operation.
Current versions of SpiderMonkey and V8 fail this test, others pass.
=> Unicode case-folding tests

test/built-ins/BigInt/asIntN/arithmetic.js, test/built-ins/BigInt/asIntN/asIntN.js, test/built-ins/BigInt/asIntN/bigint-tobigint-errors.js, test/built-ins/BigInt/asIntN/bigint-tobigint-toprimitive.js, test/built-ins/BigInt/asIntN/bigint-tobigint-wrapped-values.js, test/built-ins/BigInt/asIntN/bigint-tobigint.js, test/built-ins/BigInt/asIntN/bits-toindex-errors.js, test/built-ins/BigInt/asIntN/bits-toindex-toprimitive.js, test/built-ins/BigInt/asIntN/bits-toindex-wrapped-values.js, test/built-ins/BigInt/asIntN/bits-toindex.js, test/built-ins/BigInt/asIntN/length.js, test/built-ins/BigInt/asIntN/name.js, test/built-ins/BigInt/asIntN/order-of-steps.js, test/built-ins/BigInt/asUintN/arithmetic.js, test/built-ins/BigInt/asUintN/asUintN.js, test/built-ins/BigInt/asUintN/bigint-tobigint-errors.js, test/built-ins/BigInt/asUintN/bigint-tobigint-toprimitive.js, test/built-ins/BigInt/asUintN/bigint-tobigint-wrapped-values.js, test/built-ins/BigInt/asUintN/bigint-tobigint.js, test/built-ins/BigInt/asUintN/bits-toindex-errors.js, test/built-ins/BigInt/asUintN/bits-toindex-toprimitive.js, test/built-ins/BigInt/asUintN/bits-toindex-wrapped-values.js, test/built-ins/BigInt/asUintN/bits-toindex.js, test/built-ins/BigInt/asUintN/length.js, test/built-ins/BigInt/asUintN/name.js, test/built-ins/BigInt/asUintN/order-of-steps.js
=> Fix some esids.

.github/workflows/esmeta-test262.yml
Hi, this PR contains changes that integrate ESMeta's feature to test test262 changes. This PR heavily borrows from changes made at https://github.com/tc39/ecma262/pull/2926, which integrates ESMeta's type checker into ecma262's CI.
ESMeta is able to derive an interpreter from ECMAScript spec and execute JavaScript with it. With this change, we can confirm new or modified test files behave according to ECMAScript spec.
I could not test the changes by actually running CircleCI pipeline as that was not simply possible, but instead tested with local CircleCI cli. 
As I am not very experienced with both test262 and CircleCI, if there are any deficiencies please let me know. Thanks in advance.
cc @jhnaldo
=> CI: Integrate ESMeta

.circleci/config.yml
The Python 2 and 3 jobs run essentially the same thing twice. I asked for a sign from implementations if any of them were relying on Python 2 for their test262 runners, but didn't hear of any that were.
The Python tools are changed so rarely that I think it's OK to drop this CI job. If a future change breaks Python 2 for someone, we can accept PRs to fix it on a best-effort basis, or reinstate this CI job if it's really necessary.
Closes: #3480
=> Remove Python 2 CI job

test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-string-date-with-utc-offset.js, test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-string-time-zone-annotation.js
This reconciles changes made in two normative PRs to the Temporal proposal which each had their own separate PRs for tests. The yearOfWeek tests were written before the changes to the ISO 8601 grammar which disallowed the YYYY-MM-DD+UU format. This brings the yearOfWeek tests in line with the tests for the other calendar methods.
See: #3696, #3699
=> Temporal: Reconcile yearOfWeek tests with changes to YYYY-MM-DD+UU fmt

features.txt, test/built-ins/String/prototype/isWellFormed/length.js, test/built-ins/String/prototype/isWellFormed/name.js, test/built-ins/String/prototype/isWellFormed/not-a-constructor.js, test/built-ins/String/prototype/isWellFormed/prop-desc.js, test/built-ins/String/prototype/isWellFormed/return-abrupt-from-this.js, test/built-ins/String/prototype/isWellFormed/returns-boolean.js, test/built-ins/String/prototype/isWellFormed/to-string.js, test/built-ins/String/prototype/toWellFormed/length.js, test/built-ins/String/prototype/toWellFormed/name.js, test/built-ins/String/prototype/toWellFormed/not-a-constructor.js, test/built-ins/String/prototype/toWellFormed/prop-desc.js, test/built-ins/String/prototype/toWellFormed/return-abrupt-from-this.js, test/built-ins/String/prototype/toWellFormed/returns-well-formed-string.js, test/built-ins/String/prototype/toWellFormed/to-string.js
Tests for the stage 2 proposal https://github.com/tc39/proposal-is-usv-string.
=> `String.prototype.isWellFormed`/`String.prototype.toWellFormed`: add tests

CONTRIBUTING.md
In recent tests, I usually see a blank line after the copyright notice and `esid` as the first frontmatter key.
=> Update test case style to match current patterns

test/built-ins/Array/prototype/toLocaleString/invoke-element-tolocalestring.js, test/intl402/Array/prototype/toLocaleString/invoke-element-tolocalestring.js
Several implementations get this method wrong, including [V8](https://bugs.chromium.org/p/v8/issues/detail?id=13564) and [GraalJS](https://github.com/oracle/graal/issues/5562).
```sh
$ npm run test:diff:v8
> test262@5.0.0 test:diff:v8
> test262-harness -t 8 --hostType=d8 --hostPath=v8 $(npm run --silent diff)
FAIL test/intl402/Array/prototype/toLocaleString/invoke-element-tolocalestring.js (strict mode)
must invoke element toLocaleString with two arguments when provided no arguments Expected SameValue(«0», «2») to be true
FAIL test/intl402/Array/prototype/toLocaleString/invoke-element-tolocalestring.js (default)
must invoke element toLocaleString with two arguments when provided no arguments Expected SameValue(«0», «2») to be true
Ran 2 tests
0 passed
2 failed
```
=> Intl: Add substantive tests for Array.prototype.toLocaleString

test/intl402/Temporal/PlainDateTime/prototype/toLocaleString/resolved-time-zone.js, test/intl402/Temporal/PlainTime/prototype/toLocaleString/resolved-time-zone.js
Node 19 includes an update to ICU that broke two Temporal tests. This PR changes those tests to use more Node-version-agnostic formats.
=> Fix Temporal test failures under Node 19

test/intl402/NumberFormat/constructor-roundingIncrement.js
The order of evaluation for "notation" and "roundingIncrement" changed
in https://github.com/tc39/proposal-intl-numberformat-v3/commit/a260aa3.
=> Update Intl.NumberFormat test with recent reorder of option evaluation

harness/isConstructor.js, test/built-ins/Promise/prototype/finally/rejected-observable-then-calls-argument.js, test/harness/isConstructor.js
Prior to this commit, the `isConstructor` harness function would return `false` when invoked with a value that lacked a [[Call]] internal method. While it's true that such values are not constructors, there are no tests which intentionally use `isConstructor` to make such an assertion.
Extend `isConstructor` to throw an error when invoked with a non-function object.
---
After [suggesting](https://github.com/tc39/test262/pull/3747#pullrequestreview-1212093083) to @ptomato to explicitly verify the "callable" nature of a value in a new test, I couldn't think of any reason one would want to use `isConstructor` on a non-function value. And although the test code for the utility very explicitly supports the current behavior, the test description indicates that such input should be considered …
=> Reject exceptional input to `isConstructor`

harness/isConstructor.js, test/built-ins/Array/fromAsync/builtin.js, test/built-ins/Array/fromAsync/length.js, test/built-ins/Array/fromAsync/name.js, test/built-ins/Array/fromAsync/not-a-constructor.js, test/built-ins/Array/fromAsync/prop-desc.js
Here are some of the standard tests for property metadata of the Array.fromAsync property and for the built-in function object. These don't require doing anything asynchronously, so can be considered separately from the Async Helpers RFC.
See: #3725
=> Array.fromAsync: Boilerplate tests

test/staging/Intl402/Temporal/old/date-time-format.js, test/staging/Intl402/Temporal/old/date-toLocaleString.js, test/staging/Intl402/Temporal/old/datetime-toLocaleString.js, test/staging/Intl402/Temporal/old/instant-toLocaleString.js, test/staging/Intl402/Temporal/old/monthday-toLocaleString.js, test/staging/Intl402/Temporal/old/time-toLocaleString.js, test/staging/Intl402/Temporal/old/yearmonth-toLocaleString.js, test/staging/Intl402/Temporal/old/zoneddatetime-toLocaleString.js
Following up from #3750, this PR supports running Temporal "staging" tests (https://github.com/tc39/test262/tree/main/test/staging) under Node 19.
For context, `Intl.DateTimeFormat` implementations in Node 19 have ICU format changes:
- replace some spaces with non-breaking-space unicode characters
- change German date separators (these may be bugs)
- months in German are shown with a leading zero, but only in Year/Month formats (also may be a bug)
This PR makes affected tests more resilient to `Intl.DateTimeFormat` output changes between Node versions. They'll continue to work even if the behavior (e.g. in German) turns out to be a bug and is fixed in the platform.
=> Support running Temporal tests in Node 19 (cont'd for staging tests)

test/intl402/DateTimeFormat/constructor-no-instanceof.js, test/intl402/DateTimeFormat/prototype/format/no-instanceof.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/no-instanceof.js, test/intl402/NumberFormat/constructor-no-instanceof.js, test/intl402/NumberFormat/prototype/format/no-instanceof.js, test/intl402/NumberFormat/prototype/resolvedOptions/no-instanceof.js
This ensures that the `OrdinaryHasInstance` is actually reached in the test. It also fixes some issues with the preamble.
=> Improve NumberFormat and DateTimeFormat tests for OrdinaryHasInstance

harness/temporalHelpers.js, test/built-ins/Temporal/Duration/prototype/add/nanoseconds-to-days-loop-indefinitely-1.js, test/built-ins/Temporal/Duration/prototype/add/nanoseconds-to-days-loop-indefinitely-2.js, test/built-ins/Temporal/Duration/prototype/subtract/nanoseconds-to-days-loop-indefinitely-1.js, test/built-ins/Temporal/Duration/prototype/subtract/nanoseconds-to-days-loop-indefinitely-2.js, test/built-ins/Temporal/Duration/prototype/total/nanoseconds-to-days-loop-indefinitely-1.js, test/built-ins/Temporal/Duration/prototype/total/nanoseconds-to-days-loop-indefinitely-2.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/nanoseconds-to-days-loop-indefinitely-1.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/nanoseconds-to-days-loop-indefinitely-2.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/nanoseconds-to-days-loop-indefinitely-1.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/nanoseconds-to-days-loop-indefinitely-2.js
Extends previous coverage developed by @anba to all other callers that can reach NanosecondsToDays with a user-provided `relativeTo` and can therefore trigger the indefinite-length loops; refactors @anba's code for the original loops to try to emphasize a few things - though perhaps at the expense of making some other values/interactions less clear, feedback welcome please!
Loop 1:
1) The loop is of arbitrary but constrained length), and only one call to `relativeTo.calendar.dateUntil` determines the length of the loop.
2) The loop will call several observable methods ^ # of times
3) Show that the loop occurs the user-provided number of times for different values
Loop 2:
1) The loop is infinite, and can continue as long as `relativeTo.timeZone.getPossibleInstantsFor` returns values that …
=> Temporal operation NanosecondsToDays: Test infinite or arbitrary-length observable loops in Duration and ZonedDateTime

test/intl402/DateTimeFormat/prototype/format/temporal-objects-resolved-time-zone.js, test/intl402/DateTimeFormat/prototype/formatRange/temporal-objects-resolved-time-zone.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-objects-resolved-time-zone.js, test/intl402/DateTimeFormat/prototype/formatToParts/temporal-objects-resolved-time-zone.js
Fixes 4 more Temporal-related tests that break in ICU 72 / CLDR 42.
Follows up on https://github.com/tc39/test262/pull/3676#issuecomment-1302685505 and #3751.
=> Fix more 402 Temporal tests broken by ICU72/CLDR42

test/intl402/DateTimeFormat/prototype/format/timedatestyle-en.js, test/intl402/DateTimeFormat/prototype/formatRange/en-US.js, test/intl402/DateTimeFormat/prototype/formatRange/fractionalSecondDigits.js, test/intl402/DateTimeFormat/prototype/formatRange/temporal-objects-resolved-time-zone.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/en-US.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/fractionalSecondDigits.js
Following up on #3751 and #3762, this commit makes a few tests work on both CLDR 42 and CLDR 41. Previously these tests were tied to a specific CLDR 42 format.
=> Final batch of CLDR backwards-compatibility fixes

features.txt, test/built-ins/ArrayBuffer/prototype/transfer/descriptor.js, test/built-ins/ArrayBuffer/prototype/transfer/extensible.js, test/built-ins/ArrayBuffer/prototype/transfer/from-fixed-to-larger.js, test/built-ins/ArrayBuffer/prototype/transfer/from-fixed-to-same.js, test/built-ins/ArrayBuffer/prototype/transfer/from-fixed-to-smaller.js, test/built-ins/ArrayBuffer/prototype/transfer/from-fixed-to-zero.js, test/built-ins/ArrayBuffer/prototype/transfer/from-resizable-to-larger.js, test/built-ins/ArrayBuffer/prototype/transfer/from-resizable-to-same.js, test/built-ins/ArrayBuffer/prototype/transfer/from-resizable-to-smaller.js, test/built-ins/ArrayBuffer/prototype/transfer/from-resizable-to-zero.js, test/built-ins/ArrayBuffer/prototype/transfer/length.js, test/built-ins/ArrayBuffer/prototype/transfer/name.js, test/built-ins/ArrayBuffer/prototype/transfer/new-length-excessive.js, test/built-ins/ArrayBuffer/prototype/transfer/new-length-non-number.js, test/built-ins/ArrayBuffer/prototype/transfer/nonconstructor.js, test/built-ins/ArrayBuffer/prototype/transfer/this-is-detached.js, test/built-ins/ArrayBuffer/prototype/transfer/this-is-not-arraybuffer-object.js
This PR updates the existing transfer tests as well as add a new feature flag for it, since the proposal was split from resizable buffers.
=> Update ArrayBuffer.prototype.transfer tests

test/built-ins/Array/prototype/findLast/maximum-index.js, test/built-ins/Array/prototype/findLastIndex/maximum-index.js
* [Array.prototype.findLast](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.findlast)
* [Array.prototype.findLastIndex](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.findlastindex)
TypedArray methods are excluded because their brand-checking inherently prevents this kind of trickery.
=> Test Array.prototype.findLast* length clamping

test/intl402/DateTimeFormat/prototype/format/proleptic-gregorian-calendar.js
Ref https://github.com/tc39/ecma402/issues/723
=> Update DateTimeFormat proleptic Gregorian testing to include era

test/built-ins/Temporal/PlainDate/prototype/with/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/with/order-of-operations.js, test/built-ins/Temporal/PlainMonthDay/prototype/with/order-of-operations.js, test/built-ins/Temporal/PlainTime/prototype/with/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/until/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/with/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/with/copies-merge-fields-object.js, test/built-ins/Temporal/ZonedDateTime/prototype/with/order-of-operations.js
The with() methods, as well as PlainYearMonth's since() and until(), were adjusted to read the receiver's fields before the fields of any objects provided as arguments. This change is observable, so affects several tests that test the observed order of operations.
Normative PR: https://github.com/tc39/proposal-temporal/pull/2478
=> Temporal: Adjustments to order-of-operations tests

test/built-ins/ArrayBuffer/prototype/transfer/from-resizable-to-larger.js, test/built-ins/ArrayBuffer/prototype/transfer/from-resizable-to-same.js, test/built-ins/ArrayBuffer/prototype/transfer/from-resizable-to-smaller.js, test/built-ins/ArrayBuffer/prototype/transfer/from-resizable-to-zero.js
My bad, I missed this last time.
=> Fix ArrayBuffer#transfer tests to preserve maxByteLength

test/intl402/NumberFormat/constructor-roundingIncrement.js
The order in which these options are read was changed in commit: https://github.com/tc39/proposal-intl-numberformat-v3/commit/29acfc6c3fc9f9183f83ef49e74da747134d63c8
=> Swap call order of NumberFormat's notation and roundingIncrement options

test/intl402/NumberFormat/prototype/formatRangeToParts/en-US.js
Summary:
Add test for FormatApproximately source in formatRangeToParts
Closes https://github.com/tc39/test262/issues/3764
=> Add test to approximately format

harness/temporalHelpers.js
These functions are currently pushing values into `actual` arrays that just happen to be defined in the test and end up in the global scope (e.g. https://github.com/tc39/test262/blob/780b7b806eb6c73122f82ec8dbbe7f74bb7475bf/test/built-ins/Temporal/PlainYearMonth/prototype/add/order-of-operations.js#L77). Other pieces of the observers push their recorded calls into the `calls` array, and in all current cases this array is the same as the previous `actual` array.
=> Push into calls array in calendar and timeZone observers.

test/built-ins/Temporal/Calendar/prototype/mergeFields/arguments-not-object.js, test/built-ins/Temporal/Calendar/prototype/mergeFields/order-of-operations.js, test/intl402/Temporal/Calendar/prototype/mergeFields/gregorian-mutually-exclusive-fields.js, test/intl402/Temporal/Calendar/prototype/mergeFields/japanese-mutually-exclusive-fields.js, test/intl402/Temporal/PlainDate/prototype/with/cross-era-boundary.js, test/staging/Intl402/Temporal/old/japanese-era.js
In https://github.com/tc39/proposal-temporal/pull/2474, which achieved consensus at the TC39 plenary meeting of 2023-01-31, the implementation- defined steps for Temporal.Calendar.prototype.mergeFields had their language tightened, to better specify what implementations must do.
This adds tests covering the new spec language, and moves one related test out of staging.
=> Temporal: Tests for calendar-specific mergeFields

test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/reference-year-1972.js, test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/reference-day.js, test/intl402/Temporal/Calendar/prototype/monthDayFromFields/reference-year-1972.js, test/intl402/Temporal/Calendar/prototype/yearMonthFromFields/reference-day.js, test/staging/Intl402/Temporal/old/hebrew-leap-months.js
Tests for the process of calculating the reference ISO day for Temporal.PlainYearMonth and the reference ISO year for Temporal.PlainMonthDay.
Normative PR: https://github.com/tc39/proposal-temporal/pull/2475
=> Temporal: Tests for reference ISO dates

harness/temporalHelpers.js, test/built-ins/Array/fromAsync/mapfn-async-arraylike.js, test/built-ins/Array/fromAsync/mapfn-async-iterable-async.js, test/built-ins/Array/fromAsync/mapfn-async-iterable-sync.js, test/built-ins/Array/fromAsync/mapfn-async-throws-close-async-iterator.js, test/built-ins/Array/fromAsync/mapfn-async-throws-close-sync-iterator.js, test/built-ins/Array/fromAsync/mapfn-async-throws.js, test/built-ins/Array/fromAsync/mapfn-not-callable.js, test/built-ins/Array/fromAsync/mapfn-result-awaited-once-per-iteration.js, test/built-ins/Array/fromAsync/mapfn-sync-arraylike.js, test/built-ins/Array/fromAsync/mapfn-sync-iterable-async.js, test/built-ins/Array/fromAsync/mapfn-sync-iterable-sync.js, test/built-ins/Array/fromAsync/mapfn-sync-throws-close-async-iterator.js, test/built-ins/Array/fromAsync/mapfn-sync-throws-close-sync-iterator.js, test/built-ins/Array/fromAsync/mapfn-sync-throws.js, test/built-ins/Array/fromAsync/thisarg-object.js, test/built-ins/Array/fromAsync/thisarg-omitted-sloppy.js, test/built-ins/Array/fromAsync/thisarg-omitted-strict.js, test/built-ins/Array/fromAsync/thisarg-primitive-sloppy.js, test/built-ins/Array/fromAsync/thisarg-primitive-strict.js
- normal case with synchronous and asynchronous mapfn
- a non-callable value is passed as mapfn
- behaviour of various values of thisArg in strict and sloppy mode
- mapfn result is awaited once per iteration
- iterator is closed when mapfn throws
See #3725
=> Tests for mapfn and thisArg arguments to Array.fromAsync

test/intl402/Temporal/Calendar/prototype/dateUntil/until-across-lunisolar-leap-months.js, test/intl402/Temporal/Calendar/prototype/dateUntil/zero-length-duration-result.js
This PR adds tests to validate fixes to two bugs in Temporal's calculation of durations between two non-ISO calendar dates: 
* An infinite loop (tc39/proposal-temporal#2383) for non-ISO calendars when `Calendar.p.dateUntil` was called to calculate the duration between two identical dates. This test validates that `PT0S` is returned in that case.
* A math bug in `Calendar.p.dateUntil` (https://github.com/tc39/proposal-temporal/issues/2537) where non-ISO calendars would unexpectedly throw when calculating the number of years between two dates where the year were different, the month codes were different, but the months were the same because the earlier date's month was after a leap month. This test validates that expected values are returned for all units in this scenario.
=> Fill test holes in Temporal's non-ISO calendar `dateUntil` math

test/built-ins/Array/fromAsync/asyncitems-arraylike-holes.js, test/built-ins/Array/fromAsync/asyncitems-arraylike-length-accessor-throws.js, test/built-ins/Array/fromAsync/asyncitems-arraylike-too-long.js, test/built-ins/Array/fromAsync/asyncitems-object-not-arraylike.js, test/built-ins/Array/fromAsync/asyncitems-uses-intrinsic-iterator-symbols.js, test/built-ins/Array/fromAsync/returned-promise-resolves-to-array.js, test/built-ins/Array/fromAsync/returns-promise.js, test/built-ins/Array/fromAsync/this-constructor-operations.js, test/built-ins/Array/fromAsync/this-constructor-with-bad-length-setter.js, test/built-ins/Array/fromAsync/this-constructor-with-readonly-elements.js, test/built-ins/Array/fromAsync/this-constructor-with-readonly-length.js, test/built-ins/Array/fromAsync/this-constructor-with-unsettable-element-closes-async-iterator.js, test/built-ins/Array/fromAsync/this-constructor-with-unsettable-element-closes-sync-iterator.js, test/built-ins/Array/fromAsync/this-constructor-with-unsettable-element.js, test/built-ins/Array/fromAsync/this-constructor.js, test/built-ins/Array/fromAsync/this-non-constructor.js
This contains a few more tests for Array.fromAsync, in addition to what has already been merged and what is under review at #3791.
This covers the following items from the testing plan at #3725:
- Success cases
- Creates promise
- Create new array/arraylike in promise (with length = length property)
- Input
- Invalid input values - nonconforming object (arraylike without length, missing keys)
- Covered by polyfill tests
- Result promise rejects if length access fails (non-iterable input)
- Unaffected by globalThis.Symbol mutation (non-iterable)
- this-value
- this-value is a constructor
- this-value is not a constructor
- If this is a constructor, and items doesn't have a Symbol.iterator, returns a new instance of this
- Iterator closed when property creation on this fails
- Returned …
=> Array.fromAsync various remaining coverage

test/built-ins/Temporal/Instant/prototype/epochMicroseconds/basic.js, test/built-ins/Temporal/Instant/prototype/epochMilliseconds/basic.js, test/built-ins/Temporal/Instant/prototype/epochSeconds/basic.js, test/built-ins/Temporal/ZonedDateTime/prototype/epochMicroseconds/basic.js, test/built-ins/Temporal/ZonedDateTime/prototype/epochMilliseconds/basic.js, test/built-ins/Temporal/ZonedDateTime/prototype/epochSeconds/basic.js
Update tests to match <https://github.com/tc39/proposal-temporal/pull/2424>.
=> Round epoch time getters towards negative infinity

test/built-ins/Temporal/Duration/prototype/round/calendar-dateadd-called-with-options-undefined.js, test/built-ins/Temporal/Duration/prototype/round/calendar-dateuntil-called-with-singular-largestunit.js, test/built-ins/Temporal/Duration/prototype/round/largestunit-correct-rebalancing.js, test/built-ins/Temporal/Duration/prototype/round/timezone-getpossibleinstantsfor-iterable.js, test/intl402/Temporal/Duration/prototype/round/relativeto-string-datetime.js
This is meant to be applied after tc39/proposal-temporal#2517 is landed.
=> Temporal: reflect changes to fix tc39/proposal-temporal#2508

test/intl402/Temporal/PlainMonthDay/from/reference-date-noniso-calendar.js
Adds test for normative PR : https://github.com/tc39/proposal-temporal/pull/2460
This pull request was approved in March Plenary.
=> Temporal: Add test for non-iso calendars for Temporal.PlainMonthDay.from

harness/temporalHelpers.js, test/built-ins/Array/fromAsync/asyncitems-arraylike-promise.js, test/built-ins/Temporal/Calendar/prototype/mergeFields/order-of-operations.js, test/built-ins/Temporal/Duration/compare/order-of-operations.js, test/built-ins/Temporal/Duration/prototype/round/order-of-operations.js, test/built-ins/Temporal/Duration/prototype/round/relativeto-zoneddatetime-nanoseconds-to-days-range-errors.js, test/built-ins/Temporal/Duration/prototype/total/order-of-operations.js, test/built-ins/Temporal/Duration/prototype/total/relativeto-zoneddatetime-nanoseconds-to-days-range-errors.js, test/built-ins/Temporal/PlainDateTime/prototype/with/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/getISOFields/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/round/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/order-of-operations.js
- Fix a leftover from debugging
- Improve comments and assertion messages
- Improve printing of property names in observer helpers
- Improve coverage of order-of-operations tests in preparation for tc39/proposal-temporal#2519
=> Improvements to Temporal tests

harness/regExpUtils.js
`printCodePoint` already adds the `U+` to the output, and we shouldn’t add it again.
=> Avoid excessive `U+` in error messages

test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-01.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-02.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-03.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-04.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-05.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-06.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-07.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-08.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-09.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-10.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-11.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-12.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-13.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-14.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-15.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-16.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-17.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-18.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-19.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-20.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-21.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-22.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-23.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-24.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-25.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-26.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-27.js, test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-28.js
https://github.com/tc39/proposal-regexp-v-flag#how-is-the-v-flag-different-from-the-u-flag
Issue: #3496
Issue: https://github.com/tc39/proposal-regexp-v-flag/issues/52
=> Add tests for RegExp `v` flag errors that were allowed with `u`

test/language/expressions/postfix-decrement/this.js, test/language/expressions/postfix-increment/this.js, test/language/expressions/prefix-decrement/this.js, test/language/expressions/prefix-increment/this.js
This PR adds tests to check if postfix and prefix increment and decrement operations on `this` throws a syntax error as mentioned in [spec](https://tc39.es/ecma262/#sec-update-expressions-static-semantics-early-errors). 
We found that test262 does not test this case when fixing [related bug](https://github.com/boa-dev/boa/pull/2507#pullrequestreview-1230300104) in Boa.
P.S: First time contributing here. ~~Please let me know how to fix the frontmatter~~.
=> Test for postfix and prefix increment and decrement operations on `this`

test/intl402/Locale/constructor-non-iana-canon.js, test/intl402/Locale/prototype/minimize/removing-likely-subtags-first-adds-likely-subtags.js
intl402/Locale/constructor-non-iana-canon.js
- Likely subtags entry for "hyw" -> "hyw-Armn-AM" was added to supplemental/likelySubtags.xml
intl402/Locale/prototype/minimize/removing-likely-subtags-first-adds-likely-subtags.js
- Likely subtags entry for "aae" -> "aae-Latn-IT" was added to supplemental/likelySubtags.xml
- Likely subtags entry for "pap" was changed from "pap_Latn_AW" to "pap_Latn_CW"
=> Update expected test results for CLDR 43

harness/temporalHelpers.js
Using `\p{ID_Start}` and `\p{ID_Continue}` to match JS identifiers was not supported everywhere. Let's assume that we only want to format ASCII identifiers as bare property names. (This doesn't change any tests, just the formatting of property names in lists of user-observable actions. No tests currently checked for non-ASCII properties.)
Closes: #3841
=> Temporal helpers: format only ASCII identifiers specially

test/language/module-code/instn-iee-err-ambiguous-as.js, test/language/module-code/instn-iee-err-ambiguous.js, test/language/module-code/instn-iee-err-circular-as.js, test/language/module-code/instn-iee-err-circular.js, test/language/module-code/instn-iee-err-dflt-thru-star-as.js, test/language/module-code/instn-iee-err-dflt-thru-star.js, test/language/module-code/instn-iee-err-not-found-as.js, test/language/module-code/instn-iee-err-not-found.js, test/language/module-code/instn-named-err-ambiguous-as.js, test/language/module-code/instn-named-err-ambiguous.js, test/language/module-code/instn-named-err-dflt-thru-star-as.js, test/language/module-code/instn-named-err-dflt-thru-star-dflt.js, test/language/module-code/instn-named-err-not-found-as.js, test/language/module-code/instn-named-err-not-found-dflt.js, test/language/module-code/instn-named-err-not-found.js, test/language/module-code/instn-star-err-not-found.js
A couple of negative tests had an incorrect phase tagged, since their errors happen at linking time, which is part of the "resolution" phase. However, they were marked as happening at runtime.
This PR fixes those tests and additionally adds a `$DONOTEVALUATE` marker to them.
=> Fix phase on some negative module tests

test/staging/Intl402/Temporal/old/japanese-era.js, test/staging/Intl402/Temporal/old/non-iso-calendars.js
These tests accompany a Temporal PR that works around a bug in ICU 73.1 (which ships with Node 20). These test changes enable tests to pass in both the buggy state and after the bug is eventually fixed.
=> Work around Node 20 / ICU 73.1 calendar bug

harness/sta.js
All functions in `assert.js` and `sta.js` (which are the two files required for every test) are already regular functions, except this one.
=> Replace arrow function with regular function in harness/sta.js

.circleci/config.yml
This is broken again. I don't think we should have this in CI unless it's going to keep working.
=> Remove GraalJS from CI

test/language/expressions/prefix-decrement/this.js
I'm not sure if YAML disallows it, but test262 avoids it.
=> Delete trailing space after `|`

test/built-ins/Temporal/PlainDate/prototype/toPlainDateTime/argument-string-with-utc-designator.js, test/built-ins/Temporal/PlainDate/prototype/toZonedDateTime/argument-string-with-utc-designator.js, test/built-ins/Temporal/PlainDateTime/prototype/withPlainTime/argument-string-with-utc-designator.js, test/built-ins/Temporal/PlainTime/compare/argument-string-with-utc-designator.js, test/built-ins/Temporal/PlainTime/from/argument-string-with-utc-designator.js, test/built-ins/Temporal/PlainTime/prototype/equals/argument-string-with-utc-designator.js, test/built-ins/Temporal/PlainTime/prototype/since/argument-string-with-utc-designator.js, test/built-ins/Temporal/PlainTime/prototype/until/argument-string-with-utc-designator.js, test/built-ins/Temporal/ZonedDateTime/prototype/withPlainTime/argument-string-with-utc-designator.js
Codecov showed that PlainTime strings like "09:00:00Z[UTC]" or "09:00:00Z" were not being tested. This commit fills that gap.
It'd probably be good to make similar changes for other Plain* types, but Codecov didn't complain about them so they may be covered via other tests so it was less urgent.
=> Test Temporal.PlainTime parsing without full ISO strings

test/intl402/DateTimeFormat/constructor-options-order-dayPeriod.js, test/intl402/DateTimeFormat/constructor-options-order-fractionalSecondDigits.js, test/intl402/DateTimeFormat/constructor-options-order-timedate-style.js, test/intl402/DateTimeFormat/constructor-options-order.js
Update tests for PR tc39/ecma402#709.
=> Update tests for PR "Read date-time options only once when creating DateTimeFormat objects"

test/intl402/DateTimeFormat/constructor-options-invalid-explicit-components.js
Verifies that Intl.DateTimeFormat constructor throws a `TypeError` whenever the options bag defines explicit format components and also either of `dateStyle` and `timeStyle`.
=> created test for invalid Intl.DateTimeFormat options when dateStyle/timeStyle set

test/built-ins/Temporal/Duration/compare/relativeto-propertybag-timezone-string-datetime.js, test/built-ins/Temporal/Duration/prototype/add/relativeto-propertybag-timezone-string-datetime.js, test/built-ins/Temporal/Duration/prototype/round/relativeto-propertybag-timezone-string-datetime.js, test/built-ins/Temporal/Duration/prototype/subtract/relativeto-propertybag-timezone-string-datetime.js, test/built-ins/Temporal/Duration/prototype/total/relativeto-propertybag-timezone-string-datetime.js, test/built-ins/Temporal/Instant/prototype/toString/timezone-string-datetime.js, test/built-ins/Temporal/Instant/prototype/toZonedDateTime/timezone-string-datetime.js, test/built-ins/Temporal/Instant/prototype/toZonedDateTimeISO/timezone-string-datetime.js, test/built-ins/Temporal/Now/plainDate/timezone-string-datetime.js, test/built-ins/Temporal/Now/plainDateISO/timezone-string-datetime.js, test/built-ins/Temporal/Now/plainDateTime/timezone-string-datetime.js, test/built-ins/Temporal/Now/plainDateTimeISO/timezone-string-datetime.js, test/built-ins/Temporal/Now/plainTimeISO/timezone-string-datetime.js, test/built-ins/Temporal/Now/zonedDateTime/timezone-string-datetime.js, test/built-ins/Temporal/Now/zonedDateTimeISO/timezone-string-datetime.js, test/built-ins/Temporal/PlainDate/prototype/toZonedDateTime/timezone-string-datetime.js, test/built-ins/Temporal/PlainDateTime/prototype/toZonedDateTime/timezone-string-datetime.js, test/built-ins/Temporal/PlainTime/prototype/toZonedDateTime/timezone-string-datetime.js, test/built-ins/Temporal/TimeZone/from/timezone-string-datetime.js, test/built-ins/Temporal/ZonedDateTime/compare/argument-propertybag-timezone-string-datetime.js, test/built-ins/Temporal/ZonedDateTime/from/argument-propertybag-timezone-string-datetime.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/argument-propertybag-timezone-string-datetime.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/argument-propertybag-timezone-string-datetime.js, test/built-ins/Temporal/ZonedDateTime/prototype/withTimeZone/timezone-string-datetime.js, test/built-ins/Temporal/ZonedDateTime/timezone-string-datetime.js, test/intl402/Temporal/Now/plainDateTimeISO/timezone-string-datetime.js, test/staging/Temporal/Regex/old/timezone.js
This PR verifies that ISO strings with sub-minute offsets cannot be parsed into time zone identifiers. This was a change introduced in the recently-merged tc39/proposal-temporal#2607, but tests for this case were missing from #3862 (the tests for that PR).
I noticed in codecov results on an unrelated PR that this case wasn't being tested, so fixing that mistake now.
=> Temporal: Test rejecting ISO strings with subminute offsets

test/intl402/DisplayNames/prototype/of/type-language-valid.js
Previously there was no test coverage for this function in cases where `type` is 'language', i.e. ` new Intl.DisplayNames(undefined, {type: 'language'}).of('en');`
Related to #3840
=> Added tests for structurally valid language tags in DisplayNames.prototype.of()

test/intl402/DurationFormat/prototype/format/style-digital-en.js
ECMA-402 does not require specific CLDR format, and each platform has some customization for their platform consistency.
macOS system ICU is shipping new CLDR, but it has many overrides on the top of it to make the formatted output suitable for the system.
This change modifies the test to accept that alternative output from AppleICU.
=> Add different formatting for test/intl402/DurationFormat/prototype/format/style-digital-en.js

test/built-ins/RegExp/lookahead-quantifier-match-groups.js
This behavior is pretty subtle, and apparently JSC's two regexp engines are inconsistent here. So it seems worth testing.
=> add test for regexp matching with zero-length quantified matches

test/built-ins/Iterator/prototype/reduce/iterator-already-exhausted-no-initial-value.js, test/built-ins/Iterator/prototype/reduce/non-callable-reducer.js
These were the only 2 iterator helper tests that were passing even in implementations that had not yet added support for iterator helpers.
=> update iterator helpers tests that passed even in noncompliant impls

test/built-ins/ArrayBuffer/prototype/resize/nonconstructor.js, test/built-ins/ArrayBuffer/prototype/slice/nonconstructor.js, test/built-ins/ArrayBuffer/prototype/transfer/nonconstructor.js, test/built-ins/ArrayBuffer/prototype/transferToFixedLength/nonconstructor.js, test/built-ins/SharedArrayBuffer/prototype/grow/nonconstructor.js, test/built-ins/SharedArrayBuffer/prototype/slice/nonconstructor.js
This also allows these tests to be filtered out by "features".
=> use proper isConstructor check for recently added ArrayBuffer/SharedArrayBuffer tests

tools/lint/lint.py, tools/lint/requirements.txt
Allow to lint files even when the "inflect" module isn't available.
=> Don't require Inflect for linting files

test/intl402/Collator/prototype/compare/ignorePunctuation.js, test/intl402/Collator/prototype/resolvedOptions/ignorePunctuation-not-default.js
Test the explicit setting of ignorePunctuation in the option bag reflect to the value in resolvedOptions() under Thai and other locales. (Thai is a special case)
Test the behavior of the compare sync with the value of resolvedOptions().ignorePunctuation
Spec text
https://tc39.es/ecma402/#sec-initializecollator
https://tc39.es/ecma402/#sec-intl.collator.prototype.resolvedoptions
https://tc39.es/ecma402/#sec-collator-comparestrings
=> Add Collator test for ignorePunctuation

test/language/module-code/import-assertions/ensure-linking-error_FIXTURE.js, test/language/module-code/import-assertions/import-assertion-empty.js
- Correct file paths in "ensure-linking-error_FIXTURE.js"
- Remove no longer valid assertion in "import-assertion-empty.js".
See also #3919.
=> Fix import assertions tests

harness/propertyHelper.js, test/harness/verifyProperty-value-error.js
I didn't run the harness tests when working on #3916, which introduced these three bugs:
- `Object.getOwnPropertyNames(desc)` should be called only after verifying `desc` is not `null`.
- I didn't resolve a merge conflict with other local changes properly, which caused `failures.push(failures, ...`.
- And the "verifyProperty-value-error.js" test need to be updated to account for the new failure message.
=> Fix harness tests for verifyProperty

test/intl402/DisplayNames/prototype/of/type-language-invalid.js
Previously no test coverage for cases where {type: 'language'}, created tests for structurally invalid tags. 
fix #3840
=> Added tests for structurally invalid language tags in DisplayNames.prototype.of()

test/intl402/DateTimeFormat/prototype/resolvedOptions/hourCycle-dateStyle.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/hourCycle-default.js
Address https://github.com/tc39/test262/issues/3812 
Fix #3876 
https://github.com/tc39/ecma402/pull/758 changes the `hourCycle` logic in Intl.DateTimeFormat.InitializeDateAndTime() to no longer erroneously assume that `h24` is the 24 hour clock expected in locales using `h11` or `h12` as defaults.
73537444cb14a80f0276453f235951068f41b1b9 and 15792dab3be7758f0be7105f67902698e0865078 update hourCycle-default.js to reflect the new behaviour.
note: I don't believe any engine currently passes all of the tests in the new `hourCycle-default.js`. v8 and node fail because they associate `h12` with `h24`, as was required by the old algorithm, while jsc and spidermonkey fail because they ignore the -u-hc-h24 extension when `hour12` is set to `false`, as below:
```js
// sm and jsc
new …
```
=> updated Intl.DateTimeFormat.prototype.resolvedOptions() tests to reflect recent normative change

test/intl402/DurationFormat/constructor-options-fractionalDigits-valid.js, test/intl402/DurationFormat/prototype/format/style-digital-fractionalDigits-undefined.js, test/intl402/DurationFormat/prototype/format/style-digital-fractionalDigits.js
https://github.com/tc39/proposal-intl-duration-format/issues/144 recently changed the behaviour of Intl.DurationFormat when the number of fractional digits (i.e. sub-second values) is left undefined.  prototype/format/style-digital-fractionalDigits-undefined.js tests for this case, prototype/format/style-digital-fractionalDigits.js provides additional test coverage for fractional digits in general.
=> Update to reflect normative change in formatting when Intl.DurationFormat's fractionalDigits option is undefined

test/intl402/DurationFormat/prototype/format/style-digital-fractionalDigits-undefined.js, test/intl402/DurationFormat/prototype/format/style-digital-fractionalDigits.js
Previously merged 3890  was missing features: line, this corrects that.
=> added missing features: line to metadata for two tests

src/decorator/syntax/class-valid/cls-decl-decorators-valid-syntax.template, src/decorator/syntax/class-valid/cls-expr-decorators-valid-syntax.template, test/language/expressions/class/decorator/syntax/class-valid/decorator-member-expr-private-identifier.js, test/language/statements/class/decorator/syntax/class-valid/decorator-member-expr-private-identifier.js
For the statement level test, the inner class name is not initialized at the time the decorators evaluate, resulting in a ReferenceError that the declaration can not be accessed prior to initialization.
Similar, non-decorator code, like:
class C {
static dec() {}
static {
this.x = C.dec();
class C {}
}
}
also results in a ReferenceError.
For the expression level test, the var C is undefined at the time the decorators are evaluated, resulting in TypeError while trying to access a member of undefined.
Similar, non-decorator code, like:
var C = class {
static f() {};
static {
this.x = C.f();
}
}
also results in a TypeError.
=> Fixup class names in class decorator private identifier tests.

tools/lint/lint.py
CheckFileName is the only one that could arguably be valid for other files, but it doesn't seem worth the complexity to run it.
=> Only lint js and json files

features.txt
I didn't move Stage 4 proposal that will be published in ES2024 because the list header explicitly refers to published version of the specification. Let me know if you prefer to move them.
Finished proposals list: https://github.com/tc39/proposals/blob/main/finished-proposals.md
=> Move ES2023 features to "stable" list

test/built-ins/Object/prototype/toString/symbol-tag-generators-builtin.js
Two issues:
1. There was a typo, the first `gen` should have been `genFn`.
2. And the last `toString` result should be `'[object Generator]'`, because `Object.getPrototypeOf(gen) == genFn.prototype`. And the `@@toStringTag` property of `genFn.prototype` is inherited from `Generator.prototype[@@toStringTag]`.
That also means the "iterator-helpers" flag isn't needed for this test.
=> Fix symbol-tag-generators-builtin.js

CODEOWNERS
This came up while working on the V8 test262 2-way sync bot for `staging/`. It is likely that tests added to staging/ will be for a new feature that requires a new entry in `features.txt`, so the staging group should have write access to that file.
cc @rmahdav
=> Allow @tc39-staging to modify features.txt

.circleci/config.yml
The circleci/ images are deprecated and replaced by cimg/. Hopefully this will have a glibc that is new enough for XS's versioned symbols to link against.
Rename 'node_latest' to 'node_image' since the image is the LTS, not the latest. The name would otherwise be confusing.
Closes: #3891
~~[do not merge yet, I'm just opening a PR so that the CI jobs will run]~~ Well what ya know, it worked!
=> CI: Move from deprecated to supported Docker image

test/language/literals/boolean/false-with-unicode.js, test/language/literals/boolean/true-with-unicode.js, test/language/literals/null/null-with-unicode.js
This PR adds tests to check if literals (`true`, `false`, and `null`) containing Unicode escape sequence throws a syntax error as mentioned in NOTE 1 in the [spec](https://tc39.es/ecma262/#sec-keywords-and-reserved-words).
=> Test for Unicode Escape in Literals

test/built-ins/RegExp/unicode_full_case_folding.js
Unicode 15.1 added the following "simple" case-folding entries:
```
1FD3; S; 0390; # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
1FE3; S; 03B0; # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
FB05; S; FB06; # LATIN SMALL LIGATURE LONG S T
```
=> Update case folding tests for Unicode 15.1

test/intl402/Locale/likely-subtags.js, test/intl402/Locale/prototype/minimize/removing-likely-subtags-first-adds-likely-subtags.js
CLDR 44 changed likely-subtags mappings for "und" language tags, so we have to update these two tests.
=> Update likely subtags tests for CLDR 44

test/built-ins/Temporal/Duration/prototype/round/round-cross-unit-boundary.js, test/built-ins/Temporal/Duration/prototype/toString/round-cross-unit-boundary.js, test/built-ins/Temporal/Instant/prototype/since/round-cross-unit-boundary.js, test/built-ins/Temporal/Instant/prototype/until/round-cross-unit-boundary.js, test/built-ins/Temporal/PlainDate/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainDate/prototype/since/round-cross-unit-boundary.js, test/built-ins/Temporal/PlainDate/prototype/until/order-of-operations.js, test/built-ins/Temporal/PlainDate/prototype/until/round-cross-unit-boundary.js, test/built-ins/Temporal/PlainDateTime/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/since/round-cross-unit-boundary.js, test/built-ins/Temporal/PlainDateTime/prototype/until/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/until/round-cross-unit-boundary.js, test/built-ins/Temporal/PlainTime/prototype/since/round-cross-unit-boundary.js, test/built-ins/Temporal/PlainTime/prototype/until/round-cross-unit-boundary.js, test/built-ins/Temporal/PlainYearMonth/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/since/round-cross-unit-boundary.js, test/built-ins/Temporal/PlainYearMonth/prototype/since/roundingincrement-non-integer.js, test/built-ins/Temporal/PlainYearMonth/prototype/until/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/until/round-cross-unit-boundary.js, test/built-ins/Temporal/PlainYearMonth/prototype/until/roundingincrement-non-integer.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/calendar-dateadd-called-with-options-undefined.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/calendar-dateuntil-called-with-singular-largestunit.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/round-cross-unit-boundary.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/calendar-dateadd-called-with-options-undefined.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/calendar-dateuntil-called-with-singular-largestunit.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/round-cross-unit-boundary.js, test/staging/Temporal/Duration/old/toString.js
This PR contains tests that cover normative changes to Temporal that reached consensus in May 2023.
Normative PR: https://github.com/tc39/proposal-temporal/pull/2571
=> Temporal: Tests for balancing units after rounding

test/built-ins/Temporal/Duration/compare/order-of-operations.js, test/built-ins/Temporal/Duration/prototype/add/order-of-operations.js, test/built-ins/Temporal/Duration/prototype/round/order-of-operations.js, test/built-ins/Temporal/Duration/prototype/subtract/order-of-operations.js, test/built-ins/Temporal/Duration/prototype/total/order-of-operations.js, test/built-ins/Temporal/PlainDate/prototype/add/order-of-operations.js, test/built-ins/Temporal/PlainDate/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainDate/prototype/subtract/order-of-operations.js, test/built-ins/Temporal/PlainDate/prototype/toZonedDateTime/order-of-operations.js, test/built-ins/Temporal/PlainDate/prototype/until/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/add/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/subtract/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/toZonedDateTime/order-of-operations.js, test/built-ins/Temporal/PlainDateTime/prototype/toZonedDateTime/plain-custom-timezone.js, test/built-ins/Temporal/PlainDateTime/prototype/until/order-of-operations.js, test/built-ins/Temporal/PlainTime/prototype/toZonedDateTime/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/add/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/since/order-of-operations.js, test/built-ins/Temporal/PlainYearMonth/prototype/until/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/compare/argument-propertybag-ambiguous-wall-clock-time.js, test/built-ins/Temporal/ZonedDateTime/compare/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/from/argument-propertybag-ambiguous-wall-clock-time.js, test/built-ins/Temporal/ZonedDateTime/from/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/equals/argument-propertybag-ambiguous-wall-clock-time.js, test/built-ins/Temporal/ZonedDateTime/prototype/equals/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/argument-propertybag-ambiguous-wall-clock-time.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/order-of-operations.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/argument-propertybag-ambiguous-wall-clock-time.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/order-of-operations.js
These tests cover https://github.com/tc39/proposal-temporal/issues/2724
=> Temporal: Remove conditional lookups

features.txt, test/built-ins/Set/prototype/union/add-not-called.js, test/built-ins/Set/prototype/union/allows-set-like-class.js, test/built-ins/Set/prototype/union/allows-set-like-object.js, test/built-ins/Set/prototype/union/appends-new-values.js, test/built-ins/Set/prototype/union/array-throws.js, test/built-ins/Set/prototype/union/builtins.js, test/built-ins/Set/prototype/union/called-with-object.js, test/built-ins/Set/prototype/union/combines-Map.js, test/built-ins/Set/prototype/union/combines-empty-sets.js, test/built-ins/Set/prototype/union/combines-itself.js, test/built-ins/Set/prototype/union/combines-same-sets.js, test/built-ins/Set/prototype/union/combines-sets.js, test/built-ins/Set/prototype/union/converts-negative-zero.js, test/built-ins/Set/prototype/union/has-is-callable.js, test/built-ins/Set/prototype/union/keys-is-callable.js, test/built-ins/Set/prototype/union/length.js, test/built-ins/Set/prototype/union/name.js, test/built-ins/Set/prototype/union/not-a-constructor.js, test/built-ins/Set/prototype/union/receiver-not-set.js, test/built-ins/Set/prototype/union/require-internal-slot.js, test/built-ins/Set/prototype/union/set-like-array.js, test/built-ins/Set/prototype/union/set-like-class-mutation.js, test/built-ins/Set/prototype/union/set-like-class-order.js, test/built-ins/Set/prototype/union/size-is-a-number.js, test/built-ins/Set/prototype/union/subclass-receiver-methods.js, test/built-ins/Set/prototype/union/subclass-symbol-species.js, test/built-ins/Set/prototype/union/subclass.js, test/built-ins/Set/prototype/union/union-properties.js
After https://github.com/tc39/test262/pull/3816 we accidentally had two "set-methods" features, whoops.
=> Consolidate set methods features

test/language/expressions/postfix-decrement/target-cover-id.js, test/language/expressions/postfix-increment/target-cover-id.js
Currently failing on XS: https://github.com/Moddable-OpenSource/moddable/issues/1256
=> Test for assignment with target wrapped in two sets of parentheses

test/built-ins/Array/length/define-own-prop-length-error.js
Turns out v8 fails this test. Discovered by @Jack-Works / @rkirsling in Matrix.
=> Array length: add test ensuring RangeError is thrown

README.md
Currently it links to a dead page, which is odd.
Let's link to the PR which removed the code, to give the reader some kind of thread to follow.
=> Fixed website section in README

test/built-ins/Set/prototype/difference/subclass-receiver-methods.js
The difference between two sets is `[1]`.
=> Fix an error in expected value of difference set method 

harness/testTypedArray.js, test/built-ins/Atomics/add/bad-range.js, test/built-ins/Atomics/add/good-views.js, test/built-ins/Atomics/and/bad-range.js, test/built-ins/Atomics/and/good-views.js, test/built-ins/Atomics/compareExchange/bad-range.js, test/built-ins/Atomics/compareExchange/good-views.js, test/built-ins/Atomics/exchange/bad-range.js, test/built-ins/Atomics/exchange/good-views.js, test/built-ins/Atomics/load/bad-range.js, test/built-ins/Atomics/load/good-views.js, test/built-ins/Atomics/or/bad-range.js, test/built-ins/Atomics/or/good-views.js, test/built-ins/Atomics/store/bad-range.js, test/built-ins/Atomics/store/good-views.js, test/built-ins/Atomics/sub/bad-range.js, test/built-ins/Atomics/sub/good-views.js, test/built-ins/Atomics/xor/bad-range.js, test/built-ins/Atomics/xor/good-views.js
Per https://github.com/tc39/test262/pull/3849/files/e5d20a7fb8ed1beeeba3eb75c21aed433de164ac#r1447792194, oops.
=> introduce nonClampedIntArrayConstructors

test/staging/Intl402/Temporal/old/islamic-calendars.js, test/staging/Intl402/Temporal/old/persian-calendar.js
Tests the changes in https://github.com/tc39/proposal-temporal/pull/2743.
=> Add 402 staging tests for Islamic and Persian calendars

test/language/module-code/import-attributes/allow-nlt-before-with.js
Hosts are free to throw whatever error they want during module loading: there is no guarantee that the error thrown due to the import with `type: "foo"` is a SyntaxError (it could also be, for example, an `Error` caused by a network failure). Technically this is also true when loading just JS, but not specifying `type` reduces variance and in practice all test262 runners will not fail when loading JS modules that exist :)
=> Do not expect specific error type in `import-attributes/allow-nlt-before-with.js`

test/built-ins/Iterator/prototype/Symbol.toStringTag/prop-desc.js, test/built-ins/Iterator/prototype/Symbol.toStringTag/weird-setter.js, test/built-ins/Iterator/prototype/constructor/prop-desc.js, test/built-ins/Iterator/prototype/constructor/weird-setter.js
Updates tests for these two properties to match https://github.com/tc39/proposal-iterator-helpers/pull/287.
=> update constructor and Symbol.toStringTag properties on Iterator.prototype

harness/temporalHelpers.js
Some improvements to the formatting of assertion messages for the various Temporal types. This should make assertion failures easier to understand.
=> Temporal assertion message formatting

test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-null.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-undefined-get-return-undefined.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-undefined-poisoned-return.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-undefined-return-not-object.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-undefined-return-object.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-undefined.js
This adds tests for the normative changes in https://github.com/tc39/ecma262/pull/2600 for the new steps in ` %AsyncFromSyncIteratorPrototype%.throw`, also modifying two existing tests.
These tests have been tested with this PR of engine262, which implements the normative changes: https://github.com/engine262/engine262/pull/230
Partly fixes #3387
=> Async-from-sync test the iterator closes when .throw() is undefined

test/built-ins/AsyncFromSyncIteratorPrototype/next/iterator-result-poisoned-wrapper.js, test/built-ins/AsyncFromSyncIteratorPrototype/next/next-result-poisoned-wrapper.js, test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-result-poisoned-wrapper.js
These test new steps 6-6.a of AsyncFromSyncIteratorContinuation as per normative changes of ecma626 PR 2600
https://github.com/tc39/ecma262/pull/2600
2nd of 3 patches to fix #3387 
All these tests are based on @jridgewell 's [comment](https://github.com/tc39/ecma262/pull/2600#pullrequestreview-834955515)
=> Test closing async-from-sync iterator when resolving result promise abrupt completes.

test/built-ins/Temporal/PlainDate/prototype/since/wrapping-at-end-of-month.js, test/built-ins/Temporal/PlainDate/prototype/until/largestunit-higher-units.js, test/built-ins/Temporal/PlainDate/prototype/until/wrapping-at-end-of-month.js, test/built-ins/Temporal/PlainDateTime/prototype/since/wrapping-at-end-of-month.js, test/built-ins/Temporal/PlainDateTime/prototype/until/no-unnecessary-units.js, test/built-ins/Temporal/PlainDateTime/prototype/until/wrapping-at-end-of-month.js, test/built-ins/Temporal/ZonedDateTime/prototype/since/wrapping-at-end-of-month.js, test/built-ins/Temporal/ZonedDateTime/prototype/until/wrapping-at-end-of-month.js
This adds tests specifically for every kind of case that changes due to the tweak to the date difference algorithm: differences from a longer month to a shorter month, when the months are adjacent, in the same year but not adjacent, and in different years.
Also adds tests for a case that does *not* change, but would trip on an incorrectly implemented algorithm: when the intermediate months value falls at the end of February.
There was incidental coverage of the change to the date difference algorithm in other tests. Those are adjusted, as well.
Normative change: https://github.com/tc39/proposal-temporal/pull/2759
Consensus in February 2024
=> Temporal: Tests for date difference algorithm

test/annexB/language/comments/single-line-html-close-first-line-1.js, test/annexB/language/comments/single-line-html-close-first-line-2.js, test/annexB/language/comments/single-line-html-close-first-line-3.js
Tests for https://github.com/tc39/ecma262/pull/3244, which reached consensus today
=> Add tests for `-->` in the first line

test/language/module-code/import-attributes/allow-nlt-before-with.js
The description of the test states that `WithClause` can be preceded by a line terminator, but the syntax states the opposite.
=> Fix comment in allow-nlt-before-with.js

test/intl402/DateTimeFormat/timezone-legacy-non-iana.js, test/intl402/Temporal/TimeZone/from/timezone-string-legacy-non-iana.js, test/intl402/Temporal/TimeZone/legacy-non-iana.js
Time zone identifiers supported by ICU, but which aren't valid IANA identifiers.
=> Add test with non-IANA time zone names

test/built-ins/ArrayBuffer/options-maxbytelength-allocation-limit.js, test/built-ins/ArrayBuffer/options-maxbytelength-compared-before-object-creation.js, test/built-ins/ArrayBuffer/options-maxbytelength-data-allocation-after-object-creation.js, test/built-ins/SharedArrayBuffer/options-maxbytelength-allocation-limit.js, test/built-ins/SharedArrayBuffer/options-maxbytelength-compared-before-object-creation.js, test/built-ins/SharedArrayBuffer/options-maxbytelength-data-allocation-after-object-creation.js
Add tests to ensure that:
1. First `byteLength` isn't larger than `maxByteLength`.
2. Then `OrdinaryCreateFromConstructor` is called.
3. And finally `Create{Shared}ByteDataBlock` is called.
=> (Shared)ArrayBuffer constructor validation happens in correct order

test/language/module-code/top-level-await/async-module-does-not-block-sibling-modules.js, test/language/module-code/top-level-await/async-module-sync_FIXTURE.js, test/language/module-code/top-level-await/async-module-tla_FIXTURE.js
cc @guybedford @codehag for reviews
Currently Chrome, Deno and Node.js pass this test, while Safari, Firefox and Bun fail it. This seems to suggest a JS engine difference (V8 passes, JSC/SM fail), but given that this is related to modules I'm not sure whether the bug lives in the engine or in the embedder. Maybe it's worth duplicating this test in WPT?
=> Add test for async module not blocking sync siblings

test/built-ins/Temporal/Calendar/prototype/weekOfYear/custom-calendar-weekofyear.js, test/built-ins/Temporal/Calendar/prototype/yearOfWeek/custom-calendar-weekofyear.js, test/built-ins/Temporal/PlainDate/prototype/weekOfYear/custom-calendar-weekofyear.js, test/built-ins/Temporal/PlainDate/prototype/weekOfYear/validate-calendar-value.js, test/built-ins/Temporal/PlainDate/prototype/yearOfWeek/custom-calendar-weekofyear.js, test/built-ins/Temporal/PlainDate/prototype/yearOfWeek/validate-calendar-value.js, test/built-ins/Temporal/PlainDateTime/prototype/weekOfYear/custom-calendar-weekofyear.js, test/built-ins/Temporal/PlainDateTime/prototype/weekOfYear/validate-calendar-value.js, test/built-ins/Temporal/PlainDateTime/prototype/yearOfWeek/custom-calendar-weekofyear.js, test/built-ins/Temporal/PlainDateTime/prototype/yearOfWeek/validate-calendar-value.js, test/built-ins/Temporal/ZonedDateTime/prototype/weekOfYear/custom-calendar-weekofyear.js, test/built-ins/Temporal/ZonedDateTime/prototype/weekOfYear/validate-calendar-value.js, test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/custom-calendar-weekofyear.js, test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/validate-calendar-value.js, test/intl402/Temporal/Calendar/prototype/weekOfYear/gregory-iso-weekofyear.js, test/intl402/Temporal/Calendar/prototype/weekOfYear/non-iso-week-of-year.js, test/intl402/Temporal/Calendar/prototype/yearOfWeek/gregory-iso-weekofyear.js, test/intl402/Temporal/Calendar/prototype/yearOfWeek/non-iso-week-of-year.js, test/intl402/Temporal/PlainDate/prototype/weekOfYear/gregory-iso-weekofyear.js, test/intl402/Temporal/PlainDate/prototype/weekOfYear/non-iso-week-of-year.js, test/intl402/Temporal/PlainDate/prototype/yearOfWeek/gregory-iso-weekofyear.js, test/intl402/Temporal/PlainDate/prototype/yearOfWeek/non-iso-week-of-year.js, test/intl402/Temporal/PlainDateTime/prototype/weekOfYear/gregory-iso-weekofyear.js, test/intl402/Temporal/PlainDateTime/prototype/weekOfYear/non-iso-week-of-year.js, test/intl402/Temporal/PlainDateTime/prototype/yearOfWeek/gregory-iso-weekofyear.js, test/intl402/Temporal/PlainDateTime/prototype/yearOfWeek/non-iso-week-of-year.js, test/intl402/Temporal/ZonedDateTime/prototype/weekOfYear/gregory-iso-weekofyear.js, test/intl402/Temporal/ZonedDateTime/prototype/weekOfYear/non-iso-week-of-year.js, test/intl402/Temporal/ZonedDateTime/prototype/yearOfWeek/gregory-iso-weekofyear.js, test/intl402/Temporal/ZonedDateTime/prototype/yearOfWeek/non-iso-week-of-year.js
Adds and updates tests for PR: https://github.com/tc39/proposal-temporal/pull/2756
=> Temporal: Tests for week-numbering algorithm

test/intl402/Locale/prototype/calendar/canonicalize.js
the calenar name should be canonicalized
Spec change https://github.com/tc39/ecma402/pull/846
=> Add test for ECMA402 PR846

test/intl402/DateTimeFormat/prototype/resolvedOptions/hourCycle-default.js
The tests are passing an explicit `hour12` option, which disables any `hourCycle` option and any `u-hc` Unicode extension. Therefore passing input locales with `u-hc` is invalid.
```js
let locale = "en-u-hc-h24";
let hcDefault = new Intl.DateTimeFormat(locale, { hour: "numeric" }).resolvedOptions().hourCycle;
assert.sameValue(hcDefault, "h24", "hour-cycle through Unicode extension");
let hc24 = new Intl.DateTimeFormat(locale, { hour: "numeric", hour12: false }).resolvedOptions().hourCycle;
// Incorrect assertion, because |hc24| uses |hour12|, which disables any
// hour-cycle option and the hour-cycle is determined from the locale "en".
// That means |hc24| will be "h23".
assert.sameValue(hc24, hcDefault);
```
=> Remove locales with explicit u-hc Unicode extension

test/intl402/DurationFormat/prototype/format/numeric-hour-with-zero-minutes-and-non-zero-seconds.js
https://github.com/tc39/proposal-intl-duration-format/pull/180 changes the behavior for cases wherein:
- Hours and seconds are both displayed
- `"numeric"` style used for hours
In this case, minutes are now always displayed, even when the value of minutes is 0.
Previous output for `new Intl.DurationFormat("en", {hours: "numeric"}).format({hours: 1, minutes: 0, seconds: 2})` was `"1, 02"`, new output is `"1:00:02"`
=> update to reflect new handling for numeric-styled minutes

test/intl402/DurationFormat/prototype/format/style-digital-fractionalDigits-en.js, test/intl402/DurationFormat/prototype/format/style-digital-fractionalDigits-undefined-en.js
Two tests compared output against hardcoded strings formatted as in 'en', despite the locale for the DurationFormat being set to `*undefined*`. updated to explicitly give 'en' as locale for DurationFormat
=> Two tests previously assumed 'en' as locale for DurationFormat, assumption now made explicit

test/intl402/DurationFormat/prototype/format/negative-duration-style-default-en.js, test/intl402/DurationFormat/prototype/format/negative-duration-style-short-en.js, test/intl402/DurationFormat/prototype/format/negative-durationstyle-digital-en.js, test/intl402/DurationFormat/prototype/format/negative-durationstyle-long-en.js, test/intl402/DurationFormat/prototype/format/negative-durationstyle-narrow-en.js, test/intl402/DurationFormat/prototype/format/numeric-hour-with-zero-minutes-and-non-zero-seconds.js, test/intl402/DurationFormat/prototype/format/precision-exact-mathematical-values.js, test/intl402/DurationFormat/prototype/format/style-default-en.js, test/intl402/DurationFormat/prototype/format/style-digital-en.js, test/intl402/DurationFormat/prototype/format/style-digital-fractionalDigits-en.js, test/intl402/DurationFormat/prototype/format/style-digital-fractionalDigits-undefined-en.js, test/intl402/DurationFormat/prototype/format/style-long-en.js, test/intl402/DurationFormat/prototype/format/style-narrow-en.js, test/intl402/DurationFormat/prototype/format/style-short-en.js, test/intl402/DurationFormat/prototype/formatToParts/negative-duration-formatToParts-style-default-en.js, test/intl402/DurationFormat/prototype/formatToParts/negative-duration-formatToParts-style-digital-en.js, test/intl402/DurationFormat/prototype/formatToParts/negative-duration-formatToParts-style-long-en.js, test/intl402/DurationFormat/prototype/formatToParts/negative-duration-formatToParts-style-narrow-en.js, test/intl402/DurationFormat/prototype/formatToParts/negative-duration-formatToParts-style-short-en.js
The metadata for several Intl.DurationFormat tests list give "en-US" as the locale when the actual locale used for the tests is just "en". This PR changes the metadata to match the tests.
=> DurationFormat: changed metadata for 'en'/'en-US' tests to correctly indicate locale

test/intl402/DateTimeFormat/prototype/format/dayPeriod-long-en.js, test/intl402/DateTimeFormat/prototype/format/dayPeriod-narrow-en.js, test/intl402/DateTimeFormat/prototype/format/dayPeriod-short-en.js, test/intl402/DateTimeFormat/prototype/format/fractionalSecondDigits.js, test/intl402/DateTimeFormat/prototype/formatToParts/fractionalSecondDigits.js
Corrects metadata in `DateTimeFormat` and `DisplayNames` which inappropriately identified tests using 'en' locale as `locale: [en-US]`
=> Correct Intl.DateTimeFormat and Intl.DisplayNames locale metadata

test/intl402/DurationFormat/prototype/format/mixed-non-numeric-styles-es.js
Tests formatting for units using a mixture of `"long"`, `"short"`, and `"narrow"` styles.  Compares output from format method to output produced through using `NumberFormat` and `ListFormat` as they are used in `DurationFormat` spec.
Considers both how `Intl.NumberFormat` formats units depending on unit styles and also how `Intl.ListFormat` formats lists depending on the base style.
=> DurationFormat: test formatting for units using mixed styles

test/intl402/DurationFormat/constructor-unit-style-defaults.js
The `DurationFormat` constructor sets different default styles for units that follow units that use either `"numeric"` or `"2-digit"` style:
* `minutes` and `seconds` default to `"2-digit"`
* subsecond units default to `"numeric"`.
These tests verify that this is done correctly.
=> DurationFormat: added tests for default styles for units following numeric-styled units

test/staging/Intl402/Temporal/old/non-iso-calendars.js
This is a staging test that was tightly coupled to particular 'golden' output from toLocaleString. Rewrite it so that it uses formatToParts instead, and tests for the presence of particular parts, and their values.
Also removes some dead logging code from this test file.
=> Reduce locale dependence in non-iso-calendars.js

test/intl402/DurationFormat/prototype/format/mixed-short-and-numeric.js
Verifies that:
1. `numeric`-style minutes are not padded to 2 digits when the style for `hours` is neither `numeric` nor `2-digit`.
2. The correct `ListFormat` style (`"short"`) is used when no `DurationFormat` base style defined.
=> added test for formatting mixture of short and numeric styles

test/built-ins/Map/groupBy/string.js, test/built-ins/Object/groupBy/string.js
🥰, the first emoji, has the key `'after'`, so the insertion order of the keys is `'after', 'before'`.
Also, this test was committed after multiple engines have shipped `groupBy`. Did the CI run this against implementations?
=> Fix groupBy string test keys to be insertion order

test/intl402/DurationFormat/prototype/format/fractions-of-subsecond-units-en.js
If `microseconds` are the first `numeric`-styled unit, they should be displayed as a fractional component of milliseconds. Likewise, if `nanoseconds` is the first `numeric`-styled unit, they should be displayed as a fractional component of microseconds.
=> test formatting when microseconds or nanoseconds are the first numeric-styled unit

test/language/expressions/assignment/S11.13.1_A7_T3.js, test/language/expressions/assignment/target-member-computed-reference.js, test/language/expressions/assignment/target-super-computed-reference.js
Update S11.13.1_A7_T3.js now that consensus has been reached on https://github.com/tc39/ecma262/pull/3307.
This ends up basically the same as [target-member-computed-reference-null.js](https://github.com/tc39/test262/blob/main/test/language/expressions/assignment/target-member-computed-reference-null.js), just with a valid base object.
=> Update test for o[p] = f()

test/intl402/DisplayNames/prototype/of/type-region-invalid.js
If there is no necessity for it to be a tab, then I think we should use spaces for consistency.
context: WebKit style check is failed because of this(https://github.com/WebKit/WebKit/pull/27213).
=> Use space instead of tab in comments

test/intl402/DurationFormat/prototype/format/mixed-short-and-numeric.js
The option for the listFormat need to include {type: "unit"}
see https://tc39.es/proposal-intl-duration-format/#sec-partitiondurationformatpattern 
@ben-allen @anba @ryzokuken @Ms2ger
=> Fix mixed-short-and-numeric.js

test/intl402/DurationFormat/prototype/format/fractions-of-subsecond-units-en.js
Fixes problem analogous to one fixed by https://github.com/tc39/test262/pull/4064
=> ListFormats used in DurationFormat/prototype/format/fractions-of-subsecond-units-en.js were missing required `type: "unit"` option

harness/resizableArrayBufferUtils.js
These are the parts of the code in resizable array buffer staging tests that are heavily repeated. In order to somewhat compact the migration of RAB staging tests (see PR #3888).
=> Collection of helper constants and functions for testing RABs

features.txt, test/built-ins/Promise/race/resolved-sequence-with-rejections.js, test/built-ins/Promise/try/args.js, test/built-ins/Promise/try/ctx-ctor-throws.js, test/built-ins/Promise/try/ctx-ctor.js, test/built-ins/Promise/try/ctx-non-ctor.js, test/built-ins/Promise/try/ctx-non-object.js, test/built-ins/Promise/try/length.js, test/built-ins/Promise/try/name.js, test/built-ins/Promise/try/not-a-constructor.js, test/built-ins/Promise/try/promise.js, test/built-ins/Promise/try/prop-desc.js, test/built-ins/Promise/try/return-value.js, test/built-ins/Promise/try/throws.js, test/built-ins/Promise/withResolvers/ctx-ctor.js
https://github.com/tc39/proposal-promise-try/issues/15
=> add Promise.try tests

test/built-ins/Promise/try/args.js, test/built-ins/Promise/try/return-value.js
We've updated test262 for WebKit, then following two tests for `Promise.try` failed with an error message `Test262Error: asyncTest called with non-function argument'`[^2]:
- https://github.com/tc39/test262/blob/081808bebd96bc9c755300e8c3eb59d8bef578f1/test/built-ins/Promise/try/args.js
- https://github.com/tc39/test262/blob/081808bebd96bc9c755300e8c3eb59d8bef578f1/test/built-ins/Promise/try/return-value.js
`asyncTest` harness must be called with function type argument[^1] but, current tests call it with the result of `Promise.try` directly.
This PR changes to call it with a function that wraps `Promise.try` call.
[^1]: https://github.com/tc39/test262/blob/081808bebd96bc9c755300e8c3eb59d8bef578f1/harness/asyncHelpers.js#L13-L16
[^2]: …
=> Fix `asyncTest` usage for `Promise.try` tests

test/built-ins/Promise/try/ctx-ctor.js
Removes incorrect property access (`Promise/try/ctx-ctor.js`)
=> Remove incorrect property access in `Promise.try` test

test/built-ins/Promise/try/throws.js
In WebKit test262, `/test/built-ins/Promise/try/throws.js` fails with an error message `assert.throwsAsync is not a function.`[^1].
This PR has following changes:
- Include `asyncHelpers.js` to use `assert.throwAsync`.
- Wrap `assert.throwAsync` call with `asyncTest` according to the [CONTRIBUTING.md](https://github.com/tc39/test262/blob/main/CONTRIBUTING.md#checking-exception-type-in-asynchronous-tests).
[^1]: https://github.com/WebKit/WebKit/blob/4bae864b01100e8179cc36948b7d15b7dafe2095/JSTests/test262/expectations.yaml#L81-L83
=> Wrap `assert.throwsAsync` with `asyncTest` in `Promise.try` test

test/built-ins/Promise/try/throws.js
This callback is expected to return a thenable.
=> Add missing `return` statement to `throwsAsync` callback

.github/workflows/esmeta-test262.yml
Updates the branch version to clone in CI to v0.4.1.
[Changes](https://github.com/es-meta/esmeta/compare/v0.1.0-rc8...v0.4.1)
=> chore(ci): Update branch version for ES-META repo

test/built-ins/Temporal/Duration/out-of-range.js
Fixed test messages that incorrectly referenced the `days` parameter to say `weeks` instead.
=> Temporal: fix messages on `Duration/out-of-range` tests

test/intl402/DurationFormat/constructor-options-fractionalDigits-invalid.js, test/intl402/DurationFormat/constructor-options-fractionalDigits-valid.js
Just fix descriptions for `Intl.DurationFromat`
=> Fix description of `fractionalDigits` tests

test/built-ins/Array/prototype/copyWithin/resizable-buffer.js, test/built-ins/TypedArray/prototype/copyWithin/coerced-target-start-end-shrink.js, test/built-ins/TypedArray/prototype/copyWithin/coerced-target-start-grow.js, test/built-ins/TypedArray/prototype/copyWithin/resizable-buffer.js
=> RAB: Integrate staging tests for .copyWithin method

test/built-ins/Array/prototype/entries/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/entries/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/entries/resizable-buffer.js, test/built-ins/TypedArray/prototype/entries/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/entries/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/entries/resizable-buffer.js
=> RAB: Integrate staging tests for the .entries method

test/built-ins/Array/prototype/fill/resizable-buffer.js, test/built-ins/Array/prototype/fill/typed-array-resize.js, test/built-ins/TypedArray/prototype/fill/coerced-value-start-end-resize.js, test/built-ins/TypedArray/prototype/fill/resizable-buffer.js
This is part of PR https://github.com/tc39/test262/pull/3888 to make reviewing easier.
Includes changes to use the helper ./harness/resizableArrayBufferUtils.js
=> RAB: Integrate staging tests for .fill method

test/intl402/DurationFormat/prototype/format/rounding-mode-trunc-for-seconds.js
According to the spec[^1], `nfOptions.roundingMode` shoule be `"trunc"` when formatting seconds, microseconds, and nanoseconds.
```
1.1.14 PartitionDurationFormatPattern
(...)
4. While numericUnitFound is false, repeat for each row in Table 2 in table order, except the header row:
e. If style is "numeric" or "2-digit", then
i. Append FormatNumericUnits(durationFormat, duration, unit, signDisplayed) to result.
(...)
f. Else,
(...)
ii. If unit is "seconds", "milliseconds", or "microseconds", then
(...)
f. Perform ! CreateDataPropertyOrThrow(nfOpts, "roundingMode", "trunc").
1.1.12 FormatNumericUnits
(...)
18. If secondsFormatted is true, then
a. Append FormatNumericSeconds(durationFormat, secondsValue, minutesFormatted, signDisplayed) to numericPartsList.
(...)
1.1.11 FormatNumericSeconds …
```
=> Add test to check `nfOptions.roundingMode` for seconds / microseconds / nanoseconds is `"trunc"`

test/language/module-code/source-phase-import/import-source-binding-name-2.js, test/language/module-code/source-phase-import/import-source-binding-name.js
The current test contained a parser error due to the duplicate binding. This splits the test in two files, so that we actually successfully parse the file.
cc @legendecas
Ref https://github.com/babel/babel/pull/16596
=> Avoid duplicate binding import-source-binding-name.js

test/built-ins/Array/prototype/every/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/every/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/every/resizable-buffer.js, test/built-ins/TypedArray/prototype/every/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/every/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/every/resizable-buffer.js
=> RAB: Integrate staging tests for the .every method

test/built-ins/Array/prototype/filter/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/filter/resizable-buffer.js, test/built-ins/TypedArray/prototype/filter/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/filter/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/filter/resizable-buffer.js
=> RAB: Integrate staging tests for the .filter method

test/built-ins/Array/prototype/find/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/find/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/find/resizable-buffer.js, test/built-ins/TypedArray/prototype/find/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/find/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/find/resizable-buffer.js
=>  RAB: Integrate staging tests for the .find method

test/built-ins/Array/prototype/findIndex/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/findIndex/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/findIndex/resizable-buffer.js, test/built-ins/TypedArray/prototype/findIndex/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/findIndex/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/findIndex/resizable-buffer.js
=>  RAB: Integrate staging tests for the .findIndex method

test/built-ins/Array/prototype/findLastIndex/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/findLastIndex/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/findLastIndex/resizable-buffer.js, test/built-ins/TypedArray/prototype/findLastIndex/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/findLastIndex/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/findLastIndex/resizable-buffer.js
=>  RAB: Integrate staging tests for the .findLastIndex method

test/built-ins/Uint8Array/prototype/setFromBase64/writes-up-to-error.js, test/built-ins/Uint8Array/prototype/setFromHex/writes-up-to-error.js, test/built-ins/Uint8Array/prototype/toBase64/omit-padding.js
Tests for https://github.com/tc39/proposal-arraybuffer-base64/pull/60 and https://github.com/tc39/proposal-arraybuffer-base64/pull/58, which got consensus after the proposal had achieved stage 3 based on user and implementer feedback.
Based on https://github.com/tc39/test262/pull/3994 (which incidentally is ready).
=> Tests for later base64 changes

test/staging/top-level-await/grandparent-tla_FIXTURE.js, test/staging/top-level-await/parent-tla_FIXTURE.js, test/staging/top-level-await/tla-hang-entry.js
Use explicit relative paths to ensure cross-engine compatibility.
=> Use explicit relative paths

harness/temporalHelpers.js, test/intl402/Temporal/ZonedDateTime/construct-non-utc-non-iso.js
Temporal doesn't specify concrete era names, so tests shouldn't assert for example that the era code of the current Gregorian era is `"ce"`. We still want to validate the era names somehow however, so allow alternative era names using the era codes from the "Intl era and monthCode" proposal.
=> Allow alternative era names

test/intl402/Locale/constructor-options-firstDayOfWeek-valid.js
true will be dropped inside UTS35
See https://github.com/tc39/test262/pull/4141#pullrequestreview-2171902863 for more info
=> Update the expctation of constructor-options-firstDayOfWeek-valid.js

test/built-ins/Array/prototype/every/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/every/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/filter/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/filter/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/filter/resizable-buffer.js, test/built-ins/Array/prototype/find/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/findIndex/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/findIndex/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/findLast/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/findLast/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/findLastIndex/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/findLastIndex/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/every/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/every/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/filter/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/filter/resizable-buffer.js, test/built-ins/TypedArray/prototype/find/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/find/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/findIndex/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/findIndex/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/findLast/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/findLast/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/findLastIndex/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/findLastIndex/resizable-buffer-shrink-mid-iteration.js
Also renames `ResizeBufferMidIteration` to `ResizeMidIteration`.
=> RAB: Adds missing Array.prototype.filter 'shrink' tests plus typesetting

test/built-ins/Array/prototype/includes/coerced-searchelement-fromindex-resize.js, test/built-ins/Array/prototype/includes/resizable-buffer-special-float-values.js, test/built-ins/Array/prototype/includes/resizable-buffer.js, test/built-ins/TypedArray/prototype/includes/coerced-searchelement-fromindex-resize.js, test/built-ins/TypedArray/prototype/includes/resizable-buffer-special-float-values.js, test/built-ins/TypedArray/prototype/includes/resizable-buffer.js
=> RAB: Integrate staging tests for the .includes method

test/built-ins/Array/prototype/indexOf/coerced-searchelement-fromindex-grow.js, test/built-ins/Array/prototype/indexOf/coerced-searchelement-fromindex-shrink.js, test/built-ins/Array/prototype/indexOf/resizable-buffer-special-float-values.js, test/built-ins/Array/prototype/indexOf/resizable-buffer.js, test/built-ins/TypedArray/prototype/indexOf/coerced-searchelement-fromindex-grow.js, test/built-ins/TypedArray/prototype/indexOf/coerced-searchelement-fromindex-shrink.js, test/built-ins/TypedArray/prototype/indexOf/resizable-buffer-special-float-values.js, test/built-ins/TypedArray/prototype/indexOf/resizable-buffer.js
=> RAB: Integrate staging tests for the .indexOf method

test/built-ins/Array/prototype/join/coerced-separator-grow.js, test/built-ins/Array/prototype/join/coerced-separator-shrink.js, test/built-ins/Array/prototype/join/resizable-buffer.js, test/built-ins/TypedArray/prototype/join/coerced-separator-grow.js, test/built-ins/TypedArray/prototype/join/coerced-separator-shrink.js, test/built-ins/TypedArray/prototype/join/resizable-buffer.js
=> RAB: Integrate staging tests for the .join method

test/built-ins/Uint8Array/prototype/setFromBase64/writes-up-to-error.js, test/built-ins/Uint8Array/prototype/setFromHex/writes-up-to-error.js
#4133 brought couple test files which are using `assert.compareArray`, but the include is missing and causes errors when harness is being run.
=> Add missing compareArray includes

test/built-ins/Math/pow/applying-the-exp-operator_A1.js
In some implementations, the `pow` function may return 1, which contradicts the specification. This addition ensures that the test case covers this scenario.
=> Add missing test for `Math.pow(1, NaN)`

test/built-ins/Array/prototype/keys/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/keys/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/keys/resizable-buffer.js, test/built-ins/TypedArray/prototype/keys/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/keys/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/keys/resizable-buffer.js
=> RAB: Integrate staging tests for the .keys method

test/built-ins/Array/prototype/lastIndexOf/coerced-position-grow.js, test/built-ins/Array/prototype/lastIndexOf/coerced-position-shrink.js, test/built-ins/Array/prototype/lastIndexOf/resizable-buffer.js, test/built-ins/TypedArray/prototype/lastIndexOf/coerced-position-grow.js, test/built-ins/TypedArray/prototype/lastIndexOf/coerced-position-shrink.js, test/built-ins/TypedArray/prototype/lastIndexOf/resizable-buffer-special-float-values.js, test/built-ins/TypedArray/prototype/lastIndexOf/resizable-buffer.js
=>  RAB: Integrate staging tests for the .lastIndexOf method

features.txt, test/built-ins/RegExp/escape/cross-realm.js, test/built-ins/RegExp/escape/escaped-control-characters.js, test/built-ins/RegExp/escape/escaped-lineterminator.js, test/built-ins/RegExp/escape/escaped-otherpunctuators.js, test/built-ins/RegExp/escape/escaped-solidus-character-mixed.js, test/built-ins/RegExp/escape/escaped-solidus-character-simple.js, test/built-ins/RegExp/escape/escaped-surrogates.js, test/built-ins/RegExp/escape/escaped-syntax-characters-mixed.js, test/built-ins/RegExp/escape/escaped-syntax-characters-simple.js, test/built-ins/RegExp/escape/escaped-utf16encodecodepoint.js, test/built-ins/RegExp/escape/escaped-whitespace.js, test/built-ins/RegExp/escape/initial-char-escape.js, test/built-ins/RegExp/escape/is-function.js, test/built-ins/RegExp/escape/length.js, test/built-ins/RegExp/escape/name.js, test/built-ins/RegExp/escape/non-string-inputs.js, test/built-ins/RegExp/escape/not-a-constructor.js, test/built-ins/RegExp/escape/not-escaped-underscore.js, test/built-ins/RegExp/escape/not-escaped.js, test/built-ins/RegExp/escape/prop-desc.js
Initial implementation of tests for RegExp.escape. I still need to review if I'm missing coverage here or running the tests.
=> Add tests for RegExp.escape

harness/regExpUtils.js
In order to not fail because harness code fails to load due to using not-supported EcmaScript features while not needed 
Relates to ##3032
=> Don't use const in for (of) loops so harness code can be used in environments that don't support that

test/built-ins/TypedArray/prototype/byteLength/resized-out-of-bounds-1.js, test/built-ins/TypedArray/prototype/byteLength/resized-out-of-bounds-2.js, test/built-ins/TypedArray/prototype/byteOffset/resized-out-of-bounds.js, test/built-ins/TypedArray/prototype/length/resizable-buffer-assorted.js, test/built-ins/TypedArray/prototype/length/resized-out-of-bounds-1.js, test/built-ins/TypedArray/prototype/length/resized-out-of-bounds-2.js
=>  RAB: Integrate staging tests for the .length method

test/intl402/NumberFormat/prototype/format/useGrouping-extended-en-IN.js
In CLDR 45, in the en-IN locale, the compact thousands symbol changed from 'T' to 'K' after a survey was conducted in India:
https://github.com/unicode-org/cldr/commit/b8d447297556ee01575da2b5b710554af34b3482
=> Update NumberFormat.prototype.useGrouping test for CLDR 45

harness/hidden-constructors.js
In order to not fail because harness code fails to load due to using not-supported EcmaScript features while not needed
Relates to ##3032
=> Prevent harness code not loading when async/generator/asyncGenerator not supported

harness/hidden-constructors.js
Function statements require a name.
See #4166
=> Fix syntax error from #4164

harness/nativeFunctionMatcher.js
In order to not fail because harness code fails to load due to using not-supported EcmaScript features while not needed 
Relates to ##3032
=> Remove unneeded /u flag within harness/nativeFunctionMatcher

harness/resizableArrayBufferUtils.js
In order to not fail because harness code fails to load due to using not-supported EcmaScript features while not needed 
Relates to ##3032
=> Make resizableArrayBufferUtils not depend on syntax that may not be supported

test/intl402/DurationFormat/constructor-option-read-order.js, test/intl402/DurationFormat/prototype/resolvedOptions/return-keys-order-default.js
Test the order of resolvedOptions in default setting Also add test to check the reading order of options based on the property returned in the default setting resolvedOptions.
https://github.com/tc39/proposal-intl-duration-format/pull/167 
https://github.com/tc39/proposal-intl-duration-format/pull/172 
https://tc39.es/proposal-intl-duration-format/#sec-Intl.DurationFormat.prototype.resolvedOptions
These two PRs are presenting to TC39 2023-09 meeting
=> Add tests for DurationFormat PR 172 and 167

test/built-ins/Array/prototype/reduceRight/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/reduceRight/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/reduceRight/resizable-buffer.js, test/built-ins/TypedArray/prototype/reduceRight/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/reduceRight/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/reduceRight/resizable-buffer.js
This is very similar as PR #4156 for `.reduce`.
=> RAB: Integrate staging tests for the .reduceRight method

test/built-ins/Array/prototype/reverse/resizable-buffer.js, test/built-ins/TypedArray/prototype/reverse/resizable-buffer.js
=>  RAB: Integrate staging tests for the .reverse method

harness/resizableArrayBufferUtils.js
Added catch to achieve the entire goal of the previous PR to prevent the harness from loading if 'class' syntax isn't supported
Hopefully this is now properly sorted
=> Follow-up to #4165

test/staging/Intl402/Temporal/old/japanese-before-era.js, test/staging/Intl402/Temporal/old/japanese-era.js
- Move tests for before-start-of-era into a different file until there's a better specification how to handle this case &rarr; <https://github.com/tc39/proposal-temporal/issues/2865>.
- Use helper function from #4098 to allow different era names.
=> Adjust Temporal staging test of the Japanese calendar for alternative implementations

test/built-ins/Array/prototype/map/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/map/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/map/resizable-buffer.js, test/built-ins/TypedArray/prototype/map/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/map/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/map/resizable-buffer.js, test/built-ins/TypedArray/prototype/map/speciesctor-resizable-buffer-grow.js, test/built-ins/TypedArray/prototype/map/speciesctor-resizable-buffer-shrink.js
=> RAB: Integrate staging tests for the .map method

harness/temporalHelpers.js, test/staging/Intl402/Temporal/old/japanese-era.js
This mistakenly used a previous name for the helper function. Also adds a couple of debugging messages.
(Regression from #4102)
=> Temporal: Fix Japanese era test

test/built-ins/RegExp/escape/initial-char-escape.js
=> Fix `test/built-ins/RegExp/escape/initial-char-escape.js`

CONTRIBUTING.md, harness/asyncHelpers.js
**CONTRIBUTING.md**
* Only mention `$DONE` after `asyncTest`.
* Document that `asyncTest` is not intended to be called multiple times per file.
**harness/asyncHelpers.js**
* Add doc comments.
* Refactor `assert.throwsAsync` to fail fast and isolate error conditions.
* Clean up `assert.throwsAsync` failure messages (remove mention of an "inner" promise/thenable).
* Reduce the size of `assert.throwsAsync` for better comprehensibility in one screenful.
=> Cleanup asyncHelpers

harness/asyncHelpers.js
=> harness/asyncHelpers.js: Update throwsAsync to not succeed on a bad thenable

test/built-ins/RegExp/nullable-quantifier.js
The JavaScript regex quantifiers (star, plus, counted repetition) have unique semantics when it comes to matching the empty string.
Optional iterations of quantifiers that match the empty string are forbidden.
This is documented in [ECMAScript](https://262.ecma-international.org/15.0/index.html#sec-runtime-semantics-repeatmatcher-abstract-operation) (point 2.b)
and the PLDI2024 paper [Linear Matching of JavaScript Regular Expressions](https://dl.acm.org/doi/10.1145/3656431).
In many other regex languages however, the quantifier semantics are different.
Instead of only checking at the end of an iteration, it is forbidden to visit any part of the regex twice without having consumed a character.
In some rare cases, the two semantics give different results.
For instance, matching /(a?b??)*/ …
=> Add tests for nullable quantifiers in RegExps

test/built-ins/TypedArray/prototype/set/target-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/set/target-grow-source-length-getter.js, test/built-ins/TypedArray/prototype/set/target-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/set/target-shrink-source-length-getter.js, test/built-ins/TypedArray/prototype/set/this-backed-by-resizable-buffer.js, test/built-ins/TypedArray/prototype/set/typedarray-arg-src-backed-by-resizable-buffer.js
=>  RAB: Integrate staging tests for the .set method 

test/built-ins/Array/prototype/values/resizable-buffer-grow-mid-iteration.js, test/built-ins/Array/prototype/values/resizable-buffer-shrink-mid-iteration.js, test/built-ins/Array/prototype/values/resizable-buffer.js, test/built-ins/TypedArray/prototype/values/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/values/resizable-buffer-shrink-mid-iteration.js, test/built-ins/TypedArray/prototype/values/resizable-buffer.js
=> RAB: Integrate staging tests for the .values method

test/built-ins/TypedArray/prototype/reduce/resizable-buffer-grow-mid-iteration.js, test/built-ins/TypedArray/prototype/reduce/resizable-buffer-shrink-mid-iteration.js
Introduced in #4156 , `Array.prototype.reduce` had the correct signature for callback function, but typed array did not.
`reduce` callback has call signature `«accumulator, kValue, 𝔽(k), O»` earlier the collected values contained the accumalator instead of the actual value.
=> RAB: fix reduce tests

test/built-ins/Temporal/Duration/prototype/round/end-of-month-round-up.js
See https://github.com/tc39/proposal-temporal/issues/2919; this adds test coverage that would have caught an unintentional normative change.
=> Temporal: Add a test for a coverage gap in Duration.prototype.round

harness/asyncHelpers.js, test/harness/asyncHelpers-throwsAsync-func-never-settles.js
Some recent changes to `harness/asyncHelpers.js` regressed some harness tests; `test/harness/asyncHelpers-throwsAsync-func-throws-sync.js` and `test/harness/asyncHelpers-throwsAsync-no-arg.js` to be more specific. The cause of this was fa3d0246e74da7844843ebfb4c71453c616b923a and feb400c68598138b4e5a056c69b94bc1108d8a51, which made some changes that broke those two tests.
This PR fixes this by slightly modifying `asyncHelpers.js` so that it passes the two tests, and also adds a new test to ensure #4186 is still fixed even with the new changes.
=> Fix test regression in asyncHelpers.js

test/built-ins/TypedArray/prototype/set/array-arg-value-conversion-resizes-array-buffer.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-in-bounds-receiver-is-not-typed-array.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-out-of-bounds-receiver-is-not-object.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-out-of-bounds-receiver-is-not-typed-array.js, test/built-ins/TypedArrayConstructors/internals/Set/key-is-out-of-bounds-receiver-is-proto.js, test/language/statements/with/get-mutable-binding-binding-deleted-in-get-unscopables-strict-mode.js, test/language/statements/with/get-mutable-binding-binding-deleted-in-get-unscopables.js, test/language/statements/with/set-mutable-binding-binding-deleted-in-get-unscopables-strict-mode.js, test/language/statements/with/set-mutable-binding-binding-deleted-in-get-unscopables.js, test/language/statements/with/set-mutable-binding-binding-deleted-with-typed-array-in-proto-chain-strict-mode.js, test/language/statements/with/set-mutable-binding-binding-deleted-with-typed-array-in-proto-chain.js
Additional tests to cover some spec-compliance issues I've encountered while implementing tc39/ecma262#1556 in SpiderMonkey.
=> Add more tests for receiver check in IntegerIndexedElementSet

test/language/statements/class/elements/syntax/valid/grammar-field-named-get-followed-by-generator-asi.js, test/language/statements/class/elements/syntax/valid/grammar-field-named-set-followed-by-generator-asi.js
Currently both SpiderMonkey and TypeScript fail parsing this code. V8, Babel and ESLint all pass the test.
=> Add test for asi between `get`/`set` field and generator

test/built-ins/Temporal/Duration/prototype/round/round-and-balance-calendar-units-with-increment-disallowed.js
This test covers a normative change to disallow an ambiguous corner case in the options bag for Temporal.Duration.prototype.round().
See https://github.com/tc39/proposal-temporal/pull/2916
=> Temporal: Tests for disallowed corner case in rounding durations

test/intl402/Temporal/PlainDate/prototype/toZonedDateTime/dst-skipped-cross-midnight.js, test/intl402/Temporal/ZonedDateTime/from/dst-skipped-cross-midnight.js, test/intl402/Temporal/ZonedDateTime/prototype/hoursInDay/dst-skipped-cross-midnight.js, test/intl402/Temporal/ZonedDateTime/prototype/round/dst-skipped-cross-midnight.js, test/intl402/Temporal/ZonedDateTime/prototype/startOfDay/dst-skipped-cross-midnight.js, test/intl402/Temporal/ZonedDateTime/prototype/withPlainTime/dst-skipped-cross-midnight.js
These tests add coverage for a corner case in the TZDB. In spring 1919, the America/Toronto time zone switched to DST at 23:30 on March 30th, skipping an hour ahead to 00:30 on March 31st. This meant that both March 30th and March 31st were 23.5-hour days.
See: https://github.com/tc39/proposal-temporal/issues/2910
=> Temporal: Tests for corner case in TZDB involving DST transition in 1919

test/intl402/Temporal/PlainDate/from/calendar-not-supporting-eras.js, test/intl402/Temporal/PlainDateTime/from/calendar-not-supporting-eras.js, test/intl402/Temporal/PlainMonthDay/from/calendar-not-supporting-eras.js, test/intl402/Temporal/PlainYearMonth/from/calendar-not-supporting-eras.js, test/intl402/Temporal/ZonedDateTime/from/calendar-not-supporting-eras.js, test/staging/Intl402/Temporal/old/japanese-before-era.js
This tests some of the prose requirements of CalendarResolveFields, that previously didn't have any test coverage.
See https://github.com/tc39/proposal-temporal/issues/2870
=> Temporal: Tests for ignoring era and eraYear in calendars without eras

test/built-ins/Iterator/from/get-return-method-when-call-return.js, test/built-ins/Iterator/from/return-method-calls-base-return-method.js, test/built-ins/Iterator/from/return-method-returns-iterator-result.js, test/built-ins/Iterator/from/return-method-throws-for-invalid-this.js
While implementing `Iterator.from` in WebKit[^1], I noticed that nearly all test262 test cases pass without implementing `%WrapForValidIteratorPrototype%.return()`[^2].
Although this method is not particularly complex, I believe there should be minimal tests for it.
This PR adds tests for `%WrapForValidIteratorPrototype%.return()`.
[^1]: https://github.com/WebKit/WebKit/pull/32741
[^2]: https://tc39.es/proposal-iterator-helpers/#sec-wrapforvaliditeratorprototype.return
=> Add tests for `%WrapForValidIteratorPrototype%.return()` from Iterator Helpers Proposal

test/language/destructuring/binding/keyed-destructuring-property-reference-target-evaluation-order-with-bindings.js, test/language/expressions/assignment/destructuring/keyed-destructuring-property-reference-target-evaluation-order-with-bindings.js, test/language/expressions/delete/super-property-topropertykey.js, test/language/expressions/delete/super-property-uninitialized-this.js, test/language/expressions/object/computed-property-name-topropertykey-before-value-evaluation.js, test/language/expressions/super/prop-expr-getsuperbase-before-topropertykey-getvalue.js, test/language/expressions/super/prop-expr-getsuperbase-before-topropertykey-putvalue-compound-assign.js, test/language/expressions/super/prop-expr-getsuperbase-before-topropertykey-putvalue-increment.js, test/language/expressions/super/prop-expr-getsuperbase-before-topropertykey-putvalue.js, test/language/expressions/super/prop-expr-uninitialized-this-getvalue.js, test/language/expressions/super/prop-expr-uninitialized-this-putvalue-compound-assign.js, test/language/expressions/super/prop-expr-uninitialized-this-putvalue-increment.js, test/language/expressions/super/prop-expr-uninitialized-this-putvalue.js
Missing coverage encountered while implementing
<https://github.com/tc39/ecma262/pull/3307> in SpiderMonkey.
Ensure environment lookups are performed in the correct order:
- keyed-destructuring-property-reference-target-evaluation-order-with-bindings.js
Ensure `delete super[elem]` steps are correctly performed:
- delete/super-property-topropertykey.js
- delete/super-property-uninitialized-this.js
Ensure ToPropertyKey for computed property names in object literals correctly performed:
- object/computed-property-name-topropertykey-before-value-evaluation.js
Ensure `GetSuperBase` is executed before `ToPropertKey`:
- super/prop-expr-getsuperbase-before-topropertykey-*
Ensure `GetThisBinding` is executed first:
- super/prop-expr-uninitialized-this-*
=> Improve coverage for reference type in various contexts

test/intl402/Temporal/PlainDate/from/canonicalize-era-codes.js, test/intl402/Temporal/PlainDateTime/from/canonicalize-era-codes.js, test/intl402/Temporal/PlainYearMonth/from/canonicalize-era-codes.js, test/intl402/Temporal/ZonedDateTime/from/canonicalize-era-codes.js
There was a coverage gap for converting calendar fields to a date when the provided era was an alias.
See https://github.com/tc39/proposal-temporal/pull/2940#discussion_r1767508659
=> Temporal: Add test coverage for canonicalizing era codes in from()

test/built-ins/RegExp/prototype/exec/regexp-builtin-exec-v-flag.js, test/built-ins/String/prototype/match/regexp-prototype-match-v-flag.js, test/built-ins/String/prototype/matchAll/regexp-prototype-matchAll-v-flag.js, test/built-ins/String/prototype/replace/regexp-prototype-replace-v-flag.js, test/built-ins/String/prototype/search/regexp-prototype-search-v-flag.js.js
=> Add more tests for v flag

test/built-ins/AsyncDisposableStack/instance-extensible.js, test/built-ins/AsyncDisposableStack/proto-from-ctor-realm.js, test/built-ins/AsyncDisposableStack/proto.js, test/built-ins/AsyncDisposableStack/prototype/Symbol.asyncDispose.js, test/built-ins/AsyncDisposableStack/prototype/disposed/getter.js, test/built-ins/AsyncDisposableStack/prototype/proto.js, test/built-ins/AsyncIteratorPrototype/Symbol.asyncDispose/is-function.js, test/built-ins/DisposableStack/instance-extensible.js, test/built-ins/DisposableStack/proto-from-ctor-realm.js, test/built-ins/DisposableStack/proto.js, test/built-ins/DisposableStack/prototype/Symbol.dispose.js, test/built-ins/DisposableStack/prototype/disposed/getter.js, test/built-ins/DisposableStack/prototype/proto.js, test/built-ins/Iterator/prototype/Symbol.dispose/is-function.js, test/built-ins/NativeErrors/SuppressedError/proto-from-ctor-realm.js, test/built-ins/NativeErrors/SuppressedError/proto.js, test/built-ins/NativeErrors/SuppressedError/prototype/constructor.js, test/built-ins/NativeErrors/SuppressedError/prototype/message.js, test/built-ins/NativeErrors/SuppressedError/prototype/proto.js
This PR splits some of the boilerplate tests from PR https://github.com/tc39/test262/pull/3866 to make reviewing all those files a little easier.
Includes some proto-from-ctor-realm.js tests that look like standard tests for prototypes.
=> Builtin boilerplate tests from PR #3866

harness/compareArray.js
Just a small quality of life improvement. I usually can't wrap my head around which was the expected and which one was the actual outcome so a textual clue helps.
=> Add names for expected outcomes in compareArray.js

test/intl402/DurationFormat/prototype/format/duration-out-of-range-1.js, test/intl402/DurationFormat/prototype/format/duration-out-of-range-2.js, test/intl402/DurationFormat/prototype/format/duration-out-of-range-3.js, test/intl402/DurationFormat/prototype/format/duration-out-of-range-4.js, test/intl402/DurationFormat/prototype/format/precision-exact-mathematical-values.js
This PR is just a cherry-pick of the last commit from #3988 to resolve conflicts. Closes #3988.
---
Update tests for tc39/proposal-intl-duration-format#173.
=> Update tests for "Limit valid values for DurationFormats to match upcoming limits in Temporal"

test/built-ins/String/prototype/replace/regexp-capture-by-index.js
* $xy is a valid capture index
* $xy is not a valid capture index but $x is
* neither $xy nor $x is a valid capture index
Ref https://github.com/tc39/ecma262/issues/1426
Ref https://github.com/tc39/ecma262/pull/3157
=> Increase coverage of String.prototype.replace $xy replacement patterns

harness/propertyHelper.js, test/built-ins/Array/prototype/every/prop-desc.js, test/built-ins/DataView/prototype/getInt16/length.js, test/built-ins/Date/parse/S15.9.4.2_A1_T1.js, tools/lint/lib/checks/harness.py, tools/lint/test/fixtures/harness/propertyHelper.js
This PR is a continuation of the effort to improve test262 compatibility with Hardened JavaScript after lockdown. The [initial PR](https://github.com/tc39/test262/pull/4088) focused on language tests. This one starts the work on built-in tests.
The approach is to modify the tests as little as possible to allow them to pass before and after lockdown. None of the changes so far require the tests themselves to have knowledge of Hardened JavaScript.
The Writable and Configurable attributes of built-ins are a significant source of failures under lockdown. Lockdown increases the integrity level of built-ins to `FROZEN`, causing over 1500 tests that verify the attributes of built-ins to fail.
There are three ways that the tests verify the attributes of built-ins:
- Using the `verifyProperty` …
=> Compatibility with Hardened JavaScript - start of built-ins

test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-timezone.js
Shouldn't be merged right away to give implementations some time to update to CLDR46 / tzdata 2024b.
=> Update time zone mapping for CLDR46 / tzdata 2024b

harness/assert.js, harness/deepEqual.js
Consolidates handling of identity-bearing values via a lazy multi-use indication.
<details open><summary>comparison</summary>
```js
const v = [];
v.push(v);
const values = [
'',
Symbol('foo'),
/./gui,
[-0, 0, 0n],
((a, b) => [a, b, a, b, {}])({}, {}),
new Date(0),
{ [Symbol.toStringTag]: 'errors', error: Error(), typeError: TypeError('foo') },
function fn(){},
new Set([v, {}, {}]),
Object.create(null),
];
for (const x of values) v.push(x, x, 'NL');
String(assert.deepEqual.format(v)).replace(/ "NL",/g, '\n');
```
<details><summary>before</summary>
Note the frequently missing "as #*N*" and the total lack of indication for referentially-identical symbols/regular expressions/dates/etc., not to mention the inability to differentiate signed zeros from each other or numbers from bigints.
``` …
```
=> harness/deepEqual.js: Improve formatting and align with base assert

test/language/expressions/class/heritage-arrow-function.js
Previously this test was the exact same as https://github.com/tc39/test262/tree/main/test/language/expressions/class/heritage-async-arrow-function.js, which I think is wrong.
=> fix: heritage-arrow-function.js

test/intl402/NumberFormat/currency-digits-nonstandard-notation.js
Related PR: https://github.com/tc39/ecma402/pull/925
fix https://github.com/tc39/test262/issues/4259
=> Add test:`Intl.NumberFormat` using "currency" style and "compact", "engineering", or "scientific" notations.

test/intl402/DateTimeFormat/prototype/format/numbering-system.js, test/intl402/RelativeTimeFormat/prototype/format/en-us-numbering-systems.js
Previously there was a spec bug: the `Intl.NumberFormat`s created within `Intl.DateTimeFormat.prototype.format` and `Intl.RelativeTimeFormat` constructor were not passed the numbering system to be used. 
See https://github.com/tc39/ecma402/pull/919/
Fix #4260
=> Add tests to `Intl.DateTimeFormat` and `Intl.RelativeTimeFormat` for various numbering systems

test/intl402/DurationFormat/prototype/format/style-digital-large-hms-values.js
Grouping separators suppressed in this situation. See tc39/proposal-intl-duration-format/pull/198
fix #4190
=> DurationFormat: Add tests for durations with large hour/minute/second unit values while using digital style

test/intl402/NumberFormat/currency-digits.js
This test treats ISO 4217 data on the number of minor unit digits to use when formatting currencies. ISO 4217 is no longer normative as of https://github.com/tc39/ecma402/pull/922
Additionally, web reality before that PR is that some implementations already used CLDR data rather than ISO 4217.
I could write a test that only checks the digits on a few currencies for which CLDR and ISO 4217 agree, and which aren't likely to change any time soon. (i.e. USD and EUR using 2 minor digits, JPY using 0). Not sure if that's the right path, though -- any guidance welcome.
=> 402: Replace currency-digits.js Intl.NumberFormat test

test/intl402/Temporal/PlainYearMonth/prototype/with/minimum-valid-year-month.js
See https://github.com/tc39/proposal-temporal/issues/2998
=> Temporal: Add test for setting minimum valid year-month with non-ISO8601 calendar

test/built-ins/Temporal/Duration/prototype/toString/total-of-duration-time-units-out-of-range.js
See https://github.com/tc39/proposal-temporal/issues/3034
=> Temporal: Add test for Duration/p/toString() with total time units out of range

test/intl402/Temporal/Duration/prototype/round/rounding-with-largestunit.js
This is the test for the change in https://github.com/tc39/proposal-temporal/pull/3036 and is a variation of the test from https://github.com/tc39/proposal-temporal/issues/2814 .
=> Temporal: Add test case for rounding Duration relative to a ZonedDateTime

test/intl402/Temporal/Duration/prototype/round/adjust-rounded-duration-days.js
See https://github.com/tc39/proposal-temporal/issues/2814
=> Temporal: Add test case for rounding up to a non-24-hour ZonedDateTime

harness/testIntl.js
Cf. `FormatNumeric{Hours,Minutes,Seconds}` in <https://tc39.es/proposal-intl-duration-format/>.
=> Disable grouping for numeric units in Intl.DurationFormat

test/intl402/Temporal/Duration/prototype/round/rounding-with-largestunit.js
I mistakenly committed something slightly different in my code review suggestion for #4306 than what I had modified locally.
=> Temporal: Fix name of constructor

test/intl402/DateTimeFormat/canonicalize-utc-timezone.js
=> Test that Intl.DateTimeFormat canonicalizes the timezones "Etc/GMT", "Etc/UTC", and "GMT" to "UTC"

test/built-ins/AbstractModuleSource/prototype.js
The descriptor should be `{ [[Writable]]: false, [[Enumerable]]: false, [[Configurable]]: false }`.
=> Fix AbstractModuleSource.prototype descriptor

test/intl402/PluralRules/prototype/resolvedOptions/plural-categories-order.js
Array elements should appear in following order: "zero", "one", "two", "few", "many", "other"
see https://github.com/tc39/ecma402/pull/918/
fix #4261
=> Add tests for `Intl.PluralRules.prototype.resolvedOptions().pluralCategories` order

test/built-ins/Temporal/Duration/prototype/round/balances-up-to-weeks.js
See https://github.com/tc39/proposal-temporal/issues/2813
=> Temporal: Add test for balancing up to weeks when year/month are present

test/built-ins/Object/freeze/typedarray-backed-by-resizable-buffer.js
Object.freeze will always throw on variable-length TAs with this has-consensus PR: https://github.com/tc39/ecma262/pull/3453
=> Update Object.freeze tests for resizable TypedArrays

test/intl402/Temporal/PlainDate/prototype/until/until-across-lunisolar-leap-months.js
Year 1 in the Chinese calendar corresponds to 2637 BCE in ICU4X.
See <https://docs.rs/icu/latest/icu/calendar/chinese/struct.Chinese.html#year-and-era-codes>.
=> Allow alternative era for Chinese calendar

test/annexB/language/comments/single-line-html-close-first-line-1.js, test/annexB/language/comments/single-line-html-close-first-line-2.js, test/annexB/language/comments/single-line-html-close-first-line-3.js
closes #4020
Updated the tests per https://github.com/tc39/test262/issues/4020#issuecomment-2009885892
=> Fix `single-line-html-close-first-line-*` failing with `Test262Error is not defined`

test/built-ins/Temporal/Duration/compare/relativeto-string-limits.js, test/built-ins/Temporal/Duration/prototype/round/relativeto-string-limits.js, test/built-ins/Temporal/Duration/prototype/total/relativeto-string-limits.js
These tests did not fully cover Temporal.Duration.prototype.round and Temporal.Duration.prototype.total because they called those methods on a blank duration (all components zero), for which there is an early return in round() and total().
This meant that we missed an assertion that would be hit after the early return.
This makes sure to test both blank and non-blank Durations with these relativeTo strings, and expect some strings to fail at different steps with the two cases.
See: tc39/proposal-temporal#3015
=> Temporal: Improve coverage of relativeto-string-limits tests

test/language/import/import-defer/errors/resolution-error/import-defer-of-missing-module-fails.js, test/language/import/import-defer/errors/syntax-error/import-defer-of-syntax-error-fails.js
We probably missed those two tests when running in the WebKit implementation because they are expected to fail, but due to the error in the dependency and not in the file itself.
Noticed in https://github.com/babel/babel/pull/17011
=> Add missing `from` in two `import defer` tests

test/intl402/DateTimeFormat/timezone-case-insensitive.js, test/intl402/Temporal/ZonedDateTime/from/timezone-case-insensitive.js, test/intl402/Temporal/ZonedDateTime/timezone-case-insensitive.js
"US/Pacific-New" was removed in tzdata2020b.
=> Remove "US/Pacific-New" from time zone tests

test/language/import/import-attributes/json-invalid.js, test/language/import/import-attributes/json-named-bindings.js
These errors don't happen when parsing the file, but when linking it with its dependencies.
Fixes half of https://github.com/tc39/test262/issues/4124
=> Fix the `phase` in tests about invalid JSON module bindings

test/intl402/DateTimeFormat/prototype/formatRange/to-datetime-formattable-with-different-arg-kinds.js, test/intl402/DateTimeFormat/prototype/formatRangeToParts/to-datetime-formattable-with-different-arg-kinds.js
Note: The Temporal polyfill doesn't pass this test.
=> Ensure ToDateTimeFormattable is called for both arguments

test/intl402/DurationFormat/prototype/format/digital-style-with-hours-display-auto-with-zero-hour.js
The implementation of `Intl.DurationFormat` in WebKit (JavaScriptCore) has passed all test262 test cases, but we discovered two incompatibilities with the specification. This Pull Request adds tests addressing those issues.
The first one is described in [bug 285078](https://bugs.webkit.org/show_bug.cgi?id=285078). A separator is printed erroneously for an unprinted hours value:
```js
const df = new Intl.DurationFormat('en-US', {
style: "digital",
hoursDisplay: "auto",
});
df.format({hours: 0, minutes: 1, seconds: 2});
// expected: "01:02"
// actual  : ":, 01:02"
```
The second one is described in [bug 285212](https://bugs.webkit.org/show_bug.cgi?id=285212). A negative sign is not printed:
```js
const df = new Intl.DurationFormat('en-US', {
style: "digital",
hoursDisplay: "auto",
}); …
```
=> DurationFormat: Add tests for durations with `style: "digital"`, `hoursDisplay: "auto"` and zero hours

test/staging/sm/extensions/ArrayBuffer-slice-arguments-detaching.js, test/staging/sm/extensions/DataView-construct-arguments-detaching.js, test/staging/sm/extensions/DataView-set-arguments-detaching.js, test/staging/sm/extensions/dataview.js, test/staging/sm/extensions/recursion.js, test/staging/sm/extensions/regress-650753.js, test/staging/sm/extensions/typedarray-set-detach.js, test/staging/sm/extensions/weakmap.js, test/staging/sm/generators/gen-with-call-obj.js, test/staging/sm/generators/iteration.js, test/staging/sm/object/clear-dictionary-accessor-getset.js, test/staging/sm/regress/regress-1507322-deep-weakmap.js, test/staging/sm/regress/regress-592556-c35.js, test/staging/sm/regress/regress-596103.js, test/staging/sm/statements/for-in-with-gc-and-unvisited-deletion.js
=> Remove gc() calls from staging/sm/

test/built-ins/TypedArray/prototype/includes/search-undefined-after-shrinking-buffer-index-is-oob.js, test/built-ins/TypedArray/prototype/includes/search-undefined-after-shrinking-buffer.js
The "search-undefined-after-shrinking-buffer-index-is-oob.js" test fails in JSC and V8.
=> Add coverage when searching undefined after shrinking buffer

test/built-ins/AsyncDisposableStack/constructor.js, test/built-ins/AsyncDisposableStack/prototype-from-newtarget-abrupt.js, test/built-ins/AsyncDisposableStack/prototype-from-newtarget-custom.js, test/built-ins/AsyncDisposableStack/prototype-from-newtarget.js, test/built-ins/AsyncDisposableStack/undefined-newtarget-throws.js, test/built-ins/DisposableStack/constructor.js, test/built-ins/DisposableStack/prototype-from-newtarget-abrupt.js, test/built-ins/DisposableStack/prototype-from-newtarget-custom.js, test/built-ins/DisposableStack/prototype-from-newtarget.js, test/built-ins/DisposableStack/undefined-newtarget-throws.js
Hello test262 maintainers!
Based on the instructions in https://github.com/tc39/test262/pull/3866#issuecomment-2369085177 have split out this pr it includes some of the simple tests on the (Async)DisposableStack prototypes and constructor
Do let me know if this looks ok I shall follow this up with more split out prs sorry for the delay
Thank you!
=> Explicit resource management basic constructor and prototype tests

test/staging/Intl402/Temporal/old/islamic-calendars.js
The "islamic" calendar id refers to the observational Islamic calendar and different implementation may use different algorithms to approximate when the moon's crescent can be observed. Change the test data to allow the approximations used in ICU4X in addition to the ones used in ICU4C.
Additionally allow implementations to canonicalise the calendar id.
=> Allow different approximations in the observational Islamic calendar

test/built-ins/Iterator/prototype/drop/argument-validation-failure-closes-underlying.js, test/built-ins/Iterator/prototype/every/argument-validation-failure-closes-underlying.js, test/built-ins/Iterator/prototype/filter/argument-validation-failure-closes-underlying.js, test/built-ins/Iterator/prototype/find/argument-validation-failure-closes-underlying.js, test/built-ins/Iterator/prototype/flatMap/argument-validation-failure-closes-underlying.js, test/built-ins/Iterator/prototype/forEach/argument-validation-failure-closes-underlying.js, test/built-ins/Iterator/prototype/map/argument-validation-failure-closes-underlying.js, test/built-ins/Iterator/prototype/reduce/argument-validation-failure-closes-underlying.js, test/built-ins/Iterator/prototype/reduce/non-callable-reducer.js, test/built-ins/Iterator/prototype/some/argument-validation-failure-closes-underlying.js, test/built-ins/Iterator/prototype/take/argument-validation-failure-closes-underlying.js
Tests for https://github.com/tc39/ecma262/pull/3467, which has consensus and is just waiting for tests.
No existing tests were invalidated as far as I can tell (presumably because if we'd thought to test this behavior then we'd have updated the proposal instead of needing the PR).
=> add tests for "iterator helpers close receiver on argument validation failure"

test/language/expressions/dynamic-import/import-defer/import-defer-async-module/main.js, test/language/expressions/dynamic-import/import-defer/import-defer-async-module/setup_FIXTURE.js, test/language/expressions/dynamic-import/import-defer/import-defer-async-module/tla_FIXTURE.js, test/language/expressions/dynamic-import/import-defer/import-defer-transitive-async-module/imports-tla_FIXTURE.js, test/language/expressions/dynamic-import/import-defer/import-defer-transitive-async-module/main.js, test/language/expressions/dynamic-import/import-defer/import-defer-transitive-async-module/setup_FIXTURE.js, test/language/expressions/dynamic-import/import-defer/import-defer-transitive-async-module/tla_FIXTURE.js, test/language/expressions/dynamic-import/import-defer/sync-dependency-of-deferred-async-module/dep_FIXTURE.js, test/language/expressions/dynamic-import/import-defer/sync-dependency-of-deferred-async-module/imports-tla-with-dep_FIXTURE.js, test/language/expressions/dynamic-import/import-defer/sync-dependency-of-deferred-async-module/main.js, test/language/expressions/dynamic-import/import-defer/sync-dependency-of-deferred-async-module/setup_FIXTURE.js, test/language/expressions/dynamic-import/import-defer/sync-dependency-of-deferred-async-module/tla-with-dep_FIXTURE.js, test/language/expressions/dynamic-import/import-defer/sync/dep_FIXTURE.js, test/language/expressions/dynamic-import/import-defer/sync/main.js, test/language/expressions/dynamic-import/import-defer/sync/setup_FIXTURE.js, test/language/expressions/dynamic-import/import-defer/sync/sync_FIXTURE.js
This is the last part of https://github.com/tc39/test262/issues/4215 :)
Except for the test in the `sync` folder, the others are adaptations of the ones in https://github.com/tc39/test262/blob/main/test/language/import/import-defer/evaluation-top-level-await
=> Add evaluation tests for `import.defer` with sync/async modules

test/built-ins/AsyncIteratorPrototype/Symbol.asyncDispose/invokes-return.js, test/built-ins/AsyncIteratorPrototype/Symbol.asyncDispose/return-val.js, test/built-ins/Iterator/prototype/Symbol.dispose/invokes-return.js, test/built-ins/Iterator/prototype/Symbol.dispose/return-val.js
Hello!
This pr splits out tests for whether (Async)Iterator Symbol.dispose calls the return method or not from https://github.com/tc39/test262/pull/3866
Thank you!
=> Explicit resource management iterator return

test/built-ins/NativeErrors/SuppressedError/message-method-prop-cast.js, test/built-ins/NativeErrors/SuppressedError/message-method-prop.js, test/built-ins/NativeErrors/SuppressedError/message-tostring-abrupt-symbol.js, test/built-ins/NativeErrors/SuppressedError/message-tostring-abrupt.js, test/built-ins/NativeErrors/SuppressedError/newtarget-is-undefined.js, test/built-ins/NativeErrors/SuppressedError/newtarget-proto-custom.js, test/built-ins/NativeErrors/SuppressedError/newtarget-proto-fallback.js, test/built-ins/NativeErrors/SuppressedError/newtarget-proto.js, test/built-ins/NativeErrors/SuppressedError/order-of-args-evaluation.js, test/built-ins/NativeErrors/SuppressedError/prototype/errors-absent-on-prototype.js
Hello!
This pr adds the test of SuppressedError from https://github.com/tc39/test262/pull/3866
Thank you!
=> Add tests for SuppressedError

test/built-ins/String/fromCodePoint/argument-is-Symbol.js, test/built-ins/String/fromCodePoint/argument-is-not-integer.js, test/built-ins/String/fromCodePoint/argument-not-coercible.js, test/built-ins/String/fromCodePoint/arguments-is-empty.js, test/built-ins/String/fromCodePoint/number-is-out-of-range.js, test/built-ins/String/fromCodePoint/return-string-value.js, test/built-ins/String/fromCodePoint/to-number-conversions.js
It might be a minor detail, but it seems that the specification for fromCodePoint was changed in [tc39/ecma262#2018](https://github.com/tc39/ecma262/pull/2018) and [tc39/ecma262#2152](https://github.com/tc39/ecma262/pull/2152), while the info section had not been updated. So, I updated it accordingly.
=> Update String.fromCodePoint info to align with latest ECMAScript spec

test/intl402/DurationFormat/prototype/format/style-digital-largenumber-en.js
=> Add test for useGrouping off in digital style of DurationFormat

test/intl402/Locale/getters.js
Closes https://github.com/tc39/test262/issues/4393
=> Add `Intl.Locale` test for `language` getter where language subtag is "und"

test/staging/explicit-resource-management/using-with-null-or-undefined.js
The goal of this test is to show that `using` declarations can be used with null and undefined and should not throw. The `let` keyword should not be used here.
=> Remove `let` keyword and use `using` declaration

test/language/import/import-defer/errors/resolution-error/import-defer-of-missing-module-fails.js, test/language/import/import-defer/errors/resolution-error/main_FIXTURE.js
The error type is host-defined, so we cannot use a negative-style test.
=> Rewrite import defer resolution test to not expect specific error

test/built-ins/Date/prototype/setUTCHours/this-value-valid-date-hour.js, test/built-ins/Date/prototype/setUTCHours/this-value-valid-date-min.js, test/built-ins/Date/prototype/setUTCHours/this-value-valid-date-ms.js, test/built-ins/Date/prototype/setUTCHours/this-value-valid-date-sec.js, test/built-ins/Date/prototype/setUTCMilliseconds/this-value-valid-date.js, test/built-ins/Date/prototype/setUTCMinutes/this-value-valid-date.js, test/built-ins/Date/prototype/setUTCMonth/this-value-valid-date-date.js, test/built-ins/Date/prototype/setUTCMonth/this-value-valid-date-month.js, test/built-ins/Date/prototype/setUTCSeconds/this-value-valid-date-ms.js, test/built-ins/Date/prototype/setUTCSeconds/this-value-valid-date-sec.js
I found some missing testcase for setUTC* functions unlike set* functions do. While I am working on [this CL](https://chromium-review.googlesource.com/c/v8/v8/+/6332619), I found that I was missing the `std::optional::value_or` of setUTC* functions by mistake but test262  succeeded. (But set* functions failed.)
So, I think this is a good point to add the cases. The TCs are from set* cases. (e.g., [setHours](https://github.com/tc39/test262/blob/main/test/built-ins/Date/prototype/setHours/this-value-valid-date-hour.js))
=> Add testcases for setUTC* functions return value

test/built-ins/String/prototype/match/cstm-matcher-on-bigint-primitive.js, test/built-ins/String/prototype/match/cstm-matcher-on-boolean-primitive.js, test/built-ins/String/prototype/match/cstm-matcher-on-number-primitive.js, test/built-ins/String/prototype/match/cstm-matcher-on-string-primitive.js, test/built-ins/String/prototype/matchAll/cstm-matchall-on-bigint-primitive.js, test/built-ins/String/prototype/matchAll/cstm-matchall-on-boolean-primitive.js, test/built-ins/String/prototype/matchAll/cstm-matchall-on-number-primitive.js, test/built-ins/String/prototype/matchAll/cstm-matchall-on-string-primitive.js, test/built-ins/String/prototype/replace/cstm-replace-on-bigint-primitive.js, test/built-ins/String/prototype/replace/cstm-replace-on-boolean-primitive.js, test/built-ins/String/prototype/replace/cstm-replace-on-number-primitive.js, test/built-ins/String/prototype/replace/cstm-replace-on-string-primitive.js, test/built-ins/String/prototype/replaceAll/cstm-replaceall-on-bigint-primitive.js, test/built-ins/String/prototype/replaceAll/cstm-replaceall-on-boolean-primitive.js, test/built-ins/String/prototype/replaceAll/cstm-replaceall-on-number-primitive.js, test/built-ins/String/prototype/replaceAll/cstm-replaceall-on-string-primitive.js, test/built-ins/String/prototype/search/cstm-search-on-bigint-primitive.js, test/built-ins/String/prototype/search/cstm-search-on-boolean-primitive.js, test/built-ins/String/prototype/search/cstm-search-on-number-primitive.js, test/built-ins/String/prototype/search/cstm-search-on-string-primitive.js, test/built-ins/String/prototype/split/cstm-split-on-bigint-primitive.js, test/built-ins/String/prototype/split/cstm-split-on-boolean-primitive.js, test/built-ins/String/prototype/split/cstm-split-on-number-primitive.js, test/built-ins/String/prototype/split/cstm-split-on-string-primitive.js
See https://github.com/tc39/ecma262/pull/3009
=> Add tests for not calling well-known symbols on primitives for string methods

test/staging/sm/Iterator/prototype/every/check-fn-after-getting-iterator.js, test/staging/sm/Iterator/prototype/find/check-fn-after-getting-iterator.js, test/staging/sm/Iterator/prototype/forEach/check-fn-after-getting-iterator.js, test/staging/sm/Iterator/prototype/reduce/check-fn-after-getting-iterator.js, test/staging/sm/Iterator/prototype/some/check-fn-after-getting-iterator.js
After a recent normative change on iterator helpers (https://github.com/tc39/ecma262/pull/3467), the expectations of these tests should be updated.
=> Update sm tests for iterator helpers

test/intl402/DateTimeFormat/canonicalize-utc-timezone.js, test/intl402/Temporal/ZonedDateTime/prototype/equals/canonicalize-utc-timezone.js
The test for https://github.com/tc39/ecma402/pull/724 (added in https://github.com/tc39/test262/pull/4328) didn't take the Time Zone Canonicalization proposal into account; but it should, because that proposal is stage 3.
As of that proposal, the [[TimeZone]] slot of DateTimeFormat gets the case-regularized original identifier, no longer the primary identifier. So the resolvedOptions().timeZone property also no longer returns the primary identifier.
=> Update UTC time zone canonicalization to match proposal-canonical-tz

test/built-ins/Temporal/Duration/prototype/prop-desc.js, test/built-ins/Temporal/Instant/prototype/prop-desc.js, test/built-ins/Temporal/PlainDate/prototype/prop-desc.js, test/built-ins/Temporal/PlainDateTime/prototype/prop-desc.js, test/built-ins/Temporal/PlainMonthDay/prototype/prop-desc.js, test/built-ins/Temporal/PlainTime/prototype/prop-desc.js, test/built-ins/Temporal/PlainYearMonth/prototype/prop-desc.js, test/built-ins/Temporal/ZonedDateTime/prototype/prop-desc.js
These ESIDs were updated to use dots instead of dashes, to be more consistent with the ESIDs of other properties.
=> Update ESIDs of Temporal.*.prototype properties

test/intl402/Temporal/ZonedDateTime/prototype/equals/canonicalize-utc-timezone.js
If `timeZone` should be preserved, then it can't be the same string as `utcDateTime.timeZoneId`.
=> Fix expected value for UTC-like time zone

test/intl402/NumberFormat/currency-digits-nonstandard-notation.js
[[MaximumFractionDigits]] is set to zero in SetNumberFormatDigitOptions, step 24.b.
=> Fix expected maximumFractionDigits for compact notation

test/intl402/Temporal/Instant/prototype/toLocaleString/dateStyle.js, test/intl402/Temporal/PlainDate/prototype/toLocaleString/dateStyle.js, test/intl402/Temporal/PlainDateTime/prototype/toLocaleString/dateStyle.js, test/intl402/Temporal/PlainMonthDay/prototype/toLocaleString/dateStyle.js, test/intl402/Temporal/PlainYearMonth/prototype/toLocaleString/dateStyle.js, test/intl402/Temporal/ZonedDateTime/prototype/toLocaleString/dateStyle.js
"islamic" is underspecified because it doesn't include any information which location and algorithms should be used to approximate new moon observations. Instead switch to "islamic-tbla".
=> Prefer "islamic-tbla" over "islamic" for Hijri calendars

test/intl402/DateTimeFormat/canonicalize-timezone.js
Adds a test to check the time zone canonicalization logic to verify that the new normative requirements for canonicalizing time zone introduced by https://github.com/tc39/ecma402/pull/877 are implemented correctly.
Ref: https://github.com/tc39/ecma402/issues/825
Ref: https://github.com/unicode-org/cldr/pull/3105
Fixes: https://github.com/tc39/test262/issues/4363
=> Add a test for ecma402#877

.circleci/config.yml, CONTRIBUTING.md, package.json
While still a relatively active project, ChakraCore is no longer maintained by Microsoft. It's not supported by esvu anymore and it was already disabled on CI.
Also realized while making this PR that my editor automatically trimmed some unnecessary whitespace from CONTRIBUTING.md, wasn't sure if I should go back and get rid of those changes or if it's actually okay. Let me know either way.
=> Remove chakra

.github/workflows/checks.yml, tools/lint/lib/checks/features.py, tools/lint/lib/checks/includes.py, tools/lint/lib/checks/license.py
Fixes #4448
Also includes miscellaneous fixes to some errors reported by test linters.
=> Avoid truncating test lint annotations

test/intl402/DateTimeFormat/prototype/format/dayPeriod-long-en.js, test/intl402/DateTimeFormat/prototype/format/dayPeriod-narrow-en.js, test/intl402/DateTimeFormat/prototype/format/dayPeriod-short-en.js, test/intl402/DateTimeFormat/prototype/formatToParts/dayPeriod-long-en.js, test/intl402/DateTimeFormat/prototype/formatToParts/dayPeriod-narrow-en.js, test/intl402/DateTimeFormat/prototype/formatToParts/dayPeriod-short-en.js
Taken from Richard's suggestion in https://github.com/tc39/test262/pull/4428#pullrequestreview-2691878561
=> Refactor dayPeriod formatting tests to be robust to CLDR changes

test/intl402/Temporal/ZonedDateTime/prototype/equals/canonicalize-timezone.js
As of the Time Zone Canonicalization proposal which is stage 3, the original time zone name should be preserved in Intl.DateTimeFormat .prototype.resolvedOptions.
Add a separate test that uses Temporal.ZonedDateTime.prototype.equals to test the canonicalization behaviour.
=> Fix time zone canonicalization behaviour in DateTimeFormat test

CONTRIBUTING.md, docs/testing-plan-guide.md
A guide to help with writing testing plans for ECMAScript proposals in stage 2.7.
=> Add testing plan guide to documentation.

README.md
Integrates Test262 ECMAScript tests into the [WMAS Test Suite](https://github.com/cta-wave/WMAS/), built on Web Platform Tests ([WPT](https://github.com/web-platform-tests/wpt/)). Ensures Test262 results are compatible with the WPT format.
=> Add WMAS Test Suite to Test262 Runners section in README

test/built-ins/Object/prototype/setPrototypeOf-with-non-circular-values-__proto__.js, test/built-ins/Object/prototype/setPrototypeOf-with-non-circular-values.js
Turns out, this case fails in **engine262**, which I’m fixing in:
- <https://github.com/engine262/engine262/pull/267>
=> Add more tests for `Object.prototype.[[SetPrototypeOf]]`

test/staging/sm/Function/function-bind.js
Syntax characters need to be escaped when they are part of a regex.
https://tc39.es/ecma262/#prod-Atom
https://tc39.es/ecma262/#prod-PatternCharacter
=> Escape syntax character in regex

test/language/import/import-defer/deferred-namespace-object/exotic-object-behavior.js, test/language/import/import-defer/errors/get-self-while-defer-evaluating/main.js, test/language/import/import-defer/errors/module-throws/import-defer-throws_FIXTURE.js, test/language/import/import-defer/evaluation-top-level-await/flattening-order/main.js
All the suggestions in https://github.com/tc39/test262/issues/4416 are correct. @woess Can you confirm that this makes the tests pass? :)
Fixes https://github.com/tc39/test262/issues/4416
=> Fix import defer test bugs

test/intl402/DateTimeFormat/prototype/format/temporal-objects-formatting.js
This test file adds tests for all types of Temporal objects and various combinations of style options for Intl.DateTimeFormat.
=> Temporal: Add test for different combinations of DateTimeFormat options

test/staging/sm/Function/function-bind.js
`test/staging/sm/Function/function-bind.js` test is using a regexp pattern `/^function\s*\(\)\s*\{\s*\[native code\]\s*\}$/` for checking native functions.
That regexp pattern doesn't match JSC's output( JSC's `Function#toString` output includes indentation ).
So this patch changes to use `assertNativeFunction`.
=> Use `assertNativeFunction` instead of simple regexp pattern

test/language/expressions/dynamic-import/import-errored-module.js, test/language/expressions/dynamic-import/import-errored-module_FIXTURE.js, test/language/module-code/top-level-await/dynamic-import-of-waiting-module-2_FIXTURE.js, test/language/module-code/top-level-await/dynamic-import-of-waiting-module.js, test/language/module-code/top-level-await/dynamic-import-of-waiting-module_FIXTURE.js
This PR includes two failing cases we found in JSC while running the import defer tests, for which we didn't have previous coverage. Given that dynamic import and top level await are features on their own, it's better to also have tests for it that do not use import defer.
What these tests are testing is that dynamic import of a module that is _already_ rejected/pending returns a promise that is rejected/pending.
=> Increase coverage for dynamic import and top-level await

test/intl402/Temporal/ZonedDateTime/prototype/getTimeZoneTransition/transitions-close-together.js, test/intl402/Temporal/ZonedDateTime/prototype/startOfDay/transitions-close-together.js
Check that implementations correctly detect time zone transitions that are close together. Additionally, test startOfDay() since the time zone transitions in Brazil occur at midnight.
See https://github.com/tc39/proposal-temporal/issues/3110
=> Temporal: Add test coverage for close-together time zone transitions

test/intl402/Temporal/ZonedDateTime/prototype/getTimeZoneTransition/rule-change-without-offset-transition.js
A "time zone transition" that is supposed to be returned by this method, is defined in the spec as an exact time where the UTC offset differs from that of the previous exact time value.
Implementations reported ambiguity around rule changes in the TZDB that did not actually result in a UTC offset change. For example, a time zone changing its abbreviation, or making DST permanent. Add a test case that checks that the method does not return faulty values that would not satisfy the spec requirement of a UTC offset change.
See: https://github.com/tc39/proposal-temporal/issues/3105
=> Temporal: Add coverage for getTimeZoneTransition edge cases

harness/asyncHelpers.js, harness/temporalHelpers.js
Instead use the easily available old-fashioned way, calling the method on Object.prototype.
=> Remove usage of Object.hasOwn in helper files

test/built-ins/Atomics/notify/retrieve-length-before-index-coercion-non-shared-detached.js, test/built-ins/Atomics/notify/retrieve-length-before-index-coercion-non-shared-resize-to-zero.js, test/built-ins/Atomics/notify/retrieve-length-before-index-coercion-non-shared.js, test/built-ins/Atomics/notify/retrieve-length-before-index-coercion.js, test/built-ins/Atomics/wait/retrieve-length-before-index-coercion.js, test/built-ins/Atomics/waitAsync/retrieve-length-before-index-coercion.js
The tests pass in JSC and SpiderMonkey, but fail in V8.
=> Ensure typed array length is retrieved early in Atomics.{notify,wait}

test/built-ins/RegExp/property-escapes/special-property-value-Script_Extensions-Unknown.js
Ref https://github.com/tc39/ecma262/issues/3590
regexp-generator is unfortunately unaware of the value: https://github.com/mathiasbynens/regenerate-unicode-properties/issues/7
=> RegExp: Add test cases for Unicode Script_Extensions=Unknown

test/built-ins/AsyncIteratorPrototype/Symbol.asyncDispose/throw-rejected-return.js, test/built-ins/AsyncIteratorPrototype/Symbol.asyncDispose/throw-return-getter.js, test/built-ins/AsyncIteratorPrototype/Symbol.asyncDispose/throw-return.js
Tests added by https://github.com/tc39/test262/pull/4469 missing required `async` flag.
=> Add missing `async` flag to `AsyncIteratorPrototype` tests

test/language/statements/for-await-of/head-await-using-init.js, test/language/statements/for-await-of/head-using-init.js, test/language/statements/for-of/head-await-using-bound-names-fordecl-tdz.js, test/language/statements/for-of/head-await-using-bound-names-in-stmt.js, test/language/statements/for-of/head-await-using-bound-names-let.js, test/language/statements/for-of/head-await-using-fresh-binding-per-iteration.js, test/language/statements/for-of/head-await-using-init.js, test/language/statements/for-of/head-using-bound-names-fordecl-tdz.js, test/language/statements/for-of/head-using-bound-names-in-stmt.js, test/language/statements/for-of/head-using-bound-names-let.js, test/language/statements/for-of/head-using-fresh-binding-per-iteration.js, test/language/statements/for-of/head-using-init.js
In an effort to make review more manageable, this extracts the remaining tests specific to `using`/`await using` in `for-of` and `for-await-of` statements from #3866
=> [explicit-resource-management] Add remaining tests specific to using in for-of and for-await-of syntax

harness/propertyHelper.js, test/built-ins/isFinite/prop-desc.js, test/built-ins/isNaN/prop-desc.js, test/built-ins/parseFloat/prop-desc.js, test/built-ins/parseInt/prop-desc.js
Ref #4468
Match the data property defaults from https://tc39.es/ecma262/multipage/ecmascript-standard-built-in-objects.html (writable true, enumerable false, configurable true).
=> harness: Simplify verifyCallableProperty

test/built-ins/AsyncGeneratorPrototype/return/return-state-completed-broken-promise.js
Refs: https://github.com/tc39/test262/pull/3472/files#r2085898854
=> Fixup incorrect assertion in AsyncGenerator.p.return with broken promises

test/intl402/Collator/prototype/resolvedOptions/resolved-case-first-unicode-extensions-and-options.js, test/intl402/Collator/prototype/resolvedOptions/resolved-collation-unicode-extensions-and-options.js, test/intl402/Collator/prototype/resolvedOptions/resolved-numeric-unicode-extensions-and-options.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/resolved-calendar-unicode-extensions-and-options.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/resolved-hour-cycle-unicode-extensions-and-options.js, test/intl402/DateTimeFormat/prototype/resolvedOptions/resolved-numbering-system-unicode-extensions-and-options.js, test/intl402/DurationFormat/prototype/resolvedOptions/resolved-numbering-system-unicode-extensions-and-options.js, test/intl402/NumberFormat/prototype/resolvedOptions/resolved-numbering-system-unicode-extensions-and-options.js, test/intl402/RelativeTimeFormat/prototype/resolvedOptions/resolved-numbering-system-unicode-extensions-and-options.js
These tests currently fail in V8, but pass in JSC and SM.
=> Add coverage for resolved locale when Unicode extensions and options are present

test/built-ins/Uint8Array/fromBase64/last-chunk-invalid.js
https://tc39.es/proposal-arraybuffer-base64/spec/#sec-frombase64
* 10.3, step 10.b.i
* 10.3, step 10.e
Passes on SpiderMonkey, fails on JSC
Current tests don't catch it
=> add tests for invalid Uint8Array.fromBase64 chunks

test/built-ins/Uint8Array/fromBase64/last-chunk-invalid.js
We were seeing an error about `assert.compareArray` being undefined over at Ladybird.
=> Add missing include to Uint8Array/fromBase64/last-chunk-invalid.js

.github/workflows/esmeta-test262.yml
The latest version [v0.6.2](https://github.com/es-meta/esmeta/releases/tag/v0.6.2) of ESMeta supports ES2025 and Unicode 16.0. This update could cover more tests.
Additionally, it can prevent possible ESMeta errors related to licensing issues with the Akka library, which were caused in CI for ecma262 (https://github.com/es-meta/esmeta/pull/290).
=> Update ESMeta version to v0.6.2

test/built-ins/Iterator/concat/fresh-iterator-result.js, test/built-ins/Iterator/concat/get-value-after-done.js
These tests should match the spec changes in https://github.com/tc39/proposal-iterator-sequencing/pull/26.
=> update Iterator Sequencing tests to reflect May 2025 plenary updates

test/built-ins/DataView/prototype/setBigInt64/immutable-buffer.js, test/built-ins/DataView/prototype/setBigUint64/immutable-buffer.js, test/built-ins/DataView/prototype/setFloat16/immutable-buffer.js, test/built-ins/DataView/prototype/setFloat32/immutable-buffer.js, test/built-ins/DataView/prototype/setFloat64/immutable-buffer.js, test/built-ins/DataView/prototype/setInt16/immutable-buffer.js, test/built-ins/DataView/prototype/setInt32/immutable-buffer.js, test/built-ins/DataView/prototype/setInt8/immutable-buffer.js, test/built-ins/DataView/prototype/setUint16/immutable-buffer.js, test/built-ins/DataView/prototype/setUint32/immutable-buffer.js, test/built-ins/DataView/prototype/setUint8/immutable-buffer.js
Ref #4509
> # DataView
> 
> - [x] `DataView.prototype.set…`
>   - [x] throws a TypeError if the receiver is backed by an immutable ArrayBuffer, before touching any argument
=> [immutable-arraybuffer] DataView.prototype.set$Type

test/built-ins/Array/prototype/with/this-value-boolean.js
This assertion throws before `compareArray` is called. In addition, `compareArray` takes two parameters, not one.
It's unclear to me why it was added in the first place.
=> Remove unnecessary call to compareArray in this-value-boolean.js

test/built-ins/WeakMap/prototype/getOrInsertComputed/throw-if-key-cannot-be-held-weakly.js
There is no validation to check that the callback function is not called if the key cannot be held weakly.
This pull request modifies the throw-if-key-cannot-be-held-weakly test to also check for this.
Discovered here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1988369
=> Check that callbackfn is not called if the key cannot be held weakly

test/built-ins/WeakMap/prototype/getOrInsertComputed/check-state-after-callback-fn-throws.js
The test `check-state-after-callback-fn-throws.js` is missing the feature `symbols-as-weakmap-keys`.
This was discovered after the last pull request was merged and is therefore done here.
=> Add missing feature, symbols-as-weakmap-keys

test/built-ins/WeakMap/prototype/getOrInsertComputed/throw-if-key-cannot-be-held-weakly.js
Broken in #4578. @johauke you might want to check if the test runner you're using is including harness functions eagerly.
=> Add missing include to WeakMap.prototype.getOrInsertComputed() test

test/intl402/String/prototype/toLocaleLowerCase/validates-all-locale-identifiers.js, test/intl402/String/prototype/toLocaleUpperCase/validates-all-locale-identifiers.js
Both tests pass in JSC and SM, but fail in V8.
=> String.prototype.toLocale{Lower,Upper}Case validates all locale identifiers

test/built-ins/TypedArray/prototype/slice/resize-count-bytes-to-zero.js
`countBytes` can be set to zero in step 14.d when resizable array buffers are used.
=> Add test case when countBytes in TA.p.slice is set to zero

test/built-ins/Set/prototype/isDisjointFrom/set-like-iter-return.js, test/built-ins/Set/prototype/isSupersetOf/set-like-iter-return.js
Set.prototype.isDisjointFrom and Set.prototype.isSupersetOf should call return() on the set-like iterator but only when it is not exhausted.
Port of the downstream tests I added in quickjs-ng/quickjs@6167dcb127.
<hr>
Ed.: the other set methods don't have special cases for when set size > set-like size and where iteration can stop before exhaustion, only isDisjointFrom and isSupersetOf.
=> Test iterator close behavior of Set methods

test/built-ins/Promise/withResolvers/resolvers.js
`resolve` and `reject` from `Promise.withResolvers` are just Abstract Closure(https://tc39.es/ecma262/#sec-newpromisecapability), so those shouldn't have `Function.prototype.name`.
V8 and SM follows the spec, but JSC doesn't follow it (will be fixed).
=> Add assertions for checking names of `resolve` and `reject` from `Promise.withResolvers`
